### ISSUE TITLE
Models slowly move downwards - Pokemon BDSP

### ISSUE THREAD

**Issue by SammyWhamy** [yuzu-emu/yuzu#7403] opened 2021-11-21 15:06 UTC
Issue occurs on yuzu Early Access 2226 (2021-11-20)
To reproduce you can simply launch bdsp and wait, I'm not 100% sure if its only on openGL, but models slowly move downwards, resulting in all kinds of glitches.

![image](https://user-images.githubusercontent.com/45788465/142767343-00ef42c5-8305-4f1c-a190-9b45396e9f65.png)
![image](https://user-images.githubusercontent.com/45788465/142767347-e7e3a1f4-fee4-4ea2-89e6-bcaafb30ccaf.png)
![image](https://user-images.githubusercontent.com/45788465/142767350-e53abdcb-a8bb-4032-b804-584ed078fb51.png)

The issue resets every time you enter a loading zone, but then just continues slowly sliding again, often leading in doors becoming unreachable because theyre blocked by the actual building.
I've seen other people say that disabling "Faster FRSQRTE and FRECPE" fixes the issue

**Comment by v1993** [comment] 2021-11-21 15:11
"Faster FRSQRTE and FRECPE" is disabled on both Accurate and Auto CPU accuracy settings. Does it happen there? Unsafe is expected to cause glitches.

Additionally, does it happen only if you unlock framerate? If so, it may be game not expecting to work at high FPS and not really fixable.

**Comment by SammyWhamy** [comment] 2021-11-21 15:15
I haven't tried yet on other CPU settings, but generally unsafe makes my games quite a bit faster and in some cases even seemed to fix some bugs.
Framerate I haven't messed around with, so I believe its just locked at 30fps like the game expects, but correct me if im wrong

**Comment by v1993** [comment] 2021-11-21 15:20
As I said, unsafe is exactly what it says - it will break some games and that is expected. Use "Auto" for balance of performance and accuracy. As for framerate, if you haven't used control+u, you're indeed running at 30 FPS,

**Comment by Morph1984** [comment] 2021-11-22 03:35
As v1993 mentioned, Unsafe CPU accuracy will cause issues with this game, so this is not a bug that can be fixed without using the Auto or Accurate cpu settings, please test these out so we can confirm that this is a non-issue

**Comment by Morph1984** [comment] 2021-11-22 03:36
Also before that, what CPU are you using? If you are using a CPU without AVX. Auto should perform the same as Unsafe

**Comment by german77** [comment] 2021-12-07 03:31
Unsafe CPU bug. Use Auto CPU

**Closed by german77** 2021-12-07 03:31 UTC
