### ISSUE TITLE
armGetSystemTick is not properly implemented

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2103] opened 2019-02-10 19:37 UTC
I tried to run Homebrew applications on Yuzu while using a public and open source homebrew toolchain

https://github.com/switchbrew/switch-examples/blob/master/graphics/opengl/textured_cube/source/main.cpp

When I ran this sample, the cube was spinning at super high speeds. However, on a physical console, the cube spins much slower. Please fix this bug

**Comment by Hexagon12** [comment] 2019-02-10 19:38
Duplicate of #1821, please report the issue there.

**Closed by Hexagon12** 2019-02-10 19:38 UTC

**Comment by niko1point0** [comment] 2019-02-10 19:41
Thank you @Hexagon12
