### ISSUE TITLE
Total system lockup/freeze

### ISSUE THREAD

**Issue by barolo** [yuzu-emu/yuzu#2177] opened 2019-02-28 00:13 UTC
System, Linux 5.0, , AMD APU Raven , VEGA 2400G, 16 GB DDR4 3200, mesa 19.1, llvm 8 

It's been happening since I've started testing yuzu with all current versions/types of yuzu, I'm not sure even how to investigate it further/debug it because gpu totally freaks out, locks up, and need to hard reset PC. 
Situation: Launch Mario Odyssey, during intro, the moment Bowser hits the ground with the fist, gpu locks, freezes, hard reset is necessary.
Not sure if it's even worth investigating since apparently vulkan is coming.

**Comment by Hexagon12** [comment] 2019-02-28 07:57
Duplicate of #2018. We cannot do anything about this - it's a driver issue. Try contacting Mesa developers.

**Closed by Hexagon12** 2019-02-28 07:57 UTC
