### ISSUE TITLE
Yuzu Android ABXY-Slide Option.

### ISSUE THREAD

**Issue by routomatic** [yuzu-emu/yuzu#12114] opened 2023-11-21 06:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hi, as the title says, it'll be great to enable ABXY slide same thing with the dpad slide. where you can activate multiple face buttons simultaneously. 

I also suggest adding button mapping for controllers. 

Thank you Yuzu team!

### Why would this feature be useful?

Very useful for users who play using the on screen controls, and for games like Super Mario Wonder and other platforming games.

**Comment by Calinou** [comment] 2024-01-24 13:36
As I understand it, this is a duplicate of https://github.com/yuzu-emu/yuzu/issues/11985.

**Closed** 2024-02-18 20:43 UTC
Labels: request, android

**Comment by routomatic** [comment] 2024-02-19 02:05
> As I understand it, this is a duplicate of https://github.com/yuzu-emu/yuzu/issues/11985. (For future reference, this feature is sometimes called "pass-by press".)

thank you!
