### ISSUE TITLE
Bayonetta 3 crash/immediate reboot of emulator at Secret Chapter

### ISSUE THREAD

**Issue by Shevchenko-Py-lab** [yuzu-emu/yuzu#9378] opened 2022-12-04 14:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1260 (2022-12-04)

### Description of Issue

When you collect three keys, and buy a book from Rodin, there is one more chapter available.
When I try to start it, plays opening animation with the book opens, and then emulator reboots.

### Expected Behavior

Ehm...start of the chapter, I suppose?

### Reproduction Steps

![01004a4010fea000_2022-12-04_17-02-14-524](https://user-images.githubusercontent.com/83506735/205495059-3ff3a2d0-554b-416e-b4a2-00a633d0127f.png)
![01004a4010fea000_2022-12-04_17-02-24-228](https://user-images.githubusercontent.com/83506735/205495067-e70294fa-9e66-4660-a3a8-9510ec070e39.png)
![01004a4010fea000_2022-12-04_17-02-25-136](https://user-images.githubusercontent.com/83506735/205495069-f6e348bf-6046-4f32-be5c-39f6467e3666.png)
[save_file.zip](https://github.com/yuzu-emu/yuzu/files/10148681/save_file.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10148647/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/10148648/yuzu_log.txt.old.txt)

### System Configuration

CPU: i7-10700kf
GPU/Driver: RTX3070
RAM: DDR4 32GB
OS: Win10

**Comment by v1993** [comment] 2022-12-04 14:18
Duplicate of #9218

**Comment by G-Spawn** [comment] 2022-12-04 14:54
Closing for reason above

**Closed by G-Spawn** 2022-12-04 14:54 UTC
