### ISSUE TITLE
Yuzu crashes on Let's Go Pikachu after go outside.

### ISSUE THREAD

**Issue by inmortalkaktus** [yuzu-emu/yuzu#3260] opened 2019-12-31 20:30 UTC
Hello guys.

I'm using an AMD A10-7700K, AMD Radeon R7 Graphics, an HDD of 1 TB, but currently running Yuzu with a 200MB partition of the disk which cotains Ubuntu 18.04 (because I don't know why, the version 19.10 works slow).

I've installed the recommended libraries and compiled by myself the last version of yuzu-canary (because if I use the recommended version precompiled, yuzu crashes just when I click the "Configure" option, and I had to compile it by myself).

I don't know why, everything seems to be more or less okay trying to emulate Pokemon Let's Go Pikachu, but when I try to go outside of the player's house, yuzu get closed without any error or anything, just it get closed at this point.

It's the first time I post an issue here, so, if I forgot something, just tell what it's and where find it to send it.

**Comment by ReaperOfSouls1909** [comment] 2019-12-31 20:33
it's a known issue with openssl compile yuzu mainline it wont happen

**Comment by inmortalkaktus** [comment] 2019-12-31 20:38
> it's a known issue with openssl compile yuzu mainline it wont happen

You're talking about the configure thing or about the crash when trying to go outside? In case that you're talking about the second one, I won't have the configure issue? I need to install something to get it working right, or compile it?

**Comment by Hexagon12** [comment] 2019-12-31 21:34
Duplicate of #2957 for the configure part.

For the second part - this is a issue tracker for developers. Support questions go into our Discord server.

**Closed by Hexagon12** 2019-12-31 21:34 UTC
