### ISSUE TITLE
Hyrule Warriors AOC texture not loading and crashing

### ISSUE THREAD

**Issue by CaesarMagno96** [yuzu-emu/yuzu#4999] opened 2020-11-25 20:02 UTC

**Comment by choppymaster** [comment] 2020-11-26 02:39
Hey, please describe the issue, say your pc specs, operating system,  and upload the log file here. Otherwise, devs can't track the issue.

**Comment by CaesarMagno96** [comment] 2020-11-26 08:13
Hyrule Warriors AOC v 1.0.1

Specs:
Yuzu EA 1156 
(ndr: the problem persist also on the older/stable versions of Yuzu)
Windows 10
Hardware specs:
I5 10500
RTX 2070
32GB DDR4

Running the first opening playable scene, field texture are not loading at all and during the first battle Yuzu freezes and crashes.
Here the log and screen/video capture of the problems -> https://mega.nz/folder/AtQTmCrY#zjALyPkWEbrsKzlUoP2o4w

**Comment by Nakotei** [comment] 2020-11-26 16:32
Hi, I have the same issue too. I don't have programming knowledge, but I want to fix the game. If you need information about something, please tell me.

**Comment by FearlessTobi** [comment] 2020-11-26 22:52
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4871 and https://github.com/yuzu-emu/yuzu/issues/4862.

**Closed by FearlessTobi** 2020-11-26 22:52 UTC

**Comment by Nakotei** [comment] 2020-11-26 23:10
> 
> 
> Duplicate of #4871 and #4862.
I think they aren't exactly the same problem. The #4871 occurs in the demo, and the #4862 doesn't seem to crash.
This problem is in the full game, and the issue is that it works perfectly until the first playable battle is entered, then the game slows down to crash.

**Comment by auranticus** [comment] 2020-11-27 01:21
Solution: turn off assembly shader

**Comment by Nakotei** [comment] 2020-11-27 11:14
> 
> 
> Solution: turn off assembly shader

Well, I just tried that, and it actually works better! It allows you to play for a while, but the drops to 0 fps are almost constant and affect the gameplay (because the enemies attack you in the meantime). Eventually crash, I haven't been able to advance from the first battle.
I know the topic is closed, but I would like to solve this issue. I leave my log and my specs here, in case of someone have an idea of how to fix it. Thank you.
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5607500/yuzu_log.zip)

Specs:
Yuzu 444
Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz    1.99GHz
RAM 8,00 GB
NVIDIA GeForce GTX 1050

**Comment by auranticus** [comment] 2020-11-27 14:02
#4862 causes yuzu to crash randomly (maybe shader problem), while Ryujinx does not. There's no point bumping this issue anymore. Until that issue is fixed, try Ryujinx but expect lower FPS.

**Comment by Nakotei** [comment] 2020-11-27 16:53
> 
> 
> #4862 causes yuzu to crash randomly (maybe shader problem), while Ryujinx does not. There's no point bumping this issue anymore. Until that issue is fixed, try Ryujinx but expect lower FPS.

I see... I didn't know that Ryujinx works better (the truth is that I don't even have that emulator jajaja). Thanks for helping and advising ^-^
