### ISSUE TITLE
Inverted display in playing streets of rage 4 

### ISSUE THREAD

**Issue by Qaim155** [yuzu-emu/yuzu#10531] opened 2023-05-31 19:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early access build on Google play

### Description of Issue

![Screenshot_yuzu_2023-06-01-01-02-55-189](https://github.com/yuzu-emu/yuzu/assets/124353259/9ce1e3a1-9dab-4750-8c4d-d40d512619f1)

### Expected Behavior

Display is inverted, bottom is at the top and left side is at the the right

### Reproduction Steps

Just start the game streets of rage 4 

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11618282/yuzu_log.txt.old.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11618284/yuzu_log.txt)

### System Configuration

CPU: snapdragon 8 gen 2
GPU/Driver: Qualcomm v676.13 Vulkan 
RAM: 16gb
OS: Redmagic os 6.0 android version 13

**Comment by FearlessTobi** [comment] 2023-05-31 19:46
Duplicate of https://github.com/yuzu-emu/yuzu/issues/8839

**Closed by FearlessTobi** 2023-05-31 19:46 UTC

**Comment by Qaim155** [comment] 2023-05-31 19:52
Are you sure this issue is done for android yuzu emulator? I think Issue #8839 is related to windows, this issue I have faced is in android version of yuzu.

**Comment by FearlessTobi** [comment] 2023-05-31 20:02
It is the exact same issue.

**Comment by N1NJATHEORY** [comment] 2023-09-19 09:27
Hello I have exact same issue on my redmagic 8s pro 888 gen 2! 16gb ram android 13! Has a fix been issued ? Thanks

**Comment by Qaim155** [comment] 2023-09-19 11:15
This issue is still not fixed.

**Comment by N1NJATHEORY** [comment] 2023-09-19 11:27
I came across a post saying because it's Australian region rom. It's causing the issue, but I got some different region roms, and it's still inverted and back to front. There's not much information on how to fix this on android. Sucks as the game looks plays awesome!

**Comment by manaboy** [comment] 2023-10-22 16:56
Got the same issue with latest build of YUZU on android RK3588 TV box, the ROM itself (US nsp) works fine on my actual cfw switch also works fine on skyline edge android emulator thats heavily based on Ryujinx although the emulator has a lot of missing graphics like background, it's not flipped.

**Comment by manaboy** [comment] 2023-10-22 16:57
But ingame it's flawless playable on skyline edge
