### ISSUE TITLE
Frequent crashes in Super Smash Bros. Ultimate

### ISSUE THREAD

**Issue by robinkb** [yuzu-emu/yuzu#7740] opened 2022-01-18 21:28 UTC
Hello,

I've been playing Super Smash Bros. Ultimate with Yuzu for a few hours now. Everything generally works great, except for the known issues listed on the compatibility wiki page. However, I am also getting frequest crashes in modes that are supposed to work, like one-off Smash games, and Classic Mode. Crashes occur quite frequently. I'd say about once every half hour, at least. First the video freezes while audio keeps playing. Yuzu becomes unresponsive. At that point I just kill the emulator.

I am running Yuzu 882 as a Flatpak on Fedora Linux 35.

My output from `inxi -v3`:

```
System:
  Host: fedora Kernel: 5.15.14-200.fc35.x86_64 x86_64 bits: 64 compiler: gcc
    v: 2.37-10.fc35 Desktop: GNOME 41.3 Distro: Fedora release 35 (Thirty Five)
Machine:
  Type: Desktop System: Gigabyte product: B550I AORUS PRO AX v: N/A
    serial: <superuser required>
  Mobo: Gigabyte model: B550I AORUS PRO AX v: x.x
    serial: <superuser required> UEFI: American Megatrends v: F3
    date: 08/20/2020
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse MX Master 3
    charge: 55% (should be ignored) status: Discharging
CPU:
  Info: 8-core model: AMD Ryzen 7 3700X bits: 64 type: MT MCP arch: Zen 2
    rev: 0 cache: L1: 512 KiB L2: 4 MiB L3: 32 MiB
  Speed (MHz): avg: 2284 high: 3591 min/max: 2200/4426 boost: enabled
    cores: 1: 1941 2: 1862 3: 2295 4: 2393 5: 2050 6: 3591 7: 2052 8: 2052
    9: 2052 10: 1873 11: 1856 12: 2794 13: 2053 14: 3579 15: 2052 16: 2054
    bogomips: 114984
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT]
    vendor: Gigabyte driver: amdgpu v: kernel bus-ID: 0a:00.0
  Device-2: Logitech Logi 4K Stream Edition type: USB
    driver: snd-usb-audio,uvcvideo bus-ID: 1-2.3:6
  Display: wayland server: X.Org 1.21.1.4 compositor: gnome-shell driver:
    loaded: amdgpu note: n/a (using device driver) - try sudo/root
    resolution: 3072x1728~60Hz
  OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.42.0
    5.15.14-200.fc35.x86_64 LLVM 13.0.0)
    v: 4.6 Mesa 21.3.4 direct render: Yes
Network:
  Device-1: Realtek RTL8125 2.5GbE vendor: Gigabyte driver: r8169 v: kernel
    port: f000 bus-ID: 06:00.0
  IF: eno1 state: down mac: 18:c0:4d:66:ad:d1
  Device-2: Intel Wi-Fi 6 AX200 driver: iwlwifi v: kernel bus-ID: 07:00.0
  IF: wlp7s0 state: down mac: 82:63:45:37:6e:65
  Device-3: Realtek RTL8153 Gigabit Ethernet Adapter type: USB
    driver: r8152 bus-ID: 2-2.2:4
  IF: enp2s0f0u2u2 state: up speed: 1000 Mbps duplex: full
    mac: 3c:e1:a1:71:ad:ba
  IF-ID-1: virbr0 state: down mac: 52:54:00:3a:a5:da
Drives:
  Local Storage: total: 931.51 GiB used: 126.04 GiB (13.5%)
Info:
  Processes: 667 Uptime: 3h 17m Memory: 15.6 GiB used: 2.74 GiB (17.6%)
  Init: systemd runlevel: 5 Compilers: gcc: 11.2.1 Packages: 10
  note: see --pkg Shell: fish v: 3.3.1 inxi: 3.3.11
```

To clarify, my GPU is an RX 5700 XT.

Logs: [yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/7892463/yuzu_log.zip)

Let me know if I can provide more information.

**Comment by G-Spawn** [comment] 2022-01-19 04:17
This issue is still expected on windows - linux for smash until emulator improvement.

**Comment by fanitriastowo** [comment] 2022-01-20 12:57
Same thing happen to me. I play Monster Hunter Generations Ultimate. 

```
[1042.623722] HW.Memory <Error> core/memory.cpp:operator():498: Unmapped Read32 @ 0x00000000003B3C74
[1042.623728] HW.Memory <Error> core/memory.cpp:operator():498: Unmapped Read32 @ 0x00000000003B3C78
[1042.623734] HW.Memory <Error> core/memory.cpp:operator():498: Unmapped Read32 @ 0x00000000003B3C7C
[1042.623740] HW.Memory <Error> core/memory.cpp:operator():498: Unmapped Read32 @ 0x00000000003B3C80
[1042.623746] HW.Memory <Error> core/memory.cpp:operator():498: Unmapped Read32 @ 0x00000000003B3C84
[1042.623752] HW.Memory <Error> core/memory.cpp:operator():498: Unmapped Read32 @ 0x00000000003B3C88
[1042.623759] HW.Memory <Error> core/memory.cpp:operator():498: Unmapped Read32 @ 0x00000000003B3C8C
```

My system
```
System:
  Host: triastowo Kernel: 5.15.12-1-MANJARO x86_64 bits: 64
    compiler: gcc v: 11.1.0 Desktop: KDE Plasma 5.23.4
    Distro: Manjaro Linux base: Arch Linux
Machine:
  Type: Desktop System: Dell product: OptiPlex 3050 v: N/A
    serial: <superuser required>
  Mobo: Dell model: 08NPPY v: A00 serial: <superuser required>
    UEFI-[Legacy]: Dell v: 1.5.4 date: 07/14/2017
Battery:
  Device-1: hidpp_battery_0 model: Logitech Wireless Mouse
    charge: 50% (should be ignored) status: N/A
CPU:
  Info: quad core model: Intel Core i7-6700 bits: 64 type: MT MCP
    arch: Skylake-S rev: 3 cache: L1: 256 KiB L2: 1024 KiB
    L3: 8 MiB
  Speed (MHz): avg: 3868 high: 3996 min/max: 800/4000 cores:
    1: 3650 2: 3904 3: 3870 4: 3915 5: 3996 6: 3902 7: 3918 8: 3793
    bogomips: 54417
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2
    ssse3 vmx
Graphics:
  Device-1: Intel HD Graphics 530 vendor: Dell driver: i915
    v: kernel bus-ID: 00:02.0
  Display: x11 server: X.Org 1.21.1.2 driver:
    loaded: modesetting resolution: 1920x1080~60Hz
  Message: Unable to show advanced data. Required tool glxinfo
  missing.
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell driver: r8169 v: kernel port: e000 bus-ID: 02:00.0
  IF: enp2s0 state: up speed: 1000 Mbps duplex: full
    mac: d8:9e:f3:0c:b4:ed
  IF-ID-1: docker0 state: up speed: 10000 Mbps duplex: unknown
    mac: 02:42:91:ee:4a:7c
  IF-ID-2: veth34146c5 state: up speed: 10000 Mbps duplex: full
    mac: 56:8a:11:df:eb:36
Drives:
  Local Storage: total: 704.24 GiB used: 211.96 GiB (30.1%)
Info:
  Processes: 337 Uptime: 10h 0m Memory: 15.51 GiB
  used: 8.46 GiB (54.5%) Init: systemd Compilers: gcc: 11.1.0
  clang: 13.0.0 Packages: 1450 Shell: Zsh v: 5.8 inxi: 3.3.12
```

**Comment by lat9nq** [comment] 2022-02-08 09:50
Duplicate of #5822

**Closed** 2022-02-17 17:48 UTC
