### ISSUE TITLE
game freeze after play for a while and can not stop in the last yuzu mainline

### ISSUE THREAD

**Issue by zqisme** [yuzu-emu/yuzu#12834] opened 2024-01-28 19:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1696

### Description of Issue

game freeze and screen get white after play for a while and can not stop in the last yuzu mainline，log shows： 
[ 683.021485] Service.FS <Warning> core\hle\service\filesystem\fsp\fs_i_filesystem.cpp:Commit:182: (STUBBED) called
[1703.217022] Debug <Critical> video_core\macro\macro_hle.cpp:operator ():111: Assertion Failed!
Faulty draw!
[1703.385052] Debug <Critical> video_core\macro\macro_hle.cpp:operator ():111: Assertion Failed!
Faulty draw!
[2782.812526] Service.NVDRV <Critical> core\hle\service\nvdrv\core\nvmap.cpp:PinHandle:222: Ran out of SMMU address space!

### Expected Behavior

game just freeze

### Reproduction Steps

I dont know，maybe need more time to test
I have tested again with mainline 1697 and can't reproduce,but there are still some warning in the logs like 
[ 487.887401] Service.NIFM <Warning> core\hle\service\nifm\nifm.cpp:GetCurrentIpAddress:430: (STUBBED) called

### Log File

[yuzu_log.txt.old.zip](https://github.com/yuzu-emu/yuzu/files/14077385/yuzu_log.txt.old.zip)

### System Configuration

CPU: 9600kf
GPU/Driver: nvidia1660s/537.58
RAM: 16g
OS: windows 10

**Comment by Squall-Leonhart** [comment] 2024-01-29 03:00
Duplicate of #10660

**Comment by liamwhite** [comment] 2024-01-29 03:04
I don't think this is a duplicate

**Comment by Squall-Leonhart** [comment] 2024-01-29 19:54
I tested this for over an hour and a half on EA as well as a build from master and apart from a fault draw in the log there was no crashes, this potentially incriminates the SMMU changes currently only on mainline and android in #12749

**Comment by liamwhite** [comment] 2024-01-29 19:57
EA includes all mainline-merge changes

**Comment by liamwhite** [comment] 2024-02-01 00:09
Fire Emblem Three Houses fixed by #12869

**Closed by liamwhite** 2024-02-01 00:09 UTC
