### ISSUE TITLE
Reset Sound-System on Device-Change

### ISSUE THREAD

**Issue by chloecdn** [yuzu-emu/yuzu#10800] opened 2023-06-16 12:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I am using Cubeb with the Device on auto, and a Headset which has both Wired & Wireless-Mode. When changing it from Wired to Wireless or the other way around, the Audio will be off until the Emulator is restarted. Maybe reset the Audio-System when a new audio device is detected, or add a button the the top-bar to reset it manually.

### Why would this feature be useful?

When you're in a game where you cannot save the game on the spot, and your Headset turns off (ex. Battery empty) you have to play until you can save without sound, which can be quite annoying.

**Comment by Squall-Leonhart** [comment] 2023-06-16 13:02
I'm actually curious why this isn't already working, as Cubeb implements endpoint notices natively.

https://hg.mozilla.org/mozilla-central/file/tip/media/libcubeb/src/cubeb_wasapi.cpp

**Comment by mrcmunir** [comment] 2023-06-17 06:06
I can confirm this but not only happen in cubeb it's happen for me in sdl2 too.
It usually happens in devices that have more than one audio output available
If the emulator is running and then for whatever reason the output is automatic changed to another output, the ouput option will be lost in the emulator audio option with no name device.

**Comment by Squall-Leonhart** [comment] 2023-11-08 08:46
This seems to be working properly now

**Comment by Squall-Leonhart** [comment] 2023-11-08 08:54
Fixed by https://github.com/yuzu-emu/yuzu/pull/11359

**Comment by FearlessTobi** [comment] 2023-11-10 21:32
Thanks for the info.

**Closed by FearlessTobi** 2023-11-10 21:32 UTC
Labels: request
