### ISSUE TITLE
L3/R3 virtual control overlay support (Android)

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#10620] opened 2023-06-04 22:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

As the title says, I wish you could add L3 and R3 in the virtual controls

### Why would this feature be useful?

To Lock the camera to an enemy among other things and is necessary in many games

**Comment by FearlessTobi** [comment] 2023-06-05 10:22
Duplicate of https://github.com/yuzu-emu/yuzu/issues/10569.

**Closed by FearlessTobi** 2023-06-05 10:22 UTC
Labels: request, android
