### ISSUE TITLE
[Iris Xe][Mesa][Vulkan] Mario Kart 8 SegFault

### ISSUE THREAD

**Issue by casasfernando** [yuzu-emu/yuzu#7364] opened 2021-11-18 22:16 UTC
The game works fine using OpenGL but when trying with Vulkan Yuzu crashes (segfault) right after selecting the character, the circuit and pressing 'OK' to start the race.

Game : Mario Kart 8 (base)
Yuzu Version : yuzu mainline 815 (AppImage)
CPU : 11th Gen Intel i7-1185G7 (8) @ 4.800GHz
RAM : 16GB
GPU : Intel(R) Xe Graphics (TGL GT2)
GPU Driver : Intel open-source Mesa driver 21.0.3
OS: elementary OS 6 (based on Ubuntu 20.04)
Kernel : 5.10.0-1051-oem

Yuzu terminal output:

```
QApplication: invalid style override 'adwaita' passed, ignoring it.
	Available styles: Windows, Fusion
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
libpng warning: iCCP: known incorrect sRGB profile
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
[h264 @ 0x7fd9c70f9300] Increasing reorder buffer to 1
Unhandled SIGSEGV at rip 0x007fd99a7edd97
Segmentation fault
```
Please find attached the complete logfile:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7566329/yuzu_log.txt)

Thanks.

**Comment by lat9nq** [comment] 2021-11-18 23:56
Duplicate of #7023

**Comment by Morph1984** [comment] 2021-11-19 00:10
Closing in favor of #7023

**Closed by Morph1984** 2021-11-19 00:10 UTC
