### ISSUE TITLE
Pokémon Sword - Graphical Issue

### ISSUE THREAD

**Issue by aguirre-erriuga** [yuzu-emu/yuzu#6636] opened 2021-07-13 20:54 UTC
I don't know why it is happening. I've already changed the settings many times and had no results. it happens just with NPCs and the player.

![image](https://user-images.githubusercontent.com/87394013/125522770-eb149742-f9cf-46a9-9b94-bd5448ce00e0.png)

![image](https://user-images.githubusercontent.com/87394013/125522801-f26a284f-f336-4328-b196-da457496824b.png)

![image](https://user-images.githubusercontent.com/87394013/125522705-9b8e00f8-e83e-41de-bbc5-499e7900fd99.png)

![image](https://user-images.githubusercontent.com/87394013/125523134-891ea501-a024-467e-9af1-204bc1862f11.png)

![image](https://user-images.githubusercontent.com/87394013/125523281-7939d11d-949f-4431-bbc7-b426bec26eb3.png)

![image](https://user-images.githubusercontent.com/87394013/125523397-96351dca-06df-4d7f-8685-5e434f3cd7dc.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6811935/yuzu_log.txt)

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6811934/yuzu_log.txt.old.txt)

**Comment by ToxaGaming** [comment] 2021-07-13 21:04
this is an issue caused by AMD's proprietary drivers because of a bug with helper invocations. There's sadly nothing you can do in the yuzu settings to fix this, other than hope that AMD fix the driver bug themselves.

**Comment by Marko944** [comment] 2021-07-13 21:11
I've switched to Vulkan and it's rendering properly on my machine (Driver v21.6.1 on 5700XT with Yuzu v686).
You can find attached the settings that I copy/pasted from a reddit tutorial:
![bvYcCj89KH](https://user-images.githubusercontent.com/866831/125525190-d60b5120-6022-4c28-a9ce-a2639ad4d8d3.gif)
![yuzu_Oi5zwdH84u](https://user-images.githubusercontent.com/866831/125525560-c5a599f3-5898-415c-b6c0-32bd0049600d.jpg)

**Comment by ToxaGaming** [comment] 2021-07-13 21:17
alright, yeah I was unsure if this was on Mainline or on Early Access. Now Mainline will have the wireframe issue on OpenGL, but will render just fine on Vulkan because of a workaround present there. However on the Early Access builds there's wireframes on both OpenGL and Vulkan because those builds are missing the workaround.

Also on a closing note I'd suggest you use Vulkan for about all games in general as it performs way better than OpenGL on AMD's proprietary drivers.

**Comment by Pajn** [comment] 2021-07-28 14:10
Since project Hades there is now wireframe issues on characters with Vulkan as well.

**Comment by neonoafs** [comment] 2021-08-08 01:02
Since AMD dropped support  Fury series and older cards we will have to live with this bug.

**Comment by wwadn408312** [comment] 2021-08-16 02:03
so sad, i tried, maybe, all possible settings before reading this thread 
well, just to keep updating the problem still present on yuzu715 (RX 590 series / Vulkan)

![](https://i.imgur.com/AQDeBS6.jpeg)

![](https://i.imgur.com/KgRNxgk.jpeg)

![](https://i.imgur.com/wI0bZ74.jpeg)

**Comment by G-Spawn** [comment] 2021-08-20 03:54
> 
> 
> so sad, i tried, maybe, all possible settings before reading this thread
> well, just to keep updating the problem still present on yuzu715 (RX 590 series / Vulkan)

Just chiming in If you want to avoid it for now you can try using mainline 699 or earlier which should be prior to new compiler. At least until its addressed in updated yuzu / amd.

**Comment by FernandoS27** [comment] 2021-08-20 08:21
@ameerj found the issue. It's due to a bug in AMD driver when 2 reads of a attribute in the same 4 component vector is done unordered.

We are trying to see how we can solve this.

**Closed** 2021-09-02 00:36 UTC
