### ISSUE TITLE
Xenoblade Chronicles De/2 - Rainbow flickering

### ISSUE THREAD

**Issue by Banjo-Kazooie-fan** [yuzu-emu/yuzu#4995] opened 2020-11-24 23:17 UTC
My Specs:
Ryzen 5 3600, Rx570, 32gb Ram.
- Windows 10, Gpu Drivers: 20.11.1
- Ea 1153 - Vulkan API

The shader cache rewrite fixed the Vertex Explosions in those two titles, which is great!
Unfortunately a new issues appeared: I call it the "**rainbow flickering**".

I thought that it was related to the newest drivers (which we discussed here **#4979**).
But it is not! (the issues appear on Driver Version 20.11.1 and 20.11.2)
Here the log and some pictures:

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5593318/yuzu_log.txt)

![Xenoblade Chroncicles DE - broken](https://user-images.githubusercontent.com/74963292/100162169-3d747c80-2eb3-11eb-930c-435fedeb4993.PNG)
![Xenoblade Chroncicles DE - broken 2](https://user-images.githubusercontent.com/74963292/100162183-41a09a00-2eb3-11eb-941a-3dbe05f7e9ae.PNG)
![xenoblade 2 broken](https://user-images.githubusercontent.com/74963292/100162193-46654e00-2eb3-11eb-93c5-8fc39447c6ec.PNG)
![xenoblade 2 broken 2](https://user-images.githubusercontent.com/74963292/100162201-4a916b80-2eb3-11eb-9fa1-77c30efa7c5d.PNG)

**Comment by ReinUsesLisp** [comment] 2020-11-25 02:15
How can this be reproduced? It doesn't happen on my RX550 on `20.9.2`. I'll try updating the driver for now.

**Comment by Banjo-Kazooie-fan** [comment] 2020-11-25 03:01
> How can this be reproduced? It doesn't happen on my RX550 on `20.9.2`. I'll try updating the driver for now.

just playing - it alwyas happens - don't update to 20.11.2 tho (latest) - only to 20.11.1 (otherwise u will see the issue we had in #4979 )

**Comment by Banjo-Kazooie-fan** [comment] 2020-11-25 16:56
@ReinUsesLisp 
I rolled back to 20.9.2 just for testing purpose and was faced with the same issue.
Doesn't seem to be a driver issue...

**Comment by Banjo-Kazooie-fan** [comment] 2020-11-26 20:51
![broken 3](https://user-images.githubusercontent.com/74963292/100390632-63279000-3031-11eb-81f9-f263ac478ffe.PNG)
 #5013 seemed to make it worse
@ReinUsesLisp

**Comment by ReinUsesLisp** [comment] 2020-11-26 20:53
There's no more transparent geometry. It makes sense that it looks "worse".

**Comment by Banjo-Kazooie-fan** [comment] 2020-11-26 21:07
oh okay - do you have an idea what it could be (and how to solve it)?

**Comment by choppymaster** [comment] 2020-11-27 06:16
**[  64.289513] HW.GPU <Error> video_core\texture_cache\image_base.cpp:AddImageAlias:141: Compressed to compressed image aliasing is not implemented** 

Observed in your log

**Comment by ReinUsesLisp** [comment] 2020-11-27 06:27
That'd affect all vendors. This is probably related to one of the thousand validation error this game makes yuzu generate on Vulkan.

**Comment by AnarkoDX** [comment] 2020-11-30 19:16
i have The exact same problem in xenoblade 1 and 2  , i have a 1600AF - RX580 4gb - 16gb ram 3000mhz  - latest gpu drivers and yuzu EA 1174

**Comment by Banjo-Kazooie-fan** [comment] 2021-01-25 00:58
![upsided](https://user-images.githubusercontent.com/74963292/105649456-a62aa600-5eb0-11eb-97c8-0bdcd0c96e15.PNG)
![lololo](https://user-images.githubusercontent.com/74963292/105649460-aa56c380-5eb0-11eb-9df3-b5d737ccd522.PNG)
still occurring

**Comment by tuxedosat** [comment] 2021-01-25 21:45
Also getting this issue.
Ryzen 5 3600X, RX580 8GB
Yuzu 517

**Comment by Tellilum** [comment] 2021-02-09 12:23
![image](https://user-images.githubusercontent.com/59491721/107363074-7f629700-6a8e-11eb-84ae-97cff2e7d377.png)
Same here. 
Intel i5-9400
Radeon RX570 4GB
Yuzu 531

**Comment by BanchouBoo** [comment] 2021-10-10 18:59
Also have this issue in Yuzu EA 2117
Radeon RX 590 8GB
Seems every who has this issue has a Radeon RX 500 series GPU, or at least everyone who's reported it here and in #5756

Below is my initial report of the issue I made in the Yuzu Discord providing details about what conditions it happened in.
> So I'm having a very strange and frustrating problem. Playing XCDE, I got to the Bionis' Leg, and there was a minor graphical issue I saw with a shader out in the distance (I think it was a waterfall?) so I tried to clear my shader cache to see if that'd maybe help, but now when I load that area it's totally fucked like this.
>
> If I load a save from Colony 9, that area looks fine as do the caves, but this area is still like this when I get to it, and once I load this area, either from a save in it or by walking there, every part of the game starts to looked messed up like this too.
>
> I'm using OpenGL with GLSL. Vulkan behaves slightly differently. If I load into Colony 9 or the caves, they look fine (the intro portion of the game is still messed up though like I showed [before](https://user-images.githubusercontent.com/32691832/136709573-641175b0-fa19-46f0-bcfa-60628b0f7c3a.png)), and going to the leg still looks fucked and fucks the rest of the areas that previously worked like with GLSL, but loading directly into the leg from the main menu makes the leg look fine (except the aforementioned waterfall which still looks odd) but still messes of the rest of the areas in the game (and the leg if I leave and reenter it). Also the [map issue](https://user-images.githubusercontent.com/32691832/136709597-9a479e75-5ebd-4315-ac4b-8024dbe27cef.mp4) I posted about earlier doesn't happen on Vulkan.
> ![image](https://user-images.githubusercontent.com/32691832/136709555-1673f30e-74aa-4a45-9447-e9279b3ffabd.png)

**Comment by widardd** [comment] 2021-12-14 00:53
Yuzu 2300, RX 580, Ubuntu 20.04

Can confirm everything posted already. Gane worked fine until I hit that specific area in the game where the rainbow issue suddenly "unlocked". Niw previous areas are broken, too.

Vulkan aswell as OpenGL.

**Comment by raffermeniac** [comment] 2021-12-14 14:43
> Yuzu 2300, RX 580, Ubuntu 20.04
> 
> Can confirm everything posted already. Gane worked fine until I hit that specific area in the game where the rainbow issue suddenly "unlocked". Niw previous areas are broken, too.
> 
> Vulkan aswell as OpenGL.

This issue doesnt seem to happen when using AMDVLK drivers.
In fact, while testing this game on Manjaro with the AMDVLK, i couldnt see any visual glitches or bugs.

**Comment by raffermeniac** [comment] 2021-12-14 14:44
For those with this problem, try AMDVLK drivers.

**Comment by widardd** [comment] 2021-12-14 17:29
> > Yuzu 2300, RX 580, Ubuntu 20.04
> > Can confirm everything posted already. Gane worked fine until I hit that specific area in the game where the rainbow issue suddenly "unlocked". Niw previous areas are broken, too.
> > Vulkan aswell as OpenGL.
> 
> This issue doesnt seem to happen when using AMDVLK drivers. In fact, while testing this game on Manjaro with the AMDVLK, i couldnt see any visual glitches or bugs.

I didn't expose this bug until I hit the first big city and tried to do a blade resonance, after that even the first area of the game goes full LSD. Here's a save file:

https://drive.google.com/drive/folders/11R5ITjWYttbbRRz6wPrYrcE1ubRT3uHH?usp=sharing

It should spawn you into the first area.

**Comment by raffermeniac** [comment] 2021-12-14 20:09
> > > Yuzu 2300, RX 580, Ubuntu 20.04
> > > Can confirm everything posted already. Gane worked fine until I hit that specific area in the game where the rainbow issue suddenly "unlocked". Niw previous areas are broken, too.
> > > Vulkan aswell as OpenGL.
> > 
> > 
> > This issue doesnt seem to happen when using AMDVLK drivers. In fact, while testing this game on Manjaro with the AMDVLK, i couldnt see any visual glitches or bugs.
> 
> I didn't expose this bug until I hit the first big city and tried to do a blade resonance, after that even the first area of the game goes full LSD. Here's a save file:
> 
> https://drive.google.com/drive/folders/11R5ITjWYttbbRRz6wPrYrcE1ubRT3uHH?usp=sharing
> 
> It should spawn you into the first area.

I have 20 hours in this game, im already in Bionis Leg, and there's no glitch in any of the other areas.

**Comment by BanchouBoo** [comment] 2021-12-14 20:40
Using master+early access merges provides a slightly better result for OpenGL, some stuff is visible normally.

![image](https://user-images.githubusercontent.com/32691832/146075518-f5e48759-ad6d-40bc-a0cd-00a8fc29fbf0.png)

Additionally, using Vulkan with amdvlk as per @raffermeniac's suggestion eliminates it entirely (or at least up to where I am in the game, can't confirm it won't show up later).

**Comment by widardd** [comment] 2021-12-14 22:07
Can confirm, rainbow issue is gone via AMDVLK.
![So1BiFW](https://user-images.githubusercontent.com/5463582/146086860-3bea0314-651a-4060-8349-92f2896a4827.png)

I still have to doubt @raffermeniac's claim about no issues though, since the shadow bug visible in my screenshot is related to yuzu's vulkan implementation, it's mentioned on the game's wiki page. But that's a different topic. Thanks for the workaround!

**Comment by raffermeniac** [comment] 2021-12-15 13:50
> Can confirm, rainbow issue is gone via AMDVLK. ![So1BiFW](https://user-images.githubusercontent.com/5463582/146086860-3bea0314-651a-4060-8349-92f2896a4827.png)
> 
> I still have to doubt @raffermeniac's claim about no issues though, since the shadow bug visible in my screenshot is related to yuzu's vulkan implementation, it's mentioned on the game's wiki page. But that's a different topic. Thanks for the workaround!

I can only confirm that at least two issues are definetively gone by using AMDVLK drivers, the Black Grass Glitch (present in windows amd vulkan drivers) and the Rainbow Flickering (present on RADEONSI and RADV drivers, regardless of the api). I am not aware of other problems, since i have only found these two in my playthrough, and tested most of the vulkan implementations avaliable till i found this solution.

I analyzed the behavior of the game on the following:
Windows OpenGL AMD Drivers - No rendering issues shown, but suffers from bad performance.

Windows VULKAN AMD Drivers - Displays the Black Grass Glitch issue, but not the Rainbow Flickering. 

RADEONSI (OpenGL) - Displays the Rainbow Flickering, but not the Black Grass Glitch. 

RADV (Vulkan) - The first area displays the Rainbow Flickering, Colony 9 its fine, the Monado Expedition cutscene shows the flickering too, Tephra Cave its fine, but after Bionis Leg, this issue shows in some areas of it, and after some time and some transitions between areas, everything flickers again.

AMDVLK - No rendering issues shown, and has good performance. (My recommendation.)

**Comment by raffermeniac** [comment] 2021-12-16 01:42
Tested every area of the game till Satorl Marsh, all fine.
I'll keep updating.

**Comment by raffermeniac** [comment] 2021-12-16 22:18
Update:
The Rainbow Glitch can be seen again in the transition from Bionis Interior to Makna Path, and bleeds to Makna Path itself, but after going back to Bionis Interior and returning, the glitch is gone and everything returns to normal.

**Comment by UnionExxis** [comment] 2022-02-03 04:58
Warping to another area or point on the map (using the in-game warps) seems to resolve it. The rainbow issue is really random has been pretty rare during my 57 hour playthrough so far.

**Comment by darksylinc** [comment] 2022-12-10 01:59
I've been playing XB2 for 40hs in-game and I've occasionally experienced vertex explosions (which disappear quickly after they appear) and rainbow glitch (which can disappear if I change to a different world and then I go back).

By playing with the camera it looks like the rainbow glitch may be caused by a cubemap containing garbage values; since it's clearly the reflections what are messed up.

Given how rare the bug is, I strongly suspect the vertex explosions and the rainbow glitch are related. If the game tries to generate a cubemap on level load and the geometry randomly explodes, the cubemap will be filled with garbage.

Hence IMHO it would be wise to prioritize vertex explosion bug over the cubemap one unless further evidence says otherwise.

**Comment by gidoly** [comment] 2023-05-04 21:12
should fixed on last mainline and ea feel free to reopen if still happens

**Closed by gidoly** 2023-05-04 21:12 UTC
Labels: gpu-issue
