### ISSUE TITLE
Android 10 

### ISSUE THREAD

**Issue by kedrick021** [yuzu-emu/yuzu#12385] opened 2023-12-17 02:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Plss add for Android 10

### Why would this feature be useful?

Plss add for Android 10

**Comment by german77** [comment] 2023-12-17 02:52
Duplicate of #10585

**Closed by german77** 2023-12-17 02:52 UTC
Labels: request
