### ISSUE TITLE
[Settlers : New Allies] - Endless loading

### ISSUE THREAD

**Issue by Andhariel** [yuzu-emu/yuzu#11962] opened 2023-11-04 10:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1609

### Description of Issue

When the game displays message about autosave and ask for a button to be prompted, it enters in endless loading.
The loading icon still is animated but nothing's going anymore.

### Expected Behavior

Loading occurs.

### Reproduction Steps

Launch the game and prompt a button when asked at autosave explanation screen.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13256344/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 3700X
GPU/Driver: AMD Rx570 - drivers 23.8.2 whql
RAM: 16Go 3600MHz
OS: W10 64bits 2004

**Comment by Squall-Leonhart** [comment] 2023-11-05 05:45
Looks like a duplicate of https://github.com/yuzu-emu/yuzu/issues/11662

**Comment by Andhariel** [comment] 2023-11-14 17:48
Greetings,

I tried with a fresh new install of yuzu and the problem disapeared.
On my main yuzu directory, I usualy copy/paste "user" folder and I finaly found out that deleting \user\config\qt-config.ini solved my problem.
Hope this can help.

**Closed** 2023-11-15 00:30 UTC
