### ISSUE TITLE
Hatsune Miku: Project DIVA Mega Mix game - Desynchronization in the gameplay

### ISSUE THREAD

**Issue by NavyCS** [yuzu-emu/yuzu#4966] opened 2020-11-22 21:10 UTC
When "Use Fast GPU Time" is active, the audio-video is desynchronised (both are synchronised with each other) with the buttons to be pressed on screen, which I will refer to as "gameplay".When you start a song, they start synchronized, but when you advance, the gameplay is "accelerated", making the synchronization lose cumulatively in the course of the song, or in other words, the desynchronization is growing gradually.

When you deactivate "Use Fast GPU Time" you can see an important drop in performance (it is still playable) but the gameplay remains synchronized with the audio-video.
According to the tests I did the responsible would only be the option "Use Fast GPU Time".
The game is only playable with OpenGL.

Sorry for the bad translation.

Yuzu 444 | HEAD-mainline-636-3819-gf992b044b (2020-11-21)
Win10 / GeForce RTX 2070 with Max-Q Desingn/ 16GB RAM / Core-i7-9750H

**Comment by shiro** [comment] 2020-11-29 19:32
It renders perfectly fine with vulkan on a very recent EA build as well, however the desync issue is still present. Might be considered fully playable as soon as this gets resolved.

**Comment by wilkovatch** [comment] 2020-12-09 00:23
It's the same issue as #4592 and #4964, and it's actually caused by multicore.

I also tried disabling Fast GPU Time (both on mainline 444 and 462, Win10, GTX 1070, i7-9700k) and it had no effect (neither for the desync, nor for the performance), while disabling multicore did solve the issue (with a big performance hit) back when the game still booted even with multicore disabled (on mainline 444 and 462 it doesn't).

Anyway, until it's fixed there is actually a workaround: pausing and resuming the game triggers a resync (not ideal, but better than nothing).

**Comment by ActualMandM** [comment] 2020-12-21 05:26
If it's the same issue, then doesn't that mean that this one should be closed in favor of the ones that are already open?

**Comment by leslaliun** [comment] 2021-04-11 15:24
still a issue

**Comment by v1993** [comment] 2021-04-26 15:24
"Fast GPU Time" is a hack in its nature, lying to game about how much time was spent rendering. Not surprising that it causes desync in game that expects long audio tracks to stay synced with video.

Only 100% correct solution is to disable "Fast GPU Time", making the game advance all its timings correctly. As I said, "Fast GPU Time" is hacky, so it *will* break things that expect timing to be correct.

**Comment by willox** [comment] 2021-09-05 13:49
I'm able to reproduce this regardless of CPU accuracy or any graphics/audio settings. All the configs (including "extreme" accuracy graphics and "accurate" CPU) run at 60fps on my machine.

It seems that the gameplay is effectively perfectly synchronized between the native game and Yuzu, but the audio is playing (at least from some measurements on my own PC) at about 47.90400Khz rather than 48Khz. It's my understanding that this would lead to an almost half-second divergence by the end of a 3.5 minute song.

I made a quick hack so that when average interval between the last 1024 calls to `AudioRenderer::QueueMixedBuffer` raises above 5ms (consumption rate of 200/s), `BUFFER_SIZE` gets decremented by 1 - effectively just skipping a sample... I guess. This isn't a fix in any way, but it did lead to the playback frequency oscillating around (and very close to) 48Khz - rather than constantly being slower. The improvement in gameplay was noticeable.

Does anybody familiar with the audio system know what could be going wrong here? Or perhaps somebody has some ideas on where I could start properly looking? I wasn't able to grasp how the audio system actually works so I did a pretty lousy job of figuring anything out.

**Comment by NavyCS** [comment] 2021-12-11 21:49
In yuzu 842 apparently the problem has been solved, no desynchronization is noticeable. If someone else can check it would be good. I'm using Vulkan and all optimizations and hack enabled.

**Comment by wilkovatch** [comment] 2021-12-15 21:36
Checked in yuzu 849, using OpenGL and all optimizations enabled, and I couldn't notice any desynchronization either.

**Comment by tyou634** [comment] 2021-12-18 12:15
Can confirm. yuzu 851. 3060RTX (Laptop), Vulkan with everything default works prefectly.

**Closed** 2021-12-19 04:41 UTC
