### ISSUE TITLE
OpenGL will not work with BOTW 

### ISSUE THREAD

**Issue by tacobellfgc** [yuzu-emu/yuzu#9592] opened 2023-01-09 00:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1296 - Onward

### Description of Issue

After downloading build1296 and beyond, breath of the wild shaders and textures won't load in at all when using opengl, leaving the game unplayable.

### Expected Behavior

Textures and shaders would load in just fine, given the occasional stutter when loading shaders, on prior builds.

### Reproduction Steps

Using BOTW with openGL on an Nvidia card would most likely replicate the issue, but I can't say for sure.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10369857/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 5600
GPU/Driver: NVIDIA RTX 3070 TI (v. 528.02)
RAM: 32 GB
OS: Windows 10

**Comment by PlatinumLucario** [comment] 2023-01-09 03:02
Testing this out on NVIDIA GeForce GTX 950...

It seems that running in OpenGL actually goes in-game, but with a catch:
![Screenshot from 2023-01-09 13-48-40](https://user-images.githubusercontent.com/1906189/211234313-112f19e5-6dc9-4122-b671-3edb8907876f.png)
![Screenshot from 2023-01-09 13-49-59](https://user-images.githubusercontent.com/1906189/211234319-564b1754-e537-401f-8d15-c742aa70c6ed.png)
![Screenshot from 2023-01-09 13-50-17](https://user-images.githubusercontent.com/1906189/211234323-deb42315-f991-4af7-aea2-89d5380d41a7.png)

Here's the log file for more info:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10370106/yuzu_log.txt)

Btw, have you also checked to make sure this option has been disabled?
![Screenshot from 2023-01-09 14-00-13](https://user-images.githubusercontent.com/1906189/211234562-644e2a1d-b501-4452-8d33-fbcf329be173.png)
Because this option (at least for me), has prevented shaders from being loaded. Always make sure it's turned off before loading any games.

**Comment by tacobellfgc** [comment] 2023-01-09 04:32
Yeah that's what I meant by textures and shaders won't load in. Looks exactly like this. And yeah I have that setting turned off.

**Comment by piplup55** [comment] 2023-01-09 08:21
this will be fixed when #9583 is in mainline

**Comment by PlatinumLucario** [comment] 2023-01-10 16:28
I can now confirm that it is fixed as of Mainline 1301, thanks to pr #9583 being merged into mainline.

OGL now works as intended in BotW.
![Screenshot from 2023-01-11 03-19-04](https://user-images.githubusercontent.com/1906189/211606221-523c8833-ed24-4ae3-9954-1957a025f0b4.png)
![Screenshot from 2023-01-11 03-19-18](https://user-images.githubusercontent.com/1906189/211606249-dae697b0-73f7-427e-aee4-5fbcafbe2ea0.png)

Apart from the emulator crashing upon closing the emulator, OGL works as it should. The crash is probably unrelated to OGL.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10384713/yuzu_log.txt)

**Comment by liamwhite** [comment] 2023-01-10 20:35
Fixed by #9583

**Closed by liamwhite** 2023-01-10 20:35 UTC
