### ISSUE TITLE
[ANDROID] PS3 Dualshock 3 controller dpad doesn't work

### ISSUE THREAD

**Issue by AlanbrTKJ** [yuzu-emu/yuzu#12664] opened 2024-01-13 14:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

remapping controls manually

### Why would this feature be useful?

a feature that is sorely missed on the yuzu is manual remapping of controls, I use a ps3 controller via OTG and the dpad is not working, if you know of another way I can solve this problem I would appreciate your help, this problem is limiting a lot of gambling

**Comment by FearlessTobi** [comment] 2024-01-13 14:50
Duplicate of https://github.com/yuzu-emu/yuzu/issues/12190.

**Closed** 2024-01-13 14:50 UTC
Labels: request
