### ISSUE TITLE
Borderlands: Game of the Year Edition Don't Save The Progress 

### ISSUE THREAD

**Issue by hehk1234** [yuzu-emu/yuzu#12112] opened 2023-11-21 05:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1627/Android 137

### Description of Issue

Hello, good evening! 

The game Borderlands: Game of the Year Edition, is having problems saving progress on both Windows and Android, I tested the two most recent public versions and still the game did not show progress. 
There is also a problem selecting characters, the game only selects Roland, even if I put another character, it doesn't go. 
When I try to exit the game and force it to save, it freezes on the "saving progress" screen and doesn't crash, it doesn't display an error, it just stays on that screen. 
I've also tried to force a backup of my save, but the game doesn't recognize it either.  

I'll leave the two logs, both from android and windows. 
[Windows Log.txt](https://github.com/yuzu-emu/yuzu/files/13422063/Windows.Log.txt)
[Android Log.txt](https://github.com/yuzu-emu/yuzu/files/13422065/Android.Log.txt)

### Expected Behavior

![Screenshot_20231121-013938](https://github.com/yuzu-emu/yuzu/assets/7926091/8e94bb43-b2fb-46aa-8974-8000344640a8)

### Reproduction Steps

Try to save progress don't save and the game don't allow to play with another player then Roland. 

### Log File

[Windows Log.txt](https://github.com/yuzu-emu/yuzu/files/13422071/Windows.Log.txt)
[Android Log.txt](https://github.com/yuzu-emu/yuzu/files/13422072/Android.Log.txt)

### System Configuration

CPU: 7940HS 
GPU/Driver: RTX4070/31.0.15.4617
RAM: 40GB DDR5
OS: Windows 11

Smartphone: 
Motorola X40 
Snapdragon 8 gen 2/12GB RAM 
Storage UFS 4.0

**Comment by Squall-Leonhart** [comment] 2023-11-21 06:40
Duplicate of https://github.com/yuzu-emu/yuzu/issues/6738

**Comment by Squall-Leonhart** [comment] 2023-11-21 06:49
Can you supply a save from HW or Ryujinx after having picked a different character

**Comment by hehk1234** [comment] 2023-11-21 12:52
> Can you supply a save from HW or Ryujinx after having picked a different character

Unfortunately the game doesn't detect it in the destination folder, this happens both on Windows and Android, I tried to do the process through ryujinx and from my Nintendo switch the save backup dump, but Yuzu doesn't read the save that's inside the folder.

**Comment by FearlessTobi** [comment] 2023-11-21 14:27
Closing as duplicate.

**Closed by FearlessTobi** 2023-11-21 14:27 UTC

**Comment by Squall-Leonhart** [comment] 2023-11-21 21:02
I need the save to look at the File names and pathing, since this issue is caused by an Invalid Character in the file / path,  its ok that it doesn't work in Yuzu so long as you attach the file

**Comment by hehk1234** [comment] 2023-11-21 21:17
> I need the save to look at the File names and pathing, since this issue is caused by an Invalid Character in the file / path, its ok that it doesn't work in Yuzu so long as you attach the file

[Borderlands Game of the Year Edition.zip](https://github.com/yuzu-emu/yuzu/files/13431044/Borderlands.Game.of.the.Year.Edition.zip)
Here my save dumped from my switch
