### ISSUE TITLE
Street Of rage 4 upside down

### ISSUE THREAD

**Issue by saiyanvip** [yuzu-emu/yuzu#7627] opened 2021-12-24 19:20 UTC
Hi,

I also have Street Of rage 4 upside down https://github.com/yuzu-emu/yuzu/issues/2703#issuecomment-957077831 , it's the only game tested that has this problem.

I am using Batocera v32 (retrogaming special linux), yuzu.AppImage is installed with flatpak., I regularly update Yuzu hoping for a fix, but the problem is still present.

I have a GTX680 graphics card, the Nvdia driver is 470.63.01 paired with an I7 3770k.

Can the bug be corrected by another version or a "patch mod" or is it a problem of compatibility with the driver?

**Comment by Immersion95** [comment] 2021-12-26 08:33
Same thing here with Win11 + AMD 6800 + Vulkan/GL

**Comment by dkoluris** [comment] 2022-02-26 14:17
It is a problem in quite a few games. Streets of Rage 4, Guacamelee 2 to start with.
AMD Radeon 5500M, latest Feb drivers, 4GB VRAM

**Comment by lat9nq** [comment] 2022-02-27 13:13
Duplicate of #2703, which needs to be re-opened

**Comment by dkoluris** [comment] 2022-02-27 13:42
Yup, I have posted logs on the original (Closed) issue if that helps to re-open.

**Comment by cpal023** [comment] 2022-08-14 12:53
Having the same issue with the latest AppImage of Yuzu in Batocera. looked online everywhere and can't find anything.  Is there a patch or fix for this? Thank you!

**Closed** 2022-08-28 09:46 UTC
Labels: gpu-issue

**Comment by Immersion95** [comment] 2022-08-28 17:32
Tried with the latest EA + AMD drivers 22.8.2 and it's still upside down on Vulkan.

**Comment by Immersion95** [comment] 2022-08-30 19:14
Is it possible to reopen this issue ? Should I recreate one ?

**Comment by MrSco** [comment] 2022-10-28 14:40
Is there a fix for this? Its still happening with streets of rage 4 on the steam deck using latest EA 3060 appimage
