### ISSUE TITLE
[Android] Minecraft Dungeons : Sound bug 

### ISSUE THREAD

**Issue by Evananggasubagja** [yuzu-emu/yuzu#12725] opened 2024-01-20 19:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu github V199

### Description of Issue

When I play Minecraft dungeons, I experience a sound bug in Minecraft dungeons

https://github.com/yuzu-emu/yuzu/assets/85387395/265634fb-9c62-47a0-aeca-078d6c74e08d

### Expected Behavior

Please fix this sound bug as it is in yuzu pc
As on this channel: https://youtu.be/qYh8-VWf3fw?si=-Qm_pEy_KsPIrRAN

### Reproduction Steps

Opening the game on the Yuzu Android emulator Wait for loding and after that you can listen to the broken sound

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/13998961/yuzu_log.txt.old.txt)

### System Configuration

CPU: Snapdragon 732G
GPU/Driver: Adreno (TM) 618
RAM: 8GB
OS: Android 12

**Comment by evil-trainer** [comment] 2024-01-20 19:26
Your phone isn't strong enough to run this game at full speed (30fps). This is probably the reason you're experiencing this. But, you can try setting your audio engine in settings between cubeb and oboe. See if that helps.

**Comment by FearlessTobi** [comment] 2024-01-20 22:31
Your speed is too low for audio to be played correctly.
Also, this is a duplicate of an existing issue for this game.

**Closed by FearlessTobi** 2024-01-20 22:31 UTC
