### ISSUE TITLE
Metroid Dread Yuzu crashes after F5 quit

### ISSUE THREAD

**Issue by Hexaae** [yuzu-emu/yuzu#7470] opened 2021-11-29 18:33 UTC
Yuzu mainline build 832.
Metroid Dread, if you press F5 to quit, after the warning saying the game asked Yuzu not to quit, and you quit anyway makes often Yuzu crash a few seconds later after you're back at emulator UI... Expected, since is just beta and because of the warning, but worth mentioning IMHO.

**Comment by german77** [comment] 2021-12-05 02:22
Closing this since it's a duplicate of #7502

**Closed by german77** 2021-12-05 02:22 UTC
