### ISSUE TITLE
Yuzu doesn't release memory after stopping emulation

### ISSUE THREAD

**Issue by thndgonz** [yuzu-emu/yuzu#9328] opened 2022-11-27 17:51 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1252

### Description of Issue

Observed in Arch Linux:

It seems Yuzu doesn't release any of the memory after you stop the emulation. This is observed in titles like Super Mario 3D World

### Expected Behavior

Release the memory after stopping the emulation.

### Reproduction Steps

1. Open up the system monitor of your choosing
2. Open game until it reaches start menu preferrably
3. Notice memory is being used
4. Close game
5. Notice that the memory used isn't released

### Log File

https://gist.github.com/thndgonz/00037edb51a97408452d9ccdd6a09a03 

### System Configuration

CPU: i9-12900KF
GPU/Driver: RTX 3090
RAM: 32gb
OS: Arch Linux

**Comment by FearlessTobi** [comment] 2022-11-27 22:30
Since a few months, this is now the intended behavior.
The memory will only be released when closing yuzu in order to speed up subsequent game boots.

**Closed by FearlessTobi** 2022-11-27 22:30 UTC
