### ISSUE TITLE
Pokemon Let's Go Pikachu doesn't boot after TLOZ Breath of the wild

### ISSUE THREAD

**Issue by kurai021** [yuzu-emu/yuzu#2887] opened 2019-09-21 15:49 UTC
I can't boot Pokemon Let's Go after testing BoW, and BoW starts but gamepad doesn't work again (but it works in configuration). Disable disk shader or reinstall Yuzu (canary or nightly) can't help to fix the problem.

**Comment by FearlessTobi** [comment] 2019-09-21 15:51
This is an issue tracker for developers and not a support forum. Please use the yuzu Discord or the Citra forum for help.

**Comment by Hexagon12** [comment] 2019-09-21 15:52
Duplicate of #2785. If you want to load a new game after a previous one, restart the emulator and don't use Stop.

**Closed by FearlessTobi** 2019-09-21 15:51 UTC

**Comment by kurai021** [comment] 2019-09-21 15:59
Yuzu crashes after restart a game
