### ISSUE TITLE
 Launching Minecraft with latest update doesn't get to title screen

### ISSUE THREAD

**Issue by ThePixelGamer** [yuzu-emu/yuzu#8021] opened 2022-03-14 21:22 UTC
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8248533/yuzu_log.txt)

yuzu 951 [456954b](https://github.com/yuzu-emu/yuzu-mainline/commit/456954b8e4bec6a53c2ff0135795c8f5d5bece10)

When you launch the latest version of minecraft you get stuck on the loading screen with this being at the end of the log.
```
[  40.390093] Debug <Critical> core\hle\service\service.cpp:operator ():158: Assertion Failed!
Unknown / unimplemented function 'GetCacheStorageSize': port='fsp-srv' cmd_buf={[0]=0x6, [1]=0xD, [2]=0x0, [3]=0x0, [4]=0x120001, [5]=0x1, [6]=0x0, [7]=0x0, [8]=0x49434653}
[  40.392053] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1509: (STUBBED) called, result=0x0001A80A
[  40.392225] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:572: Signalling debugger, PANIC! info1=0x0000001015200D18, info2=0x0000000000000004
[  40.392233] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():553: debug_buffer_err_code=1A80A
[  40.392237] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:623: Emulated program broke execution! reason=0x0000000000000000, info1=0x0000001015200D18, info2=0x0000000000000004
[  40.392246] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: Backtrace, sp=0000000000000010, pc=000000001457DFA4
[  40.392249] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:268: Module Name         Address             Original Address    Offset              Symbol
[  40.392250] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:269: 
[  40.430364] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071001464D8    000000001432D4D8    00000000001464D8    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[  40.430373] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100144D80    000000001432BD80    0000000000144D80    _ZN2nn4diag6detail10VAbortImplEPKcS3_S3_iPKNS_6ResultEPKNS_2os17UserExceptionInfoES3_RSt9__va_list
[  40.430375] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100144E54    000000001432BE54    0000000000144E54    _ZN2nn4diag6detail9AbortImplEPKcS3_S3_iPKNS_6ResultES3_z
[  40.430376] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071001F0160    00000000143D7160    00000000001F0160    _ZN2nn2fs19GetCacheStorageSizeEPlS1_i
[  40.430377] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071033DECA4    000000000B3E2CA4    00000000033DECA4    
[  40.430379] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071033E526C    000000000B3E926C    00000000033E526C    
[  40.430380] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071033E0234    000000000B3E4234    00000000033E0234    
[  40.430381] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071033D9C6C    000000000B3DDC6C    00000000033D9C6C    
[  40.430385] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071014F1B80    00000000094F5B80    00000000014F1B80    
[  40.430387] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                00000071033D9738    000000000B3DD738    00000000033D9738    
[  40.430388] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                000000710001E428    0000000008022428    000000000001E428    nnMain
[  40.430391] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071002A4470    000000001448B470    00000000002A4470    _ZN2nn4init5StartEmmPFvvES2_S2_
[  40.430393] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: rtld                00000071000000D0    00000000080000D0    00000000000000D0    
```

**Comment by BSoDGamingYT** [comment] 2022-03-14 21:23
Please upload a complete log

**Comment by ThePixelGamer** [comment] 2022-03-14 21:25
I did, the file is at the top

**Comment by BSoDGamingYT** [comment] 2022-03-14 21:35
Apologies, I am blind.

Duplicate of #7332

**Comment by ThePixelGamer** [comment] 2022-03-14 21:36
All good and sorry for not looking for this issue on the repo

**Closed by BSoDGamingYT** 2022-03-14 21:35 UTC

**Comment by BSoDGamingYT** [comment] 2022-03-14 21:40
All good. Happens to the best of us!
