### ISSUE TITLE
[Azure Pipelines] "Verify Formatting" step in "Format" stage fails

### ISSUE THREAD

**Issue by meiro** [yuzu-emu/yuzu#3895] opened 2020-05-08 16:13 UTC
Docker images now run as user "yuzu" (https://github.com/yuzu-emu/build-environments/commit/2f78410b2b7d818a0ec4b2ccddc92270d188e0fe). Azure Pipelines runs exec.sh, which maps its clone of the repo to /yuzu in the docker image.

docker.sh is then run in the docker image as "yuzu" who does not have permission to write to /yuzu.
**The build currently fails when docker.sh tries to chmod the formatting script "script.sh" in /yuzu.**

This will affect other stages too, as they do most of their work in /yuzu.

[Failing Build](https://dev.azure.com/yuzu-emu/yuzu/_build/results?buildId=4656&view=logs&j=4765973d-8430-5b93-ab6c-b0f18c6f6281&t=e1ef3d02-cc8d-52b7-a9d4-84b481678739)

**Comment by jroweboy** [comment] 2020-05-08 16:55
Should be fixed by https://github.com/yuzu-emu/yuzu/pull/3735

@meiro Hello, this is addressed in https://github.com/yuzu-emu/yuzu/pull/3735/commits/8862af542352a4f4a44d55c0a44cf92054b3c075 which is part of the conan PR. (Please ignore the random debugging stuff, thats removed in the next commit :P) The reason for this change is mentioned in the build-environments PR, its a docker best practice to run the container as a different user, so we need to now chown the folder that gets mounted to the device to UID 1027.

**Comment by meiro** [comment] 2020-05-08 17:21
Ah, I missed that PR.

I reported this because the new docker image broke one of my test pipelines and noticed the failing master pipeline.

Would you like to keep the issue open until it's fixed or shall I close it now?

**Comment by jroweboy** [comment] 2020-05-08 17:30
Ah right, you are working on flatpak support right? https://github.com/yuzu-emu/yuzu/pull/3770/files#diff-5bb99ef7df088d566d94e7e406313b22R4 You'll need to add the chown commands here as well.

**Comment by meiro** [comment] 2020-05-08 17:33
Yes, that's me. ^^

I'll fix my scripts and close this as soon as I got it working, then?

**Comment by jroweboy** [comment] 2020-05-08 17:36
Sounds good 👍

**Comment by superheri** [comment] 2020-05-10 22:39
The problem is still present in mainline build even after the related PR was merged. Seems there is something else to do.

**Closed** 2021-11-03 23:05 UTC
