### ISSUE TITLE
Memory leakage in Pokémon Let's Go Eevee

### ISSUE THREAD

**Issue by DarthJahus** [yuzu-emu/yuzu#1778] opened 2018-11-22 14:15 UTC
Game: Pokémon Let's Go Eevee

Yuzu consumes 9 GB of RAM when the game is started.
It jumps to 11 GB shortly after the save has been loaded.
From there, it slowly rises the amount of used RAM until it completely fills the available space.
The probably to have a soft lock in the game increases drastically at that time; especially if you _switch_ to another program and come back to Yuzu.
Soft locks don't free RAM.

You can see all the steps in the graphics. Max is 15242 MB.

![image](https://user-images.githubusercontent.com/7353366/48907730-9cd4c780-ee68-11e8-8d4c-ecf61ccbc8d6.png)

---

**System specifications**

* Intel Core i3 6100 @ 3.7 GHz
* Gigabyte Aorus RX 570 4 GB
* 16 GB DDR4
* BioStar TB250-BTC motherboard

**Yuzu version**

* Yuzu Canary 1572 (54fe4df)

**Comment by Hexagon12** [comment] 2018-11-22 16:21
Renamed the issue to reflect more on the issue's description.

**Comment by Hexagon12** [comment] 2018-11-22 16:47
@wwylele In this case, we already know that this issue is specifically a memory leak and not just some random "consumption".

**Comment by wwylele** [comment] 2018-11-22 16:48
@Hexagon12 could you give some more explanation? Because I don't see how I can already know it is leak

**Comment by Luffykun007** [comment] 2018-11-22 17:14
@Hexagon12 is reported since July this problem!

https://github.com/yuzu-emu/yuzu/issues/674

**Comment by kevinvanrijn** [comment] 2018-11-25 21:46
Still happening on Canary 1613 with both Pokemon: Let's Go, Eevee and Pokemon: Let's Go, Pikachu though my report might also contain a separate issue.

yuzu eats more and more ram until the game eventually hangs:

![screenshot 2018-11-25 22 38 15](https://user-images.githubusercontent.com/6368561/48985004-7aaaa600-f103-11e8-9f2f-d23f3d83698e.png)

^ The memory leak.

---

After running the game twice yuzu looks like this:

![yuzu-crop](https://user-images.githubusercontent.com/6368561/48985008-84340e00-f103-11e8-85ac-e0085c063852.png)

Note that emulation has stopped but yuzu is still using 10 Gigs of RAM.

---

Closing the game before a hang still results in yuzu not releasing any memory.

Other games release memory properly after stopping emulation.

The only changes I've made to the default settings are disabling single window mode and enabling docked joycons.

**Comment by FlashMau5** [comment] 2018-11-27 12:16
Same issue, and also 1 single core to 100% and the other near 0%
CPU: i7-6700 @ 3.9Ghz
RAM: 12GB 2666Mhz
GPU: AMD r9 390 OC

![screenshot 4](https://user-images.githubusercontent.com/33010589/49081267-95d1fe80-f246-11e8-8d4a-5920e8fcf82c.png)

![screenshot 6](https://user-images.githubusercontent.com/33010589/49081268-95d1fe80-f246-11e8-93c7-3648c4eece8f.png)

**Comment by Yarou** [comment] 2018-11-28 06:17
I was also able to repro this with `Canary 1632 | HEAD-64aa729`.
OS: Windows 10
CPU: i7-7700HQ @ 2.80 GHz (base clock)
RAM: 16 GB
GPU: Nvidia GeForce GTX 1050
Compiler Version: MSVC

Curiously, this does not happen on the precompiled MinGW version. So that would lead me to believe it's an MSVC specific issue. I'd attach Valgrind but sadly there's no Windows version. 

What's perplexing is that this particular ROM causes the issue, so it's *most likely* not related to memory management per se. However, C++ memory management in general tends to be pretty 🤢. I'll dig a bit deeper into the source and report back if I've found anything.

**Comment by burakbir** [comment] 2018-12-09 13:09
> I was also able to repro this with `Canary 1632 | HEAD-64aa729`.
> OS: Windows 10
> CPU: i7-7700HQ @ 2.80 GHz (base clock)
> RAM: 16 GB
> GPU: Nvidia GeForce GTX 1050
> Compiler Version: MSVC
> 
> Curiously, this does not happen on the precompiled MinGW version. So that would lead me to believe it's an MSVC specific issue. I'd attach Valgrind but sadly there's no Windows version.
> 
> What's perplexing is that this particular ROM causes the issue, so it's _most likely_ not related to memory management per se. However, C++ memory management in general tends to be pretty 🤢. I'll dig a bit deeper into the source and report back if I've found anything.

Hi there i have tried several roms and have even ripped the rom my self and still have this issue

**Comment by EtK2000** [comment] 2018-12-10 08:38
It really doesn't matter where you get the ROM.
The issue is in the emulator itself.

**Comment by Hexagon12** [comment] 2018-12-16 16:02
Is this issue fixed in the latest Canary builds?

**Comment by DarthJahus** [comment] 2018-12-16 16:42
Testing on Canary 1711. No overwhelming RAM usage and the curve is pretty consistent after around 20 into the game.

Thank you for your work!

**Comment by Hexagon12** [comment] 2018-12-16 16:45
Fixed by #1890 + #1901.

**Closed by Hexagon12** 2018-12-16 16:45 UTC

**Comment by jschmer** [comment] 2018-12-16 19:39
My tests show that the continous memory increase during runtime is caused by caching the OpenGL surface buffers in RasterizerCacheOpenGL::surface_reserve map. The cache entries are never freed, so this can easily grow by gigabytes in a few minutes, depending on how much new content is displayed.
Not sure if this unbounded cache is by design or if there is some underlying bug.

**Comment by Atraxian** [comment] 2019-03-16 08:18
Currently using Canary build 5cadd46 for windows and can confirm that the use of memory steadily rises until the game stops working.
Seems that every time you change screen (enter a building or a new route) the ram usage kicks up a notch (100 to 200MB)
running on Windows 7 
CPU: i5-6500 3.20GHz
ram 16GB
GPU: Nvidia GeForce GTX 950

**Comment by jschmer** [comment] 2019-05-04 08:19
Looks like the OpenGL surface buffer caching issue was fixed between Canary 2205 and 2235. I no longer see unbounded memory usage.
