### ISSUE TITLE
Animal Crossing: New Horizons doesn't follow yuzu custom RTC TIMES.

### ISSUE THREAD

**Issue by oxluke** [yuzu-emu/yuzu#10127] opened 2023-04-30 22:50 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1415

### Description of Issue

Good morning/afternoon/evening,

I was playing some Animal Crossing: New Horizons on Yuzu, when I wanted to skip a day ahead in-game. I changed the custom RTC time in the settings, and loaded up the game, but it was still the same time as my system clock. If I have the custom RTC option on and set my system clock one day ahead, it also goes one day ahead in-game, even though the custom RTC option is on. I find this to be very strange.

### Expected Behavior

I'd expect the in-game time to be the exact same time as the custom RTC time. As well as that, my system clock should not affect my custom RTC at all, and I shouldn't have to set my system clock to a different time in order to change my in-game time.

### Reproduction Steps

Load up the game, play a bit, save & quit, change custom RTC time, see that this won't change the in-game time (at least it doesn't for me). 

### Log File

Don't think a log file is needed much in this case.

### System Configuration

CPU: AMD Rzyen 7 3700X 8-Core Processor
GPU/Driver: EVGA GEFORCE RTX 2080
RAM: 16GB 
OS: Windows 10,

**Comment by Soggy-Pancake** [comment] 2023-05-04 23:30
I have this issue too. For the custom rtc I have to completely close yuzu before it will apply. The game is completely closed and still doesn't update until yuzu is restarted.

**Comment by Ronshere** [comment] 2023-09-25 21:52
The day in New Horizons starts at 5AM  not 12 midnight.  that is the problem

**Comment by Soggy-Pancake** [comment] 2023-09-27 09:38
The issue is that I can have the rtc set to 5 pm and anch shows 5 pm in game right. I then close the game set the rtc to 7 pm and restart the game from being completely stopped and unless I restart yuzu the time anch detects will not update with the custom rtc until yuzu itself is restarted.

**Comment by pastue363897** [comment] 2023-09-30 16:48
Not related to OP, but there is something which may or may not be related.
I was playing Pokemon Sword and use custom RTC to time travel. I decided to binary search different mainline version and found out that I can no longer change custom RTC without closing yuzu after moving from 1095 to 1096.
In 1095 and earlier, I can F4 to pause the game, go in settings to change the time, say 1 day forward, and F4 to resume. It reflects the time skip in the Poke Jobs being finished.

**Closed** 2023-10-07 14:55 UTC
