### ISSUE TITLE
Debug <Critical> core\hle\kernel\scheduler.cpp:SwitchContext:348: Assertion Failed! Thread must be ready to become running.

### ISSUE THREAD

**Issue by FranciscoReMo** [yuzu-emu/yuzu#2861] opened 2019-09-15 14:14 UTC
First run Pokémon Let's Go Eevee or Pikachu with shader cache and force 30 fps mode, then play 3 or 4 min and stop it. Later, I run game and i see build cache and then yuzu close.
I have Pokémon Let's Go Eevee and Pikachu with update 1.02
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3613835/yuzu_log.txt)

**Comment by Hexagon12** [comment] 2019-09-15 14:16
Duplicate of #2785. You cannot stop and launch the game again currently.

**Closed by Hexagon12** 2019-09-15 14:16 UTC
