### ISSUE TITLE
Splatoon 2 ink and specials problem

### ISSUE THREAD

**Issue by MegaPika** [yuzu-emu/yuzu#8674] opened 2022-07-29 18:45 UTC
Hi heres is my issue :
Yuzu 1108

For the issue i have no idea how it's possible to reproduced no friends of mine have this problem but maybe with someone with the "same" computer specs can do it. (oh and also me and my friends have the same rom and they don't have the problems)

CPU : I5 7400
RAM : 8g ddr4 3666mhz
(i have a sshd for the storage read wikipedia)
GPU : amd rx 570 8g

The issue cannot be in the log file i guess 🤷‍♂️

Here is a video of the problems https://youtu.be/6NYeR28xcxY (my friends was thinking that i hacked so i recorded for them also)
At 
1:15 the game should not give me the special
1:28 the game thinks i'm in the ennemy ink but no
1:50 same even with no ink
2:15 the game should not give me the special
2:35 same
3:11 the same ink problem but as you can see after there is no ink on the bazoo platform and i can go in like it was my own ink
3:25 special problem again
3:40 again
3:55 ink problem here in my ink it's like i'm on ennemy ink same without ink on it and with ennemy like it should do
4:25 special problem again
4:38 same
4:47 same ink problem
5:00 special problem again
5;15 same

As you can the problem is mainly on little platforms or on the "stairs" style platforms

If there is something needed tell me and i will provide ! Yuzu is pretty much my main go because i don't like playing on my switch because i don't have a capture card XD.
Thanks for reading hope there is something i can do 👍

**Comment by lat9nq** [comment] 2022-07-29 18:55
This is a duplicate of either #7855, #4982, or a combination of them.

**Comment by MegaPika** [comment] 2022-07-29 18:59
Oh yeah correct (also when try with mods with maps that have a lot of platforms and things it's almost unplayable with the ink problem)

**Comment by MegaPika** [comment] 2022-07-29 19:20
Also in tower control when i go on top of the tower it's like i'm in the ennemy ink too (with also problems on the wall if i remember) i'm not gonna say everything but it's really like platform or "stairs" related

**Comment by lat9nq** [comment] 2022-07-29 19:29
Duplicate of #4982

**Closed by lat9nq** 2022-07-29 19:29 UTC
