### ISSUE TITLE
Yuzu Crashes when Configure is used on linux

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#3097] opened 2019-11-13 00:58 UTC
This issue is on all distro's i used like arch and fedora and ubuntu 18.04 19.04 and 19.10 and I used lldb to find the error 

also side note I compiled mainline 

[   3.579842] Service.ACC <Warning> core/hle/service/acc/profile_manager.cpp:ParseUserSaveFile:325: Failed to load profile data from save data... Generating new user 'yuzu' with random UUID.
Process 39571 stopped
* thread #9, name = 'Thread (pooled)', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
    frame #0: 0x0000000000000000
error: memory read failed for 0x0

gdb wouldnt work gave Starting program: /usr/local/bin/yuzu 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Temporary breakpoint 1, 0x0000000000551e80 in main ()
(gdb) q

**Comment by exalented** [comment] 2019-11-13 01:11
Just thought I'd throw this out there..
This issue isn't present for all.

**Comment by baconwaifu** [comment] 2019-11-13 01:24
Just built a pull from 20 minutes ago on debian (buster with unstable's libQT and libsdl) and haven't encountered this issue. (built with clang, have GCC-8.3 build in the works to test a different issue)

**Comment by ReaperOfSouls1909** [comment] 2019-11-13 01:52
I have tested Vanilla arch and ubuntu 18.04 19.04 and 19.10 and fedora 31 all have this issue and all are updated

**Comment by 7oxicshadow** [comment] 2019-11-13 14:28
I find that this happens when using the AppImage from the yuzu website but if I build from source (mainline) it works fine for me.

Fedora 31

**Comment by Hexagon12** [comment] 2019-11-13 19:37
Duplicate of #2957

**Closed by Hexagon12** 2019-11-13 19:37 UTC
