### ISSUE TITLE
Poke jobs broken in Pokemon Sword (remaining time is frozen)

### ISSUE THREAD

**Issue by bumpmann** [yuzu-emu/yuzu#5203] opened 2020-12-17 21:06 UTC
If you start a poke job in pokemon sword, they are never completed because the remaining time is frozen. I think there is something wrong with the time functions through the save time and game time are still correct.

Yuzu 476

**Comment by BSoDGamingYT** [comment] 2020-12-17 21:09
Enable custom RTC...move time forwards...Hit OK

**Comment by bumpmann** [comment] 2020-12-17 22:28
@BSoDGamingYT Nice workaround! but it's not synced with the system time ?

**Comment by FearlessTobi** [comment] 2020-12-25 20:54
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4074.

**Closed by FearlessTobi** 2020-12-25 20:54 UTC

**Comment by aecarvalho** [comment] 2022-01-29 07:44
> Enable custom RTC...move time forwards...Hit OK

Unable to get it working even with custom RTC

**Comment by lKobi** [comment] 2022-07-08 07:14
> > Enable custom RTC...move time forwards...Hit OK
> 
> Yep that's the only solution. The correct instruction is WHILE PLAYING THE GAME (preferably get out of the Pokemon center), go to Emulation > Configure > System > select custom RTC, move one day forward, then click okay, now go back and check, your job should be completed.
> 
> Much thanks @BSoDGamingYT it works well!
> 
> P.S. This issue has been resolved IN A WAY, but nobody would keep playing the game for 24 hours straight for a whole day job. The actual fix only works as long as you keep the emulator running.

That solution will trigger the game anti-cheat and stop jobs from respawning in your game, we really need a proper solution for this, Pokemon is a very time based game, with Pokemons and events only happening at a specific time.

This issue is not solved and the emulator needs to integrate real time.

**Comment by Timtam** [comment] 2023-06-21 19:22
I want to second this, running into the same issue right now.
