### ISSUE TITLE
 Unimplemented ioctl 

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3877] opened 2020-05-03 10:09 UTC
error: Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
 Debug <Critical> core\hle\service\nvdrv\devices\nvhost_vic.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
required by gears of unlimited 2

**Comment by callmenemo491** [comment] 2020-05-03 10:48
why open a duplicate ticket?
u put the same info into:  #2643   (yesterday).

**Comment by bukyapavankumar** [comment] 2020-05-03 10:51
Yes but some are stubbed and these are not that's why I opened a new issue

**Comment by Hexagon12** [comment] 2020-05-03 12:32
Duplicate of #2643

**Closed by Hexagon12** 2020-05-03 12:32 UTC
