### ISSUE TITLE
Freeze in instruction pages of Super Smash Ultimate

### ISSUE THREAD

**Issue by Pil0tXia** [yuzu-emu/yuzu#7782] opened 2022-01-26 14:28 UTC
yuzu 890 get freezed in instruction pages of Super Smash Ultimate when only 1 player, such as entering normal battle and any versus except training. When 2 players' gamepads connected (one nitendo pro controller one xbox, both set pro controller in game), only the second player can operate and pagedown the rules. yeah the player 1 can not skip the rules and stucked at the instructions. Which is quiet annoying.
HOPE for your reply! thx
here is the yuzu_log.txt, no records during 2 players connected.
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7943665/yuzu_log.txt.old.txt)

**Comment by behunin** [comment] 2022-01-26 16:53
Please remove the log text from your post and attach the actual log file.

**Comment by PilotXia** [comment] 2022-01-26 17:08
> Please remove the log text from your post and attach the actual log file.

log file uploaded

**Comment by lat9nq** [comment] 2022-02-08 09:51
Duplicate of #5822

**Comment by G-Spawn** [comment] 2022-06-10 03:49
Stability issues with smash should be fixed on latest mainline versions & early access. If it still happens to you please post updated log file

**Closed by G-Spawn** 2022-06-10 03:49 UTC
