### ISSUE TITLE
multiple instances crash when when launching game exept for 1

### ISSUE THREAD

**Issue by mightymariomanlol** [yuzu-emu/yuzu#8757] opened 2022-08-12 18:27 UTC
hello, i was trying to paly super mario odyssey splitscreen, but the multiple isntances crash, is this a new issue because it worked for multiple people sqid it worked for them, but not for me... heres the log 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9329117/yuzu_log.txt)

i really hope they fix it to where to where we can launc h multiple instances with games
its ok  if they dont fix it,. ill just show a video

https://user-images.githubusercontent.com/107736543/184420540-2229f927-d7a4-4757-927f-d5b153b78fbe.mp4

**Comment by german77** [comment] 2022-08-12 18:39
You aren't following the instructions. Have a different portable build for each instance. Each one with it's own copy of the game. Also how in the world you expect to have 4 instances running with 5GB of physical ram. This is even under minimum requirements. The 3050 Ti isn't going to hold up for this task as well.

I recommend having 24 thread cpu with minimum of 32GB of physical ram to be able to keep 4 instances running.  Only then you will be able to actually achieve something.

Duplicate of #8708

**Closed by german77** 2022-08-12 18:39 UTC
