### ISSUE TITLE
[Android] Sliding Input

### ISSUE THREAD

**Issue by santicor3** [yuzu-emu/yuzu#12762] opened 2024-01-23 03:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I'm looking for a way to activate an input by sliding one finger from one button to the next, for example, let's say I was holding the L button, dragged my finger all the way to R, L will continue to be triggered instead of triggering R, I want that to change so that it can change inputs.

### Why would this feature be useful?

Overall would help with my physical disability as well as some others'. Or maybe could help if someone has a hand busy, it could be more accessible that way too. Either way, it's gonna be very helpful if added.

**Comment by FearlessTobi** [comment] 2024-01-23 03:58
Duplicate of https://github.com/yuzu-emu/yuzu/issues/11985.

**Closed by FearlessTobi** 2024-01-23 03:58 UTC
Labels: request
