### ISSUE TITLE
Super Mario Odyssey: Linux navi10 NewTextureCache Green water rendering issues

### ISSUE THREAD

**Issue by hurricane-dorian** [yuzu-emu/yuzu#5145] opened 2020-12-06 18:32 UTC
msvc-source-20201203-1ddda12f1
Linux arch-desktop 5.9.12-zen1-1-zen #1 ZEN S
GL_VERSION: 4.6 (Compatibility Profile) Mesa 20.2.3
GL_RENDERER: AMD Radeon RX 5700 (NAVI10, DRM 3.39.0, 5.9.12-zen1-1-zen, LLVM 11.0.0)
![mario odyssey green water](https://user-images.githubusercontent.com/69684577/101288992-7a9c1100-37c7-11eb-809a-f0b8086b3323.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5649319/yuzu_log.txt)
[glinfo.log](https://github.com/yuzu-emu/yuzu/files/5649320/glinfo.log)

**Comment by goldenx86** [comment] 2020-12-06 18:40
Seems like the RDNA1 driver needs more polish.
Can you try with anisotropic filtering at default?

**Comment by hurricane-dorian** [comment] 2020-12-06 18:43
> Seems like the RDNA1 driver needs more polish.
> Can you try with anisotropic filtering at default?

Same result

**Comment by hurricane-dorian** [comment] 2020-12-06 18:57
Is this related to BC4_UNORM mesa bug mentioned in #4967
https://gitlab.freedesktop.org/mesa/mesa/-/issues/3820

**Comment by ReinUsesLisp** [comment] 2020-12-06 19:18
No. That is not used on Super Mario Odyssey.

**Comment by userofryzen** [comment] 2020-12-27 00:33
Test with vulkan!

**Comment by Olasergiolas** [comment] 2020-12-31 13:36
Exact same issue here after updating to the latest public build with TCR (R9 380 using Mesa git compiled with LLVM12 on Fedora 33)
![new1](https://user-images.githubusercontent.com/32015541/103412405-4244e400-4b75-11eb-84cd-b93e5ea0e314.png)
![new2](https://user-images.githubusercontent.com/32015541/103412409-44a73e00-4b75-11eb-9df7-3e88b3e40526.png)

Everything seems to be properly rendered with an old build
![old](https://user-images.githubusercontent.com/32015541/103412429-57217780-4b75-11eb-97e8-c7e9aab26c15.png)

**Comment by userofryzen** [comment] 2020-12-31 15:43
> Exact same issue here after updating to the latest public build with TCR (R9 380 OpenGL using Mesa git compiled with LLVM12 on Fedora 33)
> ![new1](https://user-images.githubusercontent.com/32015541/103412405-4244e400-4b75-11eb-84cd-b93e5ea0e314.png)
> ![new2](https://user-images.githubusercontent.com/32015541/103412409-44a73e00-4b75-11eb-9df7-3e88b3e40526.png)
> 
> Everything seems to be properly rendered with an old build
> ![old](https://user-images.githubusercontent.com/32015541/103412429-57217780-4b75-11eb-97e8-c7e9aab26c15.png)

But with vulkan is the same or not?

**Comment by Olasergiolas** [comment] 2020-12-31 15:46
> > Exact same issue here after updating to the latest public build with TCR (R9 380 OpenGL using Mesa git compiled with LLVM12 on Fedora 33)
> > ![new1](https://user-images.githubusercontent.com/32015541/103412405-4244e400-4b75-11eb-84cd-b93e5ea0e314.png)
> > ![new2](https://user-images.githubusercontent.com/32015541/103412409-44a73e00-4b75-11eb-9df7-3e88b3e40526.png)
> > 
> > Everything seems to be properly rendered with an old build
> > ![old](https://user-images.githubusercontent.com/32015541/103412429-57217780-4b75-11eb-97e8-c7e9aab26c15.png)
> 
> But with vulkan is the same or not?
> 

With vulkan It's properly rendered but i get out of VRAM crashes and 10-15 fps vs 45-60 on OGL so that's a no go.

**Comment by userofryzen** [comment] 2020-12-31 15:54
> > > Exact same issue here after updating to the latest public build with TCR (R9 380 OpenGL using Mesa git compiled with LLVM12 on Fedora 33)
> > > ![new1](https://user-images.githubusercontent.com/32015541/103412405-4244e400-4b75-11eb-84cd-b93e5ea0e314.png)
> > > ![new2](https://user-images.githubusercontent.com/32015541/103412409-44a73e00-4b75-11eb-9df7-3e88b3e40526.png)
> > > Everything seems to be properly rendered with an old build
> > > ![old](https://user-images.githubusercontent.com/32015541/103412429-57217780-4b75-11eb-97e8-c7e9aab26c15.png)
> > 
> > 
> > But with vulkan is the same or not?
> 
> With vulkan It's properly rendered but i get out of VRAM crashes and 10-15 fps vs 45-60 on OGL so that's a no go.

What vulkan driver? The radv , the amdvlk or amdgpupro ones? With what kernel version?

**Comment by ReinUsesLisp** [comment] 2020-12-31 18:28
It looks similar to when I had blit issues on Vulkan, as if texture view's format was being ignored. I'll try reproducing it on a separate environment.

**Comment by ReinUsesLisp** [comment] 2020-12-31 19:35
I've reported this on mesa's issue tracker https://gitlab.freedesktop.org/mesa/mesa/-/issues/4034 . Hopefully I've reproduced the same issue.

**Comment by ReinUsesLisp** [comment] 2021-01-07 21:04
As an update, in case somebody isn't tracking the mesa issue. A potential reduced version of the bug has been reproduced and a fix is being worked on. I haven't tested if it fixes this particular issue, but it's very likely it will fix other yuzu related bugs.

**Comment by userofryzen** [comment] 2021-01-07 22:10
> As an update, in case somebody isn't tracking the mesa issue. A potential reduced version of the bug has been reproduced and a fix is being worked on. I haven't tested if it fixes this particular issue, but it's very likely it will fix other yuzu related bugs.

I was tracking the issue. But I don't think it can fix the bug with animal crossing New horizons:( I hope the buffer rewrite can to us nearly... Or how cane we test it

**Comment by ReinUsesLisp** [comment] 2021-01-13 21:36
mesa master should have this fixed. I haven't tried it myself yet.

**Comment by userofryzen** [comment] 2021-01-14 01:18
advise us when you test it please.

**Comment by mjrafferty** [comment] 2021-01-14 03:40
I've been tracking this issue for a week or so after running into it myself in Mario Odyssey. I can confirm it is fixed for me after building both mesa and yuzu from master after changes merged in mesa.

**Comment by toccata10** [comment] 2021-02-22 06:48
I have the same problem on a r9 fury. Using mesa-git+llvm-gits solves the problem. The fix is not on the latest mesa stable yet (20.3.4.2). Hopefully, it'll come with mesa21.0 which should release soon.

For those interested in testing without the risk of breaking their mesa install, here's my procedure:
If you want to use mesa-git on Arch to avoid several crashes (+have better performance), you can do this:
1) download mesa-git and llvm-libs-git from https://pkgbuild.com/~lcarlier/mesa-git/x86_64/
2) from mesa-git, copy the content from usr/lib to a new folder, say ~/tmp/yuzu/mesa-git-libs. Do the same for the subfolder usr/lib/dri: copy everything to ~/tmp/yuzu/mesa-git-libs
3) from llvm-libs-git, copy the content from usr/lib to ~/tmp/yuzu/mesa-git-libs
4) launch yuzu by:
LD_LIBRARY_PATH=~/tmp/yuzu/mesa-git-libs/:$LD_LIBRARY_PATH LIBGL_DRIVERS_PATH=~/tmp/yuzu/mesa-git-libs/ EGL_DRIVERS_PATH=~/tmp/yuzu/mesa-git-libs/ mesa_glthread=true ~/tmp/yuzu/latest-yuzu-mainline

**Comment by v1993** [comment] 2021-03-01 11:01
@toccata10 I think you've missed a `~` in `LD_LIBRARY_PATH` before `/tmp`

**Closed** 2022-01-31 07:55 UTC
Labels: gpu-issue, opengl
