### ISSUE TITLE
Linux ubuntu mesa 21.0.0 Super Mario Odyssey only Purple water caused stutter

### ISSUE THREAD

**Issue by lgczszs** [yuzu-emu/yuzu#6023] opened 2021-03-02 08:56 UTC
My native language is not English, so I may not express it well
This is not a cache problem. I have loaded the cache. 

Only Purple water caused stutter

mesa 20.3 no stutter problem
but have Green water problem

**Comment by fmpallini** [comment] 2021-03-17 07:19
I can confirm this is not a Linux exclusive problem. The purple water on the Wooded Kingdom slowish the emulation as I never seen in any other game.

Win, vulkan, amd gpu here.

**Comment by FearlessTobi** [comment] 2021-04-02 13:46
Can you please provide more info for this issue?
Where exactly does it occur, what kind of problems are you facing exactly and can you please also provide a log file?

**Comment by gidoly** [comment] 2022-11-03 08:13
closing due to lack of info and log

**Closed by gidoly** 2022-11-03 08:13 UTC
