### ISSUE TITLE
vk_memory_manager.cpp:Commit:153: Unreachable code!  Ran out of VRAM!

### ISSUE THREAD

**Issue by roger6325** [yuzu-emu/yuzu#3523] opened 2020-03-16 23:14 UTC
When I play as the Link and walk into the warp point in the game - "The Legend of Zelda: Link's Awakening", the GPU will crash and in th log file I found 
the "vk_memory_manager.cpp:Commit:153: Unreachable code!  Ran out of VRAM!" in the Vulkan mode.
Environment:
Macbook Pro 2017 with AMD Radeon Pro 555
yuzu: Early Access 278 
GPU Mode: Vulkan
Here is the log:
229.082492] Render.Vulkan <Critical> video_core\renderer_vulkan\vk_memory_manager.cpp:AllocMemory:202: Device allocation failed with code ErrorOutOfDeviceMemory!
[ 229.082500] Debug <Critical> video_core\renderer_vulkan\vk_memory_manager.cpp:Commit:153: Unreachable code!
Ran out of VRAM!
Here is the log file:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4340735/yuzu_log.zip)
Screenshoot  - Warp Point
![Warp Point](https://user-images.githubusercontent.com/7112171/76807299-daf4b800-681e-11ea-94c6-c0f6e05058f1.PNG)

**Comment by Morph1984** [comment] 2020-03-17 01:48
The issue is exactly that, ran out of VRAM
Your MBP only has 2 GB of dedicated VRAM, and it fills up very fast with Vulkan. Wait for the emulator to be more optimized with it's usage of VRAM.

**Comment by roger6325** [comment] 2020-03-17 11:33
@Morph1984, you are right. Here is memory used by the OpenGL v.s. Vulkan(Dedicated, Dynamic)
OpenGL: 1363MB, 331MB
Vulkan: 1700MB, 3767MB
![OpenGL](https://user-images.githubusercontent.com/7112171/76851338-0d84cc00-6884-11ea-832a-79a5f139d418.PNG)
![Vulkan 2 - ok](https://user-images.githubusercontent.com/7112171/76851345-11185300-6884-11ea-9b7c-3ccbee8fbe92.PNG)

**Comment by FernandoS27** [comment] 2020-03-18 13:57
@roger6325 OpenGL is smarter than our Vulkan backend at managing memory. In Vulkan memory management is done by the user and not the driver. Sadly our memory management is pretty basic.

**Comment by qurious-pixel** [comment] 2020-04-10 22:44
#3586 is not a duplicate of #3523. It occurs only on the latest Nvidia vulkan beta drivers 440.66.03,.04,.07,&.08. Does not happen with 440.64 or 440.82. Also only vulkan program/emulator that crashes with out of memory error.

Nvidia GTX 1060 6GB.
Lubuntu 19.10 / Manjaro 19.01

**Comment by qurious-pixel** [comment] 2020-04-11 03:25
Adding logs
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4463979/yuzu_log.txt)
[gdb.txt](https://github.com/yuzu-emu/yuzu/files/4463981/gdb.txt)

**Comment by iWeaker4you** [comment] 2020-04-28 21:29
This problem was caused in recent versions of the emulator, I have always had the Nvidia beta drivers and it worked wonderfully until after certain builds it stopped working.

**Comment by mirh** [comment] 2020-12-01 20:25
So.. Any special progress on this?
Latest 1165 feels already a bit better than 454 for example, but vulkan still takes like twice the amount of ram than opengl once I factor in ram, vram and pagefile use.

**Comment by german77** [comment] 2022-01-08 05:43
GC has been improved. This still could happen but leaks are pretty minimal at this point

**Closed by german77** 2022-01-08 05:43 UTC
