### ISSUE TITLE
Persona 5 Royal - Occasional Freezes

### ISSUE THREAD

**Issue by WWSNK** [yuzu-emu/yuzu#9174] opened 2022-11-03 18:06 UTC
Occasional freezes keep happening during the game (in the EA and mainline), and at various times. It can happen in 5 minutes, as it can happen in 5 hours of play. I will leave the complete log as well as the exact moment when the freeze happens. Curious that the sound continues to play, but the game is frozen.

`[1523.110187] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1542: (STUBBED) called, result=0x0000EA01`
`[1523.111372] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:711: Signalling debugger, PANIC! info1=0x000000101210DE88, info2=0x0000000000000004`
`[1523.111385] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():692: debug_buffer_err_code=EA01`
`[1523.112129] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:762: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000101210DE88, info2=0x0000000000000004`
`[1523.112133] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:96: Backtrace, sp=000000101210DCD0, pc=000000000BC64F44`
`[1523.112673] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:98: Module Name         Address             Original Address    Offset              Symbol[1523.112676] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:99:`
`[1523.364999] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 00000071003CCF44    000000000BC64F44    00000000003CCF44` 
`[1523.365006] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710016D138    000000000BA05138    000000000016D138    _ZN2nn4diag6detail5AbortEPKNS_6ResultE`
`[1523.365008] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710016B8E8    000000000BA038E8    000000000016B8E8`
`[1523.365009] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710016B9AC    000000000BA039AC    000000000016B9AC    [1523.365011] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710037F7A4    000000000BC177A4    000000000037F7A4
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9931908/yuzu_log.txt)
   _ZN2nn2os6detail36InternalCriticalSectionImplByHorizon8TryEnterEv`
`[1523.365012] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 0000007100371A00    000000000BC09A00    0000000000371A00    _ZN2nn2os11SignalEventEPNS0_9EventTypeE`
`[1523.365013] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: main                0000007101028E9C    000000000902CE9C    0000000001028E9C`    
`[1523.365015] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: main                0000007100FC5504    0000000008FC9504    0000000000FC5504`    
`[1523.365017] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: main                0000007100FC5F24    0000000008FC9F24    0000000000FC5F24`    
`[1523.365019] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 00000071003779F8    000000000BC0F9F8    00000000003779F8`    
`[1523.365020] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710037E014    000000000BC16014    000000000037E014`    
`[1523.365022] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: unknown             0000007100000000    0000000000000000    0000000000000000`

My PC:

Processor: I5 3470
RAM: 8GB
GPU: RX 570 4GB

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9931911/yuzu_log.txt)

**Comment by Emogop** [comment] 2022-11-03 18:33
Can confirm it.
i7 6700 ES
Win 10 21H1
GTX 1060

**Comment by HurricanePootis** [comment] 2022-11-07 06:42
I can confirm it as well
5650U and 5600X
Arch Linux
Compiled with clang, -O3, -march=native, and -flto=thin
RX 580 (ACO Vulkan)

**Comment by HurricanePootis** [comment] 2022-11-08 04:28
In the mean time, I am just playing Persona 5 on RPCS3

**Comment by HurricanePootis** [comment] 2022-11-08 20:54
After playing it without multicore CPU emulation, I didn't encounter any crashes. However, the audio latency introduced by the the lack of multicore is so horrendous, Persona 5 isn't in too grate of a shape right now in Yuzu.

**Comment by JD-The-65th** [comment] 2022-11-13 19:14
I remedied this freeze by setting CPU to unsafe, no issues just yet on Steam Deck.

**Comment by tiagofassoni** [comment] 2022-11-16 19:54
Are you guys having that problem with the Vulkan renderer or with the OpenGL renderer? 

P.S.: Tried to disable multicore CPU emulation, still hangs with the Vullkan renderer. Trying now with OpenGL renderer.

**Comment by JD-The-65th** [comment] 2022-11-16 20:54
> Are you guys having that problem with the Vulkan renderer or with the OpenGL renderer?
> 
> P.S.: Tried to disable multicore CPU emulation, still hangs with the Vullkan renderer. Trying now with OpenGL renderer.

Vulkan

**Comment by HurricanePootis** [comment] 2022-11-16 21:27
> Are you guys having that problem with the Vulkan renderer or with the OpenGL renderer?
> 
> P.S.: Tried to disable multicore CPU emulation, still hangs with the Vullkan renderer. Trying now with OpenGL renderer.

Vulkan. It doesn't hang for me, however, with multicore disabled on Vulkan. I can't use OpenGL due to have many graphical bugs.

**Comment by zc813** [comment] 2022-11-25 06:02
Confirmed similar issue with Collar x Malice on Steam Deck with both Vulcan and OpenGL. Yuzu completely freezes after playing for ~10 minutes. Game and Yuzu UI both become irresponsive.

Disabling multicore emulation DOES SOLVE the crash but results in unstable fps and glitching audio and noisy sounds.

RAM: 12GB total with Yuzu using ~5GB, and still has 5GB free.

**Comment by Ryan2603** [comment] 2022-12-10 04:39
same freezes in Opengl 

[ 984.218975] Service.AM <Warning> core\hle\service\am\am.cpp:SetTerminateResult:1542: (STUBBED) called, result=0x0000EA01
[ 984.219217] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:696: Userspace PANIC! info1=0x000000102CEBEE88, info2=0x0000000000000004
[ 984.219222] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:operator ():677: debug_buffer_err_code=EA01
[ 984.219227] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:746: Emulated program broke execution! reason=0x0000000000000000, info1=0x000000102CEBEE88, info2=0x0000000000000004
[ 984.219228] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:96: Backtrace, sp=000000102CEBECD0, pc=000000000BC64F44
[ 984.219230] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:98: Module Name         Address             Original Address    Offset              Symbol
[ 984.219230] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:99:
[ 984.280087] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 00000071003CCF44    000000000BC64F44    00000000003CCF44
[ 984.280093] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710016D138    000000000BA05138    000000000016D138    _ZN2nn4diag6detail5AbortEPKNS_6ResultE
[ 984.280094] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710016B8E8    000000000BA038E8    000000000016B8E8
[ 984.280095] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710016B9AC    000000000BA039AC    000000000016B9AC
[ 984.280096] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710037F7A4    000000000BC177A4    000000000037F7A4    _ZN2nn2os6detail36InternalCriticalSectionImplByHorizon8TryEnterEv
[ 984.280097] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 0000007100371A00    000000000BC09A00    0000000000371A00    _ZN2nn2os11SignalEventEPNS0_9EventTypeE
[ 984.280098] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: main                0000007101028E9C    000000000902CE9C    0000000001028E9C
[ 984.280099] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: main                0000007100FC5504    0000000008FC9504    0000000000FC5504
[ 984.280100] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: main                0000007100FC5F24    0000000008FC9F24    0000000000FC5F24
[ 984.280101] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 00000071003779F8    000000000BC0F9F8    00000000003779F8
[ 984.280102] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: sdk                 000000710037E014    000000000BC16014    000000000037E014
[ 984.280103] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:104: unknown             0000007100000000    0000000000000000    0000000000000000

**Comment by liamwhite** [comment] 2022-12-19 03:17
May be fixed by https://github.com/yuzu-emu/yuzu/pull/9474

**Comment by HurricanePootis** [comment] 2022-12-19 18:38
> May be fixed by #9474

I am compiling this rn and will see if persona 5 royal still freezes with this patched applied.

**Comment by liamwhite** [comment] 2022-12-19 18:39
Or [download the PR artifact from GitHub](https://nightly.link/yuzu-emu/yuzu/actions/runs/3727532571).

**Closed** 2022-12-19 21:37 UTC
Labels: bug

**Comment by Typo112** [comment] 2022-12-23 11:29
> May be fixed by #9474

Made an account despite not having any background at all on programming just to thank you for this. I've been playing for around 6 hours and it works without any freezes. Thank you for this.

**Comment by AyushArora28** [comment] 2022-12-25 04:15
> > May be fixed by #9474
> 
> Made an account despite not having any background at all on programming just to thank you for this. I've been playing for around 6 hours and it works without any freezes. Thank you for this.
> 
> Do you mind if I share this on a certain repack site?
Well, we're pretty much the same here except I still don't have any idea what to do. Seems like you figured it out, mind helping me?

**Comment by Typo112** [comment] 2022-12-27 05:10
> > > May be fixed by #9474
> > 
> > 
> > Made an account despite not having any background at all on programming just to thank you for this. I've been playing for around 6 hours and it works without any freezes. Thank you for this.
> > Do you mind if I share this on a certain repack site?
> > Well, we're pretty much the same here except I still don't have any idea what to do. Seems like you figured it out, mind helping me?

First, make a backup of your yuzu folder. Second, download the PR artifact here based on whatever OS you're using: 


> Or [download the PR artifact from GitHub](https://nightly.link/yuzu-emu/yuzu/actions/runs/3727532571).

I tried downloading the windows first and it never worked so I tried the others. msvc one worked for me, but I would recommend trying out the msvc first and then the exe file or the windows at the last of the list if it didn't work.

Anyways, after downloading the PR artifact, go extract all the files inside (not the zip itself) into your yuzu folder and click yes if it asks if you want to replace the existing files. If you downloaded the exe file, then you only need to extract the exe file in the yuzu folder and run it instead of running the yuzu.exe you originally used to open.

That's what I did, but I'm not sure if this will work for you since as I said, I'm not literate in programming stuff. I do appreciate if someone will correct my steps though, but so far I haven't had any problems.

**Comment by AyushArora28** [comment] 2022-12-28 05:41
> > > > May be fixed by #9474
> > > 
> > > 
> > > Made an account despite not having any background at all on programming just to thank you for this. I've been playing for around 6 hours and it works without any freezes. Thank you for this.
> > > Do you mind if I share this on a certain repack site?
> > > Well, we're pretty much the same here except I still don't have any idea what to do. Seems like you figured it out, mind helping me?
> 
> First, make a backup of your yuzu folder. Second, download the PR artifact here based on whatever OS you're using:
> 
> > Or [download the PR artifact from GitHub](https://nightly.link/yuzu-emu/yuzu/actions/runs/3727532571).
> 
> I tried downloading the windows first and it never worked so I tried the others. msvc one worked for me, but I would recommend trying out the msvc first and then the exe file or the windows at the last of the list if it didn't work.
> 
> Anyways, after downloading the PR artifact, go extract all the files inside (not the zip itself) into your yuzu folder and click yes if it asks if you want to replace the existing files. If you downloaded the exe file, then you only need to extract the exe file in the yuzu folder and run it instead of running the yuzu.exe you originally used to open.
> 
> That's what I did, but I'm not sure if this will work for you since as I said, I'm not literate in programming stuff. I do appreciate if someone will correct my steps though, but so far I haven't had any problems.
> 
> EDIT: If the yuzu window is now named yuzu | pr-verify (with a bunch of numbers) then it should be working. Also, it's defaulted to be locked to 30 FPS because it's configured to Limit Speed Percent at the configurations every time you run it. You can untick it and you can play for more than 30 FPS. I always untick it and have no problem, but it might be a problem for lower-end PCs.

Thanks alot, it runs smoothly now UwU

**Comment by GenericGirl222** [comment] 2023-06-14 11:56
> > > > May be fixed by #9474
> > > 
> > > 
> > > Made an account despite not having any background at all on programming just to thank you for this. I've been playing for around 6 hours and it works without any freezes. Thank you for this.
> > > Do you mind if I share this on a certain repack site?
> > > Well, we're pretty much the same here except I still don't have any idea what to do. Seems like you figured it out, mind helping me?
> 
> First, make a backup of your yuzu folder. Second, download the PR artifact here based on whatever OS you're using:
> 
> > Or [download the PR artifact from GitHub](https://nightly.link/yuzu-emu/yuzu/actions/runs/3727532571).
> 
> I tried downloading the windows first and it never worked so I tried the others. msvc one worked for me, but I would recommend trying out the msvc first and then the exe file or the windows at the last of the list if it didn't work.
> 
> Anyways, after downloading the PR artifact, go extract all the files inside (not the zip itself) into your yuzu folder and click yes if it asks if you want to replace the existing files. If you downloaded the exe file, then you only need to extract the exe file in the yuzu folder and run it instead of running the yuzu.exe you originally used to open.
> 
> That's what I did, but I'm not sure if this will work for you since as I said, I'm not literate in programming stuff. I do appreciate if someone will correct my steps though, but so far I haven't had any problems.
> 
> EDIT: If the yuzu window is now named yuzu | pr-verify (with a bunch of numbers) then it should be working. Also, it's defaulted to be locked to 30 FPS because it's configured to Limit Speed Percent at the configurations every time you run it. You can untick it and you can play for more than 30 FPS. I always untick it and have no problem, but it might be a problem for lower-end PCs.

How can I implement this now? The PR artifact is no longer available :( :( I'm having the same issue

**Comment by JD-The-65th** [comment] 2023-06-14 16:57
> > > > > May be fixed by #9474
> > > > 
> > > > 
> > > > Made an account despite not having any background at all on programming just to thank you for this. I've been playing for around 6 hours and it works without any freezes. Thank you for this.
> > > > Do you mind if I share this on a certain repack site?
> > > > Well, we're pretty much the same here except I still don't have any idea what to do. Seems like you figured it out, mind helping me?
> > 
> > 
> > First, make a backup of your yuzu folder. Second, download the PR artifact here based on whatever OS you're using:
> > > Or [download the PR artifact from GitHub](https://nightly.link/yuzu-emu/yuzu/actions/runs/3727532571).
> > 
> > 
> > I tried downloading the windows first and it never worked so I tried the others. msvc one worked for me, but I would recommend trying out the msvc first and then the exe file or the windows at the last of the list if it didn't work.
> > Anyways, after downloading the PR artifact, go extract all the files inside (not the zip itself) into your yuzu folder and click yes if it asks if you want to replace the existing files. If you downloaded the exe file, then you only need to extract the exe file in the yuzu folder and run it instead of running the yuzu.exe you originally used to open.
> > That's what I did, but I'm not sure if this will work for you since as I said, I'm not literate in programming stuff. I do appreciate if someone will correct my steps though, but so far I haven't had any problems.
> > EDIT: If the yuzu window is now named yuzu | pr-verify (with a bunch of numbers) then it should be working. Also, it's defaulted to be locked to 30 FPS because it's configured to Limit Speed Percent at the configurations every time you run it. You can untick it and you can play for more than 30 FPS. I always untick it and have no problem, but it might be a problem for lower-end PCs.
> 
> How can I implement this now? The PR artifact is no longer available :( :( I'm having the same issue

This PR is already merged into the main codebase, so check to see if you're using a Yuzu build older than 6 months ago (December 2022)
