### ISSUE TITLE
Android: Games are rendered upside down

### ISSUE THREAD

**Issue by pha123661** [yuzu-emu/yuzu#10584] opened 2023-06-03 03:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 6273e1f2b

### Description of Issue

I am using a foldable phone, Oppo find n2.
The games are rendered upside down when the phone is unfolded:

Pokemon Scarlet:
![photo_2023-06-03_11-08-00](https://github.com/yuzu-emu/yuzu/assets/69206824/527ee3d1-b3a3-42e6-8b52-ba91e6639ced)

Loading screen of Octopath Traveler 2:
![photo_2023-06-03_11-08-02](https://github.com/yuzu-emu/yuzu/assets/69206824/eee50c57-fad4-4b1a-843c-265b794ed5e3)

They are rendered correctly when folded:
![photo_2023-06-03_11-10-40](https://github.com/yuzu-emu/yuzu/assets/69206824/58efa2dd-ae59-4b92-84bb-46b3eebddca0)

Note:
I did not fold/unfold the phone during playing. I kept it unfolded all the time.

### Expected Behavior

It should not be rendered upside down

### Reproduction Steps

1. Unfold the phone
2. Launch yuzu
3. Launch the game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11641581/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 8+ Gen1
GPU/Driver: Adreno 730 with system driver
RAM: 12 GB
OS: Android (Color OS 13)

**Comment by Squall-Leonhart** [comment] 2023-06-03 03:50
Duplicate of #8839

**Comment by eskimododo** [comment] 2023-06-03 06:03
Not really a duplicate as it seems to be unique to oppo foldable phones like the Find N and N2, which opens into landscape mode.. doesn't happen on other foldable phones like Samsung.. it's only a duplicate if it also happens on other devices..

May I suggest to the devs to hack in an option to rotate the viewport 180? It's a workaround, and not a real solution, but at least there's an option there..

![Screenshot_2023-06-02-15-47-52-20_ff30e97793d7c52fedd433a73d8d09b9](https://github.com/yuzu-emu/yuzu/assets/87049724/7c497545-055d-4171-a408-f4840e058fa3)
![Screenshot_2023-06-02-19-45-59-17_ff30e97793d7c52fedd433a73d8d09b9](https://github.com/yuzu-emu/yuzu/assets/87049724/dda7ae39-853d-4af8-af97-acd67f9cce55)

**Comment by FearlessTobi** [comment] 2023-06-03 14:41
Might be related to https://github.com/yuzu-emu/yuzu/issues/10573.

**Comment by eskimododo** [comment] 2023-06-03 17:23
Do let me know if u need any logs or testing done.. open to helping troubleshoot the issue for this unique foldable form factor..

**Comment by eskimododo** [comment] 2023-06-10 13:48
Latest update made things bad..
![Screenshot_2023-06-10-21-42-16-12_ff30e97793d7c52fedd433a73d8d09b9](https://github.com/yuzu-emu/yuzu/assets/87049724/e816ff17-ba57-4a81-a9cf-4f76dd9b0d73)

**Comment by FearlessTobi** [comment] 2023-06-11 20:15
@pha123661 Can you test again if this is fixed now please?

**Comment by pha123661** [comment] 2023-06-12 14:05
@FearlessTobi It works perfectly now. Thank you!
![photo_2023-06-12_22-04-41](https://github.com/yuzu-emu/yuzu/assets/69206824/5651e702-55a7-441a-b56d-c37428b7bf2d)

**Comment by FearlessTobi** [comment] 2023-06-13 17:04
Awesome, thanks for testing!

**Closed by FearlessTobi** 2023-06-13 17:04 UTC
Labels: android
