### ISSUE TITLE
Opening yuzu automatically creates a desktop shortcut if one isn't present

### ISSUE THREAD

**Issue by BrunoDSL** [yuzu-emu/yuzu#12485] opened 2023-12-26 23:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1663

### Description of Issue

As the title says, if you delete the yuzu Desktop shortcut, it will create a new one right after you open the program.

### Expected Behavior

The icon should stay deleted or at least have some option which allows the user to decide if they want a desktop icon or not.

### Reproduction Steps

- Delete the desktop icon
- Open yuzu

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13774116/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 1600AF
GPU/Driver: Radeon RX550. Adrenalin 23.11.1
RAM: 8GB DDR4 
OS: Windows 10 Home x64 22H2

**Comment by liamwhite** [comment] 2023-12-26 23:37
Rerun the installer and untick the option to create a desktop shortcut

Duplicate of https://github.com/j-selby/liftinstall/issues/45

**Closed by liamwhite** 2023-12-26 23:37 UTC

**Comment by BrunoDSL** [comment] 2023-12-27 00:15
Not ideal and not intuitive. And I did uncheck that option in the installer. It's not up to the software to determine how it should place its shortcuts, especially when it's already installed.

**Comment by liamwhite** [comment] 2023-12-27 00:37
The yuzu application does not place any shortcuts on its own - that is entirely on liftinstall.

**Comment by hugojmaia** [comment] 2024-02-07 13:59
By the way, you have to fully uninstall yuzu, then the installer gives you the option to unselect "create desktop shortcut".
Every other option in the installer will NOT allow you to change that option.
