### ISSUE TITLE
The Lara Croft Collection - Shader compilation keeps restarting and game never starts

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#12881] opened 2024-02-01 06:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v222

### Description of Issue

Shader compilation keeps restarting and game never starts

https://github.com/yuzu-emu/yuzu/assets/4172898/5fc03f2d-7dd0-4497-a1ed-34978a211211

### Expected Behavior

the game should start normally

### Reproduction Steps

Just launch game

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/14121240/yuzu_log.txt.old.txt)

### System Configuration

CPU: sd860
GPU/Driver: adreno 640, turnip driver 
RAM: 8gb
OS: android 13

**Comment by Squall-Leonhart** [comment] 2024-02-02 00:09
This should be resolved by #12756

**Comment by Squall-Leonhart** [comment] 2024-02-02 00:14
Duplicate of #10981

**Comment by brujo5** [comment] 2024-02-02 02:30
I think the code has not been updated, I have tried today's version v224 and the problem continues

**Comment by brujo5** [comment] 2024-02-02 02:47
> This should be resolved by #12756

Ok, shader compilation fixed with that PR build but unfortunately the game doesnt boot. Testef with NCE AND Dynarmic

![Screenshot_20240201-194213_yuzu Debug Release](https://github.com/yuzu-emu/yuzu/assets/4172898/262f2073-50a2-4288-84a4-b7509fe7702e)


[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14133484/yuzu_log.txt)

**Comment by Squall-Leonhart** [comment] 2024-02-02 03:03
You didn't boot with turnip.

**Comment by brujo5** [comment] 2024-02-02 03:14
It is the same problem with both turnip and qualcomm drivers, the game does not start and the FPS is at 0

![Screenshot_20240201-201156_yuzu Debug Release](https://github.com/yuzu-emu/yuzu/assets/4172898/7a8505c3-13c1-47a3-9b43-ebdf4306fb55)

**Comment by liamwhite** [comment] 2024-02-02 15:07
Duplicate of #10981

**Closed by liamwhite** 2024-02-02 15:07 UTC
