### ISSUE TITLE
Framepacing issues and stutters with latest Yuzu early access on OpenGL

### ISSUE THREAD

**Issue by sweetenernj** [yuzu-emu/yuzu#7640] opened 2021-12-29 04:42 UTC
So basically there's an issue where the frame pacing is inconsistent at all with Yuzu for Smash Ultimate. I'm not sure if this is an Alder Lake issue, or what but basically the game works and then it stutters and chugs then it smoothens out again, then it stutters and chugs again. I am on the latest Yuzu early access and Nvidia GPU drivers. 

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7787344/yuzu_log.txt)

My specs are 

CPU: Intel Core i7 12700K
GPU: Nvidia RTX 3080
RAM: 5200mhz Corsair Dominator DDR5
SSD: WD SN850
Monitor(s) Alienware AW2521H (360hz) Alienware AW2521HF (240hz)

Video down below:
https://youtu.be/izIbCwXrKkY

**Comment by SpecialDarkwolf999** [comment] 2021-12-29 09:43
Happens with several times for a long time with opengl

**Comment by BSoDGamingYT** [comment] 2022-02-08 12:31
Closing as this is a duplicate of: https://github.com/yuzu-emu/yuzu/issues/5853 (Which you have already opened)

**Closed by BSoDGamingYT** 2022-02-08 12:31 UTC
