### ISSUE TITLE
After upgrading the NVIDIA driver and Windows, it won't work on my Windows 10 PC anymore

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#8614] opened 2022-07-20 08:26 UTC
After upgrading the NVIDIA driver and Windows, it won't work on my Windows 10 PC anymore

Windows 10 （build 10.0.19045.1826）
NVIDIA driver （516.79-hotfix，Geforce GTX 960M）
12GB RAM
Firmware 14.1.1

Ori and the blind forest definitive edition [010061d00db74000] [1.0.1] after opening, the animation will get stuck and flash back after the game starts，The version of Yuzu a month ago did not have this problem

**Comment by G-Spawn** [comment] 2022-07-20 10:43
https://www.nvidia.com/download/driverResults.aspx/189682/en-us/ use this until nvidia figures out how to fix what they broke on newer driver and older gen GPU (pascal or maxwell etc)

**Comment by tet666** [comment] 2023-01-07 11:48
I can confirm this is still an issue with 528.02 with Maxwell cards lots of games crash at boot on Maxwell cards.
And nvidia doesn't really seem to care since they are too busy trying to sell their ridiculously overpriced new cards atm no one wants to buy.
But  yuzu is  still the only vulkan app with issues like that and even works correctly in Ryujinx and Cemu in Vulkan so it would be really nice if maybe someone could look in to it. 

I'm sure there are some old maxwell cards on ebay you could get if you don't have anyone with one or someone could donate one or something like that and there is probably at least some bandaid fix or something like that which could be applied to at least make Vulkan usable again, since with older drivers bugs are starting to appear like FE3H which is currently unplayable on older drivers so downgrading is not always possible.

**Comment by G-Spawn** [comment] 2023-01-07 13:46
Closing issue since op deleted their account anyways.

**Closed by G-Spawn** 2023-01-07 13:46 UTC
