### ISSUE TITLE
Directly connect to a room with a command line argument [LDN]

### ISSUE THREAD

**Issue by nugarp** [yuzu-emu/yuzu#9987] opened 2023-03-24 22:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be great to be able to connect to an LDN room with a command line argument for those of us launching Yuzu from various frontends. For example, running the software as `yuzu.exe -f -g "gamepath\gamefile.extension" -room 192.168.1.1`

### Why would this feature be useful?

Anyone who is using a frontend to launch games may not have immediate access to a keyboard and mouse, and may only have some type of controller connected to the PC. For me, personally, I only have a wheel connected. It becomes difficult to join rooms when we can't preprogram a room to connect to.

Thanks for taking the time read this feature request.

**Comment by FearlessTobi** [comment] 2023-03-24 22:41
Duplicate of https://github.com/yuzu-emu/yuzu/issues/8927.

**Closed by FearlessTobi** 2023-03-24 22:41 UTC
Labels: request
