### ISSUE TITLE
(Android Build) Only Display in Portrait

### ISSUE THREAD

**Issue by Smoker1** [yuzu-emu/yuzu#10510] opened 2023-05-31 00:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 67eac44f6

### Description of Issue

Controls Olverlay shows in Landscape Mode, however, the Game is showing in Reverse Portrait.

### Expected Behavior

Landscape for Both

### Reproduction Steps

Run as normal. Start Emu, Select Game, it will Load it, but the Game will show in Portrait.

### Log File

No Log.
Device is a Samsung Galaxy Tab S7+, 512GB-8GB (SM-T970)

### System Configuration

CPU: Octa-core (1x3.09 GHz Cortex-A77 & 3x2.42 GHz Cortex-A77 & 4x1.80 GHz Cortex-A55
GPU/Driver: Adreno 650
RAM: 8GB
OS: Android 13 - OneUI 5.1

**Comment by EdTheNerd** [comment] 2023-05-31 04:39
Also experiencing this on Galaxy Fold 2.
Orientation of device at game launch time has no impact.

**Comment by sigidessl** [comment] 2023-05-31 14:36
Also happens on my Fold 3 + i´v seen people using Galaxy tabs mentioning the same issue.

**Comment by tcberg2010** [comment] 2023-05-31 15:15
Same device, having the same issue.

Tested with TOTK (crashed after intro anyways), Skyward Sword, and Link's Awakening.

**Comment by denver8989** [comment] 2023-05-31 17:24
Same issue here using a fold 4

**Comment by Omnikam1111** [comment] 2023-06-01 05:59
I'm having the same problem on my Samsung galaxy S9

**Comment by staubd** [comment] 2023-06-01 17:15
same here, Fold 4

**Comment by alex1track** [comment] 2023-06-01 21:52
galaxy tab s8 ultra same issue

**Comment by FearlessTobi** [comment] 2023-06-01 22:08
Thanks for the reports, we are currently fixing this issue and have enough devices reported to reproduce it.

**Comment by vikas2316** [comment] 2023-06-02 10:51
I don't know about other devices but it's still happening on Xiaomi Pad 5 after updating to 6273e1f2b.

**Comment by kbobk** [comment] 2023-06-02 17:56
> I don't know about other devices but it started happening on Xiaomi Pad 5 after updating to [6273e1f](https://github.com/yuzu-emu/yuzu/commit/6273e1f2bde054a4d521d3a2802d36c043c70ed2), previous version was working fine.

Exactly the same for me... The previous build was working fine on my Xiaomi Pad 5.

**Comment by alex1track** [comment] 2023-06-02 22:32
Veesion 67eac44f6 problem fixed on galaxy tab s8 ultra

**Comment by PinciThiago** [comment] 2023-06-02 23:44
> > I don't know about other devices but it started happening on Xiaomi Pad 5 after updating to [6273e1f](https://github.com/yuzu-emu/yuzu/commit/6273e1f2bde054a4d521d3a2802d36c043c70ed2), previous version was working fine.
> 
> Exactly the same for me... The previous build was working fine on my Xiaomi Pad 5.

For me too, updated today and now got this bug in my Xiaomi Mi Pad 5

**Comment by FearlessTobi** [comment] 2023-06-02 23:48
The original issue seems to be fixed, please see this one for the Xiaomi problem: https://github.com/yuzu-emu/yuzu/issues/10573.

**Closed by FearlessTobi** 2023-06-02 23:48 UTC

**Comment by vjjulius** [comment] 2023-06-06 11:31
Im still having this issue. using Lenovo Y700.
both Android mainline and EA.

**Comment by vjjulius** [comment] 2023-06-06 16:21
![Screenshot_20230606-195135](https://github.com/yuzu-emu/yuzu/assets/14800655/e59f9871-bb46-448d-96f0-9772822be810)
![Screenshot_20230606-181813](https://github.com/yuzu-emu/yuzu/assets/14800655/febf3c1f-555c-4ab3-86ac-f53bcc7f99d4)
![Screenshot_20230606-181437](https://github.com/yuzu-emu/yuzu/assets/14800655/1b30fede-b445-4917-ad4a-4274764d44db)

I am still having this issue. I tried opening a new case number but was close :(

I'm currently running Early Access and Mainline 069d7e6be.ver 2023/06/06
