### ISSUE TITLE
Ghosts 'n Goblins Resurrection

### ISSUE THREAD

**Issue by willianholtz** [yuzu-emu/yuzu#11976] opened 2023-11-06 17:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Git Version - r25739.dfbc22c29-1

### Description of Issue

Game does not start unless at any resolution, not even natively (default setting)

I even found something about it here, but it seems to me that the Log error is different!
https://github.com/yuzu-emu/yuzu/issues/8099

### Expected Behavior

Game doesn't get past the first intro scene.

### Reproduction Steps

Just run the game.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13270646/yuzu_log.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13270647/yuzu_log.txt)

### System Configuration

CPU: R7 5700x
GPU/Driver: RTX 2060 12GB
RAM: 64GB
OS: Arch Linux

**Comment by FearlessTobi** [comment] 2023-11-06 19:00
Duplicate of https://github.com/yuzu-emu/yuzu/issues/8099 and https://github.com/yuzu-emu/yuzu/issues/5999.

**Closed by FearlessTobi** 2023-11-06 19:00 UTC
