### ISSUE TITLE
Pretty severe visual issues with Xenoblade Chronicles 3 during Chapter 3/Pentelas region

### ISSUE THREAD

**Issue by PhilDim1** [yuzu-emu/yuzu#8732] opened 2022-08-08 00:12 UTC
Upon entering the mines in chapter 3, there is a cutscene that is visually broken. I can't really explain it, it's just patterns and shapes going nuts, strobing very quickly. I think it may have something to do with a water texture/effect in the game. If you move the camera precisely away from whatever area is causing this in game, you can sometimes stop it. After a particular point in chapter 3, this becomes impossible.

Yuzu EA 2891
AMD RX 5700 XT with latest Radeon 22.7.1 drivers
Windows 10
Vulkan, no visual issues up until this point.

Here's a link to a very small video of this:
https://fastupload.io/en/JqeC3kS73YtlL7M/file
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/9277829/yuzu_log.zip)
[save.zip](https://github.com/yuzu-emu/yuzu/files/9277830/save.zip)

**Comment by Astranabeat** [comment] 2022-08-08 02:40
If you can play on Opengl then just use it to play this map. I'm at end game and this is only map that has visual bug. Even tho other map also have water fall. 

Vulkan'd be playable 100% if this bug don't exist. I hope they fix this bug before I finish the game.

**Comment by PhilDim1** [comment] 2022-08-08 02:57
> If you can play on Opengl then just use it to play this map.
I wish I could. OpenGL crashes after building shaders. Crashes immediately with Ryujinx. I even tried it under linux, and when I take three or four steps it crashes/screen goes black etc. Does this happen with Nvidia cards?

**Comment by witfwdre** [comment] 2022-08-08 11:52
I have the same problem as well, its unplayable right after I get to the cave region. 2888 is surprisingly bearable but the subsequent releases are worst. I will personally donate $30 once this issue gets fixed, thanks!

**Comment by DreadwyrmBahamut** [comment] 2022-08-08 15:15
I have already made an issue on this. 7 versions later and it still has the same issue.....

**Comment by GenericMeow** [comment] 2022-08-08 20:24
> I have the same problem as well, its unplayable right after I get to the cave region. 2888 is surprisingly bearable but the subsequent releases are worst. I will personally donate $30 once this issue gets fixed, thanks!

Is it better on 2888 ? I'm now tempted to try :)

Sadly for AMD GPU users there is no openGL possibility - the game will crash no matter what you do. So Vulkan is the only option for us. I searched a bit and found that this happened in Xenoblade Chronicles 2 as well. According to @goldenx86 it was caused by check issues in/with the driver.

**Comment by PhilDim1** [comment] 2022-08-09 00:54
> Is it better on 2888 ? I'm now tempted to try :)
> 
I found it to be not as blindingly obnoxious, but it was still pretty unplayable :(
Almost like the 'window' to trigger it was slightly smaller, but once you get further in there is no escaping it no matter what.

**Comment by PhilDim1** [comment] 2022-08-09 00:54
> I have already made an issue on this. 7 versions later and it still has the same issue.....
Ah, I was unaware/missed it.

**Comment by DreadwyrmBahamut** [comment] 2022-08-09 02:52
> > I have already made an issue on this. 7 versions later and it still has the same issue.....
> > Ah, I was unaware/missed it.

Its ok, its like 4 posts below yours lol, but yeah, the more people that create a topic on it the better tbh.

**Comment by TheHey78** [comment] 2022-08-09 21:12
I've found that this has also been reported here: [](https://github.com/yuzu-emu/yuzu/issues/8712)

**Comment by witfwdre** [comment] 2022-08-10 07:24
still no fix for this, I have a save that will begin at the next region if anyone wants it.

**Comment by ILoveChiaki** [comment] 2022-08-10 08:40
> still no fix for this, I have a save that will begin at the next region if anyone wants it.

hit me up u need my discord?

**Comment by mistertanooki** [comment] 2022-08-10 10:54
> still no fix for this, I have a save that will begin at the next region if anyone wants it.

I would be interest in this and I imagine many other AMD users as well.

**Comment by Arkrival** [comment] 2022-08-11 02:56
I can Confirm that there is a huge graphics glitches in in chapter 3 when you enter the mines and it get progressively worse throughout that area, and past that. Once you get past that and too the entire next area I had to use Open GL and 10fps through the entire level which took me 4 hrs lol. But it is worth it once you get past that. 

My rig 
CPU: 3900x
Board Gigabyte Aurous Extreme X570
GPU: ASRock Radeon RX 6900 XT PHANTOM GAMING D
RAM: 64gb 3200mhz

**Comment by GenericMeow** [comment] 2022-08-11 13:09
> I can Confirm that there is a huge graphics glitches in in chapter 3 when you enter the mines and it get progressively worse throughout that area, and past that. Once you get past that and too the entire next area I had to use Open GL and 10fps through the entire level which took me 4 hrs lol. But it is worth it once you get past that.
> 

Did you do any side quests or focused only on main story ? I'm curious :)

**Comment by Arkrival** [comment] 2022-08-11 20:14
Yes I did do a few that I could find once I progressed through the main story a bit, but do to the very very low FPS with OpenGL I stopped doing them but I will get to them once that area is resolved of the issue cause I updated Yuzu and it is still very present and horrible.

**Comment by foeken** [comment] 2022-08-17 08:43
Any progress on this ;)?

**Comment by PhilDim1** [comment] 2022-08-17 14:43
> Any progress on this ;)?

No, from what i've read it's either an AMD Radeon driver issue or it's something in yuzu that would require a substantial reworking of code. Or probably both. I could be wrong, I tried reading up on this as much as I could. It will probably take a good long while before this is ironed out, but that's my guess.

**Comment by G-Spawn** [comment] 2022-08-19 05:23
> I've found that this has also been reported here: #8712

^ Closing in favour of existing issue(s)

**Closed by G-Spawn** 2022-08-19 05:23 UTC
