### ISSUE TITLE
[Request] Game update manager or auto update finder

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11455] opened 2023-09-06 05:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

My recommendation is to add an update manager like Ryujinx (let's be honest), or as with mods, if we can manage our mods, why can't we manage updates?

### Why would this feature be useful?

It would be much neater and more intuitive for an emulator of this size. It would be much neater and more intuitive for an emulator of this size, it would be much more practical.

**Comment by Squall-Leonhart** [comment] 2023-09-06 12:12
not sure this needs to be open as a separate issue from whatever is already being tracked for Project Gaia.

**Comment by FearlessTobi** [comment] 2023-09-06 20:49
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/2639 and several similar issues.

**Closed by FearlessTobi** 2023-09-06 20:49 UTC
Labels: request
