### ISSUE TITLE
Attempting to load an encrypted ROM without installed keys results in incorrect NCA2 header error

### ISSUE THREAD

**Issue by anpilley** [yuzu-emu/yuzu#11139] opened 2023-07-23 22:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1504

### Description of Issue

For some users, if they don't follow the quickstart guide carefully enough, can wind up getting an error that implies that they somehow have an invalid rom, instead of just not being able to decrypt it.

![image](https://github.com/yuzu-emu/yuzu/assets/12467241/e8e78deb-1b46-463f-adf5-e4d57f46190b)

The error indicated a header type that was not implemented in yuzu because it was a pre-switch-release NCA format, and isn't supported on released switches.

This error seems to be subject to a race condition. Building yuzu locally and running it, even without a debugger attached results in the expected error (as seen in the Expected Behavior section.)

### Expected Behavior

![image](https://github.com/yuzu-emu/yuzu/assets/12467241/0c9044b6-cbeb-41e8-9353-de7687fdc5ea)

This error should be produced instead. For some people, under different conditions, this is the error they get when trying to reproduce the problem. When building locally, and running without a debugger attached, I get this. Using the mainline 1504 build off of the yuzu website, I get the NCA2 error instead.

### Reproduction Steps

- Get a build of yuzu off of the yuzu website.
- unzip it somewhere.
- Create a user folder inside it.
- Start yuzu. 
- Click through the missing keys and telemetry dialog boxes
- Use File->Load File to load a base game NSP.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12140136/yuzu_log.txt)

### System Configuration

CPU: i7-12700k
GPU/Driver: 3070ti, 31.0.15.3667 (7-12-2023)
RAM: 32GB
OS: Win11 22H2

**Comment by hypersprg** [comment] 2023-07-27 07:23
How do i fix this issue

**Comment by liamwhite** [comment] 2023-08-14 03:17
This is a bug caused by most of the loader results being offset by +2 in #11047 without updating the error strings. This made the error ErrorMissingProductionKeyFile look up the string for ErrorIncorrectHeaderKey (`"The NCA Header key is incorrect or the header is invalid."`) and ErrorMissingHeaderKey map to ErrorNCA2 (`"Support for NCA2-type NCAs is not implemented."`).

Fixed in #11284.

**Closed** 2023-08-21 14:29 UTC
