### ISSUE TITLE
Feature Request - Portrait Mode Support

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#7423] opened 2021-11-23 11:59 UTC
there are a few games that need portrait mode
Arkanoid vs Space Invaders - 0100C56012C96000
Rotating Brave - 01003A300B7A6000
Homo Machina - 010011700D6E2000

**Comment by german77** [comment] 2021-11-23 14:42
duplicate of #4759

**Closed by german77** 2021-11-23 14:42 UTC
