### ISSUE TITLE
Bluetooth 5.0 needs to remove Joycons in bluetooth setting before re-connecting

### ISSUE THREAD

**Issue by SeerZero** [yuzu-emu/yuzu#7493] opened 2021-12-03 20:04 UTC
Bluetooth 5.0 needs to remove Joycons in bluetooth setting before re-connecting, or they will not detected by YUZU, while Bluetooth 4.0 does not.

Environment: Win11   EA-2263   Bluetooth-4.0-Intel   Bluetooth-5.0-Realtek

Replicate:
1. After first connection, turn off the computer Bluetooth switch.  
2. Wait a minute, turn it on, and pressed any key on joycons.
3. Open YUZU.

Result :
1. PC displays that they are connected.  
2. Light of Joycons flicker repeatedly.
3. Joycons are not detected by Yuzu as an input device.

By the way, Bluetooth 4.0 has a huge delay when two joycons are connected at the same time, so I bought this Bluetooth 5.0 chip, but it's not very convenient. Do I need to switch to another brand of chip?

Thanks and best wishes.

**Comment by german77** [comment] 2021-12-03 20:10
This sounds like a SDL driver issue. Not a yuzu issue.

**Comment by SeerZero** [comment] 2021-12-04 19:34
Hope you can continue to promote the solution of the problem in libsdl. Thanks

**Comment by makapaka99** [comment] 2022-04-01 23:55
Is there anything that has been done to resolve this issue?

**Comment by jscoys** [comment] 2022-05-12 00:45
It's definitely "by design".

Nintendo Joycons are BT 4.0 version, not 5.0. Just use a 4.0 dongle that's it.

Yuzu can't do anything as it's a issue between the Joycons and the BT dongle.

**Comment by TheRealToshiRaw** [comment] 2022-08-19 00:23
> It's definitely "by design".
> 
> Nintendo Joycons are BT 4 version, not 5. Just use a 4 dongle that's it.
> 
> Yuzu can't do anything as it's a issue between the Joycons and the BT dongle.

omg thank you very much, that's exactly what i was thinking, but i cannot find any details about this <3

**Comment by Soul-Miku** [comment] 2022-12-06 07:09
Investigating it seems that both the Joycon (L/R) and the Pro Controller, cannot support bluetooth adapters beyond 5.0, if you connect it, but it happens exactly to the person in the post that only when you want to desynchronize or turn off the pc, they will remain connected without ever connecting and will only reconnect if you unpair and sync them and so on, unfortunately it will only work with bluetooth 4.0, if anyone has a solution for bluetooth 5.0 adapters would be kind enough to share the article. , I tried with my TP-Link UB500 which is 5.0 and I did not find a solution so I will go back to my Bluetooth 4.0 and it is a shame since in Version 5.0 I no longer had Input Lag with my Joycon but with the detail that they do not synchronize with just touch a button, so I want to find a solution for the Bluetooth 5.0 version

**Comment by bozis92** [comment] 2023-05-18 21:37
Any solution? I got the same problem

**Comment by german77** [comment] 2023-05-19 16:11
I bought myself a bt 5.0 adapter. Can confirm this issue. There seems no other way to get around this issue other than having to pair the controller each time you want to use it. This issue is on the driver itself way before yuzu can even detect it. 

I'm going to close this issue since it can't be fixed by any yuzu update.

**Closed by german77** 2023-05-19 16:11 UTC
Labels: input
