### ISSUE TITLE
[softlocks][Pokemons Let's Go Pikachu][screen freezed] - HW.GPU <Error> video_core\gpu.cpp:CallPullerMethod:215: Special puller engine method Unk2c not implemented

### ISSUE THREAD

**Issue by gjndual** [yuzu-emu/yuzu#1997] opened 2019-01-06 05:38 UTC
Version:
Canary Build - 6d59172(2019-01-05)

Game:
Pokemons Let's Go Pikachu

My PC:
Intel(R) Core(TM) i5-6400
GPU NVIDIA GeForce 1050ti
8GB Ram
Windows 10 pro

While trying Yuzu with the new Pokemon Let's Go: Pikachu, I faced an intermittent problem:
some time when play the game, this game screen freezed (softlocks,). But, strangely, the game music keeps running, The emulator shows it is running 100%, 60 FPS, if that helps.

this is log file:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/2730192/yuzu_log.txt)

**Comment by Hexagon12** [comment] 2019-01-06 07:03
Duplicate of #1935.

**Closed by Hexagon12** 2019-01-06 07:03 UTC
