### ISSUE TITLE
Xenoblade Chronicles stutters

### ISSUE THREAD

**Issue by snakethesniper** [yuzu-emu/yuzu#9858] opened 2023-02-24 20:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1350

### Description of Issue

Xenoblade Chronicles Definitive Edition with mod for 60 FPS stutters and has high frametimes.

### Expected Behavior

No stutter.

### Reproduction Steps

Just starting the game after the first cutscene, when moving the camera around you can see it stutter

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10828546/yuzu_log.txt)

### System Configuration

CPU: i5-12600K
GPU/Driver: RTX 3070 528.49
RAM: 16 GB
OS: Windows 10

**Comment by gidoly** [comment] 2023-09-21 03:56
should be fixed with yfc 1 and duplicate of closed issue

**Closed by gidoly** 2023-09-21 03:56 UTC
