### ISSUE TITLE
Master Detective Archives: Rain Code - No facial expressions during cutscenes (only works on Open GL GLASM shaders)

### ISSUE THREAD

**Issue by lKomus** [yuzu-emu/yuzu#10986] opened 2023-07-01 20:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1461

### Description of Issue

During non-FMV voiced cutscenes, their facial expressions don't change such as a character lowering their eyebrows when they're angry or when they're moving their lips when they talk.

Tested with Vulkan and High accuracy.

### Expected Behavior

Facial expressions should be working.

### Reproduction Steps

Start a new game. Once you see a cutscene with a ghost talking, her mouth must be moving while she speaks and she gets angry when she prompts you to choose the game difficulty, you can verify this by watching a walkthrough online.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11927073/yuzu_log.txt.old.txt)

### System Configuration

CPU: Ryzen 7 5800X
GPU/Driver: NVIDIA Geforce RTX 3060 Ti (535.98)
RAM: 16 GB
OS: Windows 11 Pro 22H2

**Comment by Squall-Leonhart** [comment] 2023-07-02 06:26
possibly fixed by https://github.com/yuzu-emu/yuzu/pull/10942

**Comment by lKomus** [comment] 2023-07-02 12:29
I've tested on the latest EA now that I don't have a device loss error. No, there are still no facial expressions.

**Comment by konkonchum** [comment] 2023-07-02 15:47
Damn, now I feel stupid because I thought they were supposed to have a blank expressionless face the whole time. Have the same issue.

**Comment by Seibababe** [comment] 2023-07-02 17:26
Change Vulcan to open GL GLASM, worked for me.

**Comment by lKomus** [comment] 2023-07-02 17:34
Well sure but you have to deal with the shader stuttering that comes with it. Plus someone on another issue thread commented that there are texture bugs in OpenGL.

**Comment by Seibababe** [comment] 2023-07-02 17:55
True, but while you wait for the solution you can try playing like this, if you realy badly want to play the game like i do )

**Comment by lKomus** [comment] 2023-07-02 18:10
Heh, I play the game on my Switch. And when the issues are solved I transfer the save to my PC and continue on Yuzu.

**Comment by Seibababe** [comment] 2023-07-02 18:19
Unfortunatly my switch is damaged so i have to play on yuzu to be able to do anything. But now that i managed to get to the first boss i have the same crash as the other guy...

**Comment by lKomus** [comment] 2023-07-02 22:38
Here's a comparison image:

Yuzu Mainline 1484:
![image](https://github.com/yuzu-emu/yuzu/assets/4800879/eb9c5a01-c9c0-4971-b20a-b400704339e9)

Switch Hardware:
![2023070223261700-65A9FA6CA460E1A368EF734B18EDC20B](https://github.com/yuzu-emu/yuzu/assets/4800879/2b3251e9-2a4c-43ac-b6e0-7bca3369014d)

**Comment by william-frst** [comment] 2023-07-06 04:46
still happening in EA 3741

**Comment by Midou36O** [comment] 2023-07-06 21:41
This also happens in OpenGL. No facial expressions.
(Pic unrelated as this is running under Vulkan because of the poor performance of OpenGL in my case. Just confirming the bug.)
![image](https://github.com/yuzu-emu/yuzu/assets/45198486/4c509d7b-4d5f-47d2-88ac-a975c5df74e1)

**Comment by lKomus** [comment] 2023-07-06 22:34
Which shader backend did you choose? GLSL, GL ASM or SPIR-V? Someone said it works with GL ASM.

**Comment by Midou36O** [comment] 2023-07-06 23:24
Ah, this was in SPIR-V (which is experimental, but also solves a lot of graphical glitches i'm encountering compared to GLSL). GL ASM Only works for nvidia GPUs so it's not really a "proper" solution to say :P

**Comment by Midou36O** [comment] 2023-07-06 23:24
Ah, this was in SPIR-V (which is experimental, but also solves a lot of graphical glitches i'm encountering compared to GLSL). GL ASM Only works for nvidia GPUs so it's not really a "proper" solution to say :P

**Comment by lKomus** [comment] 2023-07-07 00:01
Open GLSL is even worse.
![yuzu_JOHabIspzU](https://github.com/yuzu-emu/yuzu/assets/4800879/c15e347d-4bcd-4a68-a06c-730a2248f8ed)

**Comment by RyzenPhoenix99** [comment] 2023-07-07 08:42
Still no known fix for this?

**Comment by raditya26** [comment] 2023-07-07 12:54
The expression works well using GLASM but there's a lot of graphical glitches all over the places that keeps flickering, it's kinda annoying. 
![0100149019460000_2023-07-07_20-49-00-106](https://github.com/yuzu-emu/yuzu/assets/29937774/360ae7fc-55f0-4139-98c6-af43c57f4f6e)
![0100149019460000_2023-07-07_20-51-57-673](https://github.com/yuzu-emu/yuzu/assets/29937774/04994254-4f63-4bdd-b5e6-cd9215840af7)

**Comment by jeancaldron** [comment] 2023-07-13 11:19
please help

**Comment by AJBIRD06** [comment] 2023-07-18 20:26
Anyone found a fix for this on vulkan? I also have this problem

**Comment by jeancaldron** [comment] 2023-07-27 19:43
Please

**Comment by ZeroDivisionDev** [comment] 2023-07-31 15:59
Still present in EA 3781 with Vulkan and GLASM has other bigger issues so that's not really an option.
Hope this won't take ages to get fixed because despite that the game runs pretty much flawlessly.

**Comment by affeeney** [comment] 2023-08-02 11:13
any fixes yet?

**Comment by Squall-Leonhart** [comment] 2023-08-02 11:25
when its fixed, this will be closed and everyone will be notified, no need to bump.

**Comment by EnekoT2001** [comment] 2023-08-15 07:37
For everyone trying to play this game on pc, Ryujinx works fine, you can use Vulkan and the performance (especially ram/vram usage) is on par if not better, facial animations work and there are no graphical glitches (i've had one at some point but simply closing the emulator and opening it again fixed it tbh). So using Ryujinx is the only way to play this game on PC until Yuzu fixes whatever is wrong.

Also, Yuzu can't upscale this game, or at least not properly, it looks very pixelated and weird when I set it at 2x resolution (a bit better than 1x I guess but yeah). Setting 2x in ryujinx looks way better, maybe Yuzu can't emulate some post-processing supersampling effect or something? Idk

Anyway, to transfer your save files from yuzu to ryujinx you can just right click on the game in yuzu and click on "open save data location" and do the same on ryujinx (in this case named "open user save directory") and basically copy-paste the files, i can confirm it works and ryujinx can save/overwrite saves etc. just fine

**Comment by ele3131** [comment] 2023-08-20 23:25
Also, the "cutscene" after chapter solution has some glitches:

![Pixelated](https://github.com/yuzu-emu/yuzu/assets/13533421/e33f8038-2c1c-4f83-9b2d-beef138eb70b)
![pink](https://github.com/yuzu-emu/yuzu/assets/13533421/1be07764-e8d3-426e-b3e4-ee2360cd1556)

**Comment by EnekoT2001** [comment] 2023-08-21 04:08
> Also, the "cutscene" after chapter solution has some glitches:

that never happened to me, weird, are you using vulkan and updated drivers? either way, the only way to play this properly is using ryujinx as i mentioned the other day

**Comment by lKomus** [comment] 2023-09-22 20:08
This should be fixed in the latest EA.

**Comment by EnekoT2001** [comment] 2023-09-22 20:13
I quickly tested the latest EA and indeed it seems to work fine now! nice

**Closed** 2023-09-23 11:00 UTC
