### ISSUE TITLE
Tears of the Kingdom crash as entering the depths insta.

### ISSUE THREAD

**Issue by MaxWPz** [yuzu-emu/yuzu#10277] opened 2023-05-13 18:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acess 3588

### Description of Issue

the game instantaneously crashes as opening in the depths in the vulkan API, and in OpenGL i have 10 fps with texture glitches.

### Expected Behavior

being able to actually go into the depths 

### Reproduction Steps

if i try to TP to the depths or go down through a chams it crashes.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11470369/yuzu_log.txt.old.txt)

### System Configuration

CPU:Ryzen 5 3600
GPU/Driver:RX 570 4GB
RAM:16 Dual Channel 2400 Mhz
OS: Windows

**Comment by ddn40** [comment] 2023-05-14 01:01
same problem

**Comment by MasteJeyu** [comment] 2023-05-14 02:35
same problem 
Personally, I think this problem is related to memory overflow

**Comment by frajusu** [comment] 2023-05-14 02:37
same problem when the game crash i have my ram in 100% i think that is the problem

**Comment by Amer-xyz** [comment] 2023-05-14 03:01
Isn't this a duplicate of #10261 ?

**Comment by MysticExile** [comment] 2023-05-14 05:38
Duplicate of #10261

**Closed by MysticExile** 2023-05-14 05:38 UTC

**Comment by Toilet-Man** [comment] 2023-06-06 21:23
**[[SEMI RESOLVED]]**
For anyone finding this issue thread in the future. Search no further.

**Disable 'Decode ASTC textures asynchronously'** in Emulation > Configure > Graphics > Advanced

If this makes your game lag stutter a bit more after a while, just save and reload, this will fix it.
