### ISSUE TITLE
Remember "Limit Speed"

### ISSUE THREAD

**Issue by Anuskuss** [yuzu-emu/yuzu#11833] opened 2023-10-21 02:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Save the state of "Limit Speed" (aka "Unlock FPS"). Or at least per game.

### Why would this feature be useful?

Some games require unlocked framerate.

**Comment by liamwhite** [comment] 2023-10-21 02:16
Duplicate of #11823

**Closed by liamwhite** 2023-10-21 02:16 UTC

**Comment by Anuskuss** [comment] 2023-10-22 18:05
Both are closed.

**Comment by FearlessTobi** [comment] 2023-10-22 18:19
https://github.com/yuzu-emu/yuzu/issues/10334 is still open.

**Comment by Anuskuss** [comment] 2023-10-22 18:22
Yeah, I saw that issue before opening mine but I don't think it's the same. They're talking about a bug while I'm talking about a feature request, namely the ability to save unlocked speed (per game).
