### ISSUE TITLE
[regression][linux] yuzu crash when stopping emulation

### ISSUE THREAD

**Issue by A-w-x** [yuzu-emu/yuzu#6931] opened 2021-08-27 09:22 UTC
archLinux

it is no longer possible to stop emulation, yuzu crashes instead
no log, it is truncated

**Comment by OZtistic** [comment] 2021-08-28 09:07
Can confirm as of writing that Emulation Stop is bugged even with Single Core in quick testing on Cadence of Hyrule
It seems kind of hit-n-miss between titles
OP also tried Let's GO! as did I, I could not get the same results
side note:
Single core timing is hilariously bad on Cadence

**Comment by v1993** [comment] 2021-08-28 12:46
Likely dupe of #6630.

**Comment by MightyCreak** [comment] 2021-10-16 21:04
I had this issue a few days ago (Fedora 34) but now I can't reproduce it any more with yuzu 781.

**Comment by G-Spawn** [comment] 2022-06-17 06:07
> Likely dupe of #6630.

^

**Closed by G-Spawn** 2022-06-17 06:07 UTC
