### ISSUE TITLE
Missing HLE service command 'IsStandardNetworkSystemClockAccuracySufficient' in 'Time'

### ISSUE THREAD

**Issue by slashiee** [yuzu-emu/yuzu#2636] opened 2019-06-28 16:26 UTC
- Needed by ARMS (4.0.0+?)

Game version needs to be verified, just assuming it based off patch notes

**Comment by Hexagon12** [comment] 2019-06-28 16:29
Duplicate of #2569.

**Closed by Hexagon12** 2019-06-28 16:29 UTC
