### ISSUE TITLE
Ubuntu 18.04 build issue

### ISSUE THREAD

**Issue by Atralb** [yuzu-emu/yuzu#3408] opened 2020-02-13 04:58 UTC
I followed the building guide from yuzu, precisely :

```
sudo apt install libsdl2-2.0-0 libsdl2-dev \ 
qtbase5-dev libqt5opengl5-dev \
build-essential libboost-all-dev \  
cmake

git clone --recursive https://github.com/yuzu-emu/yuzu
cd yuzu
mkdir build && cd build
cmake ../
make -j25
```

This last step is where problems start. It seems to be working well until 97% where I get :
```
[...]
[ 97%] Building CXX object src/yuzu/CMakeFiles/yuzu.dir/configuration/configure_hotkeys.cpp.o
/home/user/gitPrograms/yuzu/src/yuzu/configuration/configure_graphics.cpp:8:10: fatal error: QVulkanInstance: No such file or directory
 #include <QVulkanInstance>
          ^~~~~~~~~~~~~~~~~
compilation terminated.
src/yuzu/CMakeFiles/yuzu.dir/build.make:374: recipe for target 'src/yuzu/CMakeFiles/yuzu.dir/configuration/configure_graphics.cpp.o' failed
make[2]: *** [src/yuzu/CMakeFiles/yuzu.dir/configuration/configure_graphics.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/home/user/gitPrograms/yuzu/src/yuzu/bootmanager.cpp:18:10: fatal error: QVulkanWindow: No such file or directory
 #include <QVulkanWindow>
          ^~~~~~~~~~~~~~~
compilation terminated.
src/yuzu/CMakeFiles/yuzu.dir/build.make:182: recipe for target 'src/yuzu/CMakeFiles/yuzu.dir/bootmanager.cpp.o' failed
make[2]: *** [src/yuzu/CMakeFiles/yuzu.dir/bootmanager.cpp.o] Error 1
[ 97%] Linking CXX executable ../../bin/yuzu-cmd
[ 97%] Linking CXX executable ../../bin/yuzu-tester
CMakeFiles/Makefile2:2815: recipe for target 'src/yuzu/CMakeFiles/yuzu.dir/all' failed
make[1]: *** [src/yuzu/CMakeFiles/yuzu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Built target yuzu-cmd
[ 97%] Built target yuzu-tester
[ 97%] Linking CXX executable ../../bin/tests
[ 97%] Built target tests
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

I still tried a `sudo make install` to see what I would get, and it's practically the same :
```
user@host 13/02/2020 05:00:54 :~/gitPrograms/yuzu/build $ sudo make install
[sudo] password for user: 
[  0%] Built target unicorn-build
[  0%] Built target fmt
[  9%] Built target dynarmic
[  9%] Built target glad
[...]
[ 96%] Built target yuzu_autogen
[ 96%] Building CXX object src/yuzu/CMakeFiles/yuzu.dir/bootmanager.cpp.o
/home/user/gitPrograms/yuzu/src/yuzu/bootmanager.cpp:18:10: fatal error: QVulkanWindow: No such file or directory
 #include <QVulkanWindow>
          ^~~~~~~~~~~~~~~
compilation terminated.
src/yuzu/CMakeFiles/yuzu.dir/build.make:182: recipe for target 'src/yuzu/CMakeFiles/yuzu.dir/bootmanager.cpp.o' failed
make[2]: *** [src/yuzu/CMakeFiles/yuzu.dir/bootmanager.cpp.o] Error 1
CMakeFiles/Makefile2:2815: recipe for target 'src/yuzu/CMakeFiles/yuzu.dir/all' failed
make[1]: *** [src/yuzu/CMakeFiles/yuzu.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

[This](https://github.com/yuzu-emu/yuzu/issues/3375) is the only thread I found with what seems to be the exact same error, on approximately the same system.

However, I have an **Nvidia GPU** contrarily to the OP and have installed the proprietary driver 440.44 for  my work.

```
$ nvidia-smi
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.44       Driver Version: 440.44       CUDA Version: 10.2     |
[...]
```

I never touched Vulkan. People answering seem to think the OP voluntarily did smth to have it work with Vulkan. I did no such thing. I simply followed the instructions given by the github guide. So, I have trouble understanding the advices they give, and if it even applies to me. (I'm actually fearing messing up my system and only doing it worse by following what they say).

My GPU is : 
```
$ glxinfo | grep OpenGL
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce RTX 2080 Ti/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 440.44
[...]

```

Thanks for the help in advance.

**Comment by goldenx86** [comment] 2020-02-13 05:02
Keep in mind that you are trying to build master there, and master will stop execution on any bad assert.
Try building mainline.

**Comment by Atralb** [comment] 2020-02-13 05:12
@goldenx86 Thx for the suggestion. I'll try. Will deleting the git folder be enough to revert all actions of `cmake` and `make` ? (I'm really not familiar with building programs, sorry...)

**Comment by jroweboy** [comment] 2020-02-13 05:13
Hi we are aware of the issue and are working on resolving it. The issue is that the system provided Qt binaries for Ubuntu 18.04 are too old and don't have Vulkan support. Now, you normally would be able to get around this by installing Qt from another PPA that has a newer Qt version (we now require at least 5.10), but I wasn't successful at finding a PPA that has a new enough Qt *and* also enabled Vulkan in the build step for Qt.

So for the time being, you need to compile without vulkan support by passing in `-DENABLE_VULKAN=No` in the CMake step in order to disable Vulkan support. We hope to have a work around so that we can re-enable vulkan on linux soon.

**Comment by Atralb** [comment] 2020-02-13 05:17
@jroweboy I specifically explained that I have a Nvdia GPU and don't use Vulkan at all. I'm kind of a noob regarding drivers, but Vulkan shouldn't apply to me anyway right ? Again, I simply followed the instructions given by the main guide.

**Comment by jroweboy** [comment] 2020-02-13 05:32
@Atralb I'm aware of what you said, but your GPU has nothing to do with this at all :) This is an issue with *building* yuzu, and vulkan is not loaded at build time. Again, this isn't about your GPU or your drivers, this is an issue where there is a problem with how Qt is built (which you installed with apt earlier in the build guide). We don't control how that Qt binary is built, and when I tested other 3rd party Qt builds, they had different problems. As a work around, you can disable the vulkan feature in yuzu which would let you build without that issue, or you can wait for the problem to be worked around in yuzu.

**Comment by Atralb** [comment] 2020-02-13 05:46
@jroweboy Alright, thanks a lot.

**Closed** 2020-02-13 06:03 UTC

**Comment by leifliddy** [comment] 2020-03-17 20:03
@jroweboy 
>The issue is that the system provided Qt binaries for Ubuntu 18.04 are too old and don't have Vulkan support. 

Could you be more specific? What is the minimum version of Qt that's supported?
I'm seeing the same ```QVulkanInstance``` errors when trying to compile yuzu on Fedora 31.
I'm have the qt5 5.13 libraries installed on my system. (the latest version of Qt is 5.14....which was released mid December 2019).
I highly doubt that my issue is that I need to upgrade to qt 5.14

I've compiled yuzu a few times in the past without issue. 
I know I have all of the required qt libraries installed

*the following was run on the latest pre-complied yuzu binary found at:
https://github.com/yuzu-emu/yuzu-mainline/releases

```
[root@black yuzu-linux-20200317-e1b703b69]$ ldd yuzu | grep -i qt
	libQt5WebEngineWidgets.so.5 => /lib64/libQt5WebEngineWidgets.so.5 (0x00007fb637f9f000)
	libQt5Widgets.so.5 => /lib64/libQt5Widgets.so.5 (0x00007fb6370f0000)
	libQt5Gui.so.5 => /lib64/libQt5Gui.so.5 (0x00007fb636bb1000)
	libQt5Core.so.5 => /lib64/libQt5Core.so.5 (0x00007fb63667d000)
	libQt5WebEngineCore.so.5 => /lib64/libQt5WebEngineCore.so.5 (0x00007fb62e49a000)
	libQt5Quick.so.5 => /lib64/libQt5Quick.so.5 (0x00007fb62dfbc000)
	libQt5PrintSupport.so.5 => /lib64/libQt5PrintSupport.so.5 (0x00007fb62df42000)
	libQt5WebChannel.so.5 => /lib64/libQt5WebChannel.so.5 (0x00007fb62df1e000)
	libQt5Qml.so.5 => /lib64/libQt5Qml.so.5 (0x00007fb62da3b000)
	libQt5Network.so.5 => /lib64/libQt5Network.so.5 (0x00007fb62d879000)
	libQt5Positioning.so.5 => /lib64/libQt5Positioning.so.5 (0x00007fb62d7ec000)
	libQt5QuickWidgets.so.5 => /lib64/libQt5QuickWidgets.so.5 (0x00007fb62d7d5000)
```

I'll try upgrading to Qt 5.14 later this week just to be sure....

**Comment by jroweboy** [comment] 2020-03-17 20:09
@leifliddy This is a different issue than the ubuntu 18.04 one. In your case, Qt was compiled without vulkan support. When building Qt, it will look for the Vulkan Headers on the machine and enable/disable vulkan depending on if it can be found. Rodrigo and myself were working on removing the QVulkanInstance and manually setting up the vulkan instance ourselves, but I don't have a linux machine to test on and work on that slowed to a halt.
