### ISSUE TITLE
Black shader after launching and audio is working

### ISSUE THREAD

**Issue by Drkblaz** [yuzu-emu/yuzu#5994] opened 2021-02-24 18:51 UTC
![Screenshot 2021-02-25 001430](https://user-images.githubusercontent.com/79601176/109050305-3f8ee700-76ff-11eb-9b13-7f2c41b420f3.png)
so this is what is happening, it is working and audio is ok too but it shows black shaders or screen. If anyone can help i will be very grateful. Btw this is pokemon sword

**Comment by OZtistic** [comment] 2021-02-27 11:27
@Drkblaz Update your GPU drivers. Everything seems to render fine on updated drivers
There however is currently a memory leak affecting Sword and Shield and possibly other games like Splat 2
https://github.com/yuzu-emu/yuzu/issues/5995#issuecomment-785358562
To mitigate this replace your exe with v456 mainline and use that until a solution is found
https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-456

**Comment by FearlessTobi** [comment] 2021-04-02 14:02
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/6003.

**Closed by FearlessTobi** 2021-04-02 14:02 UTC
