### ISSUE TITLE
[Intel Vulkan] SM3DW Crash Upon Loading Level 1-5

### ISSUE THREAD

**Issue by ameerj** [yuzu-emu/yuzu#6594] opened 2021-07-10 17:22 UTC
Copy of the report by @Masterwolf5800

Super Mario 3d World + Bowser´s fury v1.1.0 crashing at specific level: "Switch Scrumble Circus"
When entering the level the game crashes

Configurations:
undocked, cpu - accurate, multicore
vulkan: use disk shader cache - on, asynchronous gpu emulation - on, nvdec emulation - on, accelerate astc texture decoding - off
adv. graphics: global config: normal, only fast gpu time and cache garbage collection are on, antisotropic filtering - default

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6794527/yuzu_log.txt)

![imagen](https://user-images.githubusercontent.com/69664239/125149148-d2ec1600-e0fc-11eb-9a3b-16d8495fc07c.png)

It only reaches this screen

![imagen](https://user-images.githubusercontent.com/69664239/125149189-18104800-e0fd-11eb-92be-65964406fd9b.png)

Details:

Yuzu early acces 1866
windows 10 pro
Intel core i3-10100, intel graphics UHD 630
2x8 RAM 2666mhz
ssd 240gb

**Comment by FernandoS27** [comment] 2021-07-10 17:24
hmn, would be nice to have a save.

**Comment by ameerj** [comment] 2021-07-10 17:26
Here's a 100% save for SM3DW.
[SM3DW_100_save.zip](https://github.com/yuzu-emu/yuzu/files/6795680/SM3DW_100_save.zip)

**Comment by Tabby4675** [comment] 2021-07-13 11:57
Can confirm. It also happens with my Intel HD 510.

**Comment by soredake** [comment] 2021-07-13 12:07
RX 560 affected too.

**Comment by FernandoS27** [comment] 2021-07-13 13:34
Anyone knows if this happens on NVIDIA as well ?

**Comment by ToxaGaming** [comment] 2021-07-13 13:48
@soredake may I ask which driver version you are running on that AMD GPU? Trying to reproduce on my Vega 8 laptop to see if it may be a driver issue or if the issue is exclusive to one of the AMD GPU architectures

**Comment by Tabby4675** [comment] 2021-07-13 13:50
> @Tabby4675 does this happen with High accuracy as well ?
Yes, I use High accuracy all the time.

**Comment by FernandoS27** [comment] 2021-07-13 13:57
we have identified the issue, we are currently investigating.

**Comment by FernandoS27** [comment] 2021-07-13 13:57
Does this happen on OGL too?

**Comment by soredake** [comment] 2021-07-13 16:49
> 
> @Tabby4675 @soredake Does this happen on OGL too?

No, only on vulkan.

> @soredake may I ask which driver version you are running on that AMD GPU? Trying to reproduce on my Vega 8 laptop to see if it may be a driver issue or if the issue is exclusive to one of the AMD GPU architectures

21.6.1

> 
> @soredake  does this happen with High accuracy as well ?

Yes.

**Comment by BSoDGamingYT** [comment] 2021-07-13 22:46
This should be fixed on latest Early Access build. If you can test

**Comment by Tabby4675** [comment] 2021-07-14 11:11
@BSoDGamingYT I just tested and yes, the issue has been fixed on my Intel GPU, not sure about AMD though.

**Comment by soredake** [comment] 2021-07-14 11:54
Fixed on amd too.

**Closed** 2021-07-15 14:52 UTC
