### ISSUE TITLE
Performance regressions in several games

### ISSUE THREAD

**Issue by Bjorn29512** [yuzu-emu/yuzu#9022] opened 2022-10-06 11:08 UTC
Merge of PR "vulkan: automatically use larger staging buffer sizes when possible" #8987 introduced significant regressions across several titles but also a performance increase in some , all the results that i will be sharing were tested across 3 different setups the first 2 being of Intel CPU + Nvidia GPU and the third one of AMD CPU + AMD GPU, all these setups ran with the best optimized and recommended settings. 

The specs are as follows : 

Setup 1 : 
- 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.82 GiB RAM | TSC: 2.496GHz | AVX-512+ | FMA3
- Operating system: Windows, Major: 10, Minor: 0, Build: 22000
- NVIDIA GeForce GTX 1660 SUPER' running on driver 517.48.0.0

Setup 2 : 
- 12th Gen Intel(R) Core(TM) i5-12400F | 12 Threads | 31.86 GiB RAM | TSC: 2.496GHz | AVX+ | FMA3
- Operating system: Windows, Major: 10, Minor: 0, Build: 19043
- NVIDIA GeForce RTX 2080 Ti' running on driver 516.94.0.0

Setup 3 :
- OS: Arch Linux
- CPU: AMD Ryzen 7 3700X
- GPU: RX6600 XT
- Memory: 80GB, Swap: N/A 
- GPU Driver: Mesa 22.3-devel, radv: 22.3-devel
 
The Results are as Follows : 

BOTW : 

Setup 1 : 
![image](https://user-images.githubusercontent.com/110204265/194291249-bb1c9988-9bb0-4b0f-9c3f-40f5e23e9f2a.png)
![image](https://user-images.githubusercontent.com/110204265/194291271-74c0a9a9-1781-43a4-9c0b-c057de005ad6.png)

Setup 3 : 
![image](https://user-images.githubusercontent.com/110204265/194291393-3e9d6875-4f15-45fd-aaef-5d3478782ec8.png)
![image](https://user-images.githubusercontent.com/110204265/194291422-7e5c58c8-4f32-4d3c-ba58-0e3269119553.png)

SMT 5 : 

Setup 1&2 shared the exact same results : 
1188
![image](https://user-images.githubusercontent.com/110204265/194291707-de3ba5ba-74fa-469b-9442-25631e5245ca.png)
1189
![image](https://user-images.githubusercontent.com/110204265/194291747-22fd6bc5-4589-4e5a-9246-c2182b445e08.png)

SMO : 

Setup 1&2 shared similar results :
![image](https://user-images.githubusercontent.com/110204265/194292096-c603c77b-252b-437a-a4be-bcc93d710f20.png)
![image](https://user-images.githubusercontent.com/110204265/194297856-9d96618b-11f7-4808-9d80-d7c703080a56.png)

Setup 3 : 
![image](https://user-images.githubusercontent.com/110204265/194292406-0cf8cb55-cac2-454d-9f2d-58e465ebe7a7.png)
![image](https://user-images.githubusercontent.com/110204265/194297441-4b1b276f-7a72-4ccc-a85c-0b820194a6c4.png)

POKEMON SW :

Setup 1&2 shared same results again : 
![image](https://user-images.githubusercontent.com/110204265/194295542-ed3a436c-7d87-437c-b0a6-db16c27c4d77.png)
![image](https://user-images.githubusercontent.com/110204265/194293045-fc92ea4b-320b-4d62-adc3-4b5fea5926f9.png)

XB 3 : 

This was the exception as Setup 1 here noticed significant performance improvement contrary to the trend.

Setup 1 :
![image](https://user-images.githubusercontent.com/110204265/194293561-4d6c71c6-4d8e-4cb2-af83-c8ea5c1f3484.png)
![image](https://user-images.githubusercontent.com/110204265/194293601-6c78d6dc-c0e1-44d5-b6a8-2782f1e04cb7.png)

As you can see from these results that while there were regressions noticed across several games for 1&2 there were also a few where there were quite significant performance increases, whereas setup 3 noticed a performance increase across the board in general. 
This brings me to the second half of this report ie. the feature request of implementing this PR as a toggle setting in Advanced Graphics option that can be disabled by default and enabled by the user as per the requirement and their setup without hurting the end user experience too much instead of completely reverting the PR, while Intel+Nvidia setups seem to mostly suffer they still benefit in a few exception titles and Amd users seem to benefit in general which is also a significant user base

EDIT: Attached Save Files for testing.

[BOTW.zip](https://github.com/yuzu-emu/yuzu/files/9744942/BOTW.zip)
[SMO.zip](https://github.com/yuzu-emu/yuzu/files/9744953/SMO.zip)
[SMT 5.zip](https://github.com/yuzu-emu/yuzu/files/9744955/SMT.5.zip)
[XB 3.zip](https://github.com/yuzu-emu/yuzu/files/9744957/XB.3.zip)
[POKEMON SW.zip](https://github.com/yuzu-emu/yuzu/files/9744969/POKEMON.SW.zip)

**Comment by ChouGary** [comment] 2022-10-07 02:04
can you test lego incredibles ? 
my NVIDIA GeForce GTX 1060 only half speed at title.

**Comment by Bjorn29512** [comment] 2022-10-07 10:33
> can you test lego incredibles ? my NVIDIA GeForce GTX 1060 only half speed at title.

gpu is mostly irrelevant whats your cpu ?

**Comment by OZtistic** [comment] 2022-10-08 11:59
I am not 100% sure the staging buffer PR is the cause of this. 
I have issues as well across a few titles with the pre-built yuzu binaries, but when I compile myself all the issues magically disappear

**Comment by solarmystic** [comment] 2022-10-09 11:10
> @Bjorn29512 could you run a test using the 512.95 drivers and report back, with those yuzu versions? The Staging Buffer PR was reverted not to long ago. I am just curious if you get the same symptoms with the recommended 512.95 driver

Hello there, just to chime in, I've tested on drivers 511.79, 512.95 and 516.94 - all of them exhibit the same performance regression after the Staging buffer PR got merged to master.

**Comment by gidoly** [comment] 2022-11-07 05:12
closes due to pr that caused issue have been revert

**Closed by gidoly** 2022-11-07 05:12 UTC
