### ISSUE TITLE
Time bar ACNH doesn't show

### ISSUE THREAD

**Issue by Techttv** [yuzu-emu/yuzu#5845] opened 2021-01-29 23:22 UTC
The time in the time bar doesn't show and the text In the first app of the nook phone too.
![yuzu 521 _ Animal Crossing_ New Horizons               29_01_2021 22_30_41](https://user-images.githubusercontent.com/62478271/106337301-20806f00-6291-11eb-801f-662b34f5b287.png)

**Comment by german77** [comment] 2021-01-29 23:37
This is fixed in #5241

**Comment by Techttv** [comment] 2021-01-30 05:45
So why I have this problem yet? I'm using the latest version of yuzu but I use bulkam not opengl. Maybe is ths the problem? And another question. Why yuzu don't use at all the ram ? Cause when I play ACNH I have only 24fps but yuzu use only 2gb of ram

**Comment by Zeroksas** [comment] 2021-01-30 06:03
> So why I have this problem yet? I'm using the latest version of yuzu but I use bulkam not opengl. Maybe is ths the problem? And another question. Why yuzu don't use at all the ram ? Cause when I play ACNH I have only 24fps but yuzu use only 2gb of ram
The fix is not yet in mainline version only on EA. As for answer for your second question - yuzu is emulating switch which only have 4GB of RAM so it's normal. To have good fps rate must have powerful CPU and not so old GPU - RAM is not that important.

**Comment by Techttv** [comment] 2021-01-30 06:13
Ok so I'll wait for the fix 👍🏻
I check the cpu usage and yuzu use only the 25%-50% and the GPU usage 30-50%. And I have already oc they.

**Comment by Zeroksas** [comment] 2021-01-30 06:48
> Ok so I'll wait for the fix 👍🏻
> I check the cpu usage and yuzu use only the 25%-50% and the GPU usage 30-50%. And I have already oc they.

That is also normal - Switch CPU only has 4 cores and current CPUs have 8+. Emulator don't use all the cores available.

**Comment by Techttv** [comment] 2021-01-30 06:54
Oh, ok.
So AMD CPUs are disadvantaged rip.
In the furure the emulator will try to use all cores?

**Comment by FearlessTobi** [comment] 2021-01-30 21:48
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/3918.

**Closed by FearlessTobi** 2021-01-30 21:48 UTC
