### ISSUE TITLE
Speed regression Android 252+

### ISSUE THREAD

**Issue by RickSelden** [yuzu-emu/yuzu#13103] opened 2024-02-21 11:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 252+

### Description of Issue

Significant speed regression on Retroid Pocket 4 Pro: Dimensity 1200 / Mali, test game Super Mario 3D World

### Expected Behavior

60fps @ 0.5x res

### Reproduction Steps

Running any level of SM3DW:

version <= 251: 60fps (true certainly in recent 24X builds)
version > 251: 40ish fps

Confirmed by progressively rolling back versions from 253 until speed was restored.  Discovered culprit is in the commits changing v251 to v252.

### Log File

There weren't that many commits between 251 and 252 :/

### System Configuration

CPU: MediaTek Dimensity 1200
GPU/Driver: ARM Mali-G77 MP9
RAM: 8Gb
OS: Android 13

**Comment by liamwhite** [comment] 2024-02-21 13:39
Try disabling vibration

**Comment by RickSelden** [comment] 2024-02-21 13:50
> Try disabling vibration

Confirmed, this does restore frame rate 👍

**Comment by liamwhite** [comment] 2024-02-21 14:33
Duplicate of #13101

**Closed by liamwhite** 2024-02-21 14:33 UTC
