### ISSUE TITLE
Final Fantasy 8 Remastered Regression

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#3541] opened 2020-03-21 14:15 UTC
This title went from Playable to soft locking at boot between Mainline 148 and Mainline 149.

148
![148](https://user-images.githubusercontent.com/38402209/77228302-ad916c80-6b86-11ea-8ba2-f027b9cf7bee.PNG)

149
![149](https://user-images.githubusercontent.com/38402209/77228305-b2eeb700-6b86-11ea-8bca-8056c2c67236.PNG)

Log from the softlock on M 149
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4363150/yuzu_log.txt)

**Comment by FearlessTobi** [comment] 2020-03-21 14:58
https://github.com/yuzu-emu/yuzu/pull/3366 This is very likely the cause.

**Comment by BSoDGamingYT** [comment] 2020-03-26 22:49
Fixed with PR 3563: https://github.com/yuzu-emu/yuzu/pull/3563

**Comment by slashiee** [comment] 2020-03-26 22:51
The PR wasn't merged into master yet.

**Comment by FernandoS27** [comment] 2020-03-26 23:09
Close it, once merged.

**Closed** 2020-04-03 14:14 UTC

**Comment by SpecialDarkwolf999** [comment] 2021-12-08 14:07
this game doens't even boot anymore with main line 841 on opengl and vulkan, keeps saying : 
[ 175.523140] Service.NVDRV <Warning> video_core\command_classes\vic.cpp:Execute:94: Frame dimensions 1920x1088 don't match surface dimensions 1920x1080
[ 175.529786] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWait:86: (STUBBED) called, input_id=0x1, min=0xABA9500, max=0xFFFFFFFF
