### ISSUE TITLE
Problems Operating Analog Stick with Keyboard (Diablo 3)

### ISSUE THREAD

**Issue by Samsik2** [yuzu-emu/yuzu#4580] opened 2020-08-25 09:35 UTC
Analog sticks in the Diablo 3 console board use a method called 14 axis rather than a typical 8 axis.

![114](https://user-images.githubusercontent.com/70080561/91158482-a6582700-e701-11ea-8aa4-a4acc712afb7.png)

So I can't select the equipment marked in yellow.

The same problem occurred in RPCS3, but the link below seems to have been resolved.

https://github.com/RPCS3/rpcs3/pull/5468
Add mouse movement and stick lerp settings

If YUZU can implement these functions, we would like you to add them.

**Comment by german77** [comment] 2020-11-07 00:32
duplicate of #2845

**Comment by german77** [comment] 2021-07-09 00:07
Fixed by #4905

**Closed by german77** 2021-07-09 00:07 UTC
