### ISSUE TITLE
Unicorn fallback issue 0x8000000 prevent KgDoom from booting (with dynarmic and I think with Unicorn too)

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#244] opened 2018-03-17 13:38 UTC
## Hardware Specs :
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 Pro
 
## Yuzu build version used :
Yuzu Nightly build HEAD-516ef4f

## Issue :
Push A NX and KgDoom don't boot because of infinite repeat of the unicorn fallback issue 0x8000000.
And in unicorn it's seems to do the same because there is a freeze in the console i mean and nothing display anymore in the console, so I think the unicorn fallback issue won't be displayed with unicorn.

## Logs : 

- Push A NX Log : [Click Here](https://gist.github.com/greggameplayer/37d5c1716c0d04ff735b02ed582da832)
- KgDoom : [Click Here](https://gist.github.com/greggameplayer/1de33acaca9d462ad17cce4508441e94)

**Comment by gdkchan** [comment] 2018-03-17 14:56
This issue is most likely caused by the NRO being compiled with old libtransistor, so the instruction at 0x8000000 is actually 0 (not a valid opcode). Nothing to fix here if that's the case.

**Comment by greggameplayer** [comment] 2018-03-17 15:11
before it work so why it doesn't work now ?
And if that the case you can add support of old libtransistor ?

**Comment by N00byKing** [comment] 2018-03-17 17:01
Why in the World would one add support for a broken Framework @greggameplayer? The Emulator needs to stay accurate. If the old libtransistor does not work correctly, it absolutely should not work correctly in the Emulator too.

**Comment by greggameplayer** [comment] 2018-03-17 18:08
ok so delete these homebrew of the yuzu homebrew page

**Comment by Hexagon12** [comment] 2018-03-23 08:50
These programs properly work on the Unicorn CPU Core, so there's no need for deleting. It's more than likely that the issue is in Dynarmic itself.

**Comment by N00byKing** [comment] 2018-03-23 10:41
@greggameplayer If that is the case please remove the "I think unicorn too" from the title

**Comment by greggameplayer** [comment] 2018-03-23 19:09
@N00byKing no, the problem is also on Unicorn or it's another problem because we can't see any fallback or errors in the console and nothing is displayed on yuzu main screen.

**Comment by N00byKing** [comment] 2018-03-23 19:11
Huh? Didnt @Hexagon12 just say that the errors were only on Dynarmic? Someone clear this up...

**Comment by greggameplayer** [comment] 2018-03-23 19:13
@N00byKing no it's clearly not only on Dynarmic and i have notice that fallback appear too on SpaceNX.nro but not on SpaceNX.nso. So in my opinion it's an nro problem.

**Comment by Hexagon12** [comment] 2018-03-23 19:16
The fallbacks are only applicable to Dynarmic, such a thing does not happen on Unicorn, since it's the fallback itself.

**Comment by greggameplayer** [comment] 2018-03-23 19:20
So it's a different error in Unicorn i presume. If it's the case, i will open a new issue for it.

**Comment by Hexagon12** [comment] 2018-03-23 19:21
No. It's a issue with Dynarmic only. Unicorn doesn't have any issues.

**Comment by Hexagon12** [comment] 2018-03-23 19:24
It's a issue on your part. Please redownload the latest homebrew examples on the wiki page and test them with the latest Nightly.

**Comment by MerryMage** [comment] 2018-03-23 20:39
Seems like user error. Close pls.

**Comment by greggameplayer** [comment] 2018-03-23 22:42
why i have to redownload nro but nso file just working fine ?

**Comment by simontoft** [comment] 2018-03-23 22:43
gdkchan explained that in the very first comment.

**Comment by greggameplayer** [comment] 2018-03-23 22:43
redownload work for Push a NX but for kgdoom it's not working

**Comment by Hexagon12** [comment] 2018-03-24 07:48
KgDoom is not supposed to boot anyway because of unimplemented BSD functions.

Requesting to close this issue altogether.

**Closed** 2018-03-24 17:15 UTC
