### ISSUE TITLE
[Feature Request] Consider to add AMD FidelityFX Super Resolution (FSR) support in Yuzu ? 

### ISSUE THREAD

**Issue by Tikilou** [yuzu-emu/yuzu#6847] opened 2021-08-09 00:35 UTC
Hi Yuzu team !! 

AMD FSR (FidelityFX Super Resolution) add the possibility for any harware platform/OS to a good upscaling with less CPU/GPU ans so much less energy than a native resolution (HD, 4K...)
AMD FSR use spatialization (Nvidia DLSS use vectorisation), for example, RPCS3 emulator have implemented it recently. [https://wccftech.com/new-tools-allow-amd-fsr-injection-in-rpcs3-emulator-and-potentially-in-every-game/]

It could be a good solution for better performances on high resolution for many devices, and less energy consumption on laptop, or others devices with battery.

**Comment by Moonlacer** [comment] 2021-08-09 00:38
Native resolution scaling will be coming soon. FSR has already been tested on yuzu and the results are not good without some major changes

**Comment by goldenx86** [comment] 2021-08-09 00:43
FSR works as intended in high resolutions. Switch games render usually at 900p or lower, giving FSR very little information to work with.
In the end it just results in sharpening being applied to the image, something that's already possible with Radeon Image Sharpening, or Nvidia's Control Panel Sharpening settings.

We can consider looking at this again after the scaler is finished, but it won't be a priority for now.

**Comment by BreadFish64** [comment] 2021-08-09 00:55
I attempted to add FSR to yuzu the day the source code released, but the results were unimpressive. Like golden said, a spacial upscaling filter like FSR can only enhance details that are in the original image. So a low resolution input is not going to it any favors. For similar reasons, FSR works horribly unless the game is already running a good anti-aliasing algorithm, because FSR will just take the aliasing and upscale that too. It doesn't do much to "pixelated" edges in my experiments.
If someone wanted to add it still, then they would need to make sure that the upscaling filter can access the original sized framebuffer before the game scales it to the Switch's output resolution, otherwise it will again just upscale the pixelated edges. iirc this would require some heuristics to figure out what framebuffer that is.

**Comment by benderscruffy** [comment] 2021-08-09 08:48
duplicate of #6524

**Comment by v1993** [comment] 2021-08-09 10:41
Since it's a post-processing shader, a cooler idea would be to implement support for generic user-specified shaders in Yuzu, like it's done in Dolphin and Citra. That would take considerably more work, but it may be worth it.

**Comment by Dranzule** [comment] 2021-08-10 00:13
FSR was really built thinking about downscaling to recover image quality. If the point is just to do upscaling, something like CAS would fit yuzu better. Switch games already run into abysmal low resolutions anyway, and AMD doesn't recommend running FSR in agressive modes(mostly performance) on low resolutions, like 1080p.

**Comment by BreadFish64** [comment] 2021-08-10 00:32
> FSR was really built thinking about downscaling to recover image quality. If the point is just to do upscaling, something like CAS would fit yuzu better.

There is a fundamental misunderstanding here and I blame AMD/Nvidia's marketing for it. FSR and DLSS are not performance boosts for rendering at the target resolution. They render at a lower resolution and then upscale it. DLSS fills in the blanks with AI. FSR is two shader passes: Edge Adaptive Spatial **Upsampling**, and Robust Contrast Adaptive Sharpening.

**Comment by BreadFish64** [comment] 2021-08-10 00:32
> FSR was really built thinking about downscaling to recover image quality. If the point is just to do upscaling, something like CAS would fit yuzu better.

There is a fundamental misunderstanding here and I blame AMD/Nvidia's marketing for it. FSR and DLSS are not performance boosts for rendering at the target resolution. They render at a lower resolution and then upscale it. DLSS fills in the blanks with AI. FSR is two shader passes: Edge Adaptive Spatial **Upsampling**, and Robust Contrast Adaptive Sharpening.

**Comment by FernandoS27** [comment] 2021-08-16 18:36
> Since it's a post-processing shader, a cooler idea would be to implement support for generic user-specified shaders in Yuzu, like it's done in Dolphin and Citra. That would take considerably more work, but it may be worth it.

That's not hard to do. it's just adding that on each renderer's SwapBuffers just before we scale the result to your screen. We could even allow changing the screen scaling algorithm (uses bilinear currently)

**Comment by v1993** [comment] 2021-08-16 20:05
> > Since it's a post-processing shader, a cooler idea would be to implement support for generic user-specified shaders in Yuzu, like it's done in Dolphin and Citra. That would take considerably more work, but it may be worth it.
> 
> That's not hard to do. it's just adding that on each renderer's SwapBuffers just before we scale the result to your screen. We could even allow changing the screen scaling algorithm (uses bilinear currently).

This is starting to get somewhat off-topic, but:

1. How is bilinear scaling applied (blit? shader?)? For me, making yuzu window tiny still retains jaggies as if it was using NN. It's not a large issue for now (who plays with 360p window on HD monitor?), but will be critical on the great day upscaler arrives. Then again, Citra is jagged for me with its "linear filtering" even on stupid high internal resolutions as well, so dunno what kind of problem this is...
2. Wouldn't you need to link to GLSL to SPIR-V (or SPIR-V to GLSL decompiler if you're feeling funny) compiler to make shaders work on VK? Not a large issue I'd guess, but something to consider.

My overall comment about "take more work" was not as in "hit performance harder" but rather as in "require more coding to get it working nicely".

As for "change screen scaling algorithm", Dolphin/Citra allow this by providing texture game renders to as input and screen(output surface)-sized texture as output.

**Comment by BreadFish64** [comment] 2021-08-17 04:43
> How is bilinear scaling applied (blit? shader?)?
It uses a shader. 
> For me, making yuzu window tiny still retains jaggies as if it was using NN.
This is to be expected since at best bilinear can only downscale by 2x before throwing away information. Going past that actually hurts the filtering and brings it closer to nearest neighbor.

To demonstrate, here is a 9x9 image filled with colors.
![color_test_base](https://user-images.githubusercontent.com/28246325/129664350-160b9b8c-69cf-4381-8b85-ab89bff97464.png)
And here is what it looks like when it's downsampled to 3x3 by averaging each 3x3 box of pixels. (This is a box filter, used by Paint3D for downscaling to small sizes)
![color_test_box](https://user-images.githubusercontent.com/28246325/129664542-3a4e678a-6587-4a78-a453-3789c21f0c81.png)
And this is what bilinear does
![color_test_bilinear](https://user-images.githubusercontent.com/28246325/129664640-da1cd1f9-3f2e-4ac0-9ce7-6b81819a2264.png)
It mixes the top left four pixels in each box (which is easy to do with fixed function hardware) and ignores the rest.

If we want to handle this elegantly we'd need a bicubic/lanczos/box filter. Super-samping more than 2x the screen size seems questionably useful anyway.

**Comment by v1993** [comment] 2021-08-17 09:40
Having bicubic would still be pretty nice (if going down this route, how about also implementing Hermite, which Cemu recommends for 2D games). 2x screen size might seem like a lot (it's 4x SSAA, which is usually pretty decent), but keep in mind that simple grid-patterned SSAA (what you end up with by simply rendering at higher resolution instead of using driver's options) might require higher sampling rates compared to other methods.

**Comment by FernandoS27** [comment] 2021-08-17 14:26
> Having bicubic would still be pretty nice (if going down this route, how about also implementing Hermite, which Cemu recommends for 2D games). 2x screen size might seem like a lot (it's 4x SSAA, which is usually pretty decent), but keep in mind that simple grid-patterned SSAA (what you end up with by simply rendering at higher resolution instead of using driver's options) might require higher sampling rates compared to other methods.

About your first question. Yes yuzu master is using NN instead of bilinear in Vulkan (in OGL it's bilinear). I have corrected that on A.R.T and I have taken your suggestion. I have brought some of Citra's filters (so far Bicubic and ScaleForm), I'm planning on adding more stuffs but I won't spoil everything before release.

**Comment by v1993** [comment] 2021-08-17 15:32
> Yes yuzu master is using NN instead of bilinear in Vulkan (in OGL it's bilinear), it's a bug. I have corrected that on A.R.T and I have taken your suggestion.

Ah, nice to know it was a bug and not my setup acting weird. Do you mean by "I have taken your suggestion" there's going to be a selection between Bilinear/Bicubic/Hermite?

> I have brought some of Citra's filters (so far Bicubic and ScaleForce), I'm planning on adding more stuffs but I won't spoil everything before release.

Aren't those used for game textures (in Citra) rather than final image scaling? :eyes:

**Closed** 2021-11-17 02:52 UTC
