### ISSUE TITLE
[Android] Regression in overall performance in latest 162 v

### ISSUE THREAD

**Issue by RaduNastase** [yuzu-emu/yuzu#12379] opened 2023-12-16 19:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

162

### Description of Issue

Compared to version 159, latest version (162) sees a loss of performance (Ninja Gaiden 2, Bayonetta 2) of about 10%.

### Expected Behavior

Normal performance, at least on par with previous versions (159).

### Reproduction Steps

Play your favourite scenes in a more demanding game in both versions, and experience the difference.

### Log File

No log file.

### System Configuration

CPU: Snapdragon 865+
GPU/Driver: Adreno
RAM: 12 gb
OS: android 11

**Comment by liamwhite** [comment] 2023-12-16 19:48
which version does the performance lost first appear in

**Comment by RaduNastase** [comment] 2023-12-16 19:53
160 has less perf than 159 and 162 has less than 160. Never tested 161.
I'd say that 159 was the last with best performance.

**Comment by liamwhite** [comment] 2023-12-17 03:10
Can you confirm this is fixed by #12382

**Comment by RaduNastase** [comment] 2023-12-17 08:28
Hi liam!
Is it implemented in 163?

**Comment by RaduNastase** [comment] 2023-12-17 09:09
Performance in 163 is stil regressed compared to 159. We are talking similar as before ~ 10% less fps under identical conditions.

**Comment by liamwhite** [comment] 2023-12-17 15:09
These changes are not in 163. You need to specifically test the artifact on the linked page.

**Comment by RaduNastase** [comment] 2023-12-17 16:45
Not a damn clue how to do that sir 😟

**Comment by liamwhite** [comment] 2023-12-17 16:50
PR 12382 (fix attempt): https://nightly.link/yuzu-emu/yuzu/actions/runs/7234975334

If that doesn't fix it, exactly one of these should have the regression. I need to know which one it is, because I cannot reproduce this issue. I have significantly better performance on newer builds (5-10fps faster).

12335: https://nightly.link/yuzu-emu/yuzu/actions/runs/7188018340
12344: https://nightly.link/yuzu-emu/yuzu/actions/runs/7217473450
12345: https://nightly.link/yuzu-emu/yuzu/actions/runs/7214453068
12358: https://nightly.link/yuzu-emu/yuzu/actions/runs/7218068805

**Comment by brujo5** [comment] 2023-12-17 17:20
I haven't noticed any performance regression either. 
Poco F4

**Comment by RaduNastase** [comment] 2023-12-17 23:23
Here is my test:

12382 and 12344 are slower, similar to 162.
12335, 12345 and 12358 are faster, similar to v159

Ps. What equivent has 12335 in the main releases? Thank you!

**Comment by RaduNastase** [comment] 2023-12-18 05:05
Tested v164 and the performance is definitely better than 162/3. I think still lags a bit behind 12335 i think, but i will reinstall that one and re-test to make sure it's not some random framerate noise of some sort.

One little thing, unless set specifically to cubeb (default is auto) in main settings, the audio is messed up, completely distorted.

**Comment by liamwhite** [comment] 2023-12-18 05:17
audio commentary should be directed to #12379

**Comment by matthew777777** [comment] 2023-12-18 08:12
Recommend checking Turnip r11 since I see performance regression vs r12

**Comment by RaduNastase** [comment] 2023-12-18 08:27
In the games i test, i mostly use 23.1.0 (or any 23.x.x version). The other drivers may be a bit faster in some cases, but have bugs and errors in games like Donkey Kong Tropical, Arkam City, Ninja Gaiden 2, Bayonetta 2.

23.x plays them virtually flawless.

**Comment by RaduNastase** [comment] 2023-12-18 10:31
Yeah the speed is good. Your latest changes did the trick liam!
Thank you!

**Closed** 2023-12-19 15:14 UTC
