### ISSUE TITLE
[Feature Request] Add DLSS ans XeSS for window adapting fliter

### ISSUE THREAD

**Issue by I-LoveCpp** [yuzu-emu/yuzu#9659] opened 2023-01-22 03:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add DLSS ans XeSS for window adapting fliter

### Why would this feature be useful?

They can both improve performance. DLSS is useful on NVIDIA GPU and XeSS is useful on all GPU (especially Intel Arc GPU).

**Comment by liamwhite** [comment] 2023-01-22 03:51
Duplicate of #8062 and #8061

**Closed by liamwhite** 2023-01-22 03:51 UTC
Labels: request

**Comment by goldenx86** [comment] 2023-01-22 06:13
Switch games don't provide motion vectors and other information required for temporal filters, so it's not an option.

**Comment by boludoz** [comment] 2023-12-25 08:06
> Switch games don't provide motion vectors and other information required for temporal filters, so it's not an option.

https://jcgt.org/published/0010/03/02/
