### ISSUE TITLE
SEGFAULT when opening configuration on linux distros shipping OpenSSL

### ISSUE THREAD

**Issue by FaithLV** [yuzu-emu/yuzu#2957] opened 2019-10-07 09:23 UTC
Hello! Whenever I try to open the configuration window, yuzu segfaults. 

- yuzu-linux-20191007-08340e999
- Arch Linux (5.3.4-zen)
- backtrace: https://gist.github.com/FaithLV/4ebc5309edf512a931329c989ba38e1e
- yuzu_log.txt is empty

First when launching yuzu I had an issue of missing libsndio.so.6.1, so I symlinked to libsndio.so.7.0.

**Comment by youwereeatenbyalid** [comment] 2019-10-08 22:57
Can confirm, this is very real. Seems to have started after mainline 804 roughly, and it isn't an issue in 799.

**Comment by 7eia** [comment] 2019-10-09 20:33
After replicating this behaviour, I have confirmed that this is not an issue with yuzu. You are experiencing the segfault because you are providing libraries derived from OpenSSL (https://www.openssl.org/) and not LibreSSL (https://www.libressl.org/), i.e. you have compiled/sourced the OpenSSL versions of libssl and libcrypto. Either compile yuzu from source (as described at https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux and using the provided Git submodules, which includes LibreSSL), or build these libraries using the latest release of LibreSSL and then use the precompiled version of yuzu (specifying the path to the LibreSSL libraries with LD_LIBRARY_PATH).

**Comment by FaithLV** [comment] 2019-10-09 20:42
I'm not compiling the build myself, I just use binary artifacts from https://yuzu-emu.org/downloads/

**Comment by 7eia** [comment] 2019-10-09 20:45
Yes, I suspected as much. Your issue is that the OpenSSL versions of the required libraries are installed on your system. If you provide the LibreSSL versions also (being careful to avoid conflicts), then all will work as expected.

**Comment by FaithLV** [comment] 2019-10-09 20:51
Any chance for a build with the correct libraries packaged together?

**Comment by 7eia** [comment] 2019-10-09 20:54
I'm currently working on a Flatpak version of yuzu. That will simplify things greatly.

**Comment by FaithLV** [comment] 2019-10-09 20:56
That's great to hear! Any chance for an AppImage build also?

**Comment by 7eia** [comment] 2019-10-09 21:00
That is also a possibility. I have been looking into qtlinuxdeploy, but the Flatpak version will probably make such a thing redundant. You can expect to see the Flatpak version over the coming days.

**Comment by DarkLordZach** [comment] 2019-10-11 01:43
@7eia We are currently internally developing an official flatpak that should release very shortly. We would appreciate if you did not distribute your flatpak as it would cause confusion amongst our linux users. Thanks for your cooperation.

**Comment by 7eia** [comment] 2019-10-11 08:21
@DarkLordZach Close call. I was about to publish my finalised and fully-functioning yuzu Flatpak. I'll hold back though. Having said that, I was actually instructed to put this together by yuzu developers over on the Discord sever. More internal communication would probably be beneficial for all. Regardless, since you are already working on this, I will stop work on it immediately.

**Comment by chris062689** [comment] 2019-10-11 14:27
@7eia We would like your assistance in ironing out the remaining issues on ours. 
Feel free to hop on our Discord server and shoot me a message.

**Comment by FaithLV** [comment] 2019-10-16 20:36
Yeah, building from source seems to let me open the configuration. 

Still, this shouldn't be an issue, many linux distros use OpenSSL and flatpaks are a bandaid fix in my opinion.

**Comment by fluffapparition** [comment] 2019-10-16 23:10
@FaithLV if it works, its worth a try though.

Linux generally requires some maintenance and customization in order to get the desired setup so I'm sure most people wouldn't mind.

**Comment by chris062689** [comment] 2019-10-17 02:40
@FaithLV Flatpaks were specifically designed to solve this dependency issue... 
https://www.flatpak.org/


Regardless I'm glad you got it working.

**Comment by FaithLV** [comment] 2019-10-17 07:19
I know what flatpaks are and I dislike packaging dependencies for each program separately. But that's beside the point.

Another segfault when launching a game ;)

**Comment by fluffapparition** [comment] 2019-10-17 20:22
@FaithLV separate issue or??

**Comment by fluffapparition** [comment] 2019-10-28 23:51
How close are we to a fix yet, just making sure the thread hasn't died. :3

**Comment by ReaperOfSouls1909** [comment] 2019-12-02 01:55
[ 3.579842] Service.ACC core/hle/service/acc/profile_manager.cpp:ParseUserSaveFile:325: Failed to load profile data from save data... Generating new user 'yuzu' with random UUID.
Process 39571 stopped

thread #9, name = 'Thread (pooled)', stop reason = signal SIGSEGV: invalid address (fault address: 0x0)
frame #0: 0x0000000000000000
error: memory read failed for 0x0
gdb wouldnt work gave Starting program: /usr/local/bin/yuzu
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Temporary breakpoint 1, 0x0000000000551e80 in main ()
(gdb) q

thats the debug info i got from QT on the crash it still happens on downloaded builds

**Comment by catlover1019** [comment] 2019-12-16 05:12
I'm experiencing this issue or one very similar on Mint 19.1, after building it from source myself.

**Comment by synthaxx** [comment] 2019-12-16 13:43
Same issue on Kubuntu 19.10 (and 19.04). Compiled using [the standard build instructions](https://github.com/yuzu-emu/yuzu/wiki/Building-For-Linux) (using yuzu-mainline in release mode).
BT from the latest attempt attached.
[yuzu-bt-20191216.log](https://github.com/yuzu-emu/yuzu/files/3968271/yuzu-bt-20191216.log)

**Comment by dukenukemx** [comment] 2019-12-25 21:06
Ran into the same problem and decided to compile it myself, which did work until I tried today and got this error.  Does Yuzu require a newer version of QT than what comes with Ubuntu 18.04?  

`  * The installation package was faulty and contained

     "/usr/lib/x86_64-linux-gnu/cmake/Qt5Gui/Qt5Gui_QWaylandEglPlatformIntegrationPlugin.cmake"`

**Comment by PhieF** [comment] 2020-02-10 21:39
I've both built it and used provided binaries, but I can't open configure :(

**Comment by victords** [comment] 2020-03-16 23:16
I'm also experiencing the crash, both with the provided binary and building from source.

**Comment by victords** [comment] 2020-03-19 22:38
Hey @FearlessTobi , I tried applying your patch and rebuilding locally, it still crashed when opening the  configure menu... :(

**Comment by EliaGeretto** [comment] 2020-03-19 23:19
@victords Have you tried changing `bcat_backend` to `null` in your `~/.config/yuzu/qt-config.ini` file? The patch does not have any effect if you already have one, I assume. That fixes it for me.

**Comment by victords** [comment] 2020-03-20 00:07
@EliaGeretto thanks, it worked!

**Comment by victords** [comment] 2020-03-20 00:31
Now I was able to load a game (Snipperclips), but the input doesn't work at all... I tried with the keyboard and with a joystick (the joystick is recognized in the configuration screen, I was able to set all the keys correctly).
Should I open a different issue for this or is there some simple solution/something I missing?
Thanks!

**Comment by jbeich** [comment] 2020-04-21 01:37
Probably fixed by #3675 as now httplib and libzip agree on SSL library.

**Comment by H27CK** [comment] 2020-04-22 16:31
Can somebody confirm that https://github.com/yuzu-emu/yuzu/pull/3675 does indeed sort this. My Linux machine is headless, so can't confirm myself.

**Comment by EliaGeretto** [comment] 2020-04-22 18:06
It looks like it's fixed, yes. Setting BCAT Backend to Boxcat does not cause the crash when opening the Configuration window anymore.

**Closed** 2020-04-22 18:10 UTC
Labels: regression
