### ISSUE TITLE
Atelier Ryza 3

### ISSUE THREAD

**Issue by rgbarros120** [yuzu-emu/yuzu#11160] opened 2023-07-25 22:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acess 3755

### Description of Issue

Goodnight. The game mentioned above does not recognize the emulator itself, because I have the keys and the firmware all updated correctly. And when you select the game rom, it says that the key is invalid.

### Expected Behavior

Goodnight. The game mentioned above does not recognize the emulator itself, because I have the keys and the firmware all updated correctly. And when you select the game rom, it says that the key is invalid.

### Reproduction Steps

Goodnight. The game mentioned above does not recognize the emulator itself, because I have the keys and the firmware all updated correctly. And when you select the game rom, it says that the key is invalid.

### Log File

Goodnight. The game mentioned above does not recognize the emulator itself, because I have the keys and the firmware all updated correctly. And when you select the game rom, it says that the key is invalid.

### System Configuration

CPU: RYZEN 5 3600
GPU/Driver: GALAX GEFORCE GTX 1650 OC 4GB
RAM: 16GB (2400MHZ)
OS: WINDOWS 10 22H2

**Comment by FearlessTobi** [comment] 2023-07-25 22:47
This is an issue tracker for developers and not a support forum. Use our Discord for support.

**Comment by german77** [comment] 2023-07-25 22:47
Duplicate of #10045

**Closed by FearlessTobi** 2023-07-25 22:47 UTC
