### ISSUE TITLE
Multi-player or lan and save state

### ISSUE THREAD

**Issue by Hariu7** [yuzu-emu/yuzu#12137] opened 2023-11-23 10:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Multi-player or lan and save state

### Why would this feature be useful?

I have one PC and one phone so have to play Lan multi-player

**Comment by FearlessTobi** [comment] 2023-11-23 16:58
Duplicate of https://github.com/yuzu-emu/yuzu/issues/5049.

**Closed by FearlessTobi** 2023-11-23 16:58 UTC
Labels: request
