### ISSUE TITLE
Pokemon sword and shield ending logo crash

### ISSUE THREAD

**Issue by judah-b2** [yuzu-emu/yuzu#5332] opened 2021-01-11 09:34 UTC
My game crashes when the game ends and the sword logo pops up with a flare
![unknown](https://user-images.githubusercontent.com/66715197/104164471-f835eb00-541d-11eb-85d5-65c9619a87a9.png)
im using Yuzu Build 504, Windows 10, Multicore is off, using opengl, CPU: i7-97700f, GPU: 2060 SUPER, RAM: 32GB
here is the log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5794871/yuzu_log.txt)

**Comment by FearlessTobi** [comment] 2021-01-17 00:13
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4916.

**Closed by FearlessTobi** 2021-01-17 00:13 UTC

**Comment by MIKA123123** [comment] 2021-01-20 17:50
so do i use the .txt and drag it into keys?

**Comment by judah-b2** [comment] 2021-01-22 03:34
what do u mean by that
