### ISSUE TITLE
Abandon (core dumped) when going to the settings

### ISSUE THREAD

**Issue by flutterbrony** [yuzu-emu/yuzu#2986] opened 2019-10-16 18:05 UTC
Hi ! 

I'm trying a lot of builds of Yuzu, and on all, each time I go to the setting pannel (Tab Emulation > Configure...), the settings window open, then close one or two seconds after.

The build commit hash from my latest try is this one : 81df3e7
I'm running on Fedora 30, on an i7 6700HQ, GTX 980M, 32GB of Ram, 512GB of nvme ssd, and 1TB of SSHD, 1080p screen, latest drivers available for all, and Bumblebee for the gpu.

Here, the log in the terminal, that I got when launching it : 

/yuzu-linux-20191013-be89f9ebf$ ./yuzu
Gtk-Message: 19:54:12.411: Failed to load module "unity-gtk-module"
Gtk-Message: 19:54:12.411: Failed to load module "unity-gtk-module"
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
malloc(): invalid size (unsorted)
Abandon (core dumped)

Seems like there is an issue with a malloc in some builds of yuzu for linux ?

**Comment by Hexagon12** [comment] 2019-10-16 18:34
Seems to be a duplicate of #2957?

**Comment by fluffapparition** [comment] 2019-10-16 22:33
It is, the part of the logs tracing back to QPixmap are identical. Should move focus to #2957

**Comment by chris062689** [comment] 2019-11-14 13:25
Duplicate of #2957. Closing.

**Closed by chris062689** 2019-11-14 13:25 UTC
