### ISSUE TITLE
Time Played

### ISSUE THREAD

**Issue by AsafCohen9898** [yuzu-emu/yuzu#9314] opened 2022-11-26 10:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It would be nice to have the number of hours played on a game like in this image:
![image](https://user-images.githubusercontent.com/90915762/204083047-43fd87e5-b1aa-4c83-b679-18391cf7646e.png)
(Ryujinx has this functionality, in fact in the image there is Ryujinx)

### Why would this feature be useful?

I think time played on a game is a fundamental element

**Comment by SoRadGaming** [comment] 2022-12-28 02:21
https://github.com/yuzu-emu/yuzu/issues/4018

**Comment by FearlessTobi** [comment] 2022-12-28 03:17
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/4018.

**Closed by FearlessTobi** 2022-12-28 03:17 UTC
Labels: request
