### ISSUE TITLE
OpenLara missing HLE Services 'DeactivateNpad': port='hid' and 'Exit': port='ISelfController'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2713] opened 2019-07-10 23:12 UTC
[log.zip](https://github.com/yuzu-emu/yuzu/files/3379684/log.zip)

Source code https://github.com/XProger/OpenLara/releases

https://www.switchbru.com/appstore/zips/Openlara.zip app 

missing Services 'DeactivateNpad': port='hid' and 'Exit': port='ISelfController'

**Comment by DarkLordZach** [comment] 2019-07-10 23:13
Duplicate of #2664 & #2663

**Closed by DarkLordZach** 2019-07-10 23:13 UTC
