### ISSUE TITLE
[Vulkan] Broken Light Sources (Super Mario Odyssey)

### ISSUE THREAD

**Issue by DelghLay** [yuzu-emu/yuzu#7379] opened 2021-11-19 19:12 UTC
![0100000000010000_2021-11-19_15-26-59-078](https://user-images.githubusercontent.com/31009358/142676571-76c5ecf6-9193-455d-898a-fe057c15f6b0.png)
![0100000000010000_2021-11-19_15-27-11-262](https://user-images.githubusercontent.com/31009358/142676586-bff6143e-4ba9-480a-89aa-8d5ed324be67.png)

Some light sources shows with an incorrect color and intensity on Vulkan.
On older builds this issue doesn't happen.

Here's a log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7572398/yuzu_log.txt)

Setup:
CPU: i7-10700k
GPU: GTX 1070 Ti
RAM: 32 GB
Driver Version: Nvidia 472.12

**Comment by Cloudperry** [comment] 2021-11-19 21:57
Yep. I can confirm that the bug is happening on an AMD gpu as well.

Yuzu Early Access 2220:
![Screenshot_20211119_232356](https://user-images.githubusercontent.com/25011618/142694444-bbf5c68d-9e6a-4f94-89f9-da5e7bc715e0.png)
Yuzu Early Access 2211:
![Screenshot_20211119_234828](https://user-images.githubusercontent.com/25011618/142695798-28d62bbf-4f8e-4155-abde-950e7dd252fe.png)

Setup:
GPU: RX Vega 56
Driver Version: Mesa 21.2.5 (RADV)
CPU: Ryzen 3600
RAM: 32 GB
OS: Arch btw

I wasn't able to bisect this bug because I don't know which commits correspond to which Yuzu EA builds. This should be really easy to bisect now because the latest version without it (that I could find) is EA 2211.

**Comment by Cloudperry** [comment] 2021-11-25 17:30
It seems that this bug has been fixed with EA 2241 (or some version before it). Can someone else confirm that it has been fixed?

**Comment by SpecialDarkwolf999** [comment] 2021-12-10 20:29
this is fixed. no problems on EA:2300

**Closed** 2023-05-04 21:37 UTC
Labels: gpu-issue
