### ISSUE TITLE
[ERROR] POSIX SigHandler error

### ISSUE THREAD

**Issue by sabotendarsama** [yuzu-emu/yuzu#6388] opened 2021-05-29 11:24 UTC
Hi,
I work with a build based on debian called Batocera.PLUS this build consists of assembling game systems for use "ready-to-play", I am trying to include yuzu in this build because I had already tested the version 15/05/2021 and I was successful in running several games, but no version after this works on my system anymore and displays the error "POSIX SigHandler: Exception was not in registered code blocks (rip 0x007fb368180ee1), Segmentation Fault .... Would it be possible to check this problem?
I use a core i7 4770, 8GB of ram and a GTX 1650 super
![print_2021-05-29_13 23 39](https://user-images.githubusercontent.com/52870659/120068456-2c214e00-c057-11eb-8fba-522d9ed9c40a.png)
versions prior to released on 15/05/2021 also work
![print_2021-05-29_12 38 58](https://user-images.githubusercontent.com/52870659/120068469-3b080080-c057-11eb-8c6d-1ef26a5f3a4c.png)

**Comment by v1993** [comment] 2021-05-29 15:47
This is likely a duplicate of #6343. Also, please refer to yuzu versions instead of appimage dates, it makes things much simpler.

**Comment by sabotendarsama** [comment] 2021-05-30 18:35
This version also not work
https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-639/yuzu-linux-20210530-b5773a29f.7z

**Comment by MerryMage** [comment] 2021-05-30 21:16
All the message means is that there was a segfault somewhere. If you can get a stack trace that would be helpful.

**Comment by sabotendarsama** [comment] 2021-05-30 22:52
> All the message means is that there was a segfault somewhere. If you can get a stack trace that would be helpful.

The log generated by yuzu is buged, i cannot run any game
![image](https://user-images.githubusercontent.com/52870659/120122620-4acf3400-c180-11eb-9c34-905dfc231c02.png)

**Comment by v1993** [comment] 2021-07-11 13:42
Since likely dupe was closed please try testing this again on latest build. It's most likely fixed.

**Comment by gidoly** [comment] 2022-11-03 08:31
@v1993 v1993 can this be closed?

**Comment by v1993** [comment] 2022-11-03 15:10
It most likely can be - it's been forever and this issue doesn't contain relevant debugging information anyways.

**Closed** 2022-11-03 23:17 UTC
Labels: bug
