### ISSUE TITLE
Android: allow controller remapping

### ISSUE THREAD

**Issue by rogerclotet** [yuzu-emu/yuzu#11124] opened 2023-07-21 08:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Allow remapping keys from a controller (or keyboard) to allow changing buttons by preference or support controllers that aren't mapped correctly. It would also be nice to be able to edit axis deadzones, but it's less of a priority to me.

This is already implemented in other platforms, and it's even in the `config.ini` file, but as far as I know, it isn't implemented for Android. I tried editing this file and it had no effect, and I looked at the code with my limited knowledge of the project and it seems that configuration is ignored.

I am using the Yuzu Early Access app from the Play Store, and I also tried the last build from yesterday via APK to make sure this wasn't implemented yet.

### Why would this feature be useful?

There are some controllers that are correctly mapped and work out of the box (Razer Kishi v2 for me works perfectly), but some others have A/B and X/Y swapped. This is the case for my XBox Wireless Controller, and for my Backbone One, but I imagine the same thing will happen for other generic controllers.

**Comment by MIJS1019** [comment] 2023-11-21 16:01
Is this still under development or dismissed?

**Comment by chulinx** [comment] 2023-11-22 03:19
Has it been completed?

**Comment by MIJS1019** [comment] 2023-11-22 07:37
> Has it been completed?

No unfortunately. Someone said only one dev is working on controllers and he still doing something 'bout PC build. That feature on Android may take quite a while...

**Comment by Moe-Baker** [comment] 2023-11-25 10:38
Maybe it would be a good placeholder for the future to add a settings menu option to toggle between Western & Japanese layout?
This feature would make playing games much more pleasant imo, jumping with anything but the "South" button feels awful, lol.

**Comment by Kissycat** [comment] 2023-11-26 06:53
True, and joypads on android is always xbox style..

**Comment by siryorgan** [comment] 2023-11-26 07:48
Talking by experience: Gamesir X2 is pretty common as a device, and can be switched silently by some apps (other emulators, or the Xbox Game Pass app) from Switch mode to Xbox mode without the user even knowing it.
This can invert AB and XY and leave the user with inverted controls only within Yuzu (since other emulators make you map your controller beforehand, and Xbox already works with inverted controls compared to Nintendo). 
I've been there for several months, before realizing what happened. Not Yuzu's fault of course, but not allowing remapping assumes that all controllers will always behave the same way.

**Comment by Talos910** [comment] 2023-11-27 02:48
This is seriously needed every other android app has a way to map or remap the controls, can't use the hyperkin smartboy with Yuzu cause of this, Skyline already had it maybe you can use their code?

**Comment by RainZSunday** [comment] 2023-11-28 21:56
This is really needed. Even the Backbone v2 has X/Y and A/B swapped.

**Comment by pnvnd** [comment] 2023-12-09 17:23
I'm using the [Backbone One PlayStation Edition for Android](https://playbackbone.com/ca/platforms/playstation-remote-play/) on Yuzu build `2f9487cd3` and can confirm this is still an issue. A and B should be swapped, and X and Y should be swapped.

# Current State
| Backbone One | Yuzu Mapping |
| - | - |
| △ | Y |
| □ | X |
| ⨯ | A |
| ○ | B |

# Required State
| Backbone One | Yuzu Mapping |
| - | - |
| △ | X |
| □ | Y |
| ⨯ | B |
| ○ | A |

There is no other options in Yuzu (Android) that I could find to swap these myself.

**Comment by Kelvfimer** [comment] 2023-12-19 08:06
Hello 

Please it is needed a remap button option. It is a pain to play as is.

**Comment by JomPyx** [comment] 2023-12-20 07:29
Hello guys, can you add a remapping button in yuzu android ? Because the gamepad buttons on yuzu are scrambled ( generic gamepad for pc ). I use this controller on yuzu. I hope they will fix it soon at the next update

**Comment by yoyossef** [comment] 2023-12-20 18:39
L2 and R2 are not working on my razer joycat controllers

**Comment by jvankooo** [comment] 2023-12-28 06:47
Yuzu and android don't have issues switched on for their repository. So I don't know how anyone will contribute to the codebase. If it were properly open-source multiple controllers would be taken up early ?

**Comment by projShrew** [comment] 2024-01-08 15:53
can you guys please add a remapping option to yuzu android, I'm using a ps5 dual sense controller to play monster hunter generations ultimate, but unfortunately the L button is map to Y button for some reason

**Comment by Jaggerbaze** [comment] 2024-01-10 19:15
Hi Guys,

auto-mapping for A/B/X/Y on Android with Yuzu and Yuzu EA are also borked for the Razer Kishi V2 Pro.

I found a post where german77 was so kind to adjust it for the Red Magic Shadow Blade Controller after the user had send over some Input recordings.

Is there a chance to get this also for the Kishi V2 Pro ?

Thank you guys and have a good one.

**Comment by ruthan** [comment] 2024-01-12 00:38
If add whole android remapping is too complex.. Add just some option to switch A and B button.. that Nintendo ancient scheme is pure hell.
 Im using PS4 controller through Bluebooth if it matters.

**Comment by GiraffeCubed** [comment] 2024-01-17 06:57
Being able to swap A/B and swap X/Y would be great. I play Binding of Isaac with Razer Kishi.

To shoot up I must press X (left button)
To shoot left I must press Y (up button)

To shoot right I must press A (down button)
To shoot down I must press B (right button)

A simple toggle to swap these would go a long way.

**Comment by elixcat** [comment] 2024-01-21 08:50
Do the developers even read these messages?  So much time has passed, but remapping has not been implemented.  Any news about this?

**Comment by elixcat** [comment] 2024-01-22 11:45
> There are some controllers that are correctly mapped and work out of the box (Razer Kishi v2 for me works perfectly), but some others have A/B and X/Y swapped. This is the case for my XBox Wireless Controller, and for my Backbone One, but I imagine the same thing will happen for other generic controllers.

Any news?  It's really inconvenient to play on a gamepad; you need to reassign the buttons.  Swap A B. This is the only emulator for Android that does not have the ability to remap buttons

**Comment by elixcat** [comment] 2024-01-26 06:23
@german77 there have been requests to add remapping for a very long time and there are many of them.  Why are you ignoring this offer?  We understand that you are not obligated to add all of our offers.  But this is probably the only emulator that does not have such settings.  And the emulator is very cool.

**Comment by Moe-Baker** [comment] 2024-01-26 15:12
> @german77 there have been requests to add remapping for a very long time and there are many of them. Why are you ignoring this offer? We understand that you are not obligated to add all of our offers. But this is probably the only emulator that does not have such settings. And the emulator is very cool.

I don't want to be that guy, really, but I have to say, you are not owed anything here, this is a free open source project.
If you need to swap input so badly then fork the project and modify it to your needs, it's what I did.
Not too difficult too, only need to modify the
'src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/InputHandler.kt'
File to match your desired binding and then build your own version.
Build instructions are provided within the repository wiki.

**Comment by german77** [comment] 2024-01-26 15:55
We aren't ignoring this request, we have been working on it for the last couple of weeks. I even upstreamed this PR #12702 for this purpose. I still don't know when it will be ready since it needs some important UI changes + we still need to fix other things on android. But it shouldn't take awfully long to bring this feature.

**Comment by elixcat** [comment] 2024-01-26 15:59
> We aren't ignoring this request, we have been working on it for the last couple of weeks. I even upstreamed this PR #12702 for this purpose. I still don't know when it will be ready since it needs some important UI changes + we still need to fix other things on android. But it shouldn't take awfully long to bring this feature.

Thanks for the answer.  Otherwise I thought that they forgot about it))) We will wait for remapping by the entire 4pda community

**Comment by ruthan** [comment] 2024-01-28 00:13
> it needs some important UI changes
Sorry but this actually sound like some big company excuse.. What important UI changes to add one more checkbox?

**Comment by rogerclotet** [comment] 2024-01-28 03:11
> " it needs some important UI changes" Sorry but this actually sound like some big company excuse.. What important UI changes you need to add one more checkbox - with Label enable button A->B and X->Y swap until super duper robust button remapper is done?

@ruthan this is an open source project where people aren't even paid for their work, they do it for the community. If you don't like how the project is managed, either fork it and modify it yourself, or wait for their solution.

**Comment by ruthan** [comment] 2024-01-28 21:08
> @rogerclotet This sour response, you can use it as universal excuse for everything. Fact that something is open source does not mean, that you cant discus or question things.. especially if solution seems to be quite simple - add one more checkbox to existing options menu..

**Comment by Moe-Baker** [comment] 2024-01-28 21:11
> > @rogerclotet This sour response, you can use it as universal excuse for everything. Fact that something is open source does not mean, that you cant discus or question things.. especially if solution seems to be quite simple - add one more checkbox to existing options menu..

Add it yourself man

**Comment by Jaggerbaze** [comment] 2024-02-02 18:31
> > @german77 there have been requests to add remapping for a very long time and there are many of them. Why are you ignoring this offer? We understand that you are not obligated to add all of our offers. But this is probably the only emulator that does not have such settings. And the emulator is very cool.
> 
> I don't want to be that guy, really, but I have to say, you are not owed anything here, this is a free open source project.
> If you need to swap input so badly then fork the project and modify it to your needs, it's what I did.
> Not too difficult too, only need to modify the
> `src/android/app/src/main/java/org/yuzu/yuzu_emu/utils/InputHandler.kt`
> File to match your desired binding and then build your own version.
> Build instructions are provided within the repository wiki.

Man...I love you for this Info ! I'm a dummy in programming, but this I got to manage.

Fixes my problem with the Kishi V2 Pro.

Thank you so much mate. Hope you're having a good one. <3

**Comment by darix080** [comment] 2024-02-06 22:19
Hello to everyone, 
I have a generic USB controller, vendorID 0810. I tried rewriting KEYCODE_BUTTON... with the right one for my controller in the file InputHandler.kt in the right section (the generic controller), I tried creating a new getInput...Key and setAxis... but nothing worked (I copied and replaced the .kt file, I don't know if it is the right way to do it).
I tried the skyline edge 69 emulator and it has a proper remapper for every controller and mine worked well! So I know it is not a problem with the one I own. Yuzu Android is the best emulator I used and I would like to play it with this controller (Super Mario Odyssey). 
Can someone help me? 
Do I have to modify the InputHandler.kt file and other things? Do I have to do other? I am missing something?
Do you know if Yuzu has an automatic remapper?

**Comment by Moe-Baker** [comment] 2024-02-06 23:03
> Hello to everyone, I have a generic USB controller, vendorID 0810. I tried rewriting KEYCODE_BUTTON... with the right one for my controller in the file InputHandler.kt in the right section (the generic controller), I tried creating a new getInput...Key and setAxis... but nothing worked (I copied and replaced the .kt file, I don't know if it is the right way to do it). I tried the skyline edge 69 emulator and it has a proper remapper for every controller and mine worked well! So I know it is not a problem with the one I own. Yuzu Android is the best emulator I used and I would like to play it with this controller (Super Mario Odyssey). Can someone help me? Do I have to modify the InputHandler.kt file and other things? Do I have to do other? I am missing something? Do you know if Yuzu has an automatic remapper?

Does your controller work with vanilla Yuzu?
If so, then swapping the keybindings from A<-->B and X<-->Y is enough, no need to implement new input handlers.
If it never worked with vanilla yuzu then it might need keybinding to work.
What controller is it by the way?

**Comment by darix080** [comment] 2024-02-06 23:10
> > Hello to everyone, I have a generic USB controller, vendorID 0810. I tried rewriting KEYCODE_BUTTON... with the right one for my controller in the file InputHandler.kt in the right section (the generic controller), I tried creating a new getInput...Key and setAxis... but nothing worked (I copied and replaced the .kt file, I don't know if it is the right way to do it). I tried the skyline edge 69 emulator and it has a proper remapper for every controller and mine worked well! So I know it is not a problem with the one I own. Yuzu Android is the best emulator I used and I would like to play it with this controller (Super Mario Odyssey). Can someone help me? Do I have to modify the InputHandler.kt file and other things? Do I have to do other? I am missing something? Do you know if Yuzu has an automatic remapper?
> 
> Does your controller work with vanilla Yuzu? If so, then swapping the keybindings from A<-->B and X<-->Y is enough, no need to implement new input handlers. If it never worked with vanilla yuzu then it might need keybinding to work. What controller is it by the way?

It works with Yuzu, even before I did anything. The problem is that is works only with dpad and left stick. 
My controller is a generic USB gamepad
![Screenshot_20240207_000724_Gamepad Tester](https://github.com/yuzu-emu/yuzu/assets/159198668/00700a63-a3df-4c04-851d-c7c364db793e)

**Comment by german77** [comment] 2024-02-06 23:14
Your controller uses a numerical layout instead of buttons A,B,X... This doesn't mean it doesn't work just that it can be automatically mapped. You will need to wait for the mapping support to be added.

**Comment by darix080** [comment] 2024-02-06 23:22
> Your controller uses a numerical layout instead of buttons A,B,X... This doesn't mean it doesn't work, just that it can't be automatically mapped. You will need to wait for the mapping support to be added.

Ohh 😟, ok thank you! 
I will wait, thank you all. Do you know how long it takes for this feature to be implemented? 

I have another question, 
I tried using the PS4 gamepad but the left stick has a problem where it always scrolls down even if it is phisically in the middle. I know it is a problem with deadzone (or something like that). Is it possible to do something?

**Comment by german77** [comment] 2024-02-06 23:24
Yuzu uses a predefined dead zone. Sadly it can't be configured yet. We are still working on the UI so the feature hasn't reached the testing stage yet. Might take a couple of weeks more.

**Comment by darix080** [comment] 2024-02-06 23:35
> Yuzu uses a predefined dead zone. Sadly it can't be configured yet. We are still working on the UI so the feature hasn't reached the testing stage yet. Might take a couple of weeks more.

Ok, thank you!
This is a fantastic news,
I hope it will be complete as soon as possible

**Comment by Pesche007** [comment] 2024-02-13 07:44
That's fantastic indeed. Will the UI also allow for multiple controller mapping?

**Comment by YamiKaze04** [comment] 2024-02-14 12:13
i remap the button Xbox, Switch Pro Controller, and Generic Controller, on my fork off Yuzu Android

I've tested it and it works fine (with the controller i have) but I don't know how to add it to the official code. can anybody add this to the main source.?
![Uploading Screenshot_2024-02-14-19-09-41-124_com.opera.browser.jpg…]()

I'm afraid to messed up something in the official code if i add it myself

**Comment by RHYTHM1125** [comment] 2024-02-17 08:29
@german77 thank you so much for your hard work. Guys it's finally here. Now you can remap your input keys. 
![Screenshot_20240217_135637_org yuzu yuzu_emu](https://github.com/yuzu-emu/yuzu/assets/160070618/40d8c7de-fd50-4788-8b17-4bbed9e2011f)

**Comment by RHYTHM1125** [comment] 2024-02-17 09:41
I've tried everything but I'm still not able to remap my zebronics pro controller. It's not even detecting it as a controller. It says press a button or move a trigger/stick. I think it's a bug

**Comment by german77** [comment] 2024-02-17 16:22
Please discuss these issues on the PR so the dev can see it. Does it show on the drop down list?

**Comment by RHYTHM1125** [comment] 2024-02-17 17:47
> Please discuss these issues on the PR so the dev can see it. Does it show on the drop down list?

No it doesn't show in the drop down list. It says 'any'
And some of the games that was working flawlessly now it's crashing on the loading screen. ( Demon slayer hinokami chronicles, Naruto x boruto storm connections)

**Comment by german77** [comment] 2024-02-17 17:57
If you are testing the artifact those aren't like mainline releases. They lack some PR

**Comment by t895** [comment] 2024-02-18 14:24
Solved by #13034

**Closed by t895** 2024-02-18 14:24 UTC
Labels: request

**Comment by pnvnd** [comment] 2024-02-18 20:32
I've just downloaded android-254.apk from the releases and button mapping is working as expected.

Thank you!

**Comment by artzox** [comment] 2024-02-23 17:54
Is this coming to the playstore EA release,or any way to update this one?

**Comment by t895** [comment] 2024-02-23 18:33
We're still working on a release for the play store. 

For the time being, you can create a backup of your user data through the Settings tab>Manage yuzu data>User data and then import that file into the latest GitHub build.

**Comment by Pesche007** [comment] 2024-02-23 19:16
I am using Obtainium for this - works very well: [https://github.com/ImranR98/Obtainium](url)

**Comment by artzox** [comment] 2024-02-23 21:39
Thanks. Somehow I don't see the point of continuing to use EA if I can get newer features via github releases (not talking about nighties).

**Comment by JomPyx** [comment] 2024-03-01 16:29
Thanks for adding the remapping button. But I hope it will be fixed for generic gamepad usb. Because the button A, B, X, Y, R, L, ZR, ZL cannot be input and for the analog is working. I hope you will fix it soon. 🙏🙏
