### ISSUE TITLE
Yuzu Freezes when creating a Mii

### ISSUE THREAD

**Issue by DaSpoop** [yuzu-emu/yuzu#5218] opened 2020-12-22 09:40 UTC
[I play on Yuzu Early Access 1245]
Hi, Whenever, I play Super Smash Bros Ultimate, it runs on perfect full 60 FPS, but when I go to Create a Mii
![image](https://user-images.githubusercontent.com/76204153/102873546-92b79580-4441-11eb-8001-4148ba599f4d.png)
And then press X to start creating
![image](https://user-images.githubusercontent.com/76204153/102873642-ac58dd00-4441-11eb-83b0-17883221c78c.png)
It just then freezes and goes to 0 FPS
![image](https://user-images.githubusercontent.com/76204153/102873686-bc70bc80-4441-11eb-98e5-18b9594aa91c.png)
![image](https://user-images.githubusercontent.com/76204153/102873709-c2669d80-4441-11eb-8cdc-54f8043dee4a.png)
And it can stay like that forever

...And it's still frozen

**Comment by G-Spawn** [comment] 2020-12-22 23:23
Post a log please like the template of the issue when you create new asks you do to.

**Comment by DaSpoop** [comment] 2020-12-23 09:20
> 
> 
> Post a log please like the template of the issue when you create new asks you do to.

What...?
I don't understand...

**Comment by german77** [comment] 2020-12-23 18:08
Follow this guide https://yuzu-emu.org/help/reference/log-files/

**Comment by DaSpoop** [comment] 2020-12-23 18:23
[Yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5736584/Yuzu_log.zip)
Here it is, It had over 9 MB so I had to compress it, don't know what is causing the issue tho...

**Comment by DaSpoop** [comment] 2020-12-24 10:27
> 
> 
> Follow this guide https://yuzu-emu.org/help/reference/log-files/

um

**Comment by G-Spawn** [comment] 2020-12-24 14:09
Your log was from a prior Early access version, not the one you reported. 

Have you dumped your firmware from your switch? This could play a part in why its not working perhaps.

Beyond that I'm not sure I've been able to create Mii fighters for weeks+ now on both of my machines Intel - Nvidia based in almost every recent Early access builds and mainline alike. If you need further assistance perhaps consider the Discord  Server as I do believe this is for tracking issues with the emulator. This could just be particular to you.

**Comment by FearlessTobi** [comment] 2020-12-25 20:57
Duplicate of https://github.com/yuzu-emu/yuzu/issues/3587.

**Closed by FearlessTobi** 2020-12-25 20:57 UTC
