### ISSUE TITLE
Pokémon Shield - Extremely Intense Light Refractions/Reflections Yuzu Mainline Build 884

### ISSUE THREAD

**Issue by BearadactylPrime** [yuzu-emu/yuzu#7746] opened 2022-01-19 15:12 UTC
Getting some intense lighting issues, using the Vulkan renderer at 2x resolution with FSR; FXAA; and GPU set to High. Issue persists regardless of Yuzu GPU setting. The lights also seem to flicker rapidly, which can be a seizure risk to some players.

I am using the Force Max Resolution, Outline Removal, and Y Comm Fix mods from the official repository here. I am also using a single clothes replacement mod and a randomizer mod, but none of the items are present during the issue demonstration.

The issue is present, and reproducible at all times by just playing the game, I have not tested beyond the point of entering the Slumbering Weald. However, upon every load of the game the issue is very much present.

PC Specs:
Windows 10 Pro Build 21H1 - Version 19043.1288
CPU: AMD Ryzen 5 2600X 3.6 GHz
GPU: AMD RX 5700 XT 8GB Gigabyte OC Edition - Driver Version 21.12.1
RAM: 16GB 3200 MHz CL16
Motherboard: ASRock B450 PRO4
I can also attach a Dxdiag file if requested.

Below is a video demonstrating the issue on my personal Youtube channel. Video was recorded on build 2759f891a specifically and it demonstrates it far better than the screenshot. Skip to 0:56 for the best demonstration.
https://youtu.be/706_A042kro

Here is a screenshot of where it is the worst:
![Screenshot_10](https://user-images.githubusercontent.com/25111651/150158650-b412c73e-161e-4867-b460-bcdc00b0108f.png)

Yuzu log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7898071/yuzu_log.txt)

**Comment by gidoly** [comment] 2022-10-06 22:12
confirmed to be caused by force max resolution mod. closing issue as it is not caused by yuzu codebase.

**Closed by gidoly** 2022-10-06 22:12 UTC
Labels: gpu-issue
