### ISSUE TITLE
Add hd rumble or atleast rumble of some sort

### ISSUE THREAD

**Issue by jojo6903** [yuzu-emu/yuzu#4096] opened 2020-06-17 02:14 UTC
hd rumble or rumble of some kind would really add to the immersion

**Comment by FearlessTobi** [comment] 2020-06-17 13:16
Duplicate of https://github.com/yuzu-emu/yuzu/issues/3894. Please check for this the next time you open an issue,

**Closed by FearlessTobi** 2020-06-17 13:16 UTC
