### ISSUE TITLE
Pro controller gyro doesn't work properly since EA3638+

### ISSUE THREAD

**Issue by RuafuMan-Obs** [yuzu-emu/yuzu#10786] opened 2023-06-15 07:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3638~3678

### Description of Issue

Due to motion monitor the gyro works normal on turning left/right & leaning up/down,but when leaning left/right it start dirfting like hell ,still not fixed in 3678 yet. Using 3623 build such problem doesn't appear

### Expected Behavior

*

### Reproduction Steps

Intresting is when connect in wired mode ,the drifting happens on  leaning left/right , when connect in bluetooth mode it happens on leaning up/down,I always use wired connection cuz I can't expect the bluetooth stability on pc

### Log File

*

### System Configuration

CPU:i9-9900k
GPU/Driver:RTX2080Ti
RAM:4266 C19 8*2
OS:win10 pro

**Comment by RuafuMan-Obs** [comment] 2023-06-15 07:21
It works fine on 1469

**Comment by Squall-Leonhart** [comment] 2023-06-16 12:28
You can update the SDL2.dll with the one from https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.27.1 to resolve this, 

duplicate of #10708

**Comment by RuafuMan-Obs** [comment] 2023-06-16 14:50
> You can update the SDL2.dll with the one from https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.27.1 to see if it resolves this, but to my knowledge this is either a weird controller fault or third party driver being involved, such as steam input.

I took it and tried ,the drifting on leaning left/right is much better;BUT~ the gyro monitor now shows the cursor will dirft back a  bit when I done leaning left/right/up/down,which the same issue happens on Ryujinx's controller motion and The BetterJoy for Cemu,what I have experienced a lot on it :( ,maybe I can never figure out why the gyro behave so fast and accurate on yuzu mainline & EA3638 below and what changes cause it wrong

**Comment by valkyrie743** [comment] 2023-06-17 07:23
> > You can update the SDL2.dll with the one from https://github.com/libsdl-org/SDL/releases/tag/prerelease-2.27.1 to see if it resolves this, but to my knowledge this is either a weird controller fault or third party driver being involved, such as steam input.
> 
> I took it and tried ,the drifting on leaning left/right is much better;BUT~ the gyro monitor now shows the cursor will dirft back a bit when I done leaning left/right/up/down,which the same issue happens on Ryujinx's controller motion and The BetterJoy for Cemu,what I have experienced a lot on it :( ,maybe I can never figure out why the gyro behave so fast and accurate on yuzu mainline & EA3638 below and what changes cause it wrong

i just starting to have gyro issues with my pro controller today but went away when i closed steam so for me the issue must have been something with steam input. which is odd being that ive always had steam open in the background and had no issues. not sure if its because of the latest overhall update valve just released for steam??  will look more into it tomorrow going to bed now lol

**Comment by german77** [comment] 2023-06-22 17:38
Should be fixed already in EA or in mainline 1477

**Closed by german77** 2023-06-22 17:38 UTC
