### ISSUE TITLE
Snipperclips Plus freezes

### ISSUE THREAD

**Issue by sdasda7777** [yuzu-emu/yuzu#1820] opened 2018-11-28 20:06 UTC
Using yuzu Canary 1642, Snipperclips Plus completely freezes after beating first level (tested only in SP mode), in middle of level completion screen showing up. 
EDIT: Only fix is restart, meaning game is unbeatable for me. The emulator shows it is running 100%, 60 FPS, if that helps. I believed it happens to everyone, but apparently not, so here are my specs, again, if that helps: i5-4570, 16GB RAM, Intel HD 4600. The game also seems to have weird pacing and broken meter, but that seems to happen to everybody.

Title IDs: 0100704000b3a000

**Comment by Hexagon12** [comment] 2018-11-28 21:20
To be honest, it's not a freeze. The completion meter up on the right upper corner is not working correcty (it just spins around, even where it's not supposed to).

I had seen this issue before be fixed by #1339, but it was not merged, but the new version in #1497 + #1517 failed to fix the issue. I haven't noticed anything unimplemented in the secondary PR that was implemented in the first one.

**Comment by Hexagon12** [comment] 2018-11-29 08:29
The only freeze issue I experience in Snipperclips is if you stay at one screen position for too long. For example, I had RNG freezes just on the title screen if I left it for some time.

**Comment by sdasda7777** [comment] 2018-11-29 08:40
Might be related, but again, that is not really what I'm talking about.

**Comment by Hexagon12** [comment] 2019-06-28 18:05
Seems to be a duplicate of #1935

**Closed by Hexagon12** 2019-06-28 18:05 UTC
