### ISSUE TITLE
TOTK has blue and green flash in OpenGL mode

### ISSUE THREAD

**Issue by bobbybudnick** [yuzu-emu/yuzu#10439] opened 2023-05-24 16:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All tested versions

### Description of Issue

I am trying OpenGL mode due to having a number of crash issues in Vulkan mode which I will open another ticket for and one thing I am noticing is a blue and green flash that happens when panning the camera in TOTK.  I can handle the low FPS but the flashing is bright and potentially seizure-inducing.  None of the graphics sub settings that I can see have any affect on this situation.

### Expected Behavior

Standard graphics without rapid brightness and color changes.

### Reproduction Steps

Just switch to OpenGL mode and swing the camera left and right for a few seconds.  It seems to happen with all settings with OpenGL.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11556889/yuzu_log.txt)

### System Configuration

CPU: i7 6700k
GPU/Driver: AMD RX 6800 with 23.2.2
RAM: 16 GB
OS: Windows 10

**Comment by devmachine1** [comment] 2023-05-24 17:04
idk man the only thing I can see which can help is updating drivers because of this:

[ 111.144602] Shader.GLSL <Warning> shader_recompiler\backend\glsl\emit_glsl_image.cpp:EmitImageSampleDrefExplicitLod:317: Device lacks GL_EXT_texture_shadow_lod. Using textureGrad fallback

hope it helps :)

**Comment by FearlessTobi** [comment] 2023-05-24 17:39
Closing as user is unwilling to update their drivers.

**Closed by FearlessTobi** 2023-05-24 17:39 UTC

**Comment by bobbybudnick** [comment] 2023-05-24 19:04
I updated the driver against my better judgement.  Link's skin is dark is now and there are menu artifacts.  Additionally the blue and green flash persists and my Windows registry is further clogged up with unnecessary stuff.  So much for new drivers.

**Comment by SleepingSnakezzz** [comment] 2023-05-24 19:08
This is an issue tracker for development, not a support forum. Try asking for help on the yuzu Discord server or on the forums.

**Comment by bobbybudnick** [comment] 2023-05-24 19:10
I don't do Discord.  What else do you want out of me?  I posted log files?

**Comment by bobbybudnick** [comment] 2023-05-24 19:12
The development insight you are getting here is that the latest driver is not always the fix.

**Comment by SleepingSnakezzz** [comment] 2023-05-24 19:20
> I don't do Discord. What else do you want out of me? I posted log files?

Then ask on the forums. And as for what we would want out of you, open up a topic there about your issue, let the support staff help you with troubleshooting it. Either you can solve the issue with them, or they can confirm that there's an emulation issue with what you're encountering. They can *then* ask you to open up a Github issue with the **relevant** information so that the developers can keep track of it. 

This is to make it clear *what* the issue is, and under *what* circumstances you can reproduce it reliably. This helps the developers and the support team understand how to resolve the issue faster for the end-user; you.

**Comment by bobbybudnick** [comment] 2023-05-25 21:58
So ignoring the technical gatekeeping for right now I have pressed on.

The flash is fixed on 3607 and later.  I am not seeing the flash on Linux either.  I am also seeing less stutter with 3607.  I could only use up to 3603 before due to another bug.  

I had accelerate astc off for some reason and that was causing problems.
accelerate astc off (open gl) - both astc uncompressed/medium/low have unacceptable menu freezes in open gl
accelerate astc off (open gl) - astc uncompressed causes dark skin link and terrain darkness
Astc uncompressed works fine under vulkan without acceleration except for the crashes.
So it is better to leave this acceleration turned on it seems.

Open GL VRAM overcommit capability should handle VRAM issues under Open GL hopefully.
Pipeline cache off/accelerate astc on/open gl/glsl/2x/accuracy high/fast gpu time seem to be working without glitches.
Unfortunately FPS is between 15-20 so at least a third faster than on Linux but still too slow.
GPU and CPU usage are fairly low so there is a programming bottleneck within Yuzu somewhere.

I ran out of avenues of approach so I was forced to use the other emulator and the jury is still out on that one but you can not say I did not give it a good try.
