### ISSUE TITLE
Kirby and the Forgotten Land - Random vertex explosions, random crashing

### ISSUE THREAD

**Issue by ZoruaLoL** [yuzu-emu/yuzu#8082] opened 2022-03-25 15:41 UTC
![01004d300c5ae000_2022-03-24_20-57-31-770](https://user-images.githubusercontent.com/49895285/160153105-2cce1253-2f60-473f-8196-c5ede6c9f1a7.png)
![01004d300c5ae000_2022-03-24_22-45-17-086](https://user-images.githubusercontent.com/49895285/160153122-d21bcb80-4e9f-412f-b5b0-ad25ca7794ec.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8351912/yuzu_log.txt)

**Comment by Morph1984** [comment] 2022-03-25 15:42
Duplicate of #7979, will copy the images there

**Closed by Morph1984** 2022-03-25 15:42 UTC

**Comment by Codexmsters** [comment] 2022-04-01 21:35
#7979
