### ISSUE TITLE
Anyone can HELP Intel users?

### ISSUE THREAD

**Issue by jlarmijos** [yuzu-emu/yuzu#6093] opened 2021-03-20 22:26 UTC
Hello, I have an Intel i3 10100 processor with Intel UHD 630 graphics that allows me to play games of considerable demand but with Yuzu and the Bowser's Fury game I find sectors in which the game simply "freezes" having to force close of the application. (Attached video of the problem and yuzu's log file). I tested with a 1GB Asus Nvidia GT 710 card and despite being so basic the game runs without any problem. My question is, can someone help all Intel users who come across these types of incompatibilities?

https://user-images.githubusercontent.com/79478556/111887170-33feab00-89a1-11eb-8a72-3ab96db33302.mp4

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6176494/yuzu_log.txt)

**Comment by FearlessTobi** [comment] 2021-03-21 14:12
Duplicate of https://github.com/yuzu-emu/yuzu/issues/6025.

**Closed by FearlessTobi** 2021-03-21 14:12 UTC
