### ISSUE TITLE
Yuzu wont load at all.

### ISSUE THREAD

**Issue by RichardOjo** [yuzu-emu/yuzu#1061] opened 2018-08-14 16:18 UTC
Every time i attempt to launch Yuzu the only thing it says is:
`./yuzu: error while loading shared libraries: libsndio.so.6.1: cannot open shared object file: No such file or directory`
Is it just me or is there something wrong...
 
Specs:
(Note: This may not do anything with the emulator itself but just in case :+1: )
Linux Mint 17.3 with Ubuntu 14.04 (Kernel: 3.19.0-32 Generic)
AMD A6-5400K APU
Radeon HD Graphics (Bundled within APU/CPU)
 
Thank You.

**Comment by Hexagon12** [comment] 2018-08-14 16:27
This is an issue tracker for developers and not a support forum. Please report these issues on Discord before making issues here.

Requesting to close.

**Comment by ReaperOfSouls1909** [comment] 2018-08-14 16:35
may as well close it the issue is solved by whats done above

**Closed** 2018-08-14 17:17 UTC
