### ISSUE TITLE
unimplemented ioctl for pokemon sword

### ISSUE THREAD

**Issue by matthewatman** [yuzu-emu/yuzu#3921] opened 2020-05-11 11:42 UTC
[1495.627125] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_vic.cpp:Submit:55: (STUBBED) called
[1495.628382] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:GetWithId:94: (STUBBED) called
[1495.636782] Service <Warning> core\hle\service\sm\controller.cpp:QueryPointerBufferSize:43: (STUBBED) called
[1495.636789] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_vic.cpp:UnmapBufferEx:107: (STUBBED) called
[1495.639540] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.640160] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:Submit:55: (STUBBED) called
[1495.640776] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.641281] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWaitWithId:86: (STUBBED) called, input_id=0x1, min=0xE55077C0, max=0xFFFFFFFF
[1495.641362] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:GetWithId:94: (STUBBED) called
[1495.652766] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.652929] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:Submit:55: (STUBBED) called
[1495.653034] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.653551] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWaitWithId:86: (STUBBED) called, input_id=0x1, min=0xCEED4440, max=0xFFFFFFFF
[1495.653660] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:GetWithId:94: (STUBBED) called
[1495.655025] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.655468] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:Submit:55: (STUBBED) called
[1495.655571] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.656003] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWaitWithId:86: (STUBBED) called, input_id=0x1, min=0xBABB96C0, max=0xFFFFFFFF
[1495.656106] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:GetWithId:94: (STUBBED) called
[1495.657883] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.658319] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:Submit:55: (STUBBED) called
[1495.658424] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.690516] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:SetAndWaitWithId:86: (STUBBED) called, input_id=0x1, min=0xA88480C0, max=0xFFFFFFFF
[1495.690606] Service.MM <Warning> core\hle\service\mm\mm_u.cpp:GetWithId:94: (STUBBED) called
[1495.691488] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl
[1495.691623] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:Submit:55: (STUBBED) called
[1495.692012] Debug <Critical> core\hle\service\nvdrv\devices\nvhost_nvdec.cpp:ioctl:39: Assertion Failed! Unimplemented ioctl

**Comment by matthewatman** [comment] 2020-05-11 11:44
This happens just after i beat the champion and the cutscene starts playing

**Comment by SilverBeamx** [comment] 2020-05-11 12:13
This is a very well known and documented issue. yuzu still lacks proper video codec decode. As such, cutscenes are rendered without video output on any game. I'd advise to close this issue as it doesn't provide any meaningful new info :)

Cheers,
Silver

**Comment by ogniK5377** [comment] 2020-05-11 12:23
Duplicate of #2643

**Closed by ogniK5377** 2020-05-11 12:23 UTC

**Comment by matthewatman** [comment] 2020-05-11 12:33
Wait so this means that I won't be able to progress into the post game cause of this causing my game to crash everytime I beat the gym? Cause that's pretty depressing that after all that grinding I won't be able to progress any further than after beating the champion.
