### ISSUE TITLE
Yuzu Softlocking Pokemon Let's Go

### ISSUE THREAD

**Issue by chris062689** [yuzu-emu/yuzu#3016] opened 2019-10-23 15:30 UTC
Users say this was introduced in yuzu 11. Yuzu 10 works. 
Source: https://www.reddit.com/r/yuzu/comments/dkxsho/_/ 

<meta name="titleids"  content="0100187003a36000,010003f003a34000">

**Comment by walikor** [comment] 2019-10-28 19:16
any update or progress?

**Comment by fluffapparition** [comment] 2019-10-29 20:36
Can someone contact the OP over on reddit and ask him to retrace his steps and then DM us some logs along with a better description of the bug.

I cant see us going anywhere yet.

**Comment by ogniK5377** [comment] 2019-10-30 10:55
@fluffapparition It's an obvious regression, we can simply check the merged prs between yuzu 10 -> yuzu 11. You don't need to comment on every issue since it just makes issues harder to follow and doesn't add to the conversation. We are actively working on fixing issues. Also commenting on old issues without new information really stops us from tracking more recent/prominent issues which we are actively working on

**Comment by fluffapparition** [comment] 2019-10-31 00:08
@ogniK5377 apologies

**Comment by ReinUsesLisp** [comment] 2019-11-03 07:10
After playing for a few hours in yuzu 11 I didn't manage to softlock. Instead I softlocked in yuzu 12. After diffing these two version I noticed that it includes scheduler changes and a few others changes that are not related to threading.

**Comment by walikor** [comment] 2019-11-24 15:08
https://www.reddit.com/r/yuzu/comments/e05jl9/yuzu_pokemon_lets_go_pikachu_softlock_solved/

It seems Is resolved with the version 70!

**Comment by FearlessTobi** [comment] 2019-11-24 15:55
Solved by one of Blinkhawks latest PRs.

**Closed by FearlessTobi** 2019-11-24 15:55 UTC
Labels: regression
