### ISSUE TITLE
[Feature Request] linux prebuild package for newbies

### ISSUE THREAD

**Issue by jug007** [yuzu-emu/yuzu#3555] opened 2020-03-25 10:58 UTC
Yuzu just comes with "loose" binary files on linux.
For most linux users this is bound to be a pretty big turn off, since almost all apps are either in the package repositorys, have their own personal package repository or have something like an AppImage which can be integrated into the system.

Of course yuzu cannot package for all kind of distributions that are out there, but at least an AppImage or a PersonalPackageArchive for Ubuntu would make installation and system integration lot easier for people that don't nessesarily know how to do that on their own.

**Comment by goaaats** [comment] 2020-03-25 11:14
There is a pull request for Flatpak support: https://github.com/yuzu-emu/yuzu/pull/3259

**Comment by Hexagon12** [comment] 2020-03-25 11:16
Also a duplicate of #1549

**Closed by Hexagon12** 2020-03-25 11:16 UTC
