### ISSUE TITLE
Red Dead Redemption

### ISSUE THREAD

**Issue by MakandaDEV** [yuzu-emu/yuzu#11313] opened 2023-08-18 08:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1528, also EA

### Description of Issue

When enabling VULKAN backend in settings, the game has extreme temporal ghosting(?)  that seems to only appear when vegetation is around. When moving camera and then stopping, the ghosting will stay like that, and not go away.
OpenGL does not suffer from this issue.

**Apparently, RDNA 2 only has this issue around vegetation, while on RDNA3 ,its completely unplayable**.

Note: Similar behavior of ghosting can be found in other Rockstar titles on the original PSP hardware. 
When out of bounce for example.

### Expected Behavior

No temporal ghosting when moving the camera  around vegetation.

### Reproduction Steps

Enable Vulkan backend to reproduce.

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12377453/yuzu_log.txt.old.txt)

### System Configuration

Steam Deck, Linux, 16GB ram

**Comment by Levlight** [comment] 2023-08-18 09:01
Example [video](https://discord.com/channels/398318088170242053/402001453381713920/1141689106766770296) form gidoly

**Comment by gandalfthewhite19890404** [comment] 2023-08-18 11:25
Sorry for offtop, Ryujinx fixed this by `Implement support for masked stencil clears on Vulkan`

**Comment by MakandaDEV** [comment] 2023-08-18 11:29
> Sorry for offtop, Ryujinx fixed this by `Implement support for masked stencil clears on Vulkan`

Yes, So the fix is clearing the stencil buffer of a rendering target?

Ive hit up a dev about this already. Time will tell

**Comment by DonelBueno** [comment] 2023-08-19 06:29
![01007820196a6000_2023-08-19_03-23-44-975](https://github.com/yuzu-emu/yuzu/assets/4239694/7e75e075-6121-45b1-a162-a092756198c3)
Anyone else having this issue? The game works perfectly in OpenGL, but is unplayable in Vulkan due to these garbage on the screen.

Yuzu EA 3821, Windows 10 x64, Ryzen 5800x, GTX 1070 8 GB (Driver 536.99).

Maybe it's a Pascal-only bug?

**Comment by MakandaDEV** [comment] 2023-08-19 06:33
> ![01007820196a6000_2023-08-19_03-23-44-975](https://github.com/yuzu-emu/yuzu/assets/4239694/7e75e075-6121-45b1-a162-a092756198c3)
> Anyone else having this issue? The game works perfectly in OpenGL, but is unplayable in Vulkan due to this garbage on the screen.
> 
> Yuzu EA 3821, Windows 10 x64, Ryzen 5800x, GTX 1070 8 GB (Driver 536.99).
> 
> Maybe it's a Pascal-only bug?

Issue got fixed with the release of mainline 1530 roughly 20 minutes ago

**Comment by DonelBueno** [comment] 2023-08-19 06:42
I thought it was also merged into EA. Thanks for the answer.

**Comment by Dizzee112** [comment] 2023-08-19 09:55
the sunlight is flickering through objects

**Closed** 2023-08-19 15:28 UTC

**Comment by Sm0k3r83** [comment] 2023-08-20 02:55
Was working great, until i got to the part where you ride the raft to mexico, but now its doing it again

**Comment by K0bin** [comment] 2023-08-20 10:47
@Sm0k3r83 Upload your save so the developers can reproduce the issue.

**Comment by Filoppi** [comment] 2023-08-20 23:30
> the sunlight is flickering through objects

Yeah I also get this (I haven't tried without the 60fps patch).
It blinks for one frame every second or so.

**Comment by Sm0k3r83** [comment] 2023-08-21 00:16
here is my save folder, next to the river
[01007820196A6000.zip](https://github.com/yuzu-emu/yuzu/files/12389469/01007820196A6000.zip)

**Comment by Sm0k3r83** [comment] 2023-08-21 00:24
Here is my save, next to the river
