### ISSUE TITLE
Tears of the Kingdom: Gloom glitch

### ISSUE THREAD

**Issue by Sakul6499** [yuzu-emu/yuzu#10295] opened 2023-05-14 17:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3589 (and older)

### Description of Issue

Gloom (that red goo-y stuff) appears to be glitched on certain GPUs.
According to [this Reddit thread](https://www.reddit.com/r/NewYuzuPiracy/comments/13fd9hs/totk_yuzu_bugged_gloom_rendering/) and [this Reddit thread](https://www.reddit.com/r/yuzu/comments/13fdl80/totk_yuzu_bugged_gloom_rendering/), the issue seems to only happen on certain GPUs?

Here is how it looks in Yuzu:
![image](https://github.com/yuzu-emu/yuzu/assets/13678392/0df68296-38e6-4d56-9b36-0051d96768e1)

Weirdly, the effects of gloom also trigger based on the glitched appearance and not where the puddle should be.

Clearing the shader cache does not resolve this issue.
Enabling or Disabling "Accelerate ASTC texture decoding" and "Decode ASTC textures asynchronously (Hack)" like suggested in the thread does also not help.

### Expected Behavior

Meanwhile, in Ryujinx and on the Switch it looks like this:
![image](https://github.com/yuzu-emu/yuzu/assets/13678392/27a486f8-631f-4a9a-a117-f0c2bf5ae156)

### Reproduction Steps

Load the provided save:
[0100F2C0115B6000.zip](https://github.com/yuzu-emu/yuzu/files/11472484/0100F2C0115B6000.zip)

### Log File

> Note: I am using the default settings for logs. If there are better settings to better diagnose this issue please inform me about it and I will provide more logs :)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11472485/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 7 5800H (with Radeon Graphics)
GPU/Driver: NVIDIA GeForce RTX 3050 Ti Laptop GPU / v531.79 (latest currently from 05/02/2023)
RAM: 32GB, SODIMM, 3200MHz
OS: Windows 11 Enterprise, Version 22H2, OS Build 22621.1702 with Windows GPU optimizations turned off

**Comment by FernandoS27** [comment] 2023-05-14 17:35
Try keeping accuracy at High.

**Comment by Sakul6499** [comment] 2023-05-14 17:44
> Try keeping accuracy at High.

Same result on high accuracy.

**Comment by The1Bef** [comment] 2023-05-14 21:33
hey man, same stuff

**Comment by OldWorldOrdr** [comment] 2023-05-15 01:02
same issue
CPU: AMD Ryzen 5 5600H (with Radeon Graphics)
GPU: GTX 1650 mobile 531.79

**Comment by FernandoS27** [comment] 2023-05-15 03:50
Please try with 1434 and keep it in high from the start.

**Comment by Zer0Rem** [comment] 2023-05-15 09:08
same issue 
CPU: AMD Ryzen 7 5800X3D
GPU: RTX3070 with latest drivers
Yuzu 3589

**Comment by FernandoS27** [comment] 2023-05-15 09:50
Ok, we are investigating.

**Comment by joshercar** [comment] 2023-05-15 12:41
Same issue with all yuzu versions.
i5 11400h
RTX 3050ti laptop

**Comment by OldWorldOrdr** [comment] 2023-05-15 12:44
> > same issue CPU: AMD Ryzen 5 5600H (with Radeon Graphics) GPU: GTX 1650 mobile 531.79 yuzu 1433
> 
> also in 1434, gpu accuracy is high

doesnt happen on opengl btw, only vulkan

**Comment by OldWorldOrdr** [comment] 2023-05-15 12:45
> Same issue with all yuzu versions. i5 11400h RTX 3050ti laptop

seems like this is an issue with NVIDIA laptop gpus in particular

**Comment by joshercar** [comment] 2023-05-15 12:49
> > Same issue with all yuzu versions. i5 11400h RTX 3050ti laptop
> 
> seems like this is an issue with NVIDIA laptop gpus in particular

mmm i think not, bc i see people with the same issue and no laptop gpus.

**Comment by moznr542** [comment] 2023-05-15 14:45
Seems like EA3591 broke gloom rendering for some users, including myself. It works correctly in 3589.

3591
![yuzu_3591](https://github.com/yuzu-emu/yuzu/assets/90044840/1888981a-0f94-4f18-9b54-8a9c33bc571a)
3589
![yuzu_3589](https://github.com/yuzu-emu/yuzu/assets/90044840/4921cb28-84ef-4f9e-aeed-351be9a8ec2d)


![yuzu_Mzr9uSP6Ex](https://github.com/yuzu-emu/yuzu/assets/90044840/6ca394c4-f047-4cf8-8bc8-9076f12e0fbb)
![yuzu_Vg0FZl0lpq](https://github.com/yuzu-emu/yuzu/assets/90044840/fc047843-934a-427e-b132-82384ffbbc91)

Same settings, same shaders on both versions.
RTX 3080, driver 531.68.

**Comment by OldWorldOrdr** [comment] 2023-05-15 18:41
> driver 531.68
can you update to 531.79 so we're all using the same driver, makes testing easier if we eliminate as many variables as we can

**Comment by YeaSeb** [comment] 2023-05-16 02:38
I've had this for a while I'm on linux tho.
CPU: AMD r9 3900X
GPU: RX570 4gb
Kernel: 6.3.2-zen 
Mesa 23.0.3-1

**Comment by OldWorldOrdr** [comment] 2023-05-16 02:40
I have an Arch Linux dual boot, couldn't get totk working on there but it was with the version from the Arch repos so I'll try again with a more recent build.

**Comment by OldWorldOrdr** [comment] 2023-05-16 03:46
https://oldworldorder.gay/totk.mkv same bug happens on linux.

The weird stuttering is a linux only issue, video is of appimage but it happens on flatpak and builds from source as well
im on gnome 44 with wayland

**Comment by OldWorldOrdr** [comment] 2023-05-16 03:49
if someone knows if there's another issue for the stuttering in that video please lmk so I can post this there

**Comment by Waxx0000** [comment] 2023-05-16 09:30
not sure if related, but Gloom issue may be causing crash in Doom Mountain Depth Area, whole map is supposed to be covered in gloom, loading area will cause yuzu to  crash

**Comment by OldWorldOrdr** [comment] 2023-05-16 15:41
bought early access to test that, 3593 still has the issue for me

**Comment by chiptunesoprano** [comment] 2023-05-17 21:14
Possibly related to upscaling, renders correctly on 3593 at 1x scale

**Comment by Rezkyos** [comment] 2023-05-17 21:43
> Possibly related to upscaling, renders correctly on 3593 at 1x scale

Yes! that was the problem for me. (i5 10400, RX6600) Tested on 3593

**Comment by OldWorldOrdr** [comment] 2023-05-18 00:25
I've always been playing on 1x

**Comment by Zeraxon** [comment] 2023-05-18 16:41
can confirm. bug is related to upscaling. I am on yuzu 1438, Vulkan, GPU Normal, and have the glitched gloom on 2x but not on 1x

I have a GTX 1060 6G with driver version 531.79

**Comment by OldWorldOrdr** [comment] 2023-05-18 17:01
these are my settings, 1x but i still get the glitch
![Screenshot (6)](https://github.com/yuzu-emu/yuzu/assets/57970114/259b2801-8851-4dee-8b4d-9b926367a8b2)

**Comment by ftrevelin** [comment] 2023-05-18 19:56
Also got the gloom bug when I try playing with 2x upscale, with 1x it works fine. 
Yuzu 1438, Vulkan API, GPU Normal, Windows 10, Ryzen5 3600, 16GB Ram, GTX 1060 6GB, current drivers.

**Comment by JulianHeuser** [comment] 2023-05-19 03:39
Duplicate of #10255 ?

**Comment by Rafapim** [comment] 2023-05-19 06:07
On my ultrawide monitor was like this but then I played on tv and it was normal, so I deactivated my ultrawide mod to test it and it fixed.
But then I did more testing with the mod on and messing with the screen proportion in the game custom config, I was using stretch to window, but if I use "force 21:9" it fixes it!

**Comment by The1Bef** [comment] 2023-05-19 10:02
> Possibly related to upscaling, renders correctly on 3593 at 1x scale *but not 2x
> 
> R7 5700X/RTX2060

it doesent. i have always been playing on x1

**Comment by OldWorldOrdr** [comment] 2023-05-19 13:00
Oh I should mention I *kind of* have a dual monitor setup
![PXL_20230519_125822257.jpg](https://github.com/yuzu-emu/yuzu/assets/57970114/788df3a4-112d-4b90-8148-2acfbcab2a37)
But the laptop display doesn't show up in Windows when it's closed.  It's also 1080p 16:9 but at 120hz

**Comment by OldWorldOrdr** [comment] 2023-05-19 13:03
To clarify, the laptop in the top right is what's connected to the monitor, the MacBook is my secondary computer for YouTube and music and stuff, and it couldn't run yuzu at full speed anyway.
![PXL_20230519_125822257~2.jpg](https://github.com/yuzu-emu/yuzu/assets/57970114/521bb315-5ccf-4031-95d5-eeb405ae333f)

**Comment by OldWorldOrdr** [comment] 2023-05-19 13:11
https://a.co/d/fsWnq1x my only upgrades are putting in another 8 GB of RAM and an extra 512 GB SSD.

**Comment by Rafapim** [comment] 2023-05-19 14:10
I noticed no one here seems to be using ultrawide but maybe messing with the proportion settings helps, I'm also using a laptop (alienware m15 r6 with upgraded RAM to 32gb) and these are my graphics packs and settings.

![graphicsPacks](https://github.com/yuzu-emu/yuzu/assets/60678628/0f51844f-03cd-4e4f-9cba-f31a2363ef18)
![Settings](https://github.com/yuzu-emu/yuzu/assets/60678628/486dbf4c-2bfe-4170-af82-50e49e16a2a8)
![advanced](https://github.com/yuzu-emu/yuzu/assets/60678628/7f6e2656-2583-4810-af0d-f89bdfc51169)


Sorry for portuguese UI, don't know how to change to english

**Comment by OldWorldOrdr** [comment] 2023-05-19 18:09
i just never entered fullscreen and i still get the issue

**Comment by OldWorldOrdr** [comment] 2023-05-19 18:10
or if by "start in fullscreen" you mean check the box in the view menu to enter fullscreen when opening a game, I was doing that already.

**Comment by Doguinhoo** [comment] 2023-05-19 19:20
Also have the same issue.
Happens on all the versions I have tested.

Build: Early Access 3599
CPU: Intel Core i5-12600K
GPU/Driver: NVIDIA GTX 1060 3GB, driver 530.41.03
RAM: 16GB
OS: Garuda Linux (based on Arch Linux)

**Comment by revulent** [comment] 2023-05-19 19:54
Strangely this doesnt happen for me on build 1433 but does on 1434 and every build after that. this is on linux (flatpak) with an AMD rx5700.

**Comment by Sakul6499** [comment] 2023-05-19 20:35
> Duplicate of #10255 ?

Not a duplicate but similar!
That referenced issue is about the gloom effect (those red clouds) not rendering correctly, whereas this issue is about the gloom puddles themselves :) 

(At least to my understanding based on comments ...)

**Comment by OldWorldOrdr** [comment] 2023-05-20 00:52
If by "when the map loads" you mean when I can walk around and stuff, that didn't fix it. @Rafapim

**Comment by devmachine1** [comment] 2023-05-20 15:12
Same for me, my specs:

Model: Lenovo Ideapad Gaming 3
CPU: Ryzen 7 5800H 
RAM: 16GB 3200 Mhz DDr4 
GPU: RTX 3050Ti Laptop 
GPU Driver Version: v531.79 (latest right now: 20/05/23)
OS: Windows 11

yuzu Version: EA 3599 and Mainline 1439 - Vulkan - GPU HIGH - 1x

didnt test on older versions will try soon

**Comment by Rafapim** [comment] 2023-05-20 15:41
> If by "when the map loads" you mean when I can walk around and stuff, that didn't fix it. @Rafapim

Sorry it didn't work, for me it is it. Tested multiple times without changing anything, if I change from window to fullscreen during load time is the only that it bugs the gloom texture.

**Comment by devmachine1** [comment] 2023-05-20 17:31
> Same for me, my specs:
> 
> Model: Lenovo Ideapad Gaming 3 CPU: Ryzen 7 5800H RAM: 16GB 3200 Mhz DDr4 GPU: RTX 3050Ti Laptop GPU Driver Version: v531.79 (latest right now: 20/05/23) OS: Windows 11
> 
> yuzu Version: EA 3599 and Mainline 1439 - Vulkan - GPU HIGH - 1x
> 
> didnt test on older versions will try soon

I tested on EA 3588 and it doesnt work there too, I think its a translation/encryption problem, i dont think its shader related because ive also deleted my shader cache and its still the same, I also tried different mods which fix bugs like these on yuzu for TOTK but none of them worked. I guess im stuck...

**Comment by devmachine1** [comment] 2023-05-21 06:18
also my weapons icons are wrong too, my weapon is a soldier sword but the icon shows a branch etc

**Comment by chiptunesoprano** [comment] 2023-05-21 06:37
> also my weapons icons are wrong too, my weapon is a soldier sword but the icon shows a branch etc

https://github.com/yuzu-emu/yuzu/issues/10327

**Comment by HotPotatoC** [comment] 2023-05-21 06:59
> Chiming in, I also have the issue on my laptop
> 
> Early Access 3599 - Vulkan - GPU HIGH - 2x (1x still have the same issue)
> Model: Lenovo Legion Slim 7
> GPU: RTX 3060, driver 531.79
> CPU: Ryzen 7 5800h
> RAM: 32GB
> OS: Windows 11

update, reverting back to EA3588 and using 1x apparently fixed the issue for me

**Comment by devmachine1** [comment] 2023-05-21 08:23
> > Chiming in, I also have the issue on my laptop
> > Early Access 3599 - Vulkan - GPU HIGH - 2x (1x still have the same issue)
> > Model: Lenovo Legion Slim 7
> > GPU: RTX 3060, driver 531.79
> > CPU: Ryzen 7 5800h
> > RAM: 32GB
> > OS: Windows 11
> 
> update, reverting back to EA3588 and using 1x apparently fixed the issue for me

can u maybe upload your settings? I tried on EA 3588 but it doesnt work even in 1x Scale and rebuilding shaders

**Comment by devmachine1** [comment] 2023-05-21 08:28
so by that i mean the .ini file or you can just write them down manually (only the graphics and adv. graphics setting and only if u have time and u wnat to)

**Comment by HotPotatoC** [comment] 2023-05-21 09:50
> so by that i mean the .ini file or you can just write them down manually (only the graphics and adv. graphics settings and only if u have time and u want to)

alright, I'll share it whenever I'm available

**Comment by Phantom9621** [comment] 2023-05-21 11:30
This error can only be solved by changing to the standard resolution 720 and 1080 if you are using vulkan in opengl the same thing does not happen

**Comment by devmachine1** [comment] 2023-05-21 12:56
there have been changes to the vulkan renderer in the latest EA (3600), has someone tested already?

**Comment by devmachine1** [comment] 2023-05-21 12:57
> This error can only be solved by changing to the standard resolution 720 and 1080 if you are using vulkan in opengl the same thing does not happen

it doesnt work tho even on 1x default settings

**Comment by devmachine1** [comment] 2023-05-21 13:18
i just tried totk in EA 3600 its still the same but worse the game is very pixelated now lol

**Comment by HotPotatoC** [comment] 2023-05-21 13:33
> so by that i mean the .ini file or you can just write them down manually (only the graphics and adv. graphics settings and only if u have time and u want to)

Here's my settings
<img width="539" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/43059506/a5da49d2-b020-47c6-845a-37c267a81a00">
<img width="537" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/43059506/8c0b9407-7849-4960-8d7f-972e1866f8f3">

And also my mods if necessary
<img width="537" alt="image" src="https://github.com/yuzu-emu/yuzu/assets/43059506/7b17f974-b65d-4099-b9a8-4998177f218e">

**Comment by devmachine1** [comment] 2023-05-21 14:58
> 

thanks, I will try them and update if it works with them

**Comment by chiptunesoprano** [comment] 2023-05-21 17:02
For me still not broken at native for EA3600, but still broken at non-native. Using 1.1.1 and latest mods from the discord-linked GitHub including the 1008p patch (no FSR/DR/FXAA) and vulkan.

**Comment by devmachine1** [comment] 2023-05-21 17:17
> > so by that i mean the .ini file or you can just write them down manually (only the graphics and adv. graphics settings and only if u have time and u want to)
> 
> Here's my settings
> 
> TOTK Version 1.1.0
> <img alt="image" width="381" src="https://user-images.githubusercontent.com/43059506/239749552-b2a747b9-89c5-41a5-af49-114a3479d085.png"> <img alt="image" width="379" src="https://user-images.githubusercontent.com/43059506/239749564-5e52ea29-9809-42f3-9166-3a1af2510e09.png">
> 
> And also my mods if necessary <img alt="image" width="372" src="https://user-images.githubusercontent.com/43059506/239749588-dc3993a5-a1c3-486f-b48c-a391955961ed.png">

doesnt work for me even with the settings and mods, but still thanks

**Comment by devmachine1** [comment] 2023-05-21 17:17
> For me still not broken at native for EA3600, but still broken at non-native. Using 1.1.1 and latest mods from the discord-linked GitHub including the 1008p patch (no FSR/DR/FXAA) and vulkan.

what do you mean by native/non-native?

**Comment by chiptunesoprano** [comment] 2023-05-21 17:26
> > For me still not broken at native for EA3600, but still broken at non-native. Using 1.1.1 and latest mods from the discord-linked GitHub including the 1008p patch (no FSR/DR/FXAA) and vulkan.
> 
> what do you mean by native/non-native?

Native res (1x) in graphics settings vs anything above that.

**Comment by devmachine1** [comment] 2023-05-21 17:46
> > > For me still not broken at native for EA3600, but still broken at non-native. Using 1.1.1 and latest mods from the discord-linked GitHub including the 1008p patch (no FSR/DR/FXAA) and vulkan.
> > 
> > 
> > what do you mean by native/non-native?
> 
> Native res (1x) in graphics settings vs anything above that.

can u maybe share your specs? I dont know what im doing wrong.

**Comment by chiptunesoprano** [comment] 2023-05-21 18:05
> > > > For me still not broken at native for EA3600, but still broken at non-native. Using 1.1.1 and latest mods from the discord-linked GitHub including the 1008p patch (no FSR/DR/FXAA) and vulkan.
> > > 
> > > 
> > > what do you mean by native/non-native?
> > 
> > 
> > Native res (1x) in graphics settings vs anything above that.
> 
> can u maybe share your specs? I dont know what im doing wrong.

RTX2060/5700X latest Nvidia drivers. Same settings as hotpotato except I don't use async presentation or force max clocks.

**Comment by Flaming-Dorito** [comment] 2023-05-22 02:57
Same issue on yuzu EA 3600 (and earlier). Both 1x and 2x. GPU accuracy: high

Ryzen 5 3600
Nvidia GTX 1060

**Comment by chiptunesoprano** [comment] 2023-05-22 02:58
> Same issue on yuzu EA 3600 (and earlier). Both 1x and 2x. GPU accuracy: high
> 
> Ryzen 5 3600 Nvidia GTX 1060 6GB 16GB RAM

Have you tried the new texture compression feature? Fixed it for me.

**Comment by devmachine1** [comment] 2023-05-22 07:04
> > Same issue on yuzu EA 3600 (and earlier). Both 1x and 2x. GPU accuracy: high
> > Ryzen 5 3600 Nvidia GTX 1060 6GB 16GB RAM
> 
> Have you tried the new texture compression feature? Fixed it for me.

is it in ver 3600?

**Comment by chiptunesoprano** [comment] 2023-05-22 07:05
> > > Same issue on yuzu EA 3600 (and earlier). Both 1x and 2x. GPU accuracy: high
> > > Ryzen 5 3600 Nvidia GTX 1060 6GB 16GB RAM
> > 
> > 
> > Have you tried the new texture compression feature? Fixed it for me.
> 
> is it in ver 3600?

3601, though 3602 just released with more fixes

**Comment by devmachine1** [comment] 2023-05-22 07:59
> > > > Same issue on yuzu EA 3600 (and earlier). Both 1x and 2x. GPU accuracy: high
> > > > Ryzen 5 3600 Nvidia GTX 1060 6GB 16GB RAM
> > > 
> > > 
> > > Have you tried the new texture compression feature? Fixed it for me.
> > 
> > 
> > is it in ver 3600?
> 
> 3601, though 3602 just released with more fixes

oh ok is 3602 better or should i stay with 3601

**Comment by devmachine1** [comment] 2023-05-22 08:19
these are my mods (you can find them here: https://github.com/HolographicWings/TOTK-Mods-collection):
![Screenshot 2023-05-22 101401](https://github.com/yuzu-emu/yuzu/assets/94474309/e83d126c-3f20-4698-ad87-ca26de89b0db)

these are my Graphics and Advanced Graphics Settings

![Screenshot 2023-05-22 101425](https://github.com/yuzu-emu/yuzu/assets/94474309/ff39512f-2d71-4705-bc9d-7a6e59798208)
![Screenshot 2023-05-22 101448](https://github.com/yuzu-emu/yuzu/assets/94474309/14679885-56d5-425f-aa93-0e5689e4e902)

**Comment by HotPotatoC** [comment] 2023-05-22 14:42
> Chiming in, I also have the issue on my laptop
> 
> Early Access 3599 - Vulkan - GPU HIGH - 2x (1x still have the same issue) Model: Lenovo Legion Slim 7 GPU: RTX 3060, driver 531.79 CPU: Ryzen 7 5800h RAM: 32GB OS: Windows 11

I can confirm that on EA3602 the gloom issue has been fixed for me

**Comment by Sakul6499** [comment] 2023-05-22 16:49
EA 3602 fixed this for me too :) 

Probably resolved then?

**Comment by devmachine1** [comment] 2023-05-22 18:41
has someone tested it on Mainline 1440?

**Comment by OldWorldOrdr** [comment] 2023-05-22 21:12
the fix isnt in mainline yet

**Comment by devmachine1** [comment] 2023-05-23 10:18
> 

ok

**Comment by Meleagorn47** [comment] 2023-05-23 16:54
Hey guy's, got some news for the gloom glitch, download the 3602 EA Yuzu and make sure you toggle "ASTC recompression : BC3 (Medium Quality)" in the advanced video settings. It will fix all those weird glitches, it did for me. here's the link https://github.com/pineappleEA/pineapple-src/releases/tag/EA-3602

**Comment by OldWorldOrdr** [comment] 2023-05-23 20:37
I don't think we're allowed to share leaked EA builds, if you want to use EA builds sub to their patreon

**Comment by Flaming-Dorito** [comment] 2023-05-23 21:16
@OldWorldOrdr  PineappleEA is totally allowed. It's not a leaked build. Yuzu EA builds are publicly available under the GPLv3 Licence

Check the ReadMe: https://github.com/pineappleEA/pineapple-src

**Comment by OldWorldOrdr** [comment] 2023-05-23 21:44
Oh I know it's *legally* allowed, I just figured the devs wouldn't like people posting it since it's only purpose is to get around a paywall, which normally I'm all for but this seems like a smaller project so I figured they need it more then most.

**Comment by OldWorldOrdr** [comment] 2023-05-23 21:47
referring to it as a leaked build was a bit hyperbolic but I couldn't think of a better term.

**Comment by pahanakun** [comment] 2023-05-23 23:00
Still broken for me in Vulkan at 2x (handheld and docked) with a Geforce 980. Also broken in 1.5x and for some reason at 1.5x it looks like docked & handheld are switched (handheld is definitely running above 1440p) - gonna report it as a new bug if its not already listed. Gloom is fixed in OpenGL & not an issue with 1x docked 1080p Vulkan, but I'd prefer Vulkan for the performance and can easily do 45fps @1440p. Latest EA build 3602. "ASTC recompression : BC3 (Medium Quality)" unfortunately is not fixing it for me either. Guess its either 1440p OpenGL or 1080p Vulkan, maybe I'll try for 60fps
![opengl-gloom-ok](https://github.com/yuzu-emu/yuzu/assets/45723080/cfec8f3b-e0dc-4ff1-a899-4e5cc5a788f7)
![vulkan-gloom-ok-1080p](https://github.com/yuzu-emu/yuzu/assets/45723080/f833305b-093f-444f-a599-a25d45c42d3b)
![vulkan-gloom-still-issue](https://github.com/yuzu-emu/yuzu/assets/45723080/93eb2cf8-4e18-4e76-9c7d-286bf9e4a674)
![wonky-reversed-1 5x-handheld-docked](https://github.com/yuzu-emu/yuzu/assets/45723080/8b8b0614-f173-41ca-a4ab-db1f3b35f98b)

**Comment by chiptunesoprano** [comment] 2023-05-23 23:36
Try low quality, native res, or a combo of both. You only have 4gb vram, and low vram is apparently the cause of the bug.

**Comment by pahanakun** [comment] 2023-05-24 04:22
bc1 did nothing, and like i already said, native res fixes it.
works fine at this resolution in openGL. Bug also isn't present at this resolution in Ryujinx, so it *is* possible with my 4GB of VRAM, that I already knew I was limited to :/
it being listed as "fixed on all GPUs" in the reddit bug megathread is misleading. Hope its not based on like a handful of people here just saying it was fixed for them lol

**Comment by pahanakun** [comment] 2023-05-24 04:48
Vulkan in Ryujinx that is

**Comment by FernandoS27** [comment] 2023-05-24 08:24
Should be fixed next EA. Let me know if not.

**Comment by pahanakun** [comment] 2023-05-24 11:36
awesome! dancing with anticipation, loading shaders to test now :3

**Comment by Flaming-Dorito** [comment] 2023-05-25 14:54
Fixed for me in 3604. Broke again in 3606. I went back to 3604. Havent tested anything past 3606 yet.

Anybody know if the fix is in mainline yet?

**Comment by OldWorldOrdr** [comment] 2023-05-25 15:19
its fixed in 3610, not in mainline yet

**Comment by Zeraxon** [comment] 2023-05-26 10:21
just started up Mainline Build 1446. seems to be fixed now.

**Comment by VioletSkies19** [comment] 2023-05-26 13:18
I am suddenly getting this bug after updating to mainline 1446. I haven’t had this bug for weeks beforehand. This is the only thing I changed about my settings.

**Comment by VioletSkies19** [comment] 2023-05-26 13:39
I rolled back to 1444 and the issue still persists

**Comment by VioletSkies19** [comment] 2023-05-26 21:49
The latest EA build seems to have fixed it for me now

**Comment by devmachine1** [comment] 2023-05-27 10:52
> I rolled back to 1444 and the issue still persists

mainline isnt really good for totk buy early access from patreon or get it from pineappleEA (its free on github)

**Comment by gidoly** [comment] 2023-09-21 04:04
fixed on last builds

**Closed by gidoly** 2023-09-21 04:04 UTC
