### ISSUE TITLE
TOTK: Extreme "Z-fighting/flickering" in distance in versions EA 3656+

### ISSUE THREAD

**Issue by Zemeon** [yuzu-emu/yuzu#10771] opened 2023-06-14 06:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3656+

### Description of Issue

Beginning in EA 3656, distance "Z-fighting" increased in severity. See this comparison album between 3656 and 3654: https://imgur.com/a/I2bUPxJ

### Expected Behavior

Z-fighting at least no worse than video of 3564; in which it nearly doesn't occur (imgur video compression basically hides it on 3654)

### Reproduction Steps

Use one of the Skyview towers in versions 3656+ (Sahasra Slope in video) dive just below the clouds to where the sky color changes (important, severity seems the worst in this zone of the sky and gets better going higher up) and observe the distance "Z-fighting/flickering" 

I also did a launch of the game "without a custom configuration" and without mods but with 1.1.2 update installed in 3656 as a sanity check to the same results.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11742049/yuzu_log.txt)

### System Configuration

CPU: 5600x
GPU/Driver: 2070 Super 535.98
RAM: 16gb (4x4) ddr4 3200
OS: Windows 10

**Comment by StudliousMaximus** [comment] 2023-06-14 06:51
I can confirm that this issue is still present in Yuzu 3673. All over the Great Sky Island, there is LOD flickering as seen in https://i.imgur.com/DrJDgl1.mp4 and https://i.imgur.com/iSQTUdx.mp4.

**Comment by kratores85** [comment] 2023-06-14 06:51
Confirmed. Z-fighting is heavy especially when looking straight down outside of the "Room of Awakening" - more so on clear weather (no clouds). In EA 3652 the issue doesn't occur.

**Comment by kratores85** [comment] 2023-06-14 17:37
It's fixed in EA 3675. Thanks!

**Comment by Zemeon** [comment] 2023-06-16 00:23
It's better! I wouldn't say z-fighting is entirely resolved though; here's footage from 3678 https://sendvid.com/fo0a9er6

The behavior is the same as 3654 in my testing.

It's mostly just bad around the shoreline. It's not visible at all heights, so just fall slowly until you see the shore flicker. It's not super picky, but it's the most aggressive near the highest height that you can first start to see it occur on the shore lines.

**Closed** 2023-06-16 00:37 UTC

**Comment by liamwhite** [comment] 2023-06-16 01:01
@Zemeon This issue was just tracking the regression. The root cause can be fixed by #10560.
