### ISSUE TITLE
Pokemon Sword randomly crashes

### ISSUE THREAD

**Issue by Oneshinw3** [yuzu-emu/yuzu#4804] opened 2020-10-20 03:55 UTC
Yuzu just randomly crashes and closes on itself and/or the game freezes at random points. And I mean random points so it can basically happen at anytime.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5406122/yuzu_log.txt)

**Comment by FearlessTobi** [comment] 2020-10-20 21:27
Probably a duplicate of https://github.com/yuzu-emu/yuzu/issues/4227.

**Closed by FearlessTobi** 2020-10-20 21:27 UTC
