### ISSUE TITLE
Super Mario Odyssey: Dock mode causes every other frame to be blank (potential epilepsy trigger!)

### ISSUE THREAD

**Issue by ElBiggus** [yuzu-emu/yuzu#6438] opened 2021-06-09 19:40 UTC
I was getting some annoying slowdown in SM:O so I tried switching to Dock mode, but doing so appears to render every other frame as black causing the screen to flicker - from what I understand, in dock mode SM:O renders two half horizontal resolution frames (so frame 1 it renders even pixel columns, frame 2 it renders odd pixel columns but leaves the evens from the previous frame, frame 3 renders the evens and leaves the odds from the previous frame, etc.)

**Comment by G-Spawn** [comment] 2021-06-11 00:07
Providing a log would also help.

**Comment by ElBiggus** [comment] 2021-06-11 07:55
OK, here's one; I switched modes back and forth a few times, but nothing suspicious shows up in the log as far as I can see, but YMMV. (It also appears that the UI overlay *doesn't* flicker, but I will capture some footage later and take a closer look - it's unbearable to look at in real-time for more than a second or so!)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6636730/yuzu_log.txt)

**Comment by ElBiggus** [comment] 2021-06-11 08:30
Captured footage confirms the UI doesn't flicker and it is every other frame that's black, and in a potentially related (but also perhaps not) issue, slow camera pans in undocked mode sometime result in nothing being rendered for a while. Link below to captured footage. (I'm tempted to put in a feature request for a keyboard shortcut to switch between docked/undocked!)

https://drive.google.com/file/d/1fQ21ghQsl9L2qR1gUwsY3h_UQYSpjRDw/view?usp=sharing

(I also realise my initial bug report said "switch to dock mode", when I meant "switch to undocked mode". It had been a long day.)

**Comment by varlesh** [comment] 2021-06-14 02:45
Confirm this too on Linux
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6645300/yuzu_log.txt)
https://user-images.githubusercontent.com/8083855/121832161-7b63b180-ccda-11eb-810c-8f33b48596e4.mp4

**Comment by Morph1984** [comment] 2021-06-15 09:29
We do not provide support on piracy, closing.

**Closed by Morph1984** 2021-06-15 09:29 UTC

**Comment by ElBiggus** [comment] 2021-06-15 10:32
Not sure how this is a piracy issue? I own the game, and even if I didn't that doesn't make this any less of a bug. Oh well, you do you I guess.

**Comment by OZtistic** [comment] 2021-06-15 18:46
Your log clearly shows pirated content. 
It might well be a "bug"
It's also a bug no one seems to be able to reproduce
This ticket was closed for a good reason @ElBiggus

**Comment by ElBiggus** [comment] 2021-06-15 20:34
I have a Switch Lite so don't have the luxury of dumping my own ROMs (as far as I can tell, anyway; feel free to correct me if I am wrong - I am a newcomer to the platform so don't feel entirely comfortable experimenting) so I have to source them from elsewhere. Heck, I only use Yuzu in the first place because having the scrub tier console means I can't plug it in to a TV. Not supporting pirated content is all well and good, but perhaps a "cannot replicate; may be due to bad ROM dump" or something would have been helpful (if that is indeed the case) rather than what seems like an instant dismissal based on an incorrect assumption.

Perhaps you still consider downloading a copy of something I own is somehow "more wrong" than the already illegal process of circumventing DRM measures? To me it seems like a meaningless distinction, but each to their own. IANAL, but while backing up content you own may be covered by fair use (although it is not an automatic right, and as purchasing software just grants you a *license* and not ownership it probably doesn't apply at all), circumventing DRM (or other technical measures) for any reason is an offence under the DMCA even if no copyright infringement takes place; from a legal standpoint dumping your own ROM may in fact be *more* illegal than downloading it; copyright infringement is largely a civil matter, but violating the DMCA is a legit federal offence. The law is dumb.

Also, Jim Sterling makes a fair point: https://www.youtube.com/watch?v=OA8xrgLqQZ8 

Anyway, I finished the game on the actual Switch now so whatever - fix it, ignore it, accuse me of stuff based on circumstantial evidence, its all the same to me!

**Comment by G-Spawn** [comment] 2021-06-15 23:18
There isn't much point in trying to expand or justify stealing for simply being held to the same standards or rules as everyone else. 

"(I'm tempted to put in a feature request for a keyboard shortcut to switch between docked/undocked!)"
 There is already a keyboard hotkey for this by hitting f10 if you had looked into the hotkeys you might have seen this 
![image](https://user-images.githubusercontent.com/23653025/122134768-44da8380-ce0d-11eb-86ff-0c0b4b913701.png)

As for the previous issue at hand its not reproducible here on either of my rigs.. So yes, it could very well be something odd about your pirated copy. Beyond that I have nothing further to say as the issue is closed.

https://user-images.githubusercontent.com/23653025/122134799-53c13600-ce0d-11eb-8529-a0bfec07a912.mp4
