### ISSUE TITLE
AMD Delay issues info ( as requested )

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#1324] opened 2018-09-15 03:52 UTC
https://gist.github.com/ReaperOfSouls1909/9df1da67f8d853c4ef7ec21fe8b5c352 asm and text https://gist.github.com/ReaperOfSouls1909/423e8e3a9712b8124d24d5c449dc24ef FS info 

https://gist.github.com/ReaperOfSouls1909/c66676ac6e98df056cd3e4823c521a7c asm vs and text vs shader https://gist.github.com/ReaperOfSouls1909/73dfc3b897c6a3e304d2adcc468d6af6
VS info

**Comment by FernandoS27** [comment] 2018-09-15 04:05
Abstract:
That shader in particular takes a long amount of time to process for an small data subset. AMD in general is bottlenecked by the shaders we produce.

Labels:
GPU, Performance

Technical Info:

Card: AMD R9 290x.
Architecture: GCN Tahiti.

Problem:
Those shaders take 45ms for 264 input Vertices.
An inspection of the assembly is required.

**Comment by FernandoS27** [comment] 2018-09-24 01:44
Ok I've revised the issue and here's my conclusion:

It turns out that unlike NVIDIA's architecture. AMD's GCN is a SIMD architecture, meaning that all floating point instructions are done in simultanously on vectors. Since NVIDIA shaders fraction the operations into scalar operations, recompiling in that promise does not affect NVIDIA GPUs. In the case of AMD the output GCN does not seem to revectorize our shader code, thus it runs scalar operations at the cost of a SIMD instruction. In other words, in order for us to support AMD we would need to  implement a revectorizer which is extremely complex procedure to do.

Among other explanations for the AMD delay, the presented card is a bit old (2013). Modern AMD cards should perform better but they still have the added cost of running scalar code as SIMD code.

**Comment by nmiell** [comment] 2018-09-24 17:50
GCN isn't SIMD.

There are a very limited set of packed U8 instructions on all GCN and a slightly less limited set of packed U16/I16/F16 instructions on Vega. But broadly speaking it is a scalar architecture.

**Comment by FernandoS27** [comment] 2018-09-24 18:15
I don't think you are reading the manual correctly: https://gpuopen.com/compute-product/amd-gcn3-isa-architecture-manual/
ALL Floating Point Instructions are SIMD (only integer and boolean are scalar).  If you look at the generated code, you'll notice most instructions are SIMD:

```
  v_add_f32     v9, v15, v10                                // 000004DC: 0612150F
  v_cndmask_b32  v10, 0, v66, s[4:5]                        // 000004E0: D200000A 00128480
  v_add_f32     v14, v16, v17                               // 000004E8: 061C2310
  v_add_f32     v15, v18, v19                               // 000004EC: 061E2712
  v_cndmask_b32  v16, 0, v70, s[8:9]                        // 000004F0: D2000010 00228C80
  v_add_f32     v17, v20, v21                               // 000004F8: 06222B14
  v_cndmask_b32  v18, 0, v73, vcc                           // 000004FC: 00249280
  v_cmp_eq_i32  s[4:5], v1, 3                               // 00000500: D1040004 00010701
  v_add_f32     v1, v22, v23                                // 00000508: 06022F16
  v_mac_f32     v2, v5, v7                                  // 0000050C: 3E040F05
  v_mul_f32     v4, v4, v8                                  // 00000510: 10081104
  v_mac_f32     v0, v6, v11                                 // 00000514: 3E001706
  s_waitcnt     lgkmcnt(0)                                  // 00000518: BF8C007F
  s_buffer_load_dwordx2  s[8:9], s[40:43], 0x00             // 0000051C: C2442900
  v_add_f32     v7, v10, v14                                // 00000520: 060E1D0A
  v_add_f32     v8, v16, v17                                // 00000524: 06102310
  v_cndmask_b32  v10, 0, v74, s[4:5]                        // 00000528: D200000A 00129480
  v_add_f32     v1, v18, v1                                 // 00000530: 06020312
  v_mac_f32     v4, v5, v3                                  // 00000534: 3E080705
  v_mac_f32     v2, v6, v9                                  // 00000538: 3E041306
  v_add_f32     v0, v15, v0                                 // 0000053C: 0600010F
  v_add_f32     v1, v10, v1                                 // 00000540: 0602030A
  v_mac_f32     v4, v6, v8                                  // 00000544: 3E081106
  v_add_f32     v2, v7, v2                                  // 00000548: 06040507
```
the v_ prefix is for vector instruction if you read the manual instead of just skimming and cherry picking.

**Comment by FernandoS27** [comment] 2018-09-24 18:38
Read Section 3.6.4
VGPRs execute on FOUR DWords. They are not scalar registers!

Also SIMT is a SIMD that's executed in parallel Threads. So either way only one result matters as the compiler is alocating scaler floats into individual vectors without revectorizing. This means the effort of some threads is wasted.

**Comment by nmiell** [comment] 2018-09-24 18:48
VGPRs are 32 bits wide, see table 3.1.

Section 3.6.4 refers to the fact that VGPRs are dynamically assigned to a
wavefront in multiples of 4. While a shader can theoretically have a
maximum of 102 SGPRs and 256 VGPRs, the actual number of registers in a
compute unit is implementation-dependent and the fewer registers that you
assign to a shader, the more active wavefronts can be managed
simultaneously by the hardware scheduler.

On Mon, Sep 24, 2018 at 11:39 AM, Fernando Sahmkow <notifications@github.com

**Comment by pendingchaos** [comment] 2018-09-24 19:02
The VGPR and SGPR count of the vertex shader looks suspiciously high:
```
USED_VGPRS=75
USED_SGPRS=56
```
So the throughput of the shader could be pretty low because of that.

The original shader only uses 18 or so, so the code scheduler might be scheduling it too aggressively for ILP or the register allocation could just be doing a very poor job.

Or maybe GCN's instructions don't work very well with the (unusual) code yuzu is generating.

**Comment by FernandoS27** [comment] 2018-09-24 19:11
hmn if it's actualy scalar then why is it wasting so many registers?

Needs more investigation.

**Comment by pendingchaos** [comment] 2018-09-24 19:54
Looking at the code, I think it's the code scheduler's fault. It seems to be scheduling it poorly with regards to the constant buffer loads at the beginning.

Combined with the large amount of 128-bit constant buffer loads and large live ranges of the addresses used for the loads (e.g. v30 is only killed at the second last load), seems to be creating the high VGPR count.

The code is pretty bad for both ILP and occupancy. The loads are done pretty late, making them close to when they are used (instead of interleaving the address calculation with the loads, which would create much better code).

**Comment by FernandoS27** [comment] 2018-09-24 20:10
So in general we can't do anything, it's the compilers fault?

**Comment by pendingchaos** [comment] 2018-09-24 20:39
Pretty much I think?

I don't think one can easily know for sure if the code is the problem unless the code is fixed or it's presented to someone more familiar with the hardware. It probably is the problem though.

Maybe the compiler could be coaxed into generating better code or one could ask on #radeon for advice or solutions or a bug report could be filed if there isn't on already.

**Comment by pendingchaos** [comment] 2018-09-24 20:47
Looking closer, I think the ILP might be mostly ok? The shader is pretty noisy and difficult to read though.

The register usage is definitely too high and could be better (probably without even effecting ILP too much).

**Comment by nmiell** [comment] 2018-09-24 22:10
If you want to issue the loads as early as possible and run the loads in parallel, you have to store the result somewhere.

And the loads aren't done late, they're done as soon as the load of the memory descriptor they use (in S8-S11) has completed.

**Comment by ReaperOfSouls1909** [comment] 2018-09-25 16:10
if one of you can open a ticket on radon forms for devs and get it checked or have them test it out they could come up with a clean fix

**Comment by ReinUsesLisp** [comment] 2019-09-23 08:12
The issue itself is not in GPU-side performance. Emitting the same quality of shaders in SPIR-V on Vulkan makes this same scene get decent numbers on AMD's blob drivers.

This means that the issue is in the OpenGL driver's CPU side performance, as such it's beyond yuzu's control. Closing as wont-fix.

**Closed by ReinUsesLisp** 2019-09-23 08:12 UTC
Labels: gpu-issue, opengl
