### ISSUE TITLE
I have some problems with new Pokemon

### ISSUE THREAD

**Issue by toMY4534** [yuzu-emu/yuzu#3181] opened 2019-11-28 19:18 UTC
I have some problems with new Pokemon

I checked a lot of guarding with every save there is a problem otherwise the noises don't speak

https://i.imagesup.co/images2/d8bdb82447339c451c19490beac10b69b2366342.jpg

**Comment by Hexagon12** [comment] 2019-11-28 19:31
Duplicate of #3128

**Closed by Hexagon12** 2019-11-28 19:31 UTC
