### ISSUE TITLE
Yuzu sometimes shows higher fps than it actually is (async GPU related)

### ISSUE THREAD

**Issue by Gustav0ar** [yuzu-emu/yuzu#2774] opened 2019-07-30 12:32 UTC
While playing SMO, also noticed in PLG, occasionally the displayed fps shows higher values than it actually is, this causes it to hit the 100% speed limit and starting to get throttled (getting lower framerates than it should). One way to mitigate the issue is to rise manually the speed limit so that yuzu doesn't force the throttling.

Yuzu version: 2518 / d1a04b3

System Specs:
Ryzen 1800x stock
Nvidia GTX 1070
32gb of ram
Linux Mint 19.1 (based on Ubuntu 18.04)

**Comment by slashiee** [comment] 2019-08-07 23:04
Is async gpu emulation enabled? Try disabling it, as it's still rather buggy from what I recall

**Comment by Hexagon12** [comment] 2019-08-08 14:48
Disabling async is not the actual fix. Remember - this is a bug tracker and not a support forum. This issue will not be closed until this bug gets fixed in asynchronous GPU emulation.

**Comment by fluffapparition** [comment] 2019-08-08 23:51
@Hexagon12 if it were a fix, it's only partial. Itd be nice to see async working as intended and so if that were the cause of this problem finding out why is important.

I suggest the OP check to see if async is the culprit here and if it is I'd like assistance in finding out more

**Comment by Gustav0ar** [comment] 2019-08-09 00:05
@fluffapparition its related to the gpu async, that doesn't happen without it

**Comment by FernandoS27** [comment] 2019-08-09 15:09
@Hexagon12 As I've said 100 times. This is not a gpu issue but a core issue

**Comment by fluffapparition** [comment] 2019-08-10 21:33
@FernandoS27 ^^^

**Comment by antigamer101** [comment] 2021-03-07 09:29
for me async makes lights in Mario + Rabbids Kingdom Battle become too dark to see
but without it, it's too light to see
but with async gpu emulation without its shader building 
its like a party of both too light and too dark
as in this photo
![image](https://user-images.githubusercontent.com/77435073/110235364-4eb03900-7f38-11eb-9a4e-2c8059edff0e.png)

**Closed** 2022-09-02 19:34 UTC
Labels: bug, hle-issue
