### ISSUE TITLE
Fire Emblem Engage, game freezes when character will speak

### ISSUE THREAD

**Issue by M4rQu1Nh0S** [yuzu-emu/yuzu#9790] opened 2023-02-12 19:36 UTC
### yuzu Version

Mainline 1335

### Description

The game freezes almost every time when a character speaks after leveling up or when starts a conversation after beginning the battle.

Looking at dmesg, there is an error logged:
```

[36062.281965] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception on GPC 1: SAVE_RESTORE_ADDR_OOB
[36062.281979] NVRM: Xid (PCI:0000:01:00): 13, pid='<unknown>', name=<unknown>, Graphics Exception: ESR 0x508900=0x80000001
[36062.282112] NVRM: Xid (PCI:0000:01:00): 13, pid=65541, name=yuzu, Graphics Exception: ChID 003b, Class 0000c197, Offset 00001c00, Data 00001024
```

This freezes only happens on Vulkan, in OpenGL the game does not have this issue, but in OpenGL the memory usage is huge.

I'm using nvidia driver 470, but this issue happens too with versions 510, 515 and 525 of the driver.

### Reproduction Certainty

Not always, but often

### System Information

```bash session
System:
  Host: ubuntu-jammy Kernel: 5.15.0-60-generic x86_64 bits: 64 compiler: gcc
    v: 11.3.0 Desktop: GNOME 42.5 Distro: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Machine:
  Type: Desktop Mobo: ASRock model: H61M-HVS serial: <superuser required>
    UEFI: American Megatrends v: P2.50 date: 09/18/2012
CPU:
  Info: quad core model: Intel Core i7-2600 bits: 64 type: MT MCP
    arch: Sandy Bridge rev: 7 cache: L1: 256 KiB L2: 1024 KiB L3: 8 MiB
  Speed (MHz): avg: 1985 high: 3492 min/max: 1600/3800 cores: 1: 3492
    2: 2608 3: 1638 4: 1616 5: 1609 6: 1619 7: 1701 8: 1599 bogomips: 54276
  Flags: avx ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] vendor: eVga.com.
    driver: nvidia v: 470.161.03 bus-ID: 01:00.0
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    gpu: nvidia resolution: 1366x768~60Hz
  OpenGL: renderer: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
    v: 4.6.0 NVIDIA 470.161.03 direct render: Yes
Network:
  Device-1: Realtek RTL810xE PCI Express Fast Ethernet vendor: ASRock
    driver: r8168 v: 8.050.03-NAPI port: d000 bus-ID: 03:00.0
  IF: enp3s0 state: up speed: 100 Mbps duplex: full mac: bc:5f:f4:23:26:01
Drives:
  Local Storage: total: 1.25 TiB used: 406.04 GiB (31.7%)
Info:
  Processes: 345 Uptime: 1h 0m Memory: 15.59 GiB used: 4 GiB (25.7%)
  Init: systemd runlevel: 5 Compilers: gcc: 11.3.0 Packages: 2094 Shell: Bash
  v: 5.1.16 inxi: 3.3.13
```

### Logs and Backtraces

[yuzu_log.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/10711453/yuzu_log.txt)
[yuzu_log.txt.old.txt](https://github.com/flathub/org.yuzu_emu.yuzu/files/10711454/yuzu_log.txt.old.txt)

### Remarks

-This error happens with all versions, flatpak, compiled from source and AppImage version.
-After the game freezes, the Yuzu does not respond, during app closing the whole system freeze, but comes back after Yuzu finally closes.
-The issue only happens with Vulkan
-In OpenGL mode, the RAM usage is very high, using the 16GB of Physical Memory easily but the game does not freeze in OpenGL.
-This issue is present in older yuzu builds too.

**Comment by liamwhite** [comment] 2023-02-12 19:37
Duplicate of #9654 - thanks for the report

**Closed by liamwhite** 2023-02-12 19:37 UTC
