### ISSUE TITLE
Feature Request: Right Click > Delete Game

### ISSUE THREAD

**Issue by cfw34683** [yuzu-emu/yuzu#4301] opened 2020-07-11 16:55 UTC
I don't know if I'm dumb but I'm just bothered by the fact that trying to right click on a title in the NAND and I fully expected a "delete title" on the game... I copied my switch's whole nintendo folder over and it 170gigs xD so I need to delete some games.

**Comment by ToxaGaming** [comment] 2020-07-11 16:59
I think a feature to delete titles from NAND could be a useful addition too, considering you can install them

**Comment by FearlessTobi** [comment] 2020-07-11 19:04
Duplicate of https://github.com/yuzu-emu/yuzu/issues/2633.

**Closed by FearlessTobi** 2020-07-11 19:04 UTC

**Comment by Hexaae** [comment] 2022-07-07 10:24
Sorry if I ask, but why there is no option to delete also non-NAND games?
If I try with some roms I get the error "This game is not installed in the NAND and cannot be removed" when I choose "Remove All  installed contents". I expected it work also for non-NAND games...

**Comment by Norstyrm** [comment] 2022-07-07 15:02
As the setting says it will remove all **installed** contents. ROM files only reside in your game directory and are not installed into yuzu. The game settings too don't count as installed contents as they're generated.

**Comment by apennismightier** [comment] 2024-01-04 16:42
There is absolutely no option to remove any game listings within Yuzu on the Steam Deck.
