### ISSUE TITLE
Increase RUMBLE (Android) 

### ISSUE THREAD

**Issue by Fasto5** [yuzu-emu/yuzu#11054] opened 2023-07-09 03:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

REQ: Please add option for Rumble.

### Why would this feature be useful?

Adding Rumble will enhance a user's gaming experience.

**Comment by german77** [comment] 2023-07-09 05:16
We don't have rumble support on Android at the moment

**Comment by FearlessTobi** [comment] 2023-07-09 16:49
Duplicate of https://github.com/yuzu-emu/yuzu/issues/11019.

**Closed by FearlessTobi** 2023-07-09 16:49 UTC
Labels: request
