### ISSUE TITLE
Vulkan render issues, Legend of Zelda: Skyward sword HD

### ISSUE THREAD

**Issue by Conzyyy** [yuzu-emu/yuzu#7455] opened 2021-11-28 14:35 UTC
Using the latest version of Yuzu 831(Non- early access)

CPU: R5 3600
GPU: RX 570 8GB
RAM: 16GB DDR4

While using the Vulkan renderer I have been experiencing a few graphical errors in Skyward Sword HD, mainly in cutscenes. Gameplay is fine and render issues seem to be gone using OpenGL however there are terrible slowdowns in demanding areas for example Skyloft even though FPS is 60. My game is unmodded and all settings were left at default.

The graphical issues are not game-breaking however I thought I would bring this issue to the attention of the devs. The issues seem to only be present in this game (Have not experienced issues in the other games I am emulating). Keep up the great work devs!

![Main menu render error 2](https://user-images.githubusercontent.com/87369485/143772323-9237c280-ad27-4b0b-abad-bfbd29000469.PNG)
![Main Menu render error](https://user-images.githubusercontent.com/87369485/143772330-a62a9e13-b914-45ca-a01d-272df0a5c747.PNG)

**Comment by GamzMaka12** [comment] 2021-11-29 16:33
I have this same issue, I was seeing if this was a known issues but I don't see anything on it.

AMD Ryzen 5 3600
GeForce RTX 2060
16GB (2x8GB) PNY ELEX DDR4 3200
500GB WD SSD

Switching to OpenGL seemed to make the game playable with no render issues. Hopefully there's a fix. 

Vulkan
![yuzu 832 11_29_2021 11_30_56 AM](https://user-images.githubusercontent.com/95238983/143906338-027195db-3f01-4cd2-bf10-0562658f5e77.png)
![yuzu 832 11_29_2021 11_31_07 AM](https://user-images.githubusercontent.com/95238983/143906339-18c6a4d1-40cd-40ef-8a92-92d43dccc957.png)
![yuzu 832 11_29_2021 11_31_33 AM](https://user-images.githubusercontent.com/95238983/143906340-37629215-f073-4070-a167-12f66216a383.png)
![yuzu 832 11_29_2021 11_31_41 AM](https://user-images.githubusercontent.com/95238983/143906342-59081f64-1739-4be3-83a7-76337a5c7b43.png)

OpenGL
![yuzu 832 11_29_2021 11_31_56 AM](https://user-images.githubusercontent.com/95238983/143906349-09754aa9-a807-4df4-ba16-c715ecf938c2.png)
![yuzu 832 11_29_2021 11_32_21 AM](https://user-images.githubusercontent.com/95238983/143906352-96464ebf-c881-439d-ad80-36bd3c342101.png)
![yuzu 832 11_29_2021 11_32_28 AM](https://user-images.githubusercontent.com/95238983/143906356-5ed07bb6-f346-47ba-987a-01bcdeb93e33.png)

**Comment by german77** [comment] 2021-12-07 03:10
Duplicate of #7133

**Closed by german77** 2021-12-07 03:10 UTC
