### ISSUE TITLE
Huge Framerate decrease with dynarmic on some latest nightly builds

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#272] opened 2018-03-23 23:00 UTC
## Hardware Specs :
- Nvidia GeForce GTX 960
- AMD FX-6300
- 8 GB Of Ram
- Windows 7 Pro

## Yuzu Build Version tested :
Yuzu nightly build HEAD-68658ce

## The issue :
I have notice a few nightly builds ago that there is a huge frame rate decrease with dynarmic. Before on oxidgb.10-print I was able to achieve 40 fps and now I'm able to achieve 2 fps. Another example on SpaceNX before i was able to achieve 12 fps and now I'm able to achieve 8 fps.
So what the reason of this frame rate decrease ?

**Comment by bunnei** [comment] 2018-03-24 02:39
More recent nightlies do seem slower. Looking into it. If you're able to define the breaking build, please let us know.

**Comment by bunnei** [comment] 2018-03-24 03:01
Nevermind, #193 caused the slow down.
To be determined still if it's a real regression, or if the slow down is expected due to improved timing.

**Comment by bunnei** [comment] 2018-03-24 03:27
Looking at `arm_dynarmic.cpp`, I see some weird shit. For example:
<pre>
    void AddTicks(u64 ticks) override {
        if (ticks > ticks_remaining) {
            ticks_remaining = 0;
            return;
        }
        ticks -= ticks_remaining; // <--- THIS IS WRONG, RIGHT?
    }
</pre>

Furthermore, ticks is always a really small number... like 6-7.

@MerryMage any thoughts on how to fix this? I assume we can get decent enough timing accuracy without the 80%+ perf hit this PR is currently causing...

**Comment by N00byKing** [comment] 2018-03-24 08:38
fuck. Sorry .-.

**Comment by MerryMage** [comment] 2018-03-24 08:42
@bunnei Yeah, that's incorrect.
I'll do something that doesn't require a callback in the future.

**Comment by bunnei** [comment] 2018-03-24 09:49
@greggameplayer Thanks for catching this regression and reporting it 👍 
We believe it is fixed in latest nightly (with change #275). Can you please confirm that the issue is resolved, and if so close this issue? Thanks!

**Comment by Hexagon12** [comment] 2018-03-24 10:49
It's fixed for me, at least.

**Comment by N00byKing** [comment] 2018-03-24 10:49
For me too

**Comment by greggameplayer** [comment] 2018-03-24 12:13
I think it's fix but my fps is a bit less than before

**Comment by bunnei** [comment] 2018-03-24 18:00
Thanks! We've made lots of other changes so I'm not surprised if it's a little slower - but as long as there aren't any major perf regressions, I think that we are fine for now.

**Closed by bunnei** 2018-03-24 18:00 UTC
