### ISSUE TITLE
Pokemon Sword random freezes on Vulkan/Nvidia on EA 2300

### ISSUE THREAD

**Issue by anonus1231** [yuzu-emu/yuzu#7564] opened 2021-12-11 23:11 UTC
[log.zip](https://github.com/yuzu-emu/yuzu/files/7697870/log.zip)
It happens after 5 - 60 minutes of playing, very often before automatic save.
Looks like a lot of:
`[2187.998349] HW.Memory <Error> core\memory.cpp:operator ():498: Unmapped Read8 @ 0x0000002154200009
[2187.998353] HW.Memory <Error> core\memory.cpp:operator ():498: Unmapped Read8 @ 0x000000215420000A
[2187.998354] HW.Memory <Error> core\memory.cpp:operator ():498: Unmapped Read8 @ 0x000000215420000B
[2187.998354] HW.Memory <Error> core\memory.cpp:operator ():498: Unmapped Read8 @ 0x000000215420000C
[2187.998356] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x0000002154200009 = 0x0000000000000060
[2187.998358] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x000000215420000A = 0x0000000000000094
[2187.998359] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x000000215420000B = 0x0000000000000080`

NVIDIA GeForce GTX 1070
NVIDIA driver 497.9.0.0

Settings: 
![image](https://user-images.githubusercontent.com/61919372/145694396-458f9063-2c3e-466e-9654-84e1c23f40a1.png)

**Comment by gidoly** [comment] 2021-12-11 23:17
it is duplicate of already existing issue

**Comment by SpecialDarkwolf999** [comment] 2021-12-12 05:57
You use a wrong driver use 472

**Comment by anonus1231** [comment] 2021-12-12 18:19
Checked on 472.85 also and it froze after 55 minutes with the same error messages in the logs

**Comment by SpecialDarkwolf999** [comment] 2021-12-12 18:27
i played the game more then 6 hours a day for two weeks without problems and already finished it without problems but you are running on 3x instead of me on 2x dont know why you use 3x because your card doesnt support that.

**Comment by G-Spawn** [comment] 2021-12-13 13:30
> it is duplicate of already existing issue

Closing as this is duplicate of several other identical issues. It'll be fixed in future someday, stay tuned.

**Closed by G-Spawn** 2021-12-13 13:30 UTC
