### ISSUE TITLE
GDB Stub fails to connect

### ISSUE THREAD

**Issue by shibbo** [yuzu-emu/yuzu#1850] opened 2018-12-03 23:01 UTC
Using Yuzu Canary 1665 on Windows 10 (commit fa19a45), GDB completely fails to connect with the following message:

(gdb) target remote 127.0.0.1:1001
Remote debugging using 127.0.0.1:1001
Remote replied unexpectedly to 'vMustReplyEmpty': PacketSize=2000;qXfer:features:read+;qXfer:threads:read+;qXfer:libraries:read+

Previous versions of Yuzu also fail with this same exact error. I have attempted to turn off my antivirus and my firewall, and it still fails to connect with the same message. The version of GDB used is the one that is packed with devkitPro (8.0).

**Comment by jroweboy** [comment] 2018-12-04 05:48
Some quick searching on this topic reveals that gdb 8 added a new check to make sure that unknown query packets return an empty string instead. https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#Packets (search for vMustReplyEmpty) 

Curiously enough, my quick scan of the stub tells me we should already be handling this case https://github.com/yuzu-emu/yuzu/blob/adc4d332fc1a4054b80cfd575025351b970da689/src/core/gdbstub/gdbstub.cpp#L681

**Comment by shibbo** [comment] 2018-12-04 14:06
What exactly would cause this unknown query packet?

**Comment by comex** [comment] 2019-07-06 22:09
Debug.GDBStub log when reproducing this issue:
```
[   4.708084] Debug.GDBStub <Info> core\gdbstub\gdbstub.cpp:Init:1271: Starting GDB server on port 24689...
[   4.708966] Debug.GDBStub <Info> core\gdbstub\gdbstub.cpp:Init:1305: Waiting for gdb to connect...
[  13.381662] Debug.GDBStub <Info> core\gdbstub\gdbstub.cpp:Init:1318: Client connected.
[  19.596445] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:HandlePacket:1173: Packet: qSupported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+
[  19.596462] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:HandleQuery:625: gdb: query 'Supported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+'
[  19.596475] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:SendReply:591: Reply: PacketSize=2000;qXfer:features:read+;qXfer:threads:read+;qXfer:libraries:read+
[  19.596844] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:HandlePacket:1173: Packet: qSupported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+
[  19.596848] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:HandleQuery:625: gdb: query 'Supported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+'
[  19.596852] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:SendReply:591: Reply: PacketSize=2000;qXfer:features:read+;qXfer:threads:read+;qXfer:libraries:read+
[  19.597201] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:HandlePacket:1173: Packet: qSupported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+
[  19.597204] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:HandleQuery:625: gdb: query 'Supported:multiprocess+;swbreak+;hwbreak+;qRelocInsn+;fork-events+;vfork-events+;exec-events+;vContSupported+;QThreadEvents+;no-resumed+'
[  19.597207] Debug.GDBStub <Debug> core\gdbstub\gdbstub.cpp:SendReply:591: Reply: PacketSize=2000;qXfer:features:read+;qXfer:threads:read+;qXfer:libraries:read+
[  19.597516] Debug.GDBStub <Error> core\gdbstub\gdbstub.cpp:ReadByte:462: recv failed: 18446744073709551615
[  19.597520] Debug.GDBStub <Info> core\gdbstub\gdbstub.cpp:Shutdown:1337: Stopping GDB ...
[  19.597536] Debug.GDBStub <Info> core\gdbstub\gdbstub.cpp:Shutdown:1347: GDB stopped.
[  19.597543] Debug.GDBStub <Error> core\gdbstub\gdbstub.cpp:ReadByte:462: recv failed: 18446744073709551615
[  19.597544] Debug.GDBStub <Info> core\gdbstub\gdbstub.cpp:Shutdown:1337: Stopping GDB ...
[  19.597686] Debug.GDBStub <Info> core\gdbstub\gdbstub.cpp:Shutdown:1347: GDB stopped.
```
(The last three log messages are repeated infinitely, though this didn't happen a different time I reproduced it.)

Corresponding Wireshark log:
```
00000000  2b                                                 +
00000001  24 71 53 75 70 70 6f 72  74 65 64 3a 6d 75 6c 74   $qSuppor ted:mult
00000011  69 70 72 6f 63 65 73 73  2b 3b 73 77 62 72 65 61   iprocess +;swbrea
00000021  6b 2b 3b 68 77 62 72 65  61 6b 2b 3b 71 52 65 6c   k+;hwbre ak+;qRel
00000031  6f 63 49 6e 73 6e 2b 3b  66 6f 72 6b 2d 65 76 65   ocInsn+; fork-eve
00000041  6e 74 73 2b 3b 76 66 6f  72 6b 2d 65 76 65 6e 74   nts+;vfo rk-event
00000051  73 2b 3b 65 78 65 63 2d  65 76 65 6e 74 73 2b 3b   s+;exec- events+;
00000061  76 43 6f 6e 74 53 75 70  70 6f 72 74 65 64 2b 3b   vContSup ported+;
00000071  51 54 68 72 65 61 64 45  76 65 6e 74 73 2b 3b 6e   QThreadE vents+;n
00000081  6f 2d 72 65 73 75 6d 65  64 2b 23 64 66            o-resume d+#df
0000008E  24 71 53 75 70 70 6f 72  74 65 64 3a 6d 75 6c 74   $qSuppor ted:mult
0000009E  69 70 72 6f 63 65 73 73  2b 3b 73 77 62 72 65 61   iprocess +;swbrea
000000AE  6b 2b 3b 68 77 62 72 65  61 6b 2b 3b 71 52 65 6c   k+;hwbre ak+;qRel
000000BE  6f 63 49 6e 73 6e 2b 3b  66 6f 72 6b 2d 65 76 65   ocInsn+; fork-eve
000000CE  6e 74 73 2b 3b 76 66 6f  72 6b 2d 65 76 65 6e 74   nts+;vfo rk-event
000000DE  73 2b 3b 65 78 65 63 2d  65 76 65 6e 74 73 2b 3b   s+;exec- events+;
000000EE  76 43 6f 6e 74 53 75 70  70 6f 72 74 65 64 2b 3b   vContSup ported+;
000000FE  51 54 68 72 65 61 64 45  76 65 6e 74 73 2b 3b 6e   QThreadE vents+;n
0000010E  6f 2d 72 65 73 75 6d 65  64 2b 23 64 66            o-resume d+#df
0000011B  24 71 53 75 70 70 6f 72  74 65 64 3a 6d 75 6c 74   $qSuppor ted:mult
0000012B  69 70 72 6f 63 65 73 73  2b 3b 73 77 62 72 65 61   iprocess +;swbrea
0000013B  6b 2b 3b 68 77 62 72 65  61 6b 2b 3b 71 52 65 6c   k+;hwbre ak+;qRel
0000014B  6f 63 49 6e 73 6e 2b 3b  66 6f 72 6b 2d 65 76 65   ocInsn+; fork-eve
0000015B  6e 74 73 2b 3b 76 66 6f  72 6b 2d 65 76 65 6e 74   nts+;vfo rk-event
0000016B  73 2b 3b 65 78 65 63 2d  65 76 65 6e 74 73 2b 3b   s+;exec- events+;
0000017B  76 43 6f 6e 74 53 75 70  70 6f 72 74 65 64 2b 3b   vContSup ported+;
0000018B  51 54 68 72 65 61 64 45  76 65 6e 74 73 2b 3b 6e   QThreadE vents+;n
0000019B  6f 2d 72 65 73 75 6d 65  64 2b 23 64 66            o-resume d+#df
000001A8  24 71 53 75 70 70 6f 72  74 65 64 3a 6d 75 6c 74   $qSuppor ted:mult
000001B8  69 70 72 6f 63 65 73 73  2b 3b 73 77 62 72 65 61   iprocess +;swbrea
000001C8  6b 2b 3b 68 77 62 72 65  61 6b 2b 3b 71 52 65 6c   k+;hwbre ak+;qRel
000001D8  6f 63 49 6e 73 6e 2b 3b  66 6f 72 6b 2d 65 76 65   ocInsn+; fork-eve
000001E8  6e 74 73 2b 3b 76 66 6f  72 6b 2d 65 76 65 6e 74   nts+;vfo rk-event
000001F8  73 2b 3b 65 78 65 63 2d  65 76 65 6e 74 73 2b 3b   s+;exec- events+;
00000208  76 43 6f 6e 74 53 75 70  70 6f 72 74 65 64 2b 3b   vContSup ported+;
00000218  51 54 68 72 65 61 64 45  76 65 6e 74 73 2b 3b 6e   QThreadE vents+;n
00000228  6f 2d 72 65 73 75 6d 65  64 2b 23 64 66            o-resume d+#df
    00000000  2b                                                 +
    00000001  24 50 61 63 6b 65 74 53  69 7a 65 3d 32 30 30 30   $PacketS ize=2000
    00000011  3b 71 58 66 65 72 3a 66  65 61 74 75 72 65 73 3a   ;qXfer:f eatures:
    00000021  72 65 61 64 2b 3b 71 58  66 65 72 3a 74 68 72 65   read+;qX fer:thre
    00000031  61 64 73 3a 72 65 61 64  2b 3b 71 58 66 65 72 3a   ads:read +;qXfer:
    00000041  6c 69 62 72 61 72 69 65  73 3a 72 65 61 64 2b 23   librarie s:read+#
    00000051  36 64                                              6d
00000235  2b                                                 +
00000236  24 76 4d 75 73 74 52 65  70 6c 79 45 6d 70 74 79   $vMustRe plyEmpty
00000246  23 33 61                                           #3a
    00000053  2b                                                 +
    00000054  24 50 61 63 6b 65 74 53  69 7a 65 3d 32 30 30 30   $PacketS ize=2000
    00000064  3b 71 58 66 65 72 3a 66  65 61 74 75 72 65 73 3a   ;qXfer:f eatures:
    00000074  72 65 61 64 2b 3b 71 58  66 65 72 3a 74 68 72 65   read+;qX fer:thre
    00000084  61 64 73 3a 72 65 61 64  2b 3b 71 58 66 65 72 3a   ads:read +;qXfer:
    00000094  6c 69 62 72 61 72 69 65  73 3a 72 65 61 64 2b 23   librarie s:read+#
    000000A4  36 64                                              6d
00000249  2b                                                 +
    000000A6  2b                                                 +
    000000A7  24 50 61 63 6b 65 74 53  69 7a 65 3d 32 30 30 30   $PacketS ize=2000
    000000B7  3b 71 58 66 65 72 3a 66  65 61 74 75 72 65 73 3a   ;qXfer:f eatures:
    000000C7  72 65 61 64 2b 3b 71 58  66 65 72 3a 74 68 72 65   read+;qX fer:thre
    000000D7  61 64 73 3a 72 65 61 64  2b 3b 71 58 66 65 72 3a   ads:read +;qXfer:
    000000E7  6c 69 62 72 61 72 69 65  73 3a 72 65 61 64 2b 23   librarie s:read+#
    000000F7  36 64                                              6d
```

There's a notable delay between when GDB connects and when it fails, corresponding to yuzu loading the game.  I think the issue is:
- Because the relevant thread is blocked, yuzu doesn't respond immediately to the `qSupported` request.
- GDB times out and resends the request... several times.
- Eventually yuzu gets around to responding to all of GDB's requests, but GDB only expects a single response.  After it receives the first `qSupported` response it sends a `vMustReplyEmpty` command, then it receives the second `qSupported` response and thinks it's a response to `vMustReplyEmpty`.

This could be fixed by putting the GDB stub on its own thread.

**Comment by mid-kid** [comment] 2020-01-22 09:41
Knowing this, a workaround that can currently be used with the GDB CLI is using CTRL+Z shortly after connecting, until yuzu has loaded the game, and then type `fg`. This allows me to consistently connect to it.

**Closed** 2020-03-24 20:50 UTC
