### ISSUE TITLE
[Request] Launch qt in fullscreen via launch parameter

### ISSUE THREAD

**Issue by ActualMandM** [yuzu-emu/yuzu#5177] opened 2020-12-09 16:34 UTC
Currently it's only possible to launch yuzu in fullscreen if you use yuzu-cmd, which is completely busted. The main executable does not allow for any launch parameters, so you have to manually make the game fullscreen when launching yuzu via a shortcut.

**Comment by FearlessTobi** [comment] 2020-12-26 22:17
Duplicate of https://github.com/yuzu-emu/yuzu/issues/5033.

**Closed by FearlessTobi** 2020-12-26 22:17 UTC
