### ISSUE TITLE
Random and frequent freezes while playing Mario Party Superstars

### ISSUE THREAD

**Issue by erisve1337** [yuzu-emu/yuzu#7469] opened 2021-11-29 16:25 UTC
Random and frequent freezes while playing Mario Party Superstars 1.1.0. (Tried with 1.0 also same issue)

yuzu Version: yuzu 831
CPU: AMD Ryzen Threadripper 1920X 12-Core Processor  | AVX2 | FMA
OS: Windows 10 Version 2009
RAM: 95.88 GB
GPU: NVIDIA Gefore RTX 2070
OpenGL

Log goes up to 100mb filled with this error:
HW.Memory <Error> core\memory.cpp:operator ():498: Unmapped Read32 @

Log file: https://drive.google.com/file/d/1XcldmZD5Dw8D_CwTRf5njJGQP9BT67RK/view?usp=sharing

**Comment by G-Spawn** [comment] 2021-11-29 16:31
try updating gpu drivers to 472.12 and perhaps redump your update file of the game.

**Comment by legend800** [comment] 2021-11-29 17:08
This is defineyely a yuzu problem. Everyone has commented on this on discord. The game is not stable on Yuzu and soft locks constantly.

**Comment by legend800** [comment] 2021-11-29 17:10
https://github.com/yuzu-emu/yuzu/issues/7247

**Comment by SpecialDarkwolf999** [comment] 2021-12-16 07:31
the game is reporting on debug this :
[ 242.257163] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.257166] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.257167] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.257168] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.257171] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.257172] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.257173] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.257174] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.257362] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.257365] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.257366] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.257367] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.257369] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.257370] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.257370] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.257371] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.257589] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2078: called handle 0x003601AD
[ 242.258133] Service.AM <Warning> core\hle\service\am\am.cpp:TryPopFromFriendInvitationStorageChannel:1768: (STUBBED) called
[ 242.258765] Kernel.SVC <Debug> core\hle\kernel\svc.cpp:ResetSignal:2078: called handle 0x000F81EA
[ 242.258932] Service.Audio <Debug> core\hle\service\audio\audren_u.cpp:RequestUpdateImpl:94: (STUBBED) called
[ 242.259120] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259124] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259125] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259126] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259348] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259350] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259351] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259353] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259354] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.259355] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.259356] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.259357] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.259359] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259360] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259361] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259362] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259420] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259421] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259422] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259424] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259425] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.259426] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.259427] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.259428] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=753664
[ 242.259451] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259452] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259453] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259454] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259484] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259486] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259487] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259488] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259491] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259492] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259493] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259494] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259509] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259510] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259511] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259512] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:GetGraphicsSampler:141: Invalid sampler index=4095
[ 242.259514] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259515] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259516] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575
[ 242.259517] HW.GPU <Debug> video_core/texture_cache/texture_cache.h:VisitImageView:371: Invalid image view index=1048575

**Comment by benderscruffy** [comment] 2023-05-15 12:19
Can be closed
Duplicate of #7247

**Closed** 2023-05-15 14:56 UTC
Labels: bug
