### ISSUE TITLE
Making controller window more compact

### ISSUE THREAD

**Issue by VladimirVSC** [yuzu-emu/yuzu#11061] opened 2023-07-09 14:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The Controller option window is too big and bulky for 720p monitors. While in mainline 1465 this windows elements were mixing with each other, it could be fixed by stretching the window. But in 1490 with more controller features being added, the stretching doesn't help anymore - the interface elements are covering each other making some functions unselectable. Maybe it should be better to reduce the size of window elements and make the controller window interface more compact. Thanks in advance.

1465 default window
![1465 screen before stretching](https://github.com/yuzu-emu/yuzu/assets/96921167/fcb0a12d-8c77-4b0d-96b1-86f9dd666292)

1465 after stretching
![1465 screen after stretching](https://github.com/yuzu-emu/yuzu/assets/96921167/64dbce1f-eb87-4284-94ff-83b219cb46a6)

1490 after stretching
![1490 after stretching](https://github.com/yuzu-emu/yuzu/assets/96921167/b0d3b23f-9977-48b3-b86a-e7006337e0db)

### Why would this feature be useful?

It would be useful for the owners of 720p monitors, for they could fully see and use the controller functionality.

**Comment by FearlessTobi** [comment] 2023-07-09 16:41
Duplicate of https://github.com/yuzu-emu/yuzu/issues/8206.

**Closed by FearlessTobi** 2023-07-09 16:41 UTC
Labels: request
