### ISSUE TITLE
Unimplemented function "GetKeyCodeMap2"

### ISSUE THREAD

**Issue by Mr-Tako** [yuzu-emu/yuzu#3025] opened 2019-10-24 04:00 UTC
Needed for Divinity Original Sin 2.

Version: Yuzu 26

Debug Text:
Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:154: Assertion Failed! Unknown / unimplemented function 'GetKeyCodeMap2': port='set' cmd_buf={[0]=0x1000006, [1]=0x8, [2]=0x1000, [3]=0xAC0E000, [4]=0x0, [5]=0x0, [6]=0x0, [7]=0x0, [8]=0x49434653}

**Comment by Morph1984** [comment] 2019-10-24 04:03
Duplicate of #2841, please search if it exists before making the issue.

**Closed** 2019-10-24 04:11 UTC
