### ISSUE TITLE
[android] Audio issue 

### ISSUE THREAD

**Issue by M-hyun** [yuzu-emu/yuzu#10919] opened 2023-06-26 11:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

all android builds

### Description of Issue

- plugging or unplugging headset with make audio disappear while in-game 
- while in-game... entering settings and coming back to the game make the audio disappear
- screen recording while in-game does make audio disappear too (if you start SR first and use yuzu after... audio is played and captured normally)

### Expected Behavior

continuation of the audio playing 

### Reproduction Steps

none

### Log File

log have nothing to do with this issue 

### System Configuration

CPU: sd 860
GPU/Driver: adreno 640 
RAM: 8
OS: miui14 android 13

**Comment by FearlessTobi** [comment] 2023-06-26 14:21
Duplicate of https://github.com/yuzu-emu/yuzu/issues/10800.

**Closed by FearlessTobi** 2023-06-26 14:21 UTC
