### ISSUE TITLE
Super Mario Maker 2 -- Audio issues

### ISSUE THREAD

**Issue by ThePsycrow** [yuzu-emu/yuzu#3087] opened 2019-11-09 10:48 UTC
The game has audio volume all that's all over the place, along with other audio issues.
For example, in the 3DW ghost house (play mode), there's a loud wind effect that drowns everything else out, but the volume of that wind is barely noticeable in the original game (you just hear the music, whereas with Yuzu you barely hear the music, just the wind).
When hopping on a bomb, the ticker sound (the beep indicating the bomb is about to explode) keeps playing after it explodes and eternally afterwards, even if exiting the level, going to different menus, etc.
Just a couple examples

**Comment by Hexagon12** [comment] 2019-11-09 11:11
Duplicate of #1952.

All of the issues described are related to audio mixing not being implemented.

**Closed by Hexagon12** 2019-11-09 11:11 UTC

**Comment by Hexagon12** [comment] 2019-11-09 11:38
According to a dev, not all of the issues described here were related to audio mixing. Could you please open a new issue just for the ticking bomb problem?
