### ISSUE TITLE
[Xenoblade Chronicles 3] Missing VFX particles and potentially other special effects

### ISSUE THREAD

**Issue by GenericMeow** [yuzu-emu/yuzu#8723] opened 2022-08-06 01:05 UTC
Build: Yuzu EA 2890
Renderer: Vulkan
Game version : 1.1.0

CPU : Intel(R) Core(TM) i9 9900K
GPU : AMD Radeon 6700 XT
Driver : 22.7.1
RAM : 16GB
OS : Windows 10 latest build

Issue: Missing VFX particles.

Steps to reproduce: Play the game until you defeat the first Moebius boss for the second time and watch the cutscene. Or watch "Chapter 1 - Inherited Hope" cutscene from the Event Theater.

Tested on both High and Extreme GPU accuracy settings.

Old Log file is >30MB so not sure which part you need me to provide. 

Comparison screens:

Missing particles:

<a href="https://ibb.co/GPRG679"><img src="https://i.ibb.co/ThtJfc1/missing-particles.jpg" alt="missing-particles" border="0"></a>

Present particles:

<a href="https://ibb.co/gZk8XJZ"><img src="https://i.ibb.co/7tsDTKt/present-particles.jpg" alt="present-particles" border="0"></a>

Please let me know should you require any additional details.

**Comment by Bjorn29512** [comment] 2022-08-06 01:06
Duplicate of #8663

**Comment by GenericMeow** [comment] 2022-08-06 01:12
Just to note that this is occurring on Vulkan renderer, not OpenGL as specified in 8663.

**Closed** 2022-08-06 01:12 UTC

**Comment by german77** [comment] 2022-08-06 01:14
You can add the log to the other issue. Since the issue is practically the same

**Comment by laststand0810** [comment] 2022-08-06 16:39
is this issue fixed and have it merged to yuzu 1124 2022-08-06? Cuz as far as I see, there's no improvement on it...
