### ISSUE TITLE
Yuzu takes a long time to load configure and crashes when loading Zelda BotW

### ISSUE THREAD

**Issue by nhasa01** [yuzu-emu/yuzu#8302] opened 2022-05-04 06:25 UTC
It takes between a minute and a minute and a half to load the "configure" menu and meanwhile the program stops responding and when I try to run Zelda BotW it also spends around a minute trying to load the game but then the emulator crashes.

Before, everything ran perfectly, I even finished Zelda BotW without any problem or graphical glitch but for a while this happened even though I updated Yuzu with new versions.

My drivers are up to date and I've tried to solve it by deleting the qt-config.ini file but nothing worked.

My setup:
Intel Core i5 9400
AMD Radeon RX 550 4GB
16GB RAM 2400MHz

PS: how do I report that some games are already running well despite not being updated on the list? Dragon Quest III and Valis Collection are running flawlessly!

**Comment by G-Spawn** [comment] 2022-05-04 11:03
Provide a log file please. As for your other question you report compatibility whilst in game but it has to have proper entry in our list for any report to show up.

**Comment by nhasa01** [comment] 2022-05-05 00:40
Here it is. I hope i'll be enough to realize what's the problem. Thanks in advance!
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/8628207/yuzu_log.txt)
.

**Comment by RuinerVoid** [comment] 2022-05-05 15:37
I'm having the same issue on the current EA (2720).

 After starting Yuzu, if I go to configure the program or load a game, there's a LARGE amount of time before anything progresses. I don't, however, crash when starting BotW, it just takes a long time to start the process of loading it, just like the time it takes to just enter the configuration menu. What's really odd is that if I close the configuration window, then try to go into it again, the same large loading time happens again as well.
 
This is not the way it used to work, and it's been a minute since I used it so I don't know at which point this regression occurred. BotW seems to be playing a bit slower than before as well. (I usually use x3 scale with FSR an no AA, and it would load up and play pretty quick, not anymore)

Using the other menu options that doesn't have to load anything is quick and snappy like normal.

My setup:
AMD Ryzen 5900X
AMD Radeon RX 5700 XT
32GB RAM @ 3600MHz

Also loading off a M.2 drive. 

There are no errors in my log, only warnings of games not having the correct file extension. The rest is the same as what loaded fine before.

**Comment by nhasa01** [comment] 2022-05-05 17:43
Some other think i didn't said, all game take more time to load and the program stops responding while is loading but the game in the end runs. I tested with Super Mario Odyssey, Dragon Quest III and Valis Collection. But as i said before, The Legend of Zelda BotW crashes the emulator.

**Comment by G-Spawn** [comment] 2022-05-06 04:40
@nhasa01 Sadly we can't support piracy here you'll have to dump everything from your nintendo switch in order for us to help.

**Comment by nhasa01** [comment] 2022-05-07 03:23
@G-Spawn ok, understood. If you want you even can delete this issue. Thanks in advance.

**Comment by G-Spawn** [comment] 2022-05-07 21:29
Your understanding is appreciated. Closing.

**Closed by G-Spawn** 2022-05-07 21:29 UTC
