### ISSUE TITLE
Totk yuzu, Gloom is flat, no volume, when closeby, fine when seen by far

### ISSUE THREAD

**Issue by The1Bef** [yuzu-emu/yuzu#10255] opened 2023-05-12 20:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1429/1431

### Description of Issue

Gloom , when the character is close, is flat, either dots, or lines, totally flat. EDIT: even the hitzone is altered to those spots
![rn_image_picker_lib_temp_299a9ac2-e275-417d-909b-f4b3b6a207b2](https://github.com/yuzu-emu/yuzu/assets/133425869/fd54b726-210f-49fe-a7c2-a221f20df8e1)
![SPOILER_cec0658e-2e9c-4eab-b41c-9570dc6e6743](https://github.com/yuzu-emu/yuzu/assets/133425869/3ba21b76-f318-47f7-ba1d-fd2d6dbe5ba1)
![SPOILER_0d1ef6cc-2bd7-4bf2-9f32-4e1eb8b8bddd](https://github.com/yuzu-emu/yuzu/assets/133425869/db9b811f-f98c-4878-815e-31d64abf29d4)

### Expected Behavior

it should be....  more spread like the usual gloom

![rn_image_picker_lib_temp_38726272-4bd8-441f-b01f-f74e77db0094](https://github.com/yuzu-emu/yuzu/assets/133425869/f97126b5-726a-4564-b7e7-46c64db161da)

### Reproduction Steps

just walk by any of the pits, either the castle one or the others

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11467354/yuzu_log.txt)

### System Configuration

CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz | AVX2 | FMA
GPU/Driver:  NVIDIA GeForce GTX 1650 with Max-Q Design / NVIDIA 531.79.0.0
OS: Windows 11 Version 22H2 (Build 22621.1702)

**Comment by ryanidrizaj** [comment] 2023-05-13 01:31
The regular gloom isn't supposed to have the same smoky effect that your example at Hyrule Castle does. It's literally just a flat texture on the ground/walls.

**Comment by IvanVaa** [comment] 2023-05-13 07:08
i have the same problem with same gpu and drivers

**Comment by Amer-xyz** [comment] 2023-05-13 14:12
> The regular gloom isn't supposed to have the same smoky effect that your example at Hyrule Castle does. It's literally just a flat texture on the ground/walls.

If it looks like this
![](https://i.redd.it/xl19pzqwpkza1.jpg) on your PC as well then just know it's not supposed to look like that

**Comment by ryanidrizaj** [comment] 2023-05-13 17:43
> > The regular gloom isn't supposed to have the same smoky effect that your example at Hyrule Castle does. It's literally just a flat texture on the ground/walls.
> 
> If it looks like this ![](https://camo.githubusercontent.com/3ecf7fde63ea54999c0f21144ce732aa261dcba197db74f437f0141ea70f8a09/68747470733a2f2f692e726564642e69742f786c3139707a7177706b7a61312e6a7067) on your PC as well then just know it's not supposed to look like that

Obviously. That's not what I'm saying. I'm saying it's not supposed to have the wispy smoky effect that that person said in their post. That's only on Hyrule Castle, and emanating from the Chasms on the overworld when you're further away from them, and it gets more and more transparent as you approach. I'm literally testing it on my Switch and comparing it, which everybody else should be able to do as well.

**Comment by The1Bef** [comment] 2023-05-13 22:33
> > > The regular gloom isn't supposed to have the same smoky effect that your example at Hyrule Castle does. It's literally just a flat texture on the ground/walls.
> > 
> > 
> > If it looks like this ![](https://camo.githubusercontent.com/3ecf7fde63ea54999c0f21144ce732aa261dcba197db74f437f0141ea70f8a09/68747470733a2f2f692e726564642e69742f786c3139707a7177706b7a61312e6a7067) on your PC as well then just know it's not supposed to look like that
> 
> Obviously. That's not what I'm saying. I'm saying it's not supposed to have the wispy smoky effect that that person said in their post. That's only on Hyrule Castle, and emanating from the Chasms on the overworld when you're further away from them, and it gets more and more transparent as you approach. I'm literally testing it on my Switch and comparing it, which everybody else should be able to do as well.

**Comment by aminenr-hub** [comment] 2023-05-14 02:26
Here is how it supposw to look , i have the same problem on two nvidia gpus a pascal one and a maxwell gen 2 one 
![Uploading image-2.png…]()

**Comment by nickmass** [comment] 2023-05-15 00:14
I am seeing the same incorrect gloom effect, however about 10% of the time when I launch ToTK I get correct rendering.

Using Vulkan renderer
AMD 5700 XT 8gb
Linux 6.3.1
Mesa 23.0.3

**Comment by aminenr-hub** [comment] 2023-05-15 01:16
> I am seeing the same incorrect gloom effect, however about 10% of the time when I launch ToTK I get correct rendering.
> 
> Using Vulkan renderer AMD 5700 XT 8gb Linux 6.3.1 Mesa 23.0.3

yeah i never saw them render correctly also if i change to open gl they render correctly but as soon as i get to the depths i will get damage from gloom while not standing in it ( this bug made me remember the long standing bug in splatoon 2 with its ink not running correctly )

**Comment by jedinjapan** [comment] 2023-05-18 06:52
Can reproduce this by running at 1.5x scale or above under Graphics. Issue alleviates at 1x.

**Comment by Flaming-Dorito** [comment] 2023-05-19 00:20
Getting the same thing on an Nvidia GTX 1060. 

Does anybody know if any of the visual fixes mods fixes this? Or any other workarounds/fixes?

**Comment by JulianHeuser** [comment] 2023-05-19 03:43
Happens at 1x scale for me (vulkan). Granted, I am a bit low spec.

Ryzen 2200g
RX570 (4gb vram)
16gb ram

**Comment by Rafapim** [comment] 2023-05-19 06:07
On my ultrawide monitor was like this but then I played on tv and it was normal, so I deactivated my ultrawide mod to test it and it fixed.
But then I did more testing with the mod on and messing with the screen proportion in the game custom config, I was using stretch to window, but if I use "force 21:9" it fixes it!

**Comment by The1Bef** [comment] 2023-05-19 10:11
> On my ultrawide monitor was like this but then I played on tv and it was normal, so I deactivated my ultrawide mod to test it and it fixed. But then I did more testing with the mod on and messing with the screen proportion in the game custom config, I was using stretch to window, but if I use "force 21:9" it fixes it!

doesen't do anything

**Comment by Rafapim** [comment] 2023-05-19 17:02
Ok nevermind that, now I think I figure out!
You can't change to fullscreen when the game is loading, either start in fullscreen, or start in window mode and wait the map to load to put in fullscreen. You can even change to fullscreen in the game menu but not on the loading screen.
Please tell me if it fixed for you.

**Comment by aminenr-hub** [comment] 2023-05-19 18:15
> Ok nevermind that, now I think I figure out! You can't change to fullscreen when the game is loading, either start in fullscreen, or start in window mode and wait the map to load to put in fullscreen. You can even change to fullscreen in the game menu but not on the loading screen. Please tell me if it fixed for you.

well try and never cange to fullscreen and see if its fixed

**Comment by Squall-Leonhart** [comment] 2023-08-13 13:22
I believe this is fixed?

**Comment by gidoly** [comment] 2023-09-21 04:03
it is fixed on lastest build of yuzu.

**Closed by gidoly** 2023-09-21 04:03 UTC
