### ISSUE TITLE
Huge graphical glitch in emulators

### ISSUE THREAD

**Issue by Xryzo11** [yuzu-emu/yuzu#10336] opened 2023-05-16 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All

### Description of Issue

I recently posted this issue on a Yuzu TOTK bug megathread on Reddit and the OP recommended me to post it here

So basically what I know is that this only happens on emulators, all others games run fine. Here's a list of where I noticed it the most:
Yuzu TOTK - usually occurs when swapping weapons, ALWAYS happens in the depths
Ryujinx TOTK - randomly happens after ~45 minutes of gameplay, almost always when entering the depths through a chasm
Yuzu SSBU - randomly on round finish after 30+ minutes of gameplay
Cemu BOTW - only with the Second Wind mod, happens randomly, but most often near Ordon Village (added by the mod, apparently uses up a lot of memory which results in frequent panic blood moons near it)

Whenever the glitch happens I need to restart the emulator to fix it.

I guess it is somehow related to memory, either RAM or VRAM. I had some RAM replaced a while back for ones with a higher frequency, as the old ones were apparently too slow for my CPU and the issue still occurs, so what's left is VRAM, but what wouldn't make much sense, because the game doesn't drop frames when it happens and it doesn't even use all of the 3GB (usually stays at about 2800MB and uses ~500MB shared system).

Also a thing I would like to point out: it only started happening like a year ago or so. Maybe a driver related issue?

### Expected Behavior

All textures start glitching out (depends on the game, it's more subtle in SSBU and much more visible in BOTW and TOTK on Cemu or the Switch emu's): https://imgur.com/a/rz0NOh3
This happens most often in Yuzu.

### Reproduction Steps

It happens on it's own, usually randomly

### Log File

[log.txt](https://github.com/yuzu-emu/yuzu/files/11486403/log.txt)

### System Configuration

CPU: i7-9700KF
GPU/Driver: GTX 1060 3GB, 531.79
RAM: 24GB 3000MHz
OS: Windows 11 Insider Beta (system on SSD, all emulators and nintendo games on HDD)

**Comment by Squall-Leonhart** [comment] 2023-05-16 10:31
Duplicate of several different bugs, the checkbox asking you to confirm that you searched is not just there for show :\

**Comment by Xryzo11** [comment] 2023-05-16 10:36
I did look for it, tried I don't know how many fixes at this point and the issue still persists

**Comment by FearlessTobi** [comment] 2023-05-16 15:17
Closing in favor of all the different issue reports we already have open for this.

**Closed by FearlessTobi** 2023-05-16 15:17 UTC
