### ISSUE TITLE
[FEATURE REQUEST] Implement Controller Profile Assignment 

### ISSUE THREAD

**Issue by CassiusOtho** [yuzu-emu/yuzu#6704] opened 2021-07-24 06:01 UTC
It would be great if we could select controller profiles for each game so that the game automatically opens with the users selected profiles. It would save the end user some time, especially those of us that like to use custom profiles. Cemu has a really great way of doing this. I have attached some pictures that give a better idea of how the Wii U emulator uses this feature which could provide some inspiration. 

By right clicking on the game and going to "Edit game profile" it takes you to an "Edit game profile" box. In the far right there is the "Controller" option. Clicking here allows dropdowns of profiles for the various controllers. The game now opens with that controller profile. 

**Right clicking a game displays the image below:** 
![Cemu Controller Config 1](https://user-images.githubusercontent.com/63135347/130235218-e2459245-81e3-440f-a703-d1a791872963.jpg)

**Clicking "Edit game profile" displays the image below:** 
![Cemu Controller Config 2](https://user-images.githubusercontent.com/63135347/130235221-7a6e5237-7a40-400d-a02b-295962b00f26.jpg)

Version: Mainline Build - ed1e288c6

**Comment by v1993** [comment] 2021-07-24 11:06
Sort-of dupe of #6691 since both suggest per game controller configuration in slightly different ways.

**Comment by CassiusOtho** [comment] 2021-07-24 12:11
@v1993 should I delete my post since this feature has already been suggested?

**Comment by FernandoS27** [comment] 2021-07-24 13:29
Actually this way it's easier.

**Comment by Hassiopeia** [comment] 2022-01-02 05:14
I would be very willing to help test this if needed. This feature is great in cemu and I’d love to see it in Yuzu!

**Closed** 2023-05-12 14:10 UTC
Labels: request, input
