### ISSUE TITLE
Lets Sing - Not recognizing mic input

### ISSUE THREAD

**Issue by Quickkill0** [yuzu-emu/yuzu#5227] opened 2020-12-25 04:01 UTC
Im using the latest build to date for yuzu. When you try to start a match in lets sing it asks for audio input. Not sure if itd be something easy to fix or not.
![Untitled](https://user-images.githubusercontent.com/76577322/103118317-5734eb00-463c-11eb-84d5-5934d18be9ed.png)

**Comment by FearlessTobi** [comment] 2020-12-25 20:47
This is because no microphone or usb services have been implemented yet.
Closing as a duplicate of https://github.com/yuzu-emu/yuzu/issues/4498.

**Closed by FearlessTobi** 2020-12-25 20:47 UTC
