### ISSUE TITLE
Zelda: Link's Awakening

### ISSUE THREAD

**Issue by mi6pl** [yuzu-emu/yuzu#3139] opened 2019-11-18 11:36 UTC
Hi, I have a problem with the character blocking, after the animation the character blocks (for example the photo below, the statue is shifting). I noticed in several places.

i7 4790k, 32gb, 1080ti. 

[https://ifotos.pl/zobacz/zeldajpg_qaheanx.jpg](url)

`[  38.025360] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:469: API PERFORMANCE 131186: Buffer performance warning: Buffer object 139 (bound to NONE, usage hint is GL_DYNAMIC_DRAW) is being copied/moved from VIDEO memory to HOST memory.
[  38.025376] Render.OpenGL <Warning> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:469: API PERFORMANCE 131154: Pixel-path performance warning: Pixel transfer is synchronized with 3D rendering.
[  38.046910] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1281: GL_INVALID_VALUE error generated. <numlayers> must be 1 for new texture's target.
[  38.046918] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1282: GL_INVALID_OPERATION error generated. <texture> does not refer to an existing texture object
[  38.046920] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1282: GL_INVALID_OPERATION error generated. <texture> does not refer to an existing texture object
[  38.046921] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1282: GL_INVALID_OPERATION error generated. <texture> does not refer to an existing texture object
[  38.046923] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1282: GL_INVALID_OPERATION error generated. <texture> does not refer to an existing texture object
[  38.046924] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1282: GL_INVALID_OPERATION error generated. <texture> does not refer to an existing texture object
[  38.046928] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1281: GL_INVALID_VALUE error generated. ObjectLabel: unknown texture object <name>
[  38.047039] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1282: GL_INVALID_OPERATION error generated. <textures> contains an invalid texture name.
[  38.049066] Render.OpenGL <Critical> video_core\renderer_opengl\renderer_opengl.cpp:DebugHandler:466: API ERROR 1282: GL_INVALID_OPERATION error generated. <textures> contains an invalid texture name.`

**Comment by Hexagon12** [comment] 2019-11-20 16:01
Duplicate of #3056

**Closed by Hexagon12** 2019-11-20 16:01 UTC
