### ISSUE TITLE
Yuzu function mapping beyond keyboard

### ISSUE THREAD

**Issue by VoidedReality** [yuzu-emu/yuzu#4613] opened 2020-08-30 23:09 UTC
I would like to suggest an option to map functions from Yuzu to unused mouse buttons and/or controller buttons. There is no way to map any function to anything outside the keyboard currently. One example of a productive use of this feature would be to map the "exit fullscreen" function to a wireless mouse or controller for when someone may want to game from a couch or chair rather than at a desk.

**Comment by goldenx86** [comment] 2020-08-30 23:13
Couch gaming needs some love.

**Comment by FearlessTobi** [comment] 2020-08-31 01:24
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4566.

**Closed by FearlessTobi** 2020-08-31 01:24 UTC
