### ISSUE TITLE
zelda Tears of kingdom crash after cutscene

### ISSUE THREAD

**Issue by jesusfistus218** [yuzu-emu/yuzu#10312] opened 2023-05-15 09:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1434 / EA 3591

### Description of Issue

After the first Cutscene Ganondorf awaking, in loadingscreen the framerate drops 0 and yuzu crash (use vulkan and rx560). I try it on OpenGL and it works but the Framerate is very low. On my Vega 8 and Vulkan its work but the Framerate is low. When i use the RX560 in Vulkan the Game crash every time after the Cutscene.

### Expected Behavior

other Games run perfectly like Mario or Pokemon and BOTW

### Reproduction Steps

I only start the game normaly and play normaly to the cutscene

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11476426/yuzu_log.txt)

### System Configuration

CPU: AMD Ryzen 5 3550H
GPU/Driver:Onboard Vega 8 / RX560
RAM: DDR4 8GB
OS:Windows 11

**Comment by Squall-Leonhart** [comment] 2023-05-15 12:04
Duplicate of https://github.com/yuzu-emu/yuzu/issues/10290

**Closed** 2023-05-15 15:01 UTC

**Comment by WhyNotTsheko** [comment] 2023-05-21 08:34
I think I found something that prevents the bug after the Ganondorf cutscene when using Vulkan and an AMD card on Zelda TOTK. I have an AMD Radeon RX 590 series graphics card, i5 4440 CPU, 12GB Ram. I tried on Yuzu 3600. For it to work, I set the video decoding on the CPU, and activated all the advanced video settings (Hack etc). It seems to work for the moment, no bug, I passed the cutscene and continue my progress in the game without worries.

**Comment by thongza1025** [comment] 2023-05-24 14:51
i use openGL for this cutscene

**Comment by Pablo-DS** [comment] 2023-05-26 21:58
> I think I found something that prevents the bug after the Ganondorf cutscene when using Vulkan and an AMD card on Zelda TOTK. I have an AMD Radeon RX 590 series graphics card, i5 4440 CPU, 12GB Ram. I tried on Yuzu 3600. For it to work, I set the video decoding on the CPU, and activated all the advanced video settings (Hack etc). It seems to work for the moment, no bug, I passed the cutscene and continue my progress in the game without worries.

Where can I find this video decoding setting?
