### ISSUE TITLE
Request: I would like the PS4 joystick not to be connected twice.

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11858] opened 2023-10-23 04:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

I would like the PS4 joystick to not connect twice depending on whether it is connected via bluetooth or cable. If the joystick has the same MAC address, it should automatically recaptured ins settings when I connect it via cable.

### Why would this feature be useful?

It is useful because sometimes I want to charge my joystick and I have to reconfigure everything, it would be more useful if the MAC address reference parameter is taken.

**Comment by german77** [comment] 2023-10-23 04:46
SDL provides a controller id https://wiki.libsdl.org/SDL2/SDL_JoystickGetGUID this id changes depending on connection or driver. We use this to distinguish between different controllers. If you manage to get something more reliable then I'm listening for ideas.

**Comment by boludoz** [comment] 2023-10-23 05:14
> SDL provides a controller id https://wiki.libsdl.org/SDL2/SDL_JoystickGetGUID this id changes depending on connection or driver. We use this to distinguish between different controllers. If you manage to get something more reliable then I'm listening for ideas.

I don't think there is anything more generically reliable than the function you mentioned.

**Comment by boludoz** [comment] 2023-10-23 05:15
I just said MAC per say, but it could be anything.

**Comment by Squall-Leonhart** [comment] 2023-10-23 06:10
There is *no* way to do this.

the GUID is *not* the same.

**Comment by FearlessTobi** [comment] 2023-10-26 11:26
^

Also a duplicate of https://github.com/yuzu-emu/yuzu/issues/10470.

**Closed by FearlessTobi** 2023-10-26 11:26 UTC
Labels: request
