### ISSUE TITLE
[android] per_game settings 

### ISSUE THREAD

**Issue by M-hyun** [yuzu-emu/yuzu#10646] opened 2023-06-06 14:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

(long click) or (one click) on game icon to bring up a UI that contains everything related to the selected game
like:
-settigs.
-per_game driver selection.
-homescreen shortcut.
...etc.

### Why would this feature be useful?

easy way to play games without keep changing the settings Everytime.

**Comment by FearlessTobi** [comment] 2023-06-06 20:39
Duplicate of https://github.com/yuzu-emu/yuzu/issues/10521.

**Closed by FearlessTobi** 2023-06-06 20:39 UTC
Labels: request
