### ISSUE TITLE
EVERDREAM VALLEY Worse than before

### ISSUE THREAD

**Issue by Noob-n00b** [yuzu-emu/yuzu#11179] opened 2023-07-29 18:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 482c957f5.ver 2023/07/22 

### Description of Issue

Before i reported that the game won't booting
But after this update my file can't be even try to booting bcs suddenly it said ROM is encrypted

### Expected Behavior

Doesn't it suppose to be better instead worse

### Reproduction Steps

idk

### Log File

[   0.005647] Frontend <Info> main/jni/native.cpp:RunEmulation:514: starting
[   0.005938] Config <Info> main/jni/config.cpp:LoadINI:46: Successfully loaded /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/config/config.ini
[   0.006067] Frontend <Info> main/jni/emu_window/emu_window.cpp:EmuWindow_Android:58: initializing
[   0.006184] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.006213] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   0.006554] Config <Info> common/settings.cpp:LogSettings:63: yuzu Configuration:
[   0.006563] Config <Info> common/settings.cpp:operator():56: Controls_UseDockedMode: false
[   0.006564] Config <Info> common/settings.cpp:operator():56: System_RngSeed: 0
[   0.006565] Config <Info> common/settings.cpp:operator():56: System_DeviceName: Yuzu
[   0.006567] Config <Info> common/settings.cpp:operator():56: System_CurrentUser: 0
[   0.006586] Config <Info> common/settings.cpp:operator():56: System_LanguageIndex: 1
[   0.006588] Config <Info> common/settings.cpp:operator():56: System_RegionIndex: 0
[   0.006589] Config <Info> common/settings.cpp:operator():56: System_TimeZoneIndex: 0
[   0.006590] Config <Info> common/settings.cpp:operator():56: System_UnsafeMemoryLayout: false
[   0.006591] Config <Info> common/settings.cpp:operator():56: Core_UseMultiCore: true
[   0.006594] Config <Info> common/settings.cpp:operator():56: CPU_Accuracy: 0
[   0.006595] Config <Info> common/settings.cpp:operator():56: Renderer_UseResolutionScaling: 1
[   0.006596] Config <Info> common/settings.cpp:operator():56: Renderer_ScalingFilter: 1
[   0.006597] Config <Info> common/settings.cpp:operator():56: Renderer_FSRSlider: 25
[   0.006598] Config <Info> common/settings.cpp:operator():56: Renderer_AntiAliasing: 0
[   0.006598] Config <Info> common/settings.cpp:operator():56: Renderer_UseSpeedLimit: true
[   0.006599] Config <Info> common/settings.cpp:operator():56: Renderer_SpeedLimit: 50
[   0.006600] Config <Info> common/settings.cpp:operator():56: Renderer_UseDiskShaderCache: true
[   0.006601] Config <Info> common/settings.cpp:operator():56: Renderer_GPUAccuracyLevel: 0
[   0.006601] Config <Info> common/settings.cpp:operator():56: Renderer_UseAsynchronousGpuEmulation: true
[   0.006602] Config <Info> common/settings.cpp:operator():56: Renderer_NvdecEmulation: 2
[   0.006603] Config <Info> common/settings.cpp:operator():56: Renderer_AccelerateASTC: false
[   0.006604] Config <Info> common/settings.cpp:operator():56: Renderer_AsyncASTC: false
[   0.006605] Config <Info> common/settings.cpp:operator():56: Renderer_AstcRecompression: 0
[   0.006605] Config <Info> common/settings.cpp:operator():56: Renderer_UseVsync: 0
[   0.006606] Config <Info> common/settings.cpp:operator():56: Renderer_UseReactiveFlushing: false
[   0.006607] Config <Info> common/settings.cpp:operator():56: Renderer_ShaderBackend: 0
[   0.006607] Config <Info> common/settings.cpp:operator():56: Renderer_UseAsynchronousShaders: false
[   0.006608] Config <Info> common/settings.cpp:operator():56: Renderer_AnisotropicFilteringLevel: 1
[   0.006609] Config <Info> common/settings.cpp:operator():56: Audio_OutputEngine: auto
[   0.006609] Config <Info> common/settings.cpp:operator():56: Audio_OutputDevice: auto
[   0.006610] Config <Info> common/settings.cpp:operator():56: Audio_InputDevice: auto
[   0.006611] Config <Info> common/settings.cpp:operator():56: DataStorage_UseVirtualSd: true
[   0.006612] Config <Info> common/settings.cpp:operator():60: DataStorage_CacheDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/cache
[   0.006614] Config <Info> common/settings.cpp:operator():60: DataStorage_ConfigDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/config
[   0.006614] Config <Info> common/settings.cpp:operator():60: DataStorage_LoadDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/load
[   0.006615] Config <Info> common/settings.cpp:operator():60: DataStorage_NANDDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/nand
[   0.006616] Config <Info> common/settings.cpp:operator():60: DataStorage_SDMCDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/sdmc
[   0.006617] Config <Info> common/settings.cpp:operator():56: Debugging_ProgramArgs: 
[   0.006617] Config <Info> common/settings.cpp:operator():56: Debugging_GDBStub: false
[   0.006618] Config <Info> common/settings.cpp:operator():56: Input_EnableMotion: true
[   0.006618] Config <Info> common/settings.cpp:operator():56: Input_EnableVibration: true
[   0.006619] Config <Info> common/settings.cpp:operator():56: Input_EnableTouch: true
[   0.006620] Config <Info> common/settings.cpp:operator():56: Input_EnableMouse: false
[   0.006620] Config <Info> common/settings.cpp:operator():56: Input_EnableKeyboard: false
[   0.006621] Config <Info> common/settings.cpp:operator():56: Input_EnableRingController: true
[   0.006622] Config <Info> common/settings.cpp:operator():56: Input_EnableIrSensor: false
[   0.006622] Config <Info> common/settings.cpp:operator():56: Input_EnableCustomJoycon: true
[   0.006623] Config <Info> common/settings.cpp:operator():56: Input_EnableCustomProController: false
[   0.006624] Config <Info> common/settings.cpp:operator():56: Input_EnableRawInput: false
[   0.006697] Input <Error> ./common/input.h:CreateDevice:510: Unknown engine name: joycon
[   0.007625] Input <Error> ./common/input.h:CreateDevice:510: Unknown engine name: joycon
[   0.208208] Loader <Error> core/file_sys/content_archive.cpp:ReadSections:260: Compressed NCAs are not supported.
[   0.232725] Loader <Error> core/file_sys/content_archive.cpp:ReadSections:260: Compressed NCAs are not supported.
[   0.234149] Loader <Warning> core/loader/loader.cpp:GetLoader:257: File primary%3ASwitch%20%2FGAME%2FEverdream%20Valley%20%5B0100B9801AA3C000%5D%5Bv0%5D%5BUS%5D(nsw2u.com).nsp has a different type (unknown) than its extension.
[   0.238224] Loader <Error> core/file_sys/content_archive.cpp:ReadSections:260: Compressed NCAs are not supported.
[   0.238406] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:443:     RomFS: Update (v0.1.0) applied successfully
[   0.329858] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:875: Device doesn't support extension VK_EXT_conservative_rasterization
[   0.329871] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:875: Device doesn't support extension VK_EXT_depth_range_unrestricted
[   0.329873] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:875: Device doesn't support extension VK_NV_geometry_shader_passthrough
[   0.329873] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:875: Device doesn't support extension VK_NV_viewport_array2
[   0.329874] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:875: Device doesn't support extension VK_NV_viewport_swizzle
[   0.329878] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:937: Device doesn't support feature shaderInt8
[   0.329897] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:938: Missing required feature uniformAndStorageBuffer16BitAccess
[   0.329898] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:938: Missing required feature storageBuffer8BitAccess
[   0.329899] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:938: Missing required feature uniformAndStorageBuffer8BitAccess
[   0.329900] Render.Vulkan <Error> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:938: Missing required feature wideLines
[   0.329906] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:353: Unsuitable driver, continuing anyway
[   0.330002] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:400: Qualcomm and Turnip drivers have broken VK_EXT_custom_border_color
[   0.498713] Debug <Critical> video_core/vulkan_common/vulkan_device.cpp:operator():756: Assertion Failed!
Unimplemented format query=58
[   0.498743] Debug <Critical> video_core/vulkan_common/vulkan_device.cpp:operator():672: Assertion Failed!
Format=106 with usage=49153 and type=1 has no defined alternatives and host hardware does not support it
[   0.512795] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:173: Driver: turnip Mesa driver 23.0.99
[   0.512806] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:174: Device: Turnip Adreno (TM) 650
[   0.512808] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:175: Vulkan: 1.3.241
[   0.512821] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:176: Available VRAM: 4.00 GiB
[   0.512857] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[   0.513232] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the cubeb backend
[   0.530819] Loader <Error> core/file_sys/content_archive.cpp:ReadSections:260: Compressed NCAs are not supported.
[   0.530919] Core <Critical> core/core.cpp:Load:313: Failed to load ROM (Error 13)!

### System Configuration

SD 870
RAM 8Gb

**Comment by german77** [comment] 2023-07-29 18:18
This is normal. Instead of just silently failing to load the game. We show an error the game is not actually supported. Duplicate of #10906

**Closed by german77** 2023-07-29 18:18 UTC
