### ISSUE TITLE
Request: applying Updates and DLCs on the go

### ISSUE THREAD

**Issue by Leafdomain** [yuzu-emu/yuzu#12069] opened 2023-11-18 13:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

It'd be better to be able to apply update and dlc packages on the go, as you start running the game. This can be set via individual game settings. The other popular Switch emulator can do this.

### Why would this feature be useful?

The reason for the necessity of this is that once you have a few Switch roms, it already becomes problematic for the hard drive by taking double the space they normally should, due to Yuzu forcing the update and dlc packages to be installed. If it could apply them on the go too, it would be so much better and more user-friendly, making it so much easier to manage your roms and their update packages.

Hopefully this can be implemented to Yuzu as well.

**Comment by FearlessTobi** [comment] 2023-11-18 13:37
Duplicate of https://github.com/yuzu-emu/yuzu/issues/9963.

**Closed by FearlessTobi** 2023-11-18 13:37 UTC
Labels: request
