### ISSUE TITLE
ACA NEOGEO METAL SLUG 2 panics due to acc:u0 StoreSaveDataThumbnail being unimplemented.

### ISSUE THREAD

**Issue by MoochMcGee** [yuzu-emu/yuzu#3336] opened 2020-01-21 16:08 UTC
Version: yuzu Early Access 139
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4091997/yuzu_log.txt)

**Comment by Hexagon12** [comment] 2020-01-21 16:11
Duplicate of #2645

**Closed by Hexagon12** 2020-01-21 16:11 UTC
