### ISSUE TITLE
Shipped makes yuzu crash

### ISSUE THREAD

**Issue by pinguicodes** [yuzu-emu/yuzu#3072] opened 2019-11-04 11:29 UTC
Yuzu version: 42
Tried with Async on and off.
Log: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3803723/yuzu_log.txt)

**Comment by Hexagon12** [comment] 2019-11-04 11:43
Duplicate of #2751

**Closed by Hexagon12** 2019-11-04 11:43 UTC
