### ISSUE TITLE
yuzu-cmd.exe work perfectly, but Controller does not Vibrate

### ISSUE THREAD

**Issue by mcastellonc201** [yuzu-emu/yuzu#9170] opened 2022-11-02 16:11 UTC
yuzu-cmd.exe
SDL2 + Vulkan work perfectly, but Nintendo Switch Pro Controller, does not Rumble.

What changes do I need to make to the driver for it to work?
https://github.com/yuzu-emu/yuzu/blob/master/src/input_common/drivers/sdl_driver.cpp

Please.

Regards

**Comment by liamwhite** [comment] 2022-11-02 20:09
Duplicate of #9142

Please do not file duplicate issues if you do not get a response right away

**Closed by liamwhite** 2022-11-02 20:09 UTC
