### ISSUE TITLE
Donkey Kong Country : Tropical Freeze Weird Glitch on Vulkan with YUZU 706

### ISSUE THREAD

**Issue by Moodie92** [yuzu-emu/yuzu#6797] opened 2021-08-02 13:55 UTC
Experiencing  glitch while moving  with Donkey Kong
![0100c1f0051b6000_2021-08-02_15-49-17-843](https://user-images.githubusercontent.com/40892036/127872787-1b933e6a-6b4e-4c07-87d5-972d9f4b1808.png)
![0100c1f0051b6000_2021-08-02_15-49-46-434](https://user-images.githubusercontent.com/40892036/127872850-fa9a6ed2-a9c8-420f-9afa-0c76be49f5f7.png)
 and here is the logs
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6917446/yuzu_log.txt)
GPU ACCURACY : HIGH
API : VULKAN
MODE: DOCKED

**Comment by RinMaru** [comment] 2021-08-02 17:52
Duplicate of #6612

**Comment by asheenlevrai** [comment] 2021-11-26 23:19
Still there on Yuzu ML826.
Goes away when using OpenGL
(however other glitches appear when using res scaling above 1X (2X or 3X -> water is green)

**Comment by benderscruffy** [comment] 2022-11-07 11:57
please close
has been fixed with #7799

**Closed** 2023-01-14 05:23 UTC
