### ISSUE TITLE
Pokemon Sword crashing on linux

### ISSUE THREAD

**Issue by Pandr4** [yuzu-emu/yuzu#5969] opened 2021-02-20 21:24 UTC
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6016473/yuzu_log.txt)

[System]
OS: Manjaro Linux 20.2.1 Nibia
Arch: x86_64
Kernel: 5.10.15-1-MANJARO
Desktop: KDE
Display Server: x11

[CPU]
Vendor: GenuineIntel
Model: Intel® Core™ i3-3220 CPU @ 3.30GHz
Physical cores: 2
Logical cores: 4

[Memory]
RAM: 7.7 GB
Swap: 25.0 GB

[Graphics]
Vendor: AMD
OpenGL Renderer: Radeon RX550/550 Series (POLARIS12, DRM 3.40.0, 5.10.15-1-MANJARO, LLVM 11.0.1)
OpenGL Version: 4.6 (Compatibility Profile) Mesa 21.1.0-devel (git-d8236e32de)
OpenGL Core: 4.6 (Core Profile) Mesa 21.1.0-devel (git-d8236e32de)
OpenGL ES: OpenGL ES 3.2 Mesa 21.1.0-devel (git-d8236e32de)
Vulkan: Supported

After a few minutes of play, the game crashes and is at 0 fps. I've tested other games, he's the only one that crashed
I’m using this file yuzu-linux-20210218-540014e83.tar.xz
I already looked for help on the forum but they told me to come here

**Comment by CrusadingNinja** [comment] 2021-02-20 23:44
I'm not sure what forum you are referring to but the discord server is best for support requests. The issue tracker is only for bug reports.

**Comment by FearlessTobi** [comment] 2021-02-21 14:33
Also, this issue is a duplicate of others that have been opened already for this game.

**Closed by FearlessTobi** 2021-02-21 14:33 UTC
