### ISSUE TITLE
Streets of Rage 4 (Intel)

### ISSUE THREAD

**Issue by natebizzle** [yuzu-emu/yuzu#11297] opened 2023-08-16 06:44 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1524

### Description of Issue

Streets of Rage 4 loads to a black screen initially, after skipping the menu is mirrored and upside down.

There is a similar issue open for AMD and Android (#8839) however this relates to an Intel CPU with integrated graphics.

### Expected Behavior

The screen is displayed in the correct orientation and not mirrored.

### Reproduction Steps

Load game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12356385/yuzu_log.txt)

### System Configuration

CPU: Intel i5-13600k
GPU/Driver: Intel UHD Graphics 770/31.0.101.4578
RAM: 32GB
OS: Win11

**Comment by german77** [comment] 2023-08-16 06:48
Duplicate of #8839

**Closed by german77** 2023-08-16 06:48 UTC
