### ISSUE TITLE
vk::OutOfDeviceMemoryError with Nvidia Vulkan Driver on Linux

### ISSUE THREAD

**Issue by iWeaker4you** [yuzu-emu/yuzu#3586] opened 2020-03-30 21:37 UTC
That message appears to me when I start a game with Vulkan with the vulkan driver provided by Nvidia, either version 440.66.03 or 440.66.04, with the stable version 440.64 it works well without any problems, but the Vulkan version is old, version 1.1.119.

**Comment by goldenx86** [comment] 2020-03-30 21:40
Our current Vulkan implementation doesn't discard unused textures/assets, so any GPU will slowly fill up the VRAM.
Stick to OpenGL on NVIDIA cards, it should be faster and more stable.

**Comment by ReinUsesLisp** [comment] 2020-04-08 09:17
Closing as duplicate of #3523.

**Closed by ReinUsesLisp** 2020-04-08 09:17 UTC
