### ISSUE TITLE
Missing HLE service command  'OpenCacheStorageList' in 'fsp-srv' 

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3858] opened 2020-05-01 18:43 UTC
required by mortal comat 11
unimplemented function 'OpenCacheStorageList': port='fsp-srv'
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4565832/yuzu_log.txt)

**Comment by callmenemo491** [comment] 2020-05-02 00:40
duplicate of: #2882

**Closed** 2020-05-02 04:06 UTC
