### ISSUE TITLE
Custom RTC

### ISSUE THREAD

**Issue by seeblo** [yuzu-emu/yuzu#10235] opened 2023-05-11 21:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

The ability to choose between changing the time, the date, or both

### Why would this feature be useful?

I've been using the custom rtc feature and i noticed theres no way to change the date without locking the time to one point, this is annoying especially with ACNH because i want it to still parrallel the real life time (usually) but i might want the date to change, i think being able to change the date while keeping the time synced would be nice

**Comment by seeblo** [comment] 2023-05-11 22:11
also the date doesnt change until you close and reopen the app

**Comment by FearlessTobi** [comment] 2023-05-11 22:25
Duplicate of https://github.com/yuzu-emu/yuzu/issues/10127.

**Closed by FearlessTobi** 2023-05-11 22:25 UTC
Labels: request

**Comment by seeblo** [comment] 2023-05-11 22:36
sorry if i didnt explain well but its not the same as that persons issue, i am suggesting that it should be possible to change the date while keeping the time synced with the system, and maybe even have the custom time keep moving, sorry if im still not being clear im not exactly sure how to explain but i could probably explain in a discord call
