### ISSUE TITLE
Age Of Calamity Calamity Ganon Crash

### ISSUE THREAD

**Issue by YuNarukamii** [yuzu-emu/yuzu#5062] opened 2020-12-03 19:35 UTC
When i try a Y+Y+Y or Y+X or Y+Y+X move with Calamity Ganon the Game freezes and Crashes
My Specs:
I5-5500K
1050 Ti
16GB RAM

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5638531/yuzu_log.txt)
Here is the Log

**Comment by FearlessTobi** [comment] 2020-12-05 01:06
Likely a duplicate of https://github.com/yuzu-emu/yuzu/issues/4871.

**Closed by FearlessTobi** 2020-12-05 01:06 UTC
