### ISSUE TITLE
ACA NEOGEO Metalslug  unimplemented function 'StoreSaveDataThumbnail'

### ISSUE THREAD

**Issue by gidoly** [yuzu-emu/yuzu#4892] opened 2020-11-05 04:11 UTC
this game can't go ingame because of unimplemented function StoreSaveDataThumbnail.
here is the log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5491936/yuzu_log.txt)

**Comment by benderscruffy** [comment] 2020-11-05 06:15
duplicate of #2645

**Closed** 2020-11-06 00:12 UTC
