### ISSUE TITLE
Dragon Quest Builders crash

### ISSUE THREAD

**Issue by Zemogiter** [yuzu-emu/yuzu#4558] opened 2020-08-22 19:26 UTC
The game crashes right after SquareEnix logo.

Version: 355 | HEAD-manline-636-3205-gb-44d885d3 (2020-08-22)
CPU: i7-7700K
GPU: GTX 1080 ti
RAM: 16GB
Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5112826/yuzu_log.txt)

**Comment by FearlessTobi** [comment] 2020-08-24 12:17
This seems like a duplicate of https://github.com/yuzu-emu/yuzu/issues/4566.

**Closed by FearlessTobi** 2020-08-24 12:17 UTC
