### ISSUE TITLE
Currently Unimplemented Audio Services

### ISSUE THREAD

**Issue by Shrek5InTheatres2019** [yuzu-emu/yuzu#3266] opened 2020-01-02 03:33 UTC
As of writing this issue, here is a full list of the audio services not currently implemented.

- [ ] IAudioDevice::GetAudioSystemMasterVolumeSetting
- [ ] AudInU::ListAudioIns
- [ ] AudInU::OpenAudioIn
- [ ] AudInU::ListAudioInsAuto
- [ ] AudInU::OpenAudioInAuto
- [ ] AudInU::ListAudioInsAutoFiltered
- [ ] AudInU::OpenAudioInProtocolSpecified
- [ ] IAudioIn::GetAudioInState
- [ ] IAudioIn::StartAudioIn
- [ ] IAudioIn::StopAudioIn
- [ ] IAudioIn::AppendAudioInBuffer
- [ ] IAudioIn::RegisterBufferEvent
- [ ] IAudioIn::GetReleasedAudioInBuffer
- [ ] IAudioIn::ContainsAudioInBuffer
- [ ] IAudioIn::AppendAudioInBufferWithUserEvent
- [ ] IAudioIn::AppendAudioInBufferAuto
- [ ] IAudioIn::GetReleasedAudioInBufferAuto
- [ ] IAudioIn::AppendAudioInBufferWithUserEventAuto
- [ ] IAudioIn::GetAudioInBufferCount
- [ ] IAudioIn::SetAudioInDeviceGain
- [ ] IAudioIn::FlushAudioInBuffers
- [ ] AudInA::RequestSuspendAudioIns
- [ ] AudInA::RequestResumeAudioIns
- [ ] AudInA::GetAudioInsProcessMasterVolume
- [ ] AudInA::SetAudioInsProcessMasterVolume
- [ ] IAudioOut::GetAudioOutPlayedSampleCount
- [ ] IAudioOut::FlushAudioOutBuffers
- [ ] AudRecU::OpenFinalOutputRecorder
- [ ] IFinalOutputRecorder::GetFinalOutputRecorderState
- [ ] IFinalOutputRecorder::StartFinalOutputRecorder
- [ ] IFinalOutputRecorder::StopFinalOutputRecorder
- [ ] IFinalOutputRecorder::AppendFinalOutputRecorderBuffer
- [ ] IFinalOutputRecorder::RegisterBufferEvent
- [ ] IFinalOutputRecorder::GetReleasedFinalOutputRecorderBuffer
- [ ] IFinalOutputRecorder::ContainsFinalOutputRecorderBuffer
- [ ] IFinalOutputRecorder::GetFinalOutputRecorderBufferEndTime
- [ ] IFinalOutputRecorder::AppendFinalOutputRecorderBufferAuto
- [ ] IFinalOutputRecorder::GetReleasedFinalOutputRecorderBufferAuto
- [ ] IFinalOutputRecorder::FlushFinalOutputRecorderBuffers
- [ ] AudDev::EnableDspUsageMeasurement
- [ ] AudDev::DisableDspUsageMeasurement
- [ ] AudDev::GetDspUsage
- [ ] AudOutA::RequestSuspendAudioOuts
- [ ] AudOutA::RequestResumeAudioOuts
- [ ] AudOutA::GetAudioOutsProcessMasterVolume
- [ ] AudOutA::SetAudioOutsProcessMasterVolume
- [ ] AudOutA::GetAudioOutsProcessRecordVolume
- [ ] AudOutA::SetAudioOutsProcessRecordVolume
- [ ] AudRecA::RequestSuspendFinalOutputRecorders
- [ ] AudRecA::RequestResumeFinalOutputRecorders
- [ ] AudRenA::RequestSuspendAudioRenderers
- [ ] AudRenA::RequestResumeAudioRenderers
- [ ] AudRenA::GetAudioRenderersProcessMasterVolume
- [ ] AudRenA::SetAudioRenderersProcessMasterVolume
- [ ] AudRenA::RegisterAppletResourceUserId
- [ ] AudRenA::UnregisterAppletResourceUserId
- [ ] AudRenA::GetAudioRenderersProcessRecordVolume
- [ ] AudRenA::SetAudioRenderersProcessRecordVolume
- [ ] AudDbg::RequestSuspendForDebug
- [ ] AudDbg::RequestResumeForDebug
- [ ] AudCtl::GetTargetVolume
- [ ] AudCtl::SetTargetVolume
- [ ] AudCtl::IsTargetMute
- [ ] AudCtl::SetTargetMute
- [ ] AudCtl::IsTargetConnected
- [ ] AudCtl:SetDefaultTarget
- [ ] AudCtl::GetDefaultTarget
- [ ] AutCtl::GetAudioOutputMode
- [ ] AudCtl::SetAudioOutputMode
- [ ] AudCtl::SetForceMutePolicy
- [ ] AudCtl::GetForceMutePolicy
- [ ] AudCtl::GetOutputModeSetting
- [ ] AudCtl::SetOutputModeSetting
- [ ] AudCtl::SetOutputTarget
- [ ] AudCtl::SetHeadphoneOutputLevelMode
- [ ] AudCtl::GetHeadphoneOutputLevelMode
- [ ] AudCtl::AcquireAudioVolumeUpdateEventForPlayReport
- [ ] AudCtl::AcquireAudioOutputDeviceUpdateEventForPlayReport
- [ ] AudCtl::GetAudioOutputTargeetForPlayReport
- [ ] AudCtl::NotifyHeadphoneVolumeWarningDisplayedEvent
- [ ] AudCtl::SetSystemOutputMasterVolume
- [ ] AudCtl::GetSystemOutputMasterVolume
- [ ] AudCtl::GetAudioVolumeDataForPlayReport
- [ ] AudCtl::UpdateHeadphoneSettings
- [ ] AudCtl::SetVolumeMappingTableForDev
- [ ] CodecCtl::InitializeCodecController
- [ ] CodecCtl::FinalizeCodecController
- [ ] CodecCtl::SleepCodecController
- [ ] CodecCtl::WakeCodecController
- [ ] CodecCtl::SetCodecVolume
- [ ] CodecCtl::GetCodecVolumeMax
- [ ] CodecCtl::GetCodexVolumeMin
- [ ] CodecCtl::SetCodecActiveTarget
- [ ] CodecCtl::GetCodecActiveTarget
- [ ] CodecCtl::BindCodecHeadphoneMicJackInterrupt
- [ ] CodecCtl::IsCodecHeadphoneMicJackInserted
- [ ] CodecCtl::ClearCodecHeadphoneMicJackInterrupt
- [ ] CodecCtl::IsCodecDeviceRequested
- [ ] IHardwareOpusDecoderManager::SetContext
- [ ] IHardwareOpusDecoderManager::DecodeInterleavedForMultiStreamOld
- [ ] IHardwareOpusDecoderManager::SetContextForMultiStream
- [ ] IHardwareOpusDecoderManager::DecodeInterleavedForMultiStreamWithPerfOld
- [ ] IHardwareOpusDecoderManager::DecodeInterleavedForMultiStream
- [ ] IHardwareOpusDecoderManager::DecodeInterleavedWithHardware
- [ ] HwOpus::OpenOpusDecoderForMultiStream
- [ ] HwOpus::GetWorkBufferSizeForMultiStream

**Comment by Hexagon12** [comment] 2020-01-17 17:22
Closing this issue because of uncertain info surrounding actual specifics and additional details. The issue is currently a list without arguments and nothing more.

**Closed by Hexagon12** 2020-01-17 17:22 UTC
Labels: audio-issue, hle-issue

**Comment by fluffapparition** [comment] 2020-01-26 18:12
@Hexagon12 heres an argument:

Implement the services.
