### ISSUE TITLE
Load Amiibo Problem

### ISSUE THREAD

**Issue by znssky0107** [yuzu-emu/yuzu#3275] opened 2020-01-05 12:01 UTC
Super Mario Odyssey

load the bin
Mario Wedding
Peach Wedding
Bowser Wedding

The Uncle amiibo said
it’s a good ol‘ Mario amiibo
it’s a good ol‘ Peach amiibo
it’s a good ol‘ Bowser amiibo

unlock
grants temporary invincibility.
gives a Life-Up Heart.
reveals location of regional coins.

cannot unlock
Mario wedding outfit 
Peach wedding outfit
Bowser wedding outfit

the correct text is
it‘s a Mario (Wedding) amiibo
it‘s a Peach (Wedding) amiibo
it’s a Bowser (Wedding) amiibo

Maybe the bug is amiibo name unrecognized

**Comment by znssky0107** [comment] 2020-01-05 12:19
other amiibo

Unlock the outfit
8Bit-Mario30thAnniversary
Diddy-Kong
Dr-Mario
Luigi
Waluigi
Wario

Cannot unlock  the outfit
Gold-Mario

**Comment by Hexagon12** [comment] 2020-01-05 12:23
Duplicate of #2625

**Closed by Hexagon12** 2020-01-05 12:23 UTC
