### ISSUE TITLE
TOTK and BOTW crash on start since 1483 mainline version

### ISSUE THREAD

**Issue by Legoalda** [yuzu-emu/yuzu#11003] opened 2023-07-02 22:02 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1483 / Mainline 1484

### Description of Issue

When I try to start The Legend of Zelda : Tears of The Kingdom (0100F2C0115B6000) or The Legend of Zelda: Breath of the Wild (01007EF00011E000) Yuzu crash after 3 seconds. (There is no shader loading progress bar).
I tried on Vulkan and OpenGL and clean caches but the issue is still here.

I rollbacked with flatpak on mainline 1482 and both games are loading successfully on this version.

### Expected Behavior

The games should start same as mainline 1482 version

### Reproduction Steps

Update Yuzu with flatpak on 1484 or 1483 version, try to load Zelda TOTK or Zelda BOTW.

### Log File

[   0.022536] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[   0.022555] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[   1.421990] Input <Info> input_common/drivers/joycon.cpp:Joycons:22: Joycon driver Initialization started
[   1.451729] Frontend <Info> yuzu/main.cpp:GMainWindow:361: yuzu Version: yuzu 1484
[   1.451733] Frontend <Info> yuzu/main.cpp:LogRuntimes:249: Qt Compile: 5.15.10 Runtime: 5.15.10
[   1.451733] Frontend <Info> yuzu/main.cpp:GMainWindow:377: Host CPU: AMD Ryzen 7 5800H with Radeon Graphics          | AVX2 | FMA
[   1.451758] Frontend <Info> yuzu/main.cpp:GMainWindow:379: Host CPU Cores: 8
[   1.451759] Frontend <Info> yuzu/main.cpp:GMainWindow:382: Host CPU Threads: 16
[   1.451774] Frontend <Info> yuzu/main.cpp:GMainWindow:383: Host OS: KDE Flatpak runtime
[   1.451780] Frontend <Info> yuzu/main.cpp:GMainWindow:384: Host RAM: 30.74 GiB
[   1.451781] Frontend <Info> yuzu/main.cpp:GMainWindow:386: Host Swap: 8.00 GiB
[   1.618048] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:442:     RomFS: Update (v0.4.0) applied successfully
[   1.625984] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:442:     RomFS: Update (v0.4.0) applied successfully
[   1.631846] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:442:     RomFS: Update (v0.0.0) applied successfully
[   1.636010] Frontend <Warning> yuzu/main.cpp:SetupPrepareForSleep:1609: QDBusConnection system bus is not connected
[  13.268569] Frontend <Info> yuzu/main.cpp:BootGame:1812: yuzu starting...
[  13.284120] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:442:     RomFS: Update (v0.4.0) applied successfully
[  13.287824] Config <Info> common/settings.cpp:LogSettings:62: yuzu Configuration:
[  13.287827] Config <Info> common/settings.cpp:operator():55: Controls_UseDockedMode: true
[  13.287828] Config <Info> common/settings.cpp:operator():55: System_RngSeed: 0
[  13.287828] Config <Info> common/settings.cpp:operator():55: System_DeviceName: Kazuha
[  13.287829] Config <Info> common/settings.cpp:operator():55: System_CurrentUser: 0
[  13.287829] Config <Info> common/settings.cpp:operator():55: System_LanguageIndex: 2
[  13.287829] Config <Info> common/settings.cpp:operator():55: System_RegionIndex: 2
[  13.287830] Config <Info> common/settings.cpp:operator():55: System_TimeZoneIndex: 0
[  13.287830] Config <Info> common/settings.cpp:operator():55: System_UnsafeMemoryLayout: false
[  13.287831] Config <Info> common/settings.cpp:operator():55: Core_UseMultiCore: true
[  13.287831] Config <Info> common/settings.cpp:operator():55: CPU_Accuracy: 0
[  13.287832] Config <Info> common/settings.cpp:operator():55: Renderer_UseResolutionScaling: 2
[  13.287833] Config <Info> common/settings.cpp:operator():55: Renderer_ScalingFilter: 1
[  13.287834] Config <Info> common/settings.cpp:operator():55: Renderer_FSRSlider: 25
[  13.287834] Config <Info> common/settings.cpp:operator():55: Renderer_AntiAliasing: 0
[  13.287834] Config <Info> common/settings.cpp:operator():55: Renderer_UseSpeedLimit: true
[  13.287835] Config <Info> common/settings.cpp:operator():55: Renderer_SpeedLimit: 100
[  13.287835] Config <Info> common/settings.cpp:operator():55: Renderer_UseDiskShaderCache: true
[  13.287836] Config <Info> common/settings.cpp:operator():55: Renderer_GPUAccuracyLevel: 1
[  13.287836] Config <Info> common/settings.cpp:operator():55: Renderer_UseAsynchronousGpuEmulation: true
[  13.287837] Config <Info> common/settings.cpp:operator():55: Renderer_NvdecEmulation: 2
[  13.287837] Config <Info> common/settings.cpp:operator():55: Renderer_AccelerateASTC: true
[  13.287837] Config <Info> common/settings.cpp:operator():55: Renderer_AsyncASTC: false
[  13.287839] Config <Info> common/settings.cpp:operator():55: Renderer_AstcRecompression: 0
[  13.287839] Config <Info> common/settings.cpp:operator():55: Renderer_UseVsync: 2
[  13.287840] Config <Info> common/settings.cpp:operator():55: Renderer_UseReactiveFlushing: true
[  13.287840] Config <Info> common/settings.cpp:operator():55: Renderer_ShaderBackend: 0
[  13.287841] Config <Info> common/settings.cpp:operator():55: Renderer_UseAsynchronousShaders: false
[  13.287842] Config <Info> common/settings.cpp:operator():55: Renderer_AnisotropicFilteringLevel: 0
[  13.287842] Config <Info> common/settings.cpp:operator():55: Audio_OutputEngine: auto
[  13.287843] Config <Info> common/settings.cpp:operator():55: Audio_OutputDevice: auto
[  13.287843] Config <Info> common/settings.cpp:operator():55: Audio_InputDevice: auto
[  13.287843] Config <Info> common/settings.cpp:operator():55: DataStorage_UseVirtualSd: true
[  13.287844] Config <Info> common/settings.cpp:operator():59: DataStorage_CacheDir: /home/user/.var/app/org.yuzu_emu.yuzu/cache/yuzu
[  13.287845] Config <Info> common/settings.cpp:operator():59: DataStorage_ConfigDir: /home/user/.var/app/org.yuzu_emu.yuzu/config/yuzu
[  13.287846] Config <Info> common/settings.cpp:operator():59: DataStorage_LoadDir: /home/user/.var/app/org.yuzu_emu.yuzu/data/yuzu/load
[  13.287846] Config <Info> common/settings.cpp:operator():59: DataStorage_NANDDir: /home/user/.var/app/org.yuzu_emu.yuzu/data/yuzu/nand
[  13.287847] Config <Info> common/settings.cpp:operator():59: DataStorage_SDMCDir: /home/user/.var/app/org.yuzu_emu.yuzu/data/yuzu/sdmc
[  13.287848] Config <Info> common/settings.cpp:operator():55: Debugging_ProgramArgs: 
[  13.287848] Config <Info> common/settings.cpp:operator():55: Debugging_GDBStub: false
[  13.287848] Config <Info> common/settings.cpp:operator():55: Input_EnableMotion: true
[  13.287849] Config <Info> common/settings.cpp:operator():55: Input_EnableVibration: true
[  13.287849] Config <Info> common/settings.cpp:operator():55: Input_EnableTouch: true
[  13.287849] Config <Info> common/settings.cpp:operator():55: Input_EnableMouse: false
[  13.287850] Config <Info> common/settings.cpp:operator():55: Input_EnableKeyboard: false
[  13.287850] Config <Info> common/settings.cpp:operator():55: Input_EnableRingController: true
[  13.287852] Config <Info> common/settings.cpp:operator():55: Input_EnableIrSensor: false
[  13.287852] Config <Info> common/settings.cpp:operator():55: Input_EnableCustomJoycon: true
[  13.287853] Config <Info> common/settings.cpp:operator():55: Input_EnableCustomProController: false
[  13.287854] Config <Info> common/settings.cpp:operator():55: Input_EnableRawInput: false
[  13.290488] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:442:     RomFS: Update (v0.4.0) applied successfully
[  13.453384] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:460: Ampere and newer have broken float16 math
[  13.453387] Render.Vulkan <Warning> video_core/vulkan_common/vulkan_device.cpp:Device:474: NVIDIA Drivers >= 510 do not support MSAA image blits
[  13.600527] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:173: Driver: NVIDIA 535.54.3.0
[  13.600530] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:174: Device: NVIDIA GeForce RTX 3070 Laptop GPU
[  13.600531] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:175: Vulkan: 1.3.242
[  13.600537] Render.Vulkan <Info> video_core/renderer_vulkan/renderer_vulkan.cpp:Report:176: Available VRAM: 6.81 GiB
[  13.603748] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the sdl2 backend
[  13.607396] Service.Audio <Info> audio_core/sink/sink_details.cpp:GetOutputSinkDetails:84: Auto-selecting the sdl2 backend
[  13.611122] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:131: Patching ExeFS for title_id=0100F2C0115B6000
[  13.611337] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:146:     ExeFS: Update (v0.4.0) applied successfully
[  13.611392] Loader <Info> core/file_sys/patch_manager.cpp:PatchExeFS:178:     ExeFS: LayeredExeFS patches applied successfully
[  13.795753] Loader <Info> core/file_sys/patch_manager.cpp:HasNSOPatch:302: Querying NSO patch existence f

### System Configuration

CPU: AMD Ryzen 7 5800H with Radeon Graphics (16) @ 3.200GHz
GPU/Driver: NVIDIA GeForce RTX 3070 Mobile / Max-Q 3:535.54.03-1.fc38
RAM: 32 GB
OS: Fedora Linux 38 (Workstation Edition) x86_64

**Comment by liamwhite** [comment] 2023-07-02 22:08
follow the directions here https://github.com/flathub/org.yuzu_emu.yuzu#obtaining-a-debugger-trace-as-the-crash-happens

**Comment by Legoalda** [comment] 2023-07-02 22:18
[org yuzu emu yuzu gdb.txt](https://github.com/yuzu-emu/yuzu/files/11931603/org.yuzu.emu.yuzu.gdb.txt)

**Comment by liamwhite** [comment] 2023-07-02 23:58
@zeltermann Regression caused by #10679, please check

**Comment by liamwhite** [comment] 2023-07-03 00:05
@Legoalda what is your system locale?

**Comment by Legoalda** [comment] 2023-07-03 04:58
> @Legoalda what is your system locale?

It's French France: fr_FR

**Comment by zeltermann** [comment] 2023-07-03 09:11
Please re-test with a build from https://github.com/yuzu-emu/yuzu/actions/runs/5441924929#artifacts and report back.

**Comment by Legoalda** [comment] 2023-07-03 11:29
Tested successfully with TOTK and BOTW. However TOTK takes around 20~30 seconds to be loaded.

Thank you for the fix.
Have a nice day

**Comment by zeltermann** [comment] 2023-07-03 11:51
Thanks. When #11007 gets merged, you should be able to switch back to mainline again.

**Closed** 2023-07-03 17:23 UTC
