### ISSUE TITLE
Linux build crashes when configure menu selected

### ISSUE THREAD

**Issue by spacestate1** [yuzu-emu/yuzu#3286] opened 2020-01-09 05:06 UTC
Consistently crashes in Ubuntu 18.04 when Emulation -> configure is selected. No messages in logs. 

Tested on: 

mainline-636-810-gc2c83b4ff-dirty
mainline-636-797-gfd606531e-dirty

**Comment by ReaperOfSouls1909** [comment] 2020-01-09 05:07
#2957 duplicate of this issue

**Comment by Hexagon12** [comment] 2020-01-09 19:31
Duplicate of #2957

**Closed by Hexagon12** 2020-01-09 19:31 UTC
