### ISSUE TITLE
(Android) Sniper Elite 4 gyro doesn't work properly 

### ISSUE THREAD

**Issue by Gorillaisdork** [yuzu-emu/yuzu#11901] opened 2023-10-28 22:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 15ddd882d

### Description of Issue

When enabling the motion controls on the options menu. Gyroscope does work but doesn't properly register the left and right directions when i tilt the device, however it works when i tilt it up and down.

### Expected Behavior

It should detect motion wherever i tilt my phone 

### Reproduction Steps

Simply enable gyro under motion controls and tilt the device left and right. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13196852/yuzu_log.txt)

### System Configuration

CPU: SD 855
GPU/Driver: Turnip R8
RAM: 8 GB
OS: Android 12

**Comment by FearlessTobi** [comment] 2023-10-29 23:21
Duplicate of https://github.com/yuzu-emu/yuzu/issues/11891.

**Closed by FearlessTobi** 2023-10-29 23:21 UTC
