### ISSUE TITLE
yuzu EA 1246: XC2 Infinite boot loop with DLC & Update

### ISSUE THREAD

**Issue by normand668** [yuzu-emu/yuzu#5220] opened 2020-12-22 15:50 UTC
As title describes, this is a widely reported issue across reddit and dates back at least 2 months. Apologies if incorrect forum or means to request/report this issue as a patreon.

This error has is also on main channel and has been tested by myself over the last couple months, providing the infinite initial boot loop whenever the game has selected both the title update and DLC. Without the DLC the game does boot. This has also been tested on XC2 Update versions 2.0.1, 2.0.2 and 2.1.0.

Any feedback on when this issue may get resolved would be greatly appreciated. Please let me know if there is any further information i can provide.
![Capture](https://user-images.githubusercontent.com/76486731/102907043-60bc2880-446d-11eb-877a-c48baea59382.JPG)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5730747/yuzu_log.txt)

**Comment by FearlessTobi** [comment] 2020-12-25 21:00
Thank you very much for your report, although I believe this a duplicate of https://github.com/yuzu-emu/yuzu/issues/4712.
Therefore I'm merging those issue reports. It would be greatly appreciated if you could repost your findings as a comment there.

**Closed by FearlessTobi** 2020-12-25 21:00 UTC
