### ISSUE TITLE
custom rtc keeps advancing with time

### ISSUE THREAD

**Issue by Jashi77** [yuzu-emu/yuzu#11606] opened 2023-09-26 15:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Yuzu offers a custom rtc function to change the time, but unlike ryujinx and even actual switches the clock doesnt advance with custom rtc enabled. I’d like to play ACNH in summer, without having to change the time each time i play, and yes, changing my system’s time is an option, but it’s not ideal and it would be cool to have a toggle in the emulators options.

### Why would this feature be useful?

This would also be parity with the switch functionality, as changing the time there works like this as well.

**Comment by Squall-Leonhart** [comment] 2023-09-27 23:51
duplicate of https://github.com/yuzu-emu/yuzu/issues/10862

**Closed** 2023-09-29 18:22 UTC
Labels: request
