### ISSUE TITLE
Unimplemented Function - FlushAudioOutBuffers - Devil May Cry 1-3

### ISSUE THREAD

**Issue by BSoDGamingYT** [yuzu-emu/yuzu#4924] opened 2020-11-14 12:20 UTC
Devil May Cry 1-3 all freeze/softlock if you attempt to skip video playback. The reported issue is the following:

**Debug <Critical> core\hle\service\service.cpp:ReportUnimplementedFunction:150: Assertion Failed!
Unknown / unimplemented function 'FlushAudioOutBuffers': port='IAudioOut' cmd_buf={[0]=0x6, [1]=0x8, [2]=0x0, [3]=0x0, [4]=0x49434653, [5]=0x1, [6]=0xB, [7]=0x0, [8]=0x0}**

Log from this issue:
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5540666/yuzu_log.zip)

**Comment by FearlessTobi** [comment] 2020-11-15 01:38
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4924.

**Closed by FearlessTobi** 2020-11-15 01:38 UTC
