### ISSUE TITLE
segfault when opening configure

### ISSUE THREAD

**Issue by Sur3** [yuzu-emu/yuzu#3382] opened 2020-02-06 19:22 UTC
Hi I get a Segmentation fault when trying to open the configure dialogue on the linux version of yuzu...

---

qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 670, resource id: 20480070, major code: 40 (TranslateCoords), minor code: 0
malloc(): invalid size (unsorted)

---

```
munmap_chunk(): invalid pointer

Thread 21 "Thread (pooled)" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff934b9700 (LWP 3620)]
0x00007ffff6338ec1 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff6338ec1 in raise () at /lib64/libc.so.6
#1  0x00007ffff6322535 in abort () at /lib64/libc.so.6
#2  0x00007ffff637eec8 in  () at /lib64/libc.so.6
#3  0x00007ffff6386b88 in  () at /lib64/libc.so.6
#4  0x00007ffff6386ebc in  () at /lib64/libc.so.6
#5  0x00007ffff7d35fcd in CRYPTO_clear_realloc () at /usr/lib64/libcrypto.so.1.1
#6  0x00007ffff7c930a9 in BUF_MEM_grow_clean () at /usr/lib64/libcrypto.so.1.1
#7  0x00007ffff7c752c4 in  () at /usr/lib64/libcrypto.so.1.1
#8  0x00007ffff7c70e6a in  () at /usr/lib64/libcrypto.so.1.1
#9  0x00007ffff7c6fec4 in  () at /usr/lib64/libcrypto.so.1.1
#10 0x00007ffff7c70383 in BIO_write () at /usr/lib64/libcrypto.so.1.1
#11 0x0000555555deabe8 in tls1_finish_mac ()
#12 0x0000555555df8e95 in ssl3_get_message ()
#13 0x0000555555dfae71 in ssl3_get_server_certificate ()
#14 0x0000555555dfefc8 in ssl3_connect ()
#15 0x00005555558868ed in httplib::SSLClient::process_and_close_socket(int, unsigned long, std::function<bool (httplib::Stream&, bool, bool&)>) ()
#16 0x00005555558939b5 in httplib::Client::send(httplib::Request const&, httplib::Response&) ()
#17 0x0000555555893df2 in httplib::Client::Get(char const*, std::multimap<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, httplib::detail::ci, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&) ()
#18 0x000055555587cf85 in Service::BCAT::Boxcat::GetStatus(std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >&, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Service::BCAT::EventStatus, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Service::BCAT::EventStatus> > >&) ()
#19 0x00005555556c1550 in ConfigureService::BCATDownloadEvents() ()
#20 0x00005555556c4dfb in non-virtual thunk to QtConcurrent::RunFunctionTask<std::pair<QString, QString> >::run() ()
#21 0x00007ffff696be93 in  () at /usr/lib64/libQt5Core.so.5
#22 0x00007ffff6968be2 in  () at /usr/lib64/libQt5Core.so.5
#23 0x00007ffff799d427 in start_thread () at /lib64/libpthread.so.0
#24 0x00007ffff64052bf in clone () at /lib64/libc.so.6

```

**Comment by Morph1984** [comment] 2020-02-06 19:24
Duplicate of #2957

**Comment by goldenx86** [comment] 2020-02-06 19:24
Are you building from source, or using the precompiled binary?
This is usually a problem for non Ubuntu users using the precompiled binary, it should be gone if you build mainline from source.

**Comment by Sur3** [comment] 2020-02-06 19:26
I used the precompiled binary, ok I'll try to build it from source then.

**Comment by goldenx86** [comment] 2020-02-06 19:26
Make sure to clone mainline and not master.

**Closed** 2020-02-06 19:25 UTC

**Comment by Sur3** [comment] 2020-02-06 20:16
Ok compiling from source took quite a while with all those submodules, but it fixed it. :)
