### ISSUE TITLE
Pokemon Lets Go Pikachu

### ISSUE THREAD

**Issue by KranKRival** [yuzu-emu/yuzu#2001] opened 2019-01-06 08:50 UTC
Latest builds of canary runnning the game preaty good on my pc 
i5 cpu dual core 
Nvidia gtx 650 ti boost gpu
8 giga of cheap ram.. 

I have one ennoying issue that the game like soft locks it self and the screen freeze or gets black randomly, and that frame and percentage count jump to like 200% and 200fps .. from there i must restart the emulation ... 

Ill be providing a full log file when im back home today ... thanks in advantage

**Comment by legoj15** [comment] 2019-01-06 09:53
Duplicate of #1935

**Closed** 2019-01-06 11:40 UTC
