### ISSUE TITLE
Cemu crashes when accessing configure in Linux Mint 19.2

### ISSUE THREAD

**Issue by dukenukemx** [yuzu-emu/yuzu#3246] opened 2019-12-25 16:14 UTC
Using build yuzu-linux-20191225-03baae298 the moment I click configure, Cemu will crash and gives this error in terminal.  Games will start and run.  

`free(): invalid next size (fast)
Aborted`

**Comment by Hexagon12** [comment] 2019-12-25 16:18
Duplicate of #2957

**Closed by Hexagon12** 2019-12-25 16:18 UTC
