### ISSUE TITLE
unimplemented function 'StoreSaveDataThumbnail' (Arcade Archives LIFEFORCE )

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#4681] opened 2020-09-18 08:28 UTC
after you choose your game Yuzu just freezes up 
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5244330/yuzu_log.zip)

**Comment by FearlessTobi** [comment] 2020-11-06 00:13
Duplicate of #2645.

**Closed by FearlessTobi** 2020-11-06 00:13 UTC

**Comment by benderscruffy** [comment] 2020-11-06 08:43
thanks was about to close
