### ISSUE TITLE
Crash when clicking "Configure"

### ISSUE THREAD

**Issue by Matthysse** [yuzu-emu/yuzu#4215] opened 2020-06-30 20:15 UTC
Hello!

The problem is as simple as the title says. The Yuzu emulator crashes (doesn't respond) when clicking configure.
It's a common crash, I saw a lot of other people who have this bug. When I report it on the discord, I'm always ignored so I post it here, even if it seems that nobody from the team reads the issues here. 
Before you ask : there are no logs, absolutely not, because I don't run any games the log file is empty.
I have the latest vulkan beta drivers for my nvdia gtx 1050ti : 443.41
And the latest drivers for the intel hd gpu : (sorry it's in french but there is everything you need)
![Capture](https://user-images.githubusercontent.com/32510957/86172637-01fd9e00-bb1f-11ea-863d-79f3bf8cb578.PNG)

**Comment by Arkahaine** [comment] 2020-07-01 11:14
Same problem here, I have a i5-8400 and a GTX 1060 6GB.
I tried uninstalling my nvidia driver with DDU and it worked again but when I reinstalled the drivers it stopped working again so I guess it's a issue with the graphic card software.

**Comment by Matthysse** [comment] 2020-07-01 20:08
Yeah, but there are many other people who have the Vulkan Beta drivers, and it works fine for them so I don't understand.

**Comment by german77** [comment] 2022-01-08 06:01
This issue is caused by recording software that use vulkan and make the driver report features that the GPU doesn't support. Uninstalling such program will fix the issue. Keeping open since this crash shouldn't happen.

**Comment by liamwhite** [comment] 2022-09-28 02:08
Should be fixed by https://github.com/yuzu-emu/yuzu/pull/8393

**Closed by liamwhite** 2022-09-28 02:08 UTC
