### ISSUE TITLE
Rogue Legacy screen is upside down

### ISSUE THREAD

**Issue by benderscruffy** [yuzu-emu/yuzu#3862] opened 2020-05-02 06:50 UTC
all the screens are upside down 
no change if it is docked or undocked
![rogue](https://user-images.githubusercontent.com/2696404/80857374-3d493100-8c84-11ea-943f-0e49d0f22294.PNG)
![rogue1](https://user-images.githubusercontent.com/2696404/80857377-3e7a5e00-8c84-11ea-839d-b5f3f5add277.PNG)
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4567210/yuzu_log.zip)

**Comment by callmenemo491** [comment] 2020-05-02 06:53
looks to be similar to: #2703

**Comment by benderscruffy** [comment] 2020-05-02 09:56
Undertale has the same problem

**Comment by Hexagon12** [comment] 2020-05-03 12:40
Duplicate of #2703

**Closed by Hexagon12** 2020-05-03 12:40 UTC
