### ISSUE TITLE
[Feature Request] Controller friendly input confirmation applet

### ISSUE THREAD

**Issue by Anabas27** [yuzu-emu/yuzu#8552] opened 2022-07-08 10:55 UTC
Description:
Controller confirmation applet is controllable only via mouse/kb which is emulation breaker for many users. Especially if you use your PC as a Gaming Box (Network Streaming or as a Standalone controller controlled PC which boots up straight into a game list).

Request:
There's two solutions - First is an easy but homebrew one and second is the proper way,

1. Make an experimental checkbox somewhere in preferences which will bypass this applet altogether, because in 99.9% cases everything is already setup and you only have to press OK.  If you have this checkbox enabled - auto confirm controllers in the background.
2. Make a controller controlled overlay or window so you can confirm or/and configure everything with a controller (overlay is better because that way you can hide Windows UI altogether)

Requests describing the same problem:

#8132 - Solution presented here is awful and is just a workaround not a solution.
#4211

**Comment by FernandoS27** [comment] 2022-07-08 12:11
@Its-Rei @Morph1984 I think this a feature we have wanted to add in sometime and the UI was already done. any ideas?

**Comment by Gamerboi520** [comment] 2022-07-23 11:03
Upvote

**Comment by Gamerboi520** [comment] 2022-07-23 11:05
If anything id prefer the popup not even appear at all

**Comment by D1Vad22** [comment] 2022-08-22 10:28
Just started using Yuzu for the first time, adding this feature would be very helpful for controller only setups

**Comment by mdac3564444** [comment] 2022-09-06 22:37
Please add...

**Comment by MaLDox77** [comment] 2022-10-11 06:13
Upvote

**Comment by devcordlesssystems** [comment] 2022-10-24 10:18
Upvote! I use Steam Deck with 2 controllers and TV and I have to stand up, unplug steam deck, press OK on a touch screen, connect it back, go back to sofa each time I start a game :) Never had to change anything there, btw

**Comment by djeer** [comment] 2022-10-24 10:23
Upvote! I use Steam Deck with 2 controllers and TV and I have to stand up, unplug steam deck, press OK on a touch screen, connect it back, go back to sofa each time I start a game 🙂 Never had to change anything there, btw. I have a great experience in all other aspects and even with this hustle it's still awesome project 👍

**Comment by Silas888** [comment] 2022-10-31 21:51
Upvote from me too

**Comment by MrAngularVelocity** [comment] 2022-11-01 04:45
Just chiming in to say I've been using yuzu for years and this small popup breaks my controller only setup. Would love to just hit A and accept whatever is there.

**Comment by devcordlesssystems** [comment] 2022-11-01 11:33
For **Steam Deck** users there is a way to close this window - press "Enter" by pressing "Steam" + "D-pad Right", it works reliable for me (I press Xbox+Right on a remote xbox controller connected to steamdeck, same result).

**Comment by djeer** [comment] 2022-11-01 11:33
For **Steam Deck** users there is a way to close this window - press "Enter" by pressing "Steam" + "D-pad Right", it works reliable for me (I press Xbox+Right on a remote xbox controller connected to **Steam Deck**, same result).

**Comment by Hixbot2** [comment] 2022-12-31 21:12
Big upvote from me!  Thanks to those who contribute on this amazing software!

**Comment by ebadbeef** [comment] 2023-01-04 21:40
If you build yuzu from source, you can remove the "Controller Selector" applet from main.cpp (diff included below) and it will use a default controller applet that tries to assign controllers based on a simple set of rules. I would guess this is probably also used in yuzu-sdl (looks like it from #4597)

I tested Super Mario Odyssey and Cadence of Hyrule with this and it seems to do what I want!

See https://github.com/yuzu-emu/yuzu-mainline/blob/mainline-0-1275/src/yuzu/main.cpp#L1563
and https://github.com/yuzu-emu/yuzu-mainline/blob/mainline-0-1275/src/core/hle/service/am/applets/applets.cpp#L250
and https://github.com/yuzu-emu/yuzu-mainline/blob/mainline-0-1275/src/core/frontend/applets/controller.cpp#L19

My vote for an "easy fix" would be for an option in the UI to force using the default controller applet instead of the Qt one.

```
diff --git a/src/yuzu/main.cpp b/src/yuzu/main.cpp
index 44ba47afe..1bfb82060 100644
--- a/src/yuzu/main.cpp
+++ b/src/yuzu/main.cpp
@@ -1560,7 +1560,7 @@ bool GMainWindow::LoadROM(const QString& filename, u64 program_id, std::size_t p

     system->SetAppletFrontendSet({
         std::make_unique<QtAmiiboSettings>(*this),     // Amiibo Settings
-        std::make_unique<QtControllerSelector>(*this), // Controller Selector
+        nullptr, // Controller Selector
         std::make_unique<QtErrorDisplay>(*this),       // Error Display
         nullptr,                                       // Mii Editor
         nullptr,                                       // Parental Controls
```

**Comment by Pozuelos78** [comment] 2023-01-12 05:45
https://github.com/yuzu-emu/yuzu/issues/8132#issuecomment-1379843421

**Comment by Pozuelos78** [comment] 2023-01-12 05:48
Workaround with JoyTokey
assign the keyboard key "Enter" to the guide button on the Xbox 360 controller 1 and 2 (my case) the controls must be previously configured.
When the applet control appears, just press the guide button on control 1 or the guide button on control 2.
I use Yuzu with hyperspin with RocketLauncher

![360_controller](https://user-images.githubusercontent.com/76235602/211987641-647843e6-9db1-4131-b15c-14882f5bd5ea.png)
![1](https://user-images.githubusercontent.com/76235602/211987657-4a837923-9bca-4377-be2a-b0e6468ad603.png)
![2](https://user-images.githubusercontent.com/76235602/211987664-f20964e6-544f-4328-82c9-d98f95faca90.png)
![Sin título3](https://user-images.githubusercontent.com/76235602/211987671-1b4f1b6a-c1ba-41ec-9573-0fa98a4155e0.jpg)

**Comment by tastyratz** [comment] 2023-01-12 14:47
Is there any actual benefit to using the applet popup over just configuring the controller in the options like any other emulator? 

Part of this confuses me because while a lot of people are mentioning how to get around it and justifying why it shouldn't be there I'm wondering the inverse - why do we even have it at all? What benefit is it providing? Doubly when everything is connected and working where it adds a prompt you just click "OK" on. It's like being forced to choose a profile when there is only 1 profile.

If controller binding doesn't show a connected controller, poll for it and re-detect every x seconds. If pairing picks the wrong one, you select it in the config menu. 
If some dev's are really married to it, make it a checkbox in the UI for "show controller applet pop every time" and tie to the section of code mentioned by [EBADBEEF](https://github.com/EBADBEEF).

**Comment by Pozuelos78** [comment] 2023-03-29 08:17
I want to believe that something happened here..  EA-3481

https://github.com/pineappleEA/pineapple-src/commit/d3dddd9776828c979f98af1dc14ec7d59a3d3c62

![Screenshot_20230329-021605_Chrome](https://user-images.githubusercontent.com/76235602/228470972-5b76bd19-da62-4abd-bc71-6746eaae9edc.jpg)

**Comment by PilaScat** [comment] 2023-07-14 20:15
Hello? this problem keep bothering me for years, could you add a checkbox to disable this? I'm streaming to a tv in another floor and this is very annoying

**Comment by D1Vad22** [comment] 2023-07-14 21:21
> Hello? this problem keep bothering me for years, could you add a checkbox to disable this? I'm streaming to a tv in another floor and this is very annoying

It was added recently, make sure you have latest version. Thanks to the devs, massive benefit.

**Comment by maddox** [comment] 2023-07-14 21:52
Whoa really? It just won’t show up when playing Mario kart anymore?

I’ve been following EA extensively since TOTK. I’m not sure how I missed this.

**Comment by maddox** [comment] 2023-07-14 21:53
So can this issue be closed?

**Comment by PilaScat** [comment] 2023-07-15 01:19
I've the latest version and the switch is not there, the popup keep appearing, where did you find it?

**Comment by D1Vad22** [comment] 2023-07-15 01:36
> I've the latest version and the switch is not there, the popup keep appearing, where did you find it?
It was on general tab first page down bottom, or in some advanced tab. Wasnt in the controller input settings

**Comment by PilaScat** [comment] 2023-07-15 10:19
no there isn't, make a screen pls, disable web applet is not that anyway

**Comment by maddox** [comment] 2023-07-17 15:52
I just confirmed the setting and that it works. I started Mario Kart 8 Deluxe with 3 controllers attached, and was able to launch into a race without being prompted with the controller applet.

**Comment by PilaScat** [comment] 2023-07-17 15:56
This is mine general tab, I cannot find it, I'm on latest build (1259)
![image](https://github.com/yuzu-emu/yuzu/assets/12989749/fff79257-c667-425b-9400-da14087e69b9)

**Comment by maddox** [comment] 2023-07-17 15:56
I was using the latest EA

**Comment by PilaScat** [comment] 2023-07-17 16:05
I found out now that I'm not on the latest, it stopped updating 6 months ago for no reason, now I have the checkbox

**Comment by german77** [comment] 2023-11-09 16:17
Latest mainline will let you do basic configuration with just a controller

**Closed by german77** 2023-11-09 16:17 UTC
