### ISSUE TITLE
FSR's sharpening  and antialiasing mode modifier is disabled in game and you can't choose the quality of the FSR either.

### ISSUE THREAD

**Issue by boludoz** [yuzu-emu/yuzu#11423] opened 2023-08-31 16:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

All Yuzu versions with FSR like EA 3851

### Description of Issue

FSR's sharpening level modifier is disabled in game. The quality modifier is not available. The antialiasing selector has also been disabled. 

### Expected Behavior

This should allow you to change the modifier in real time, including its quality.

### Reproduction Steps

Fire up the game and play with FSR.

### Log File

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/5bbe6ec5-3679-4be1-bc8b-1d2b73bc872b)
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/730e6a8b-28d0-4253-8a53-6569c51b6ad7)

### System Configuration

Not neccesary, it is GUI problem

**Comment by lat9nq** [comment] 2023-09-02 22:18
Please upload a log file like the issue template already asked you to do.

**Comment by boludoz** [comment] 2023-09-03 06:19
> Please upload a log file like the issue template already asked you to do.

There is nothing to log in. It should simply let you choose the antialiasing and sharpening of the fsr in real time.

**Comment by boludoz** [comment] 2023-09-03 06:20
I looked at the program code and indeed it should be able to, the variable is set to true.

**Comment by lat9nq** [comment] 2023-09-03 06:38
Start any guest/program or game and upload the log file.

What is likely happening is that you overrode those settings in a specific game's properties and did not clear them when opening the global config. I cannot reproduce this error otherwise.

**Comment by boludoz** [comment] 2023-09-04 06:13
> Inicie cualquier invitado/programa o juego y cargue el archivo de registro.
> 
> Lo que probablemente suceda es que anulaste esa configuración en las propiedades de un juego específico y no las borraste al abrir la configuración global. No puedo reproducir este error de otra manera.

TRUE. I recommend adding vsync mode in custom game settings. And add a button that opens the game's graphical configuration window or something like that.

**Comment by boludoz** [comment] 2023-09-04 06:26
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/73b2939c-8444-4802-8a23-dcc5fba3cb64)

Or more izi :

![image](https://github.com/yuzu-emu/yuzu/assets/11653030/a4ee164e-0b23-4611-9053-d575ba3ea31f)

**Comment by FearlessTobi** [comment] 2023-09-04 12:40
Issue caused by user error, closing.

**Closed by FearlessTobi** 2023-09-04 12:40 UTC
