### ISSUE TITLE
 Add option to be able to use cheats

### ISSUE THREAD

**Issue by Benyi25** [yuzu-emu/yuzu#12295] opened 2023-12-06 18:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hello, I have tried in every way to be able to use cheats, but it is complicated, in the end I was not able to achieve it, a simpler option would be good to be able to apply cheats to our games, like most of the emulators currently on Android

### Why would this feature be useful?

The cheats features are very important to use mod, whether it is money, life or tricks for fps

**Comment by FearlessTobi** [comment] 2023-12-06 19:00
Duplicate of https://github.com/yuzu-emu/yuzu/issues/10202.

**Closed by FearlessTobi** 2023-12-06 19:00 UTC
Labels: request
