### ISSUE TITLE
Want to add the grid game list

### ISSUE THREAD

**Issue by nangongjing1** [yuzu-emu/yuzu#12638] opened 2024-01-10 13:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Hopefully, the list of games can be displayed in the form of a grid.What I envisioned was a main screen divided into a number of resizable grids, with the majority of the grid being used to display the game cover and the game name at the bottom.Just like the sketch I attached, I only drew the first square, and everything else is similar to the first one.
<img width="768" alt="Sketch of the interface style" src="https://github.com/yuzu-emu/yuzu/assets/115774212/16ea79b1-f551-43de-b9d1-9ba81438c4d9">

### Why would this feature be useful?

This is because displaying a list of games in a grid allows for a more efficient selection of games to run, while also being more aesthetically pleasing. At the same time, it is also more convenient for users to manage their own local games.

**Comment by t895** [comment] 2024-01-10 17:42
Duplicate of #8720 
Don't open duplicate issues because the original doesn't have much activity

**Closed by t895** 2024-01-10 17:42 UTC
Labels: request

**Comment by nangongjing1** [comment] 2024-01-11 03:48
> Duplicate of #8720 Don't open duplicate issues because the original doesn't have much activity

Okey,I see.
