### ISSUE TITLE
Random crash intel uhd 630 

### ISSUE THREAD

**Issue by edergames29** [yuzu-emu/yuzu#10496] opened 2023-05-29 17:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA 3621

### Description of Issue

Zelda TEARS OF KINGDOM 1.1.1
I start playing and out of nowhere the game crashes sometimes it takes time to crash sometimes it crashes right away

### Expected Behavior

don't crash

### Reproduction Steps

I start playing and out of nowhere the game crashes sometimes it takes time to crash sometimes it crashes right away

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11593469/yuzu_log.txt.old.txt)

### System Configuration

CPU: 8
GPU/Driver: uhd 630
RAM: 12
OS: Windows 11

**Comment by FearlessTobi** [comment] 2023-05-29 19:40
Duplicate of https://github.com/yuzu-emu/yuzu/issues/10480 and several other issues.

**Closed by FearlessTobi** 2023-05-29 19:40 UTC
