### ISSUE TITLE
Ben 10 Crash Issue + Log File

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#2850] opened 2019-09-09 20:33 UTC
The game shows some credits, plays a glitchy sound and then crashes.

Log File:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3592497/yuzu_log.txt)

**Comment by Hexagon12** [comment] 2019-09-10 11:58
Duplicate of #2825

**Closed by Hexagon12** 2019-09-10 11:59 UTC
