### ISSUE TITLE
Super Smash Bros Ultimate and Pokemon Sword and Shield randomly crashes

### ISSUE THREAD

**Issue by SeuChico** [yuzu-emu/yuzu#6000] opened 2021-02-26 00:14 UTC
Hello, 

Those two games randomly crashes after some time, ssbu more often than Pokemon, and it's happening with my friends too, I'd like to know if there is any fix for this? I think the mainly problem it's the amount of shaders those two games has.

GTX 960
i7 4770k
12GB RAM

**Comment by G-Spawn** [comment] 2021-02-26 12:15
Try to provide logs like the create new issue asks for please.

**Comment by OZtistic** [comment] 2021-02-26 22:28
Pokemon mem leak issue, I assume these are both related
https://github.com/yuzu-emu/yuzu/issues/5995#issuecomment-785358562

**Comment by FearlessTobi** [comment] 2021-04-02 14:02
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/6003.

**Closed by FearlessTobi** 2021-04-02 14:02 UTC
