### ISSUE TITLE
Pokemon violet/scarlet rendering bug (Android)

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#10626] opened 2023-06-05 02:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Acces Playstore 627e1f2b

### Description of Issue

As the title says there is a rendering bug when it is time to control the character in which the textures are corrupted

here in the intro everything perfect

![Screenshot_20230604-180641_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/1eb9946a-e8d7-4d9c-9dff-ee4f60642d92)
![Screenshot_20230604-180429_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/2420a709-4d33-457e-b6cf-ba250c7fa34d)
![Screenshot_20230604-180435_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/c469bb43-70eb-4abb-b9f5-18a5b57fe2af)
![Screenshot_20230604-180447_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/e42fb8eb-bd28-4232-bfb0-bbbeaadf17c2)
![Screenshot_20230604-180521_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/5eeaa1ed-412f-4586-8293-fb6724322757)
![Screenshot_20230604-180537_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/e4d8f67e-8471-4cb7-95ef-34ce65ce88c9)
![Screenshot_20230604-180558_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/a5a9644b-1b80-4349-946c-162b323125d6)

this happens later

![Screenshot_20230604-180826_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/a77577ce-bb19-4dcf-b409-b7c1034a6cd7)
![Screenshot_20230604-180810_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/c7362d9a-63d4-4c00-9a91-e2a49e193efd)

### Expected Behavior

this shouldn't happen normally in the game

### Reproduction Steps

nothing special just start a game

### Log File

[yuzu_log_violeta.txt](https://github.com/yuzu-emu/yuzu/files/11648032/yuzu_log_violeta.txt)

### System Configuration

CPU: SD860
GPU/Driver: Adreno 640 turnip driver
RAM: 8gb
OS: Android 13

**Comment by Ragul32** [comment] 2023-06-05 06:53
I already opened same issue but using Adreno https://github.com/yuzu-emu/yuzu/issues/10563

**Comment by FearlessTobi** [comment] 2023-06-05 20:40
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/10563.

**Closed by FearlessTobi** 2023-06-05 20:40 UTC

**Comment by thinh5556727** [comment] 2023-08-03 09:30
How to download the game
