### ISSUE TITLE
Navi shader cache problem and vulkan stutters

### ISSUE THREAD

**Issue by ghost** [yuzu-emu/yuzu#3294] opened 2020-01-12 15:24 UTC
Hello. I have a Navi 5700xt card pairing with an 8700k cpu. The problems in yuzu are a lot.

First the shader cache arent working at all with opengl. I use opengl in pokemon lets go because it play fine at 30fps without issues but after i close the game and open it even if it load the shaders it will still stutter in the battle when i make moves. Its like the shader cache isnt working at all despite its compiling while i play.

The second problem is with the vulkan and first with pokemon lets go it keeps stutters a lot in battles after each time i start the game and the second one is the black rendering artifacts issues in mario odyssey with vulkan. Maybe the drivers are completely broken by AMD maybe there are other things that produce these problems.

**Comment by Hexagon12** [comment] 2020-01-12 16:35
For your stutter issues: this is an issue tracker for developers and not a support forum.
Please use our Discord for support requests.

For the second issue, it's a duplicate of #3262

**Comment by Hexagon12** [comment] 2020-01-12 17:12
Nevermind, you were linked to report this issue. Could you please provide video footage of the stutters you're experiencing?

**Comment by losh11** [comment] 2020-02-26 17:38
@Hexagon12 seeing that OP hasn't replied I can share a video if you still need it?

**Comment by FearlessTobi** [comment] 2020-02-26 17:39
yes, that would be very helpful

**Comment by emudem** [comment] 2020-04-29 19:48
Post video please

**Comment by losh11** [comment] 2020-04-29 21:10
Here's a video that others have posted: https://youtu.be/8zX6ihSCLIk?t=23
It's the weird black pixels where shadows usually occur.

**Comment by G-Spawn** [comment] 2022-06-17 05:04
Closing as OP has deleted their account.

**Closed by G-Spawn** 2022-06-17 05:04 UTC
Labels: vulkan
