### ISSUE TITLE
Tears of the kingdom : abnormal overcoat

### ISSUE THREAD

**Issue by CelerSan** [yuzu-emu/yuzu#12628] opened 2024-01-09 06:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

N/A

### Description of Issue

Hi, I installed Tears of the kingdom on yuzu with some mods (https://gbatemp.net/download/loz-tears-of-the-kingdom-dynamic-fps-static-fps-and-visual-fixes-patch-collection.37996/) and updates to the game. The game started on the opening cutscene with a sort of black semi-square layer over the entire screen with elements of the game either above this layer is on top. I tried to erase everything from yuzu that redistribute from scratch with only the base game installed but nothing to do. This overlay is still there.

### Expected Behavior

![Capture d’écran du 2024-01-08 19-56-14](https://github.com/yuzu-emu/yuzu/assets/144831071/119cfa80-0499-4c25-9e1d-de6fc515646f)

### Reproduction Steps

N/A

### Log File

N/A

### System Configuration

CPU: Intel Core i5 7300U
GPU/Driver: Intel HD Graphics 630
RAM: 16 Gb
OS: Ubuntu 22.04

**Comment by Squall-Leonhart** [comment] 2024-01-09 09:35
Duplicate of https://github.com/yuzu-emu/yuzu/issues/12464

**Comment by gidoly** [comment] 2024-01-09 10:45
Close due to duplicated issue

**Closed by gidoly** 2024-01-09 10:45 UTC
