### ISSUE TITLE
Pokémon Sword "polygon" graphical glitch beyond yuzu 700

### ISSUE THREAD

**Issue by dancp** [yuzu-emu/yuzu#6891] opened 2021-08-20 02:17 UTC
Pokémon sword in yuzu more recent versions, starting with version 700, has a graphical bug, despite having increased the game performance considerably. In older yuzu versions it didn't have this graphical bug but the performance was pretty bad.

Yuzu 699:
![699](https://user-images.githubusercontent.com/33817001/130168311-5d07e973-18b1-45da-81f2-340bf8d4142d.png)

Yuzu 720:
![720](https://user-images.githubusercontent.com/33817001/130168314-2500fdeb-8b87-459c-9a6b-2735b25b3259.png)

I'm using vulkan on both screenshots, my graphic card is a RX 570 4GB and updated.

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7018673/yuzu_log.txt)

**Comment by german77** [comment] 2021-08-20 02:25
duplicate of #6636

**Closed by german77** 2021-08-20 02:25 UTC
