### ISSUE TITLE
Xenoblade Chronicles 2: Enabling DLC prevents game boot

### ISSUE THREAD

**Issue by WJCra** [yuzu-emu/yuzu#4712] opened 2020-09-24 22:31 UTC
I've been trying to get DLC working for Xenoblade Chronicles 2 with mixed results. Sometimes the game doesn't boot (infinite load) with DLC installed, and sometimes I just get a black screen. Unchecking DLC and starting the game then makes the game load properly. The only DLC that seems to work is the "Helpful Items Pack".

Also, the same issue occurs with just the update, but in a lower frequency. Most of the time I can boot the game just fine with the update installed and selected.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5279550/yuzu_log.txt)

**Comment by XeroZen** [comment] 2020-10-03 07:12
Have the same issue too. Hope they can fix it soon!

**Comment by RaienryuuNoNatsu** [comment] 2020-11-21 17:47
I've been having the same issue up to Mainline 441, but after the update I've literally just done to Mainline 442, the game now properly loads and takes you to the language selection. This is a quick report, I still have to check if it goes any further, but I booted the game twice in a row without issues.

![immagine](https://user-images.githubusercontent.com/31509027/99883763-ca0c0a00-2c29-11eb-8a82-44d1fe688b39.png)
![immagine](https://user-images.githubusercontent.com/31509027/99883777-d8f2bc80-2c29-11eb-92f2-52d8b816cde8.png)

**Comment by normand668** [comment] 2020-12-26 01:52
![102907043-60bc2880-446d-11eb-877a-c48baea59382 jpeg](https://user-images.githubusercontent.com/76486731/103144147-c5e97580-471c-11eb-9705-77e7d286eaf4.jpg)

As title above in closed  duplicate issue (yuzu EA 1246..)  describes, this is a widely reported issue across reddit and dates back at least 2  

> @months.

This error has is also on main channel and has been tested by myself over the last couple months, providing the infinite initial boot loop whenever the game has selected both the title update and DLC. Without the DLC the game does boot. This has also been tested on XC2 Update versions 2.0.1, 2.0.2 and 2.1.0.

Any feedback on when this issue may get resolved would be greatly appreciated. Please let me know if there is any further information i can provide.

**Comment by normand668** [comment] 2021-02-16 01:56
Patreon sub cancelled after lack of support on this issue after near 6 months at least, considering its a AAA game and its a critical issue i would have hoped this would be better supported. That and how Ryujinx plays it with DLC and allows higher resolutions i find it disappointing.

**Comment by normand668** [comment] 2021-04-27 22:54
Another 2 months and no response or update.

**Comment by crono686** [comment] 2021-05-17 22:49
With Yuzu EA1691 i got the DLCs and the update running simultaniously for the first time. But it doesn't always load. The game is still crashing left and right though. Needs stability.
Thanks for your work Yuzu Dev Team

**Comment by Morph1984** [comment] 2021-06-13 14:45
The root cause of the issue has been found, and is fixed in the PR linked above

**Closed** 2021-06-16 18:03 UTC

**Comment by JustinSpedding** [comment] 2022-08-01 16:50
I am running the latest yuzu early access as of July 31, 2022, and I am experiencing this same issue again. I have all DLCs installed + update 2.1.0, and it has a high chance of soft-locking on loading screens/transitions. Perhaps there was a regression...?

Additional info:

I tried running the game with zero mods and with the 60 FPS mod. The 60 FPS mod makes the bug less likely to happen for some reason. It still happens, but less often.

**Comment by mvituriano** [comment] 2023-06-09 10:22
Maybe no more attention because it is a very old game but I am passing by the same issue as explained before. It seems random. Sometimes a second play just pass with no errors, sometimes I need to disable the update to pass. One example I don't the experience is the same for everyone but the third Zeke fight after the cutscene the loading time is infinite. I hope you have some love even being a old game.

**Comment by ThusSpokeJamie** [comment] 2023-09-22 21:14
ss
