### ISSUE TITLE
Pokemon sword Freezing

### ISSUE THREAD

**Issue by Eroc444** [yuzu-emu/yuzu#4229] opened 2020-07-03 02:22 UTC
Game freezes to 0 frames and audio is still played.

Using Yuzu 300.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4867437/yuzu_log.txt)

Happens after battles or during cutscenes.

**Comment by Amuren** [comment] 2020-07-04 18:41
I'm struggling with that problem too.

**Comment by Aris-t2** [comment] 2020-07-05 07:53
Last working yuzu build was EA 678.

**Comment by FearlessTobi** [comment] 2020-07-05 14:05
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4227.

**Closed by FearlessTobi** 2020-07-05 14:05 UTC
