### ISSUE TITLE
Yuzu won't load DLCs if a patched xci file is used with a frontend Launcher

### ISSUE THREAD

**Issue by SiriusVI87** [yuzu-emu/yuzu#8352] opened 2022-05-17 20:21 UTC
Hello everyone,

I have a problem. I want to play Xenoblade Chronicles II with Yuzu and have updated the romfile so it includes the Torna DLC. The DLC campaign can be selected on the main menu screen. If I start Yuzu and then launch the game within the Yuzu game list, everything works fine. However, when I launch the same game with the same emulator from Launchbox or EmulationStation, the Torna button isn't there.

I later found out that this happens with all xci files that have the DLCs patched into them. Updates still work, but DLCs are never loaded.

When I install the DLCs to the NAND Launchbox will load the the rom with the DLC.

On the Launchbox Forums, an experienced user advised me to contact the yuzu team. he wrote this (hopefully it helps):

"This really sounds like a command line bug in YUZU that is launching a game differently from the UI as apposed to the command line. Have you reached out to the YUZU devs or checked there forums/discord for such a bug? At the end of the day Launchbox isn't doing anything different than launching the game via the YUZU UI, its just saying hey here is a file and this is it's location. I have however seen emulation bugs that effect the command line before, dolphin had one not long ago that meant your controller didn't work when a game was launched via the command line, which obviously broke Gamecube/Wii games launched from Launchbox, but it was a emulator bug in that case that was fixed in a week or two."

**Comment by rcz01** [comment] 2022-06-18 20:04
It's been around for a very long time - I played XC II Torna year ago or so and this has been happening every second launch. First launch - no DLC, second one (after process kill) and it was all fine. I noticed this with other titles started from command line (thorugh EmulationStation and fancy scripts) too. There is something wrong with DLC detection, but only on the first launch.

**Comment by AndreAuth** [comment] 2022-08-17 08:14
I have this issue too with 2907. It worked a few weeks ago, but now no DLC or Update is loaded anymore via command line.

**Comment by Darknior** [comment] 2022-08-18 12:01
Hi
I have investigate for this bug. I have it too when i launch some games from Emulationstation. And i have it every time, not only the first time. And finally i have understand why we have this bug. Maybe it will can help the team to fix it quickly.

- When i launch a game with ES from the Yuzu rom directory "userdata/roms/switch" the game is working fine with DLC
- When i launch a game from "userdata/roms/switch/Action" the game works too but WITHOUT any update and DLC
- If i launch the same game from Yuzu in "userdata/roms/switch/Action" all is working fine with DLC

But Why ?
It's easy, it's because to launch a game from Yuzu we must add his PATH to Yuzu !!!!
And Yuzu not scanning sub directories alone. Only his root game directory. I have not added the "/Action" sub directory to Yuzu to launch my game from ES, i've do it only to launch it from the Yuzu menu, it is the only difference.

I think when we launching a game by command line, Yuzu don't analyse it, if it is not in his root directory and don't know it include UPDATES and DLC. But if we have added this directory to Yuzu he know the game and launch them.
Maybe in command line, Yuzu must start by mounting the game directory, and after, launching this game. To prevent this bug.
Or adding to Yuzu an option to scan sub directories too ?

**Comment by AndreAuth** [comment] 2022-08-18 14:34
I tried to reproduce that but i am out of luck.

- When i launch a game with ES from the Yuzu rom directory "userdata/roms/switch" the game is working fine with DLC
What command line parameter do you use from ES?

**Comment by Darknior** [comment] 2022-08-20 09:34
We have found and try to activating deep_scan", "true" but it change nothing with command line
Our command line is : 
`runCommand command: ['/userdata/system/switch/yuzu.AppImage', '-f', '-g', '/userdata/roms/switch/+Test/_test Game.xci']`

**Comment by AndreAuth** [comment] 2022-11-07 10:37
Hey, i tried it with the latest EA, still not working. Even with the command line from @Darknior,

Has anyone a workaround for this?

**Comment by NoisyFlake** [comment] 2022-11-27 14:35
Same issue here, latest EA.

**Comment by AndreAuth** [comment] 2023-01-09 16:37
On EA 3301 it seems do be fixed. @Darknior and @NoisyFlake could you comfirm this?

**Comment by Darknior** [comment] 2023-01-09 17:27
> On EA 3301 it seems do be fixed. @Darknior and @NoisyFlake and @SiriusVI87 could you comfirm this?

Hi, thanks a lot for the report, i will try it too and report to you :)

**Comment by Squall-Leonhart** [comment] 2023-06-17 08:03
This doesn't seem specifically linked to an merged XCI, but a more general issue where updates and DLC aren't applied when the emulator is executed from command line.

**Comment by lawhazl** [comment] 2023-06-17 20:06
I can confirm this also applies to nsp files as well

**Comment by XmemphistoX** [comment] 2023-08-16 20:43
Trying to use Launchbox on my couch with Yuzu and I too am running into this.

**Comment by FearlessTobi** [comment] 2023-08-17 14:01
I am unable to reproduce this issue.

**Comment by FearlessTobi** [comment] 2023-08-23 22:50
I have an idea for a potential fix, please reach out to me on Discord at `flTobi` if you want to test it.

**Comment by XmemphistoX** [comment] 2023-08-24 06:38
> I have an idea for a potential fix, please reach out to me on Discord at `flTobi` if you want to test it.

Just sent you a friend req to DM

**Closed** 2023-08-25 22:02 UTC
Labels: filesystem-issue
