### ISSUE TITLE
SDL2.dll 2.26.5 bug

### ISSUE THREAD

**Issue by lovelygfj** [yuzu-emu/yuzu#10845] opened 2023-06-19 05:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

EA-3698

### Description of Issue

After SDL2.dll replace to the latest V2.26.5, my NS Pro-compatible controller (Betop 3S). not working properly in switch pro model.
Everything is fine with SDL.dll version 2.0.18 but ever since the Yuzu EA replaced it with the newer version my controller stopped working.
when first open Yuzu, it can detected my controller with pro model. motion and keys are fine.
But after load game, with 2 mins, controller is not working, also every key are not able to be detected in setting menu.
I tested SLD2.dll, the latest version working fine is V2.0.20, after v2.0.20 every version have same problem.

### Expected Behavior

vulkan
![image](https://github.com/yuzu-emu/yuzu/assets/36533985/817c113b-207d-4d10-be91-e75cbab4d4d9)

### Reproduction Steps

![image](https://github.com/yuzu-emu/yuzu/assets/36533985/4944f057-dcd3-422f-9828-4dfc0a89cfb5)
can be detected, but all keys and motion are not working.

### Log File

![image](https://github.com/yuzu-emu/yuzu/assets/36533985/808b6dbb-9716-46f9-9428-b4b2d1ab5d70)

### System Configuration

CPU: 13900K
GPU/Driver: 4090 / latest
RAM: 64G DDR5-6400
OS: Win11 Pro

**Comment by Squall-Leonhart** [comment] 2023-06-19 11:26
Already known, duplicate of https://github.com/yuzu-emu/yuzu/issues/10786 and https://github.com/yuzu-emu/yuzu/issues/10708

**Comment by FearlessTobi** [comment] 2023-06-19 14:14
Closing as duplicate then.

**Closed by FearlessTobi** 2023-06-19 14:14 UTC

**Comment by Squall-Leonhart** [comment] 2023-06-22 19:28
This should be fixed in EA or in mainline 1477
