### ISSUE TITLE
Support the maximum amount of IAudioRenderer events (2) at the same time

### ISSUE THREAD

**Issue by GDhex12** [yuzu-emu/yuzu#2648] opened 2019-06-29 08:58 UTC
This missing implementation may cause softlocks for titles below:

* Needed for Nintendo Labo 01
* Needed for Crash Team Racing: Nitro-Fueled
* Needed for Donkey Kong Country: Tropical Freeze
* Needed for Skyrim

<meta name="titleids"  content="0100C4B0034B2000,0100F9F00C696000,0100C1F0051B6000,010028D005A3C000,01000A10041EA000">

**Comment by FernandoS27** [comment] 2019-06-29 15:19
This is actualy instances of audren service.

**Comment by Hexagon12** [comment] 2019-07-13 09:13
Fixed by #2725

**Comment by FernandoS27** [comment] 2019-07-13 20:13
You sure, you checked every game?

**Comment by manotroll** [comment] 2019-07-13 23:49
Crash Team Racing: Nitro-Fueled not rum

**Comment by fluffapparition** [comment] 2019-07-14 00:11
Someone says CTR wont work but I cant see the comment, I dont own the game so can someone here test it? @FernandoS27

**Comment by FernandoS27** [comment] 2019-07-14 00:34
In general it's better to check if the issue is the same. Just because CTR can't run it does not mean this issue hasn't been fixed. So I deleted the comment. Please let developers and people familiar with how the issue work, report on issues.

**Comment by manotroll** [comment] 2019-07-14 12:35
> 
> 
> Someone says CTR wont work but I cant see the comment, I dont own the game so can someone here test it? @FernandoS27

the CRT was running in some previous versions more frozen now not the most boot

**Comment by manotroll** [comment] 2019-07-14 14:21
https://i.imgur.com/erour5r.png
you have to clear the cache every time you open the game again, otherwise it will crash
But now you're doing well.
it's muted

**Comment by FernandoS27** [comment] 2019-07-14 15:12
@manotroll That is not realted to this issue please refrain to going offtopic and let issues be handle by devs.

**Comment by german77** [comment] 2022-08-29 04:57
Implemented in Project Andio #8545

**Closed by german77** 2022-08-29 04:57 UTC
Labels: unimplemented, hle-issue

**Comment by ZikoRenamonBirdo** [comment] 2023-02-06 22:28
good evening. The problem with crash team racing nitro fueled. it's the audio there are moments when the audio is horrible. yes indeed the playing skill is great but the audio.
There are times when it's good. other moments it starts to get bad like the game is running at 10 FPS in the audio. How long will it take until you no longer have this problem with the audio?
