### ISSUE TITLE
[Android] AC IV: Black Flag crash issue

### ISSUE THREAD

**Issue by zZardd** [yuzu-emu/yuzu#12145] opened 2023-11-24 02:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android 140

### Description of Issue

Back in v139 and previous builds, it seems pretty fine and working well. But when I updated it to v140 and opened it like usual and play it up until the choosing of the game to be played, it loads and I closed it to reopen but everytime I quit the emulation it just crashes instantly.

### Expected Behavior

If you load it up and the fps becomes to 0, it should be closed and reopen again, and it should work fine.

### Reproduction Steps

this is from v140.

https://github.com/yuzu-emu/yuzu/assets/108114549/9d4b2fd9-b0b6-40b2-8236-6264ad19f09e

### Log File

[yuzu_log.txt.old (3).txt](https://github.com/yuzu-emu/yuzu/files/13454652/yuzu_log.txt.old.3.txt)

### System Configuration

CPU: Snapdragon 778g
GPU/Driver: Adreno 642L / Turnip Driver 24.0.0 Revision X
RAM: 8 GB
OS: Android 13

**Comment by liamwhite** [comment] 2023-11-24 03:03
I see no evidence of a crash here? The video shows the expected behavior - when closing the game a normal shutdown occurs.

**Comment by zZardd** [comment] 2023-11-24 03:15
> I see no evidence of a crash here? The video shows the expected behavior - when closing the game a normal shutdown occurs.

Yes, but before on v139 and the previous builds, when you 'exit emulation'/close the game, it should've been in the yuzu home menu page only. But as you can see on the recording, it crashed - as opposed to be in just in the home menu of yuzu. 
- and when you open it again, it will go back to choosing the game just like in the recording, instead of opening the 'black flag' intro which what usually happens in previous builds.

**Comment by zZardd** [comment] 2023-11-24 03:27
this is what I get from the previous versions, and I think what it supposed to be, I guess. Credits: EmuGaming ID

https://github.com/yuzu-emu/yuzu/assets/108114549/5cab181b-5640-4ea5-ae54-12ba52dab243

**Comment by boludoz** [comment] 2023-11-24 05:15
Because of how it crashes and even more so when loading, it may be something related to memory.

**Comment by zZardd** [comment] 2023-11-24 05:30
> Because of how it crashes and even more so when loading, it may be something related to memory.

I don't know. It was working fine on previous builds tho

**Comment by boludoz** [comment] 2023-11-24 18:09
![image](https://github.com/yuzu-emu/yuzu/assets/11653030/55edcbc9-3708-40af-aef6-026f2d4c22f4)
Try activating that and then tell me.

**Comment by liamwhite** [comment] 2023-11-25 02:08
Fixed in 141

**Closed by liamwhite** 2023-11-25 02:08 UTC
