### ISSUE TITLE
Pokemon Sword: Random crash while in battle

### ISSUE THREAD

**Issue by geft** [yuzu-emu/yuzu#6063] opened 2021-03-13 03:42 UTC
I enabled extended/verbose logging.

```
[   0.790734] Frontend <Info> yuzu\main.cpp:GMainWindow:245: yuzu Version: yuzu 561             . | HEAD-mainline-636-4826-g6d5436df9
[   0.790742] Frontend <Info> yuzu\main.cpp:GMainWindow:260: Host CPU: AMD Ryzen 7 4800H with Radeon Graphics          | AVX2 | FMA
[   0.790772] Frontend <Info> yuzu\main.cpp:GMainWindow:262: Host OS: Windows 10 (10.0)
[   0.790784] Frontend <Info> yuzu\main.cpp:GMainWindow:264: Host RAM: 15.37 GB
[   0.790784] Frontend <Info> yuzu\main.cpp:GMainWindow:266: Host Swap: 5.50 GB
```

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/6134124/yuzu_log.zip)

**Comment by FearlessTobi** [comment] 2021-04-02 14:04
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/6003.
There are also other issues for this problem made already.

**Closed by FearlessTobi** 2021-04-02 14:04 UTC
