### ISSUE TITLE
Web Applet causing crash in smash ultimate

### ISSUE THREAD

**Issue by Crysyf** [yuzu-emu/yuzu#4131] opened 2020-06-20 20:45 UTC
Whenever I pick the characters and the game is about to start a window pops up and the web Applet starts to load and goes to 75 percent and ends with an error message. Pressing enter makes it go away but the game crashes soon after.

**Comment by FearlessTobi** [comment] 2020-06-20 20:50
Duplicate of https://github.com/yuzu-emu/yuzu/issues/3615.

**Closed by FearlessTobi** 2020-06-20 20:50 UTC
