### ISSUE TITLE
Android street of rage 4 upside down

### ISSUE THREAD

**Issue by JhonfaRaccoon** [yuzu-emu/yuzu#11251] opened 2023-08-09 22:13 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 65a0

### Description of Issue

the game open perfect with amazing FPS but upside down...The same errors have already appeared, but there has been no solution.

### Expected Behavior

that it works correctly, that the image does not look upside down

### Reproduction Steps

![WhatsApp Image 2023-08-09 at 5 10 13 PM](https://github.com/yuzu-emu/yuzu/assets/91033800/0f822f67-5613-48f2-8318-40f8e34645c8)

### Log File

there is no log, because the game enters well, only that the image is seen upside down

### System Configuration

CPU: Snapdragon 845
GPU/Driver: V615.37 / V615.50
RAM: 8gigas
OS: Android

**Comment by FearlessTobi** [comment] 2023-08-09 22:21
Duplicate of https://github.com/yuzu-emu/yuzu/issues/8839.

**Closed by FearlessTobi** 2023-08-09 22:21 UTC
