### ISSUE TITLE
Super Smash Bros Ultimate crashing when starting a fight in Adventure Mode

### ISSUE THREAD

**Issue by Mortus06** [yuzu-emu/yuzu#7863] opened 2022-02-07 18:25 UTC
The game is super smooth, but everytime I try to start a brawl in Adventure Mode a black screen pops up, followed by the emulator crashing.
I'm running it with the latest Switch firmware, on the latest update version and all DLCs installed.

**Comment by lat9nq** [comment] 2022-02-08 09:44
Duplicate of #6898

**Comment by ken7877** [comment] 2022-02-08 15:35
> Duplicate of #6898

12700
GTX980
ddr4 3000

**Closed** 2022-02-09 00:09 UTC
