### ISSUE TITLE
Xenoblade Chronicles 2 Vulkan Rendering issue

### ISSUE THREAD

**Issue by RaienryuuNoNatsu** [yuzu-emu/yuzu#7435] opened 2021-11-25 23:34 UTC
**EDIT (28th of September 2021):** It's a long thread, all Resolution Scaler bugs assumptions are actually a Vulkan issue.

Hey there! As per title, I'm experiencing graphical glitches and possibly a major bug. First, my system specs:

OS: Windows 10 Pro 20H2 Build 19042.1348
CPU: Intel Core i7 8700K
RAM: Dual channel 16GB
GPU: Gigabyte Nvidia GTX 1060 6GB Windforce (Driver v472.12, apparently the last known working version as per FAQs)

Yuzu EA 2237, following my settings for Xenoblade Chronicles 2:
![immagine](https://user-images.githubusercontent.com/31509027/143507172-7bef5533-fa39-40ef-84d6-6cd358c23480.png)

OpenGL (the Scaler is irrelevant here)
![immagine](https://user-images.githubusercontent.com/31509027/143507204-c9362d2e-8da6-4637-966a-e763f7db50fa.png)

Vulkan (the Scaler is irrelevant here as well for the time being)
![immagine](https://user-images.githubusercontent.com/31509027/143507238-0bff0235-b0f2-4c95-b564-120bcada6039.png)

![immagine](https://user-images.githubusercontent.com/31509027/143507268-71c36ad1-b228-49d9-b84b-53dabc4bb8f0.png)

I also have the Supersampling mod, it's in this folder:
> %YUZU_DIR%/load/<title_id>/exefs/2.1.0.pchtxt

I thought this could be the issue, as I read 2.1.0 and the JP version I have goes up to 2.0.2, but this bug also happened before I dropped the mod in there.

I've come back to Xenoblade after quite some time, so I don't remember if any of those settings should remain unchecked under Vulkan with an Nvidia GPU, but it'd drop my FPS instead. The present issue came up with the Scaler.

So, like the opened issue #7400, I have lines appearing as well.

OpenGL/Scaleforce/FXAA
![immagine](https://user-images.githubusercontent.com/31509027/143505846-ae9cf854-982c-4a89-b788-a4f477735910.png)

OpenGL/Scaleforce/No FXAA
![immagine](https://user-images.githubusercontent.com/31509027/143505914-c91d1f1f-8887-4fc3-b04a-45363c936278.png)

So, this apparently has nothing to do with FXAA. At this point, if I try Vulkan, the fun begins. 

Vulkan/Scaleforce/FXAA
![immagine](https://user-images.githubusercontent.com/31509027/143506287-ce52c0c5-8529-4ca1-9aa6-6cad7f1942d7.png)
![immagine](https://user-images.githubusercontent.com/31509027/143506394-2eeb9a83-a548-4ca4-8559-c11db4e48eae.png)
![immagine](https://user-images.githubusercontent.com/31509027/143506436-c63d3501-684a-4781-9ff3-fca848a2c2aa.png)

So, we still have lines appearing, like in the other issue, but it also breaks the rest completely. I don't know if OpenGL is still the go-to with Nvidia GPUs, but I wanted to try Fidelity, which is Vulkan only. So, about Fidelity.

Vulkan/Fidelity/FXAA
![immagine](https://user-images.githubusercontent.com/31509027/143506512-bfcc982f-be26-4ebc-af19-7bdd89dcfb10.png)

While still being present, it feels like in the outside areas it's apparently less severe than indoors (at least the sky during the day). So, here are a couple screens at native resolution and no FXAA.

Out of easiness, I went 1x Nearest, ignore its typical result, it's more about that bright stuff.
![immagine](https://user-images.githubusercontent.com/31509027/143506722-7e98b666-db83-4640-9ef5-6d8ecf1b9c64.png)
![immagine](https://user-images.githubusercontent.com/31509027/143506739-994c7693-014b-4eb9-aef7-25ce4366fe7e.png)

Lines gone, saturation back to normal. But this isn't the end of it, because this doesn't happen everywhere.

Vulkan/2x Fidelity/FXAA
![immagine](https://user-images.githubusercontent.com/31509027/143506941-cf6c629e-ebe9-4893-b138-add1f244f74f.png)

OpenGL/1x Nearest/No FXAA
![immagine](https://user-images.githubusercontent.com/31509027/143507029-aa74b67a-56e2-4466-94c6-00d952b41c48.png)

Unless my eyes are playing tricks on me, this looks fine. Unfortunately I had to trim it because it was too big filesize wise.

Conclusions: So first and firemost, main menu and obviously FMVs aren't afflicted by this issue. Why is the tutorial fight fine is beyond me, but I haven't gone past the port myself, so I can't say for sure if this is a constant. However, by the look of it, any indoor area could possibly be afflicted. The problem comes outside, and I could eventually explore further or anyone else could pitch in and add details and screenshots. I'm gonna leave the save here so you can check the area without having to do the tutorial.

[0100F3400332C000.zip](https://github.com/yuzu-emu/yuzu/files/7605501/0100F3400332C000.zip)

**Comment by FernandoS27** [comment] 2021-11-28 11:28
Please don't mix unique Vulkan issues with scaler issues.

**Comment by RaienryuuNoNatsu** [comment] 2021-11-28 16:11
Oh, you're right. I'm gonna change the title of the issue. I don't remember this issue from older releases, I'm pretty sure I saw this fixed at some point, that's why I didn't double check. But does this happen only on Nvidia GPUs?

**Comment by Icenowy** [comment] 2021-11-29 19:26
I have an AMD-NVIDIA dual GPU setup, so I tested it on AMD RADV ACO, and the same issue happens.

**Comment by RaienryuuNoNatsu** [comment] 2021-11-29 21:41
I went to check on YouTube some people testing Vulkan on the RTX series 3'000, but I don't see this issue under Vulkan.

Like, this is Project Hades on a 3080 using Vulkan.
[https://www.youtube.com/watch?v=Qb-C0ZloUMo](url)

And this is Fastmem on yet another 3080, again using Vulkan. Obviously the Fidelity 4K upscale was done during editing.
[https://www.youtube.com/watch?v=e4lhbmNxdcY](url)

I didn't go past that part of the game on the emulator myself, and the beginning was fine. So I'm curious if these YouTubers knew and skipped it, and if this issue happens only there.

**Comment by LeiteLixo** [comment] 2021-12-01 01:56
When using Vulkan and an AMD GPU the game is basically unplayable, black lines everywhere.
Only happens on Windows, Linux still has glitches, but not this one.


![xeno2](https://user-images.githubusercontent.com/92181138/144157500-ce56d1bb-f016-4232-a1c8-b150ad951084.PNG)

**Comment by RaienryuuNoNatsu** [comment] 2021-12-01 13:55
That's weird. In my post before yours, the 3rd YouTube link has a sample on an AMD GPU and doesn't have those issues. Xenoblade requires specific settings to work. You can check my first post, that's what I use and that I found on YouTube. See if that helps you.

**Comment by FernandoS27** [comment] 2021-12-01 16:16
AMD's GPU's issue is not a yuzu issue. It's an AMD driver issue in which Transform Feedback is entirely broken:  https://github.com/GPUOpen-Drivers/AMDVLK/issues/251 that's the driver issue.

**Comment by LeiteLixo** [comment] 2021-12-01 16:35
This is a glitch with the grass textures, in the video it only shows the port area, that area does not have the black lines.

https://user-images.githubusercontent.com/92181138/144274543-2e2465ab-71f4-4364-ba99-163cb28151f0.mp4

**Comment by RaienryuuNoNatsu** [comment] 2021-12-02 13:12
Gotcha. I remember hearing about such bugs some time ago, but I mostly looked up Nvidia setups, considering I myself have one. We'll see what the devs can do about this. Eventually, a big update should fix the issue altogether.

**Comment by german77** [comment] 2021-12-07 03:29
Duplicate of #5007

**Closed by german77** 2021-12-07 03:29 UTC
