### ISSUE TITLE
Super Smash Bros Ultimate Crash 

### ISSUE THREAD

**Issue by giancarlosxlr** [yuzu-emu/yuzu#7908] opened 2022-02-17 12:45 UTC
Hello, I have a bug for a few months, I always update to new versions and it keeps happening, basically yuzu crash playing Super smash bros ultimate after a few games, it keeps varying, sometimes it crashes after playing 2 or 3 5min games , happens in the middle of the game or sometimes in the loading of the game, I've tested it in practically all versions of the yuzu since the middle of last year, this happens on friends computers too, usually in smash mode

NVIDIA® GeForce® GTX 1050Ti 4 GB GDDR5
16 GB (1x16GB) RAM DDR4
Intel® Core™ i7-8750H 2.2 GHz  / 4.1 GHz
Vulkan/Open GL

Logs:

[ 177.456543] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 177.458068] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 177.459638] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 177.461334] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 177.464092] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 177.466829] Service.NVDRV <Warning> core\hle\service\nvdrv\devices\nvmap.cpp:IocParam:202: (STUBBED) called type=1
[ 177.478243] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x00000015530A1D28 = 0x0000000000000000
[ 177.478253] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x00000015530A1F3B = 0x0000000000000000
[ 177.478258] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x00000015530A1D29 = 0x0000000000000000
[ 177.478263] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x00000015530A1D2A = 0x0000000000000000
[ 177.478268] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x00000015530A1F3A = 0x0000000000000000
[ 177.478273] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x00000015530A1F39 = 0x0000000000000000
[ 177.478279] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x00000015530A1D2B = 0x0000000000000000
[ 177.478283] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write8 @ 0x00000015530A1F38 = 0x0000000000000000
[ 177.478289] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1D28 = 0x0000000000000000
[ 177.478294] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1F38 = 0x0000000000000000
[ 177.478299] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1D2C = 0x0000000000000000
[ 177.478305] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1D30 = 0x0000000000000000
[ 177.478310] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1F30 = 0x0000000000000000
[ 177.478314] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1F34 = 0x0000000000000000
[ 177.478320] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1D34 = 0x0000000000000000
[ 177.478324] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1D38 = 0x0000000000000000
[ 177.478329] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1D3C = 0x0000000000000000
[ 177.478333] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1D40 = 0x0000000000000000
[ 177.478338] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1F20 = 0x0000000000000000
[ 177.478343] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1F24 = 0x0000000000000000
[ 177.478347] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1F28 = 0x0000000000000000
[ 177.478352] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write32 @ 0x00000015530A1F2C = 0x0000000000000000
[ 177.478359] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D40 = 0x0000000000000000
[ 177.478360] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D48 = 0x0000000000000000
[ 177.478364] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D50 = 0x0000000000000000
[ 177.478365] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D58 = 0x0000000000000000
[ 177.478370] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D60 = 0x0000000000000000
[ 177.478371] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D68 = 0x0000000000000000
[ 177.478376] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D70 = 0x0000000000000000
[ 177.478377] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D78 = 0x0000000000000000
[ 177.478383] HW.Memory <Error> core\memory.cpp:operator ():522: Unmapped Write64 @ 0x00000015530A1D80 = 0x0000000000000000

**Comment by german77** [comment] 2022-02-17 17:48
Duplicate of #5822

**Closed by german77** 2022-02-17 17:48 UTC
