### ISSUE TITLE
Unimplemented Service

### ISSUE THREAD

**Issue by niko1point0** [yuzu-emu/yuzu#2949] opened 2019-10-06 06:20 UTC
I ran a Hello World NRO, and noticed something in the log. Normally in this homebrew, you can press the '+' button to exit, but when I press that button in the emulator, I get "Assertion Failed" messages in the log.

Technically, this program still does exactly what it is supposed to do, which is print Hello World, but it wanted to point it out anyways in case somebody wanted to fix it

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3694000/yuzu_log.txt)

[hello-world.zip](https://github.com/yuzu-emu/yuzu/files/3694001/hello-world.zip)

https://github.com/switchbrew/switch-examples/blob/master/graphics/printing/hello-world/source/main.c

**Comment by ReaperOfSouls1909** [comment] 2019-10-06 06:22
DeactivateNpad is already reported #2663

**Comment by Hexagon12** [comment] 2019-10-06 06:26
Duplicate of #2663

**Comment by niko1point0** [comment] 2019-10-06 06:27
Oh, sorry

**Closed by Hexagon12** 2019-10-06 06:26 UTC
