### ISSUE TITLE
Xenoblade Chronicles 2 Memory Leak

### ISSUE THREAD

**Issue by ItsJustMoe** [yuzu-emu/yuzu#8112] opened 2022-03-29 05:43 UTC
I've been experiencing a memory leak in Xenoblade Chronicles 2. When I start the game up it starts at 10.5 GB used, and it slowly rises in utilization till it reach max utilization then promptly crashes right after. Only happens in XC2, and only started after updating to Yuzu 963 was perfectly fine beforehand. Wondering if theres a fix for this already? or if theres a better place to report this let me know.

Here is my configuration/specs and the log.

Yuzu version: Yuzu 967
CPU accuracy: Auto
Video API: OpenGL
Video Accuracy: Extreme
Resolution: 1x
Window Adapting Filter: Bicubic
AAM: FXAA
Processor: Intel i5-9300h
Graphics Card: Nvidia gtx 1650 mobile
Memory: 24 GB
Virtual Memory: 12 GB

**Note:**
It happens with any combination of settings this is just the one I mainly use.
**Log redacted due to pirated content which we don't support here**

**Comment by goldenx86** [comment] 2022-03-29 06:23
Confirmed to be caused by #8080

**Comment by G-Spawn** [comment] 2022-03-29 07:48
Closing issue as we don't support pirated content here.

**Closed by G-Spawn** 2022-03-29 07:48 UTC
