### ISSUE TITLE
[Enhancement] Support for Nvidia image scaler

### ISSUE THREAD

**Issue by LifeIsStrange** [yuzu-emu/yuzu#8062] opened 2022-03-21 21:11 UTC
it is complementary to DLSS and probably does not require motion vectors.
I know that FSR is already supported but this alternative has the potential to offer better results https://github.com/NVIDIAGameWorks/NVIDIAImageScaling

edit: I expect to see better improvements from FSR 2.0 or intel XeSS so this issue is lower priority

**Comment by BreadFish64** [comment] 2022-03-21 21:32
Duplicate of #7921

**Closed** 2022-03-21 21:39 UTC
