### ISSUE TITLE
Mary Skelter 2: The Game works but does not render

### ISSUE THREAD

**Issue by HtronFerns** [yuzu-emu/yuzu#4824] opened 2020-10-24 16:02 UTC
The game works works perfectly fine... i am able to hear clear audio, and use the key bindings.
But the catch is, the screen stays black and shows no signs of rendering

Specs: GTX 1050ti
           Intel Core i7-7700
           Windows 10
           8gb ddr4 Ram
           64-bit Operating System

![412](https://user-images.githubusercontent.com/73397077/97086337-285ac280-1655-11eb-87af-cb529a6507ac.PNG)

**Comment by HtronFerns** [comment] 2020-10-24 16:05
Log file here..
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5433164/yuzu_log.txt)

**Comment by G-Spawn** [comment] 2020-10-24 16:15
Host Swap: 8.50 GB 
Make a Larger pagefile. Beyond that idk.

**Comment by HtronFerns** [comment] 2020-10-25 07:09
> Host Swap: 8.50 GB
> Make a Larger pagefile. Beyond that idk.
How do i do that? im prettu much clueless...

**Comment by G-Spawn** [comment] 2020-10-25 11:41
Lookup videos for that from BSOD or join the discord server to ask for help. It's the first pinned message in the support channel.

**Comment by G-Spawn** [comment] 2020-10-25 11:42
Most Cut scenes dont load in Mainline anyways. Wait until it does.

**Comment by KingKrouch** [comment] 2021-07-28 21:20
I can confirm with the latest Yuzu build (at least when running on Linux), that the game doesn't have the black screen issue anymore, and can run around 100FPS pretty consistently on a Ryzen 5 5600X and GTX 1060.

**Comment by G-Spawn** [comment] 2021-07-29 21:02
This issue is likely worth closing due to it being corrected now. @HtronFerns  please test and consider such.

**Closed** 2021-07-30 01:39 UTC
