### ISSUE TITLE
I'm stuck in the first scene with hop

### ISSUE THREAD

**Issue by kristianlentino** [yuzu-emu/yuzu#3149] opened 2019-11-21 20:21 UTC
![image](https://user-images.githubusercontent.com/23060554/69373577-695b9180-0ca4-11ea-9c3e-5a01510087d1.png)

Hi, i was starting to play but in the first scene near the main character house, when i talk to hop and see the sheep use takle it blocks but the sound seems to working, so i can't understand why the screen is blocked but the sound goes on. 
Thank you.

**Comment by Hexagon12** [comment] 2019-11-21 20:21
Duplicate of #3128

**Closed by Hexagon12** 2019-11-21 20:21 UTC
