### ISSUE TITLE
Super Smash Bros. Ultimate - svcBreak on various ingame actions

### ISSUE THREAD

**Issue by theincredibleplayer** [yuzu-emu/yuzu#2791] opened 2019-08-19 14:03 UTC
Here is a list of actions that causes Super Smash Bros. Ultimate to softlock:

* Interrupting the first few frames of a jump with an attack
* Moving on land
* Landing while attacking
* Doing damage to someone in stamina mode after critical health when the characters start emitting smoke (the poison flower also softlocks; in stocks and time it doesn't softlock if you hit)
* Landing while in the middle of an animation other than falling (includes the knockback animation)
* Unpausing the training pause menu
* Charging a smash attack (in the mii sound changing menu smash attacks don't softlock ![Image #1](https://cdn.discordapp.com/attachments/472575665334648833/610612426785816578/Screenshot_96.png) ![Image #2](https://cdn.discordapp.com/attachments/472575665334648833/610612347769454603/Screenshot_88.png)
* Respawning in stock battles, squad strike, or training and getting out of the invincibility platform ![Image 3](https://cdn.discordapp.com/attachments/502096661850488832/612794954082680834/unknown.png)
* Grabbing the ledge
* Spot dodging, rolling, air dodging, or anything that involves invincibility frames (shielding doesnt softlock; attacks that have invincibility frames softlock)
* Miis cause a softlock before the match starts if on critical ealth (over 100% or under 50 stamina)
* Throwing characters
* Mario's fireball softlocks only if thrown twice
* Doing any knockback (softlocks on the frame when the knockback is applied)
* Hitting someone at 100% damage or more

Using Canary 2523, all testing was done on Battlefield or Big Battlefield with the following save:

[save_data.zip](https://github.com/yuzu-emu/yuzu/files/3516246/save_data.zip)

<meta name="titleids"  content="01006A800016E000">

**Comment by Benedani** [comment] 2020-02-29 12:31
Let me make an updated and somewhat cleaned up list 6 months later (tested on EA 245), feel free to edit the OP:

- Moving on land - interestingly, slightly tilting the control stick to slowly walk works fine... until the character's foot lands on the ground
- Doing damage to someone after critical health (20hp stamina or 100% stock battles, when the characters start emitting smoke)
- Interrupting the first few frames of a jump with an attack
- Landing while in the middle of an animation other than falling (includes the knockback animation and attacking)
- Unpausing the training pause menu
- Using a chargeable smash attack
- ~~Not skipping the intro cutscene~~
- ~~Waiting until the tutorial cutscene and skipping that~~ Somewhere into the tutorial cutscene, a match starts to load with the tips shown, but it never actually loads (the loading icon just spins, and it's technically a softlock)
- Spot dodging, rolling, air dodging, grabbing the ledge, respawning and getting off the invincibility platform, or anything else that involves invincibility frames (shielding doesnt softlock; attacks that have invincibility frames softlock)
- ~~Throwing~~ Grabbing characters
- ~~Mario's fireball softlocks only if thrown twice~~
- ~~Doing any knockback (softlocks on the frame when the knockback is applied)~~ 
- ~~Backing out of Sounds menu~~ I also used to experience this softlock on newer builds, but now My Music works fine too

And I'd like to add:

- Jumping more than 2 times in a row in the air as Kirby, maybe other characters too who work similarly
- Fox and Kirby's neutral B
- After the victory screen (you have to win a 1 stock battle so the respawn platform doesn't softlock first due to invincibility frames)

Also, would like to mention #3255. What exactly happened there?

**Comment by theincredibleplayer** [comment] 2020-02-29 20:04
i need to close that issue and open a new, more useful one with all the graphical bugs in smash

**Comment by Morph1984** [comment] 2020-03-27 07:00
#3563 Fixes some of the softlocks, need to verify if all of the above are fixed

**Comment by Benedani** [comment] 2020-03-27 09:25
Indeed, looks like all of the following have been fixed:

- Different forms of interaction with the ground - walking, dodging, rolling, grabbing the ledge
- Doing damage to someone after critical health (20hp stamina or 100% stock battles, when the characters start emitting smoke)
- Interrupting the first few frames of a jump
- Landing while in the middle of an animation other than falling (includes the knockback animation and attacking)
- Unpausing the training pause menu
- Using a chargeable smash attack
- Somewhere into the tutorial cutscene, a match starts to load with the tips shown ~~but it never actually loads (the loading icon just spins, and it's technically a softlock)~~ it loads now, with a softlock
- Respawning in general
- Grabbing characters
- Becoming a Kirby rock
- Fox and Kirby's neutral B
- Invincibility frames
- After the victory screen


Also, there's a huge graphical improvement. Just need some performance improvements and it should become playable! Didn't test World of Light though.

**Comment by theincredibleplayer** [comment] 2020-03-27 19:48
all of the ones listed are fixed by #3563 will close the issue

**Comment by Hexagon12** [comment] 2020-03-27 21:25
The PR which fixes the issue isn't merged yet.

**Closed** 2020-04-03 14:14 UTC
Labels: bug

**Comment by DragonShifterYT** [comment] 2020-11-06 00:19
ssbb yuzu download?
