### ISSUE TITLE
Ability to remove data [UPDATES/DLCs] after game has been deleted on Android 

### ISSUE THREAD

**Issue by tommy-sorce** [yuzu-emu/yuzu#12910] opened 2024-02-04 07:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Ability to remove data [UPDATES/DLCs] after game has been deleted from the game directory on Android

### Why would this feature be useful?

You can delete data now, but only when a game icon is still present if you deleted it, then you have to export saves, delete yuzu, import saves and add current games.

**Comment by FearlessTobi** [comment] 2024-02-04 15:11
Duplicate of https://github.com/yuzu-emu/yuzu/issues/12239.

**Closed by FearlessTobi** 2024-02-04 15:11 UTC
Labels: request
