### ISSUE TITLE
Penny's Big Breakaway - run in black screen 

### ISSUE THREAD

**Issue by brujo5** [yuzu-emu/yuzu#13111] opened 2024-02-21 19:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Android v259

### Description of Issue

The game runs with a screen but I can hear the game audio. Tested with turnip and Qualcomm drivers

![Screenshot_20240221-122044_yuzu](https://github.com/yuzu-emu/yuzu/assets/4172898/f7d2c3d3-7a8a-44b8-a7ef-5d57139d9d4b)

### Expected Behavior

the game should look without a black screen

### Reproduction Steps

Just launch the gale

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14364108/yuzu_log.txt)

### System Configuration

CPU: 7+gen2
GPU/Driver: Adreno 725, turnip, Qualcomm driver
RAM: 12gb
OS: android 14

**Comment by liamwhite** [comment] 2024-02-21 19:29
Duplicate of #13107
Please search for existing issues before you check the box saying you have searched for them

**Closed by liamwhite** 2024-02-21 19:29 UTC
