### ISSUE TITLE
Mario Party Superstars Eatsa Pizza Broken

### ISSUE THREAD

**Issue by Codyjames34526** [yuzu-emu/yuzu#7300] opened 2021-11-06 13:30 UTC
Pizza appears broken with interlaced lines and AI doesn't seem to work properly.
![image](https://user-images.githubusercontent.com/47513920/140611468-7a8f8d44-cdf5-4d9f-853f-472ffe0ce85a.png)

**Comment by FernandoS27** [comment] 2021-11-06 13:40
this is a duplicate of the general mario party bugs issues.

**Closed by FernandoS27** 2021-11-06 13:40 UTC
