### ISSUE TITLE
Hyrule Warriors Age of Calamity - Multicore - Char Select Screen FPS DROP to 0

### ISSUE THREAD

**Issue by AizerMortenort** [yuzu-emu/yuzu#5001] opened 2020-11-25 22:08 UTC
The Game freezes whenever i enter CHAR SELECT screen and char shows up 
I have to disable FAST GPU and Multicore in order to make it work but this looses OVERALL FPS 

PC 
AMD RYZEN 2700X
NVIDIA RTX 2070 SUPERGAMING OC
16 GB RAM
WIN 10
Yuzu 1146

**Comment by Chocobobobo** [comment] 2020-11-28 23:28
Current workaround is to move your save to ryujinx, make all your changes related to characters / weapons / equipment, save, and then transfer back to yuzu :)

**Comment by ReinUsesLisp** [comment] 2020-11-29 19:42
Closing as duplicate of #4871.

**Closed by ReinUsesLisp** 2020-11-29 19:42 UTC
