### ISSUE TITLE
[Android] Super Mario 3D All-Stars - endless loading screen after picking a game

### ISSUE THREAD

**Issue by SkySlider** [yuzu-emu/yuzu#11818] opened 2023-10-19 11:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-105

### Description of Issue

None of the 3 games load after picking them in the initial menu.

### Expected Behavior

-

### Reproduction Steps

-

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13041928/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 870
GPU/Driver: Adreno 650 / Mesa Turnip Adreno Driver v23.3.0-devel + Vulkan 1.3.267. System default driver also shows the same behavior.
RAM: 8 GB
OS: MIUI 14 / Android 13

**Comment by XKnightRiderX** [comment] 2023-11-29 08:11
I can confirm that I have the same problem

**Comment by prkodi** [comment] 2023-12-26 21:53
I read some files nsp downloaded are corrupt. I also downloaded ones and them won't work. Maybe yours it's one of them. If you bought limited edition xci you haven't any problem after update.

**Comment by pakrett** [comment] 2024-01-07 10:43
I got it working, you need to extract the ncas from the nsp/xci and use them like standalone games.
I think that the issue is that all 3 games are 32bit so they can't run on nce while the menu can so the nsp starts well with nce but do not switch to jit when loading the games and so, freeze.
Edit: I though it was the only issue and maybe you can force the nsp to run dynarmic instead of nce but no the games don't load like that so extract the nsp and launch them like 3 different game as an nca is the only way to load them.
Mario Galaxy is 028b1462f115cfb4dad1badc3afe6e70.nca

**Comment by prkodi** [comment] 2024-01-07 20:59
How can I do on my android device? Thanks.

**Comment by me7** [comment] 2024-02-02 07:16
1.  You need Rom(Super Mario 3D All-Stars.nsp), prod.keys, title.keys and [NSTool](https://github.com/jakcron/nstool) to extract the file
2. put NSP and prod.keys together and title.keys in $HOME/.switch
3. `nstool -k prod.keys OUTDIR ROM.nsp`
 
here's 3 output files you need
- mario galaxy 33b3271907e378d90579161a24261b9b.nca
- mario sunshine 94b649803873ec7e230ccc709227377f.nca
- mario 3d 5977df9d4848858cbde157c6723dd1de.nca

**Comment by liamwhite** [comment] 2024-02-05 19:14
fixed by #12824

**Closed by liamwhite** 2024-02-05 19:14 UTC
Labels: android
