### ISSUE TITLE
Remember "Limit Speed"

### ISSUE THREAD

**Issue by Anuskuss** [yuzu-emu/yuzu#11865] opened 2023-10-23 23:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Save the state of "Limit Speed" (aka "Unlock FPS"). Or at least per game.

### Why would this feature be useful?

Some games require unlocked framerate. Most settings can be used per-game while this one can not (which is kinda weird).

**Comment by german77** [comment] 2023-10-23 23:47
No game require unlocked framerate. Unlocked framerate at boot causes crashes.

Duplicate of #10334

**Closed by german77** 2023-10-23 23:47 UTC

**Comment by Squall-Leonhart** [comment] 2023-10-24 20:30
This is now the third instance of this "Request" that has been posted by this user, for an issue that was already fixed.
