### ISSUE TITLE
Bayonetta 3 - Enemies fogs are invisible

### ISSUE THREAD

**Issue by yohoman123** [yuzu-emu/yuzu#9290] opened 2022-11-21 17:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1234

### Description of Issue

The enemies fog is invisible, in the whole game.

Original:
![Untitled-1](https://user-images.githubusercontent.com/58602721/202920101-7bcd2acc-ca02-49f5-aae5-add4129bd2ed.png)

Yuzu:
![Untitled-2](https://user-images.githubusercontent.com/58602721/202920105-cdc5d41f-6497-4a12-9dcd-d04c692c37ee.png)

### Expected Behavior

As original.

### Reproduction Steps

?

### Log File

Empty

### System Configuration

CPU: Core i9-8950HK
GPU/Driver: 3060
RAM: 32
OS: W 11

**Comment by BSoDGamingYT** [comment] 2022-11-21 17:59
Duplicate of https://github.com/yuzu-emu/yuzu/issues/9150. Closing

**Closed by BSoDGamingYT** 2022-11-21 17:59 UTC
