### ISSUE TITLE
LAYTON’S MYSTERY JOURNEY: Katrielle and the Millionaires’ Conspiracy - Deluxe Edition - video playback is jerky

### ISSUE THREAD

**Issue by klz-fc** [yuzu-emu/yuzu#11089] opened 2023-07-14 18:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1495

### Description of Issue

Using Version 1.0.0

On the Steam Deck, video plays as expected.

Under my currrent Windows configuration, the video is choppy. 

### Expected Behavior

All videos, including the intro video should play normally as expected after the updated code for issue #10283[https://github.com/yuzu-emu/yuzu/pull/10283]. 

Yuzu:
https://github.com/yuzu-emu/yuzu/assets/103147197/e394f1ad-207f-4d56-b14c-aa30bb1381c4

Normal:
https://github.com/yuzu-emu/yuzu/assets/103147197/241f10b1-9e71-481b-a45d-5b0ade4894ce

### Reproduction Steps

This is from the intro, so no save file needed. 
I only started the game and wiated until partway through the video playback before stopping it.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12053141/yuzu_log.txt)

### System Configuration

CPU: Intel Core i9 12900H
GPU/Driver: NVIDIA GeForce RTX 3070 Ti Laptop GPU 8Gb/ nVidia 31.0.15.3179
RAM: 32 Gb
OS: Windows 11 Pro 22H2 Build 22621.1992

Yuzu settings in case I messed something up:
![image](https://github.com/yuzu-emu/yuzu/assets/103147197/b8e72db0-1be3-4240-82d9-f60ca40e5cba)
![image](https://github.com/yuzu-emu/yuzu/assets/103147197/0817666c-35e6-4e45-b8f2-31bd12956d19)
![image](https://github.com/yuzu-emu/yuzu/assets/103147197/911af1f8-557e-4df3-9649-65dab6a35b2f)

**Comment by danilaml** [comment] 2023-07-16 02:48
Just to test - what if you set NVDEC emulation to CPU? Also, can you generate log with your current settings, but log filter set to `*:Debug` (in General->Debug)?

**Comment by klz-fc** [comment] 2023-07-16 03:25
That worked! Smooth playback now using CPU for NVDEC:
![Screenshot 2023-07-15 231832](https://github.com/yuzu-emu/yuzu/assets/103147197/bb3603e6-f0f2-47f0-b7f3-2cc198fa2eb1)

Just in case it's useful, logs set to *
![Screenshot 2023-07-15 231931](https://github.com/yuzu-emu/yuzu/assets/103147197/affc63a5-221f-4dfb-84ae-ec99b5704851)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12063193/yuzu_log.txt)

Leaving this open for you if you want to investigate further or please close it if you consider this to be the workaround for others to use.

Thank you again!

**Comment by danilaml** [comment] 2023-07-16 13:20
@klz-fc , Thanks! I have an idea of what might be happening, although I don't HW to test it.
Can you please test this build (just rename the yuzu.exe in your folder to yuzu-backup.exe or something and place this one here, you can return back the original exe after the test)?
Before the test, don't forget to set the NVDEC option to GPU decode (default) back again. And set the log filter to `*:Debug` (`:Debug` part is important).
[yuzu.zip](https://github.com/yuzu-emu/yuzu/files/12064132/yuzu.zip)

**Comment by klz-fc** [comment] 2023-07-17 13:48
Glad to help!

Game setting set back to default (GPU) and adjusted the Debug filter to *:Debug
![Screenshot 2023-07-17 094328](https://github.com/yuzu-emu/yuzu/assets/103147197/9a3e7e8c-fc0f-4587-a170-9e12e3b6e21e)
![Screenshot 2023-07-17 094417](https://github.com/yuzu-emu/yuzu/assets/103147197/a1f4b924-011c-4897-8aec-fca54899bbae)

I played the intro up to the same spot (after yawning, then looking through her closet)
Logfile:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12069958/yuzu_log.txt)

**Comment by klz-fc** [comment] 2023-07-17 18:44
I checked the settings for the Debug log before restesting and it loaded up the dev videos, then crashed to the desktop while trying to start playing the into video.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12072875/yuzu_log.txt.old.txt)

If I recall, the original bug with getting video to play was isolated to one and a half games and then you found out about the interlaced video bug, so this was much farther along than I think anyone expected. 

I get the academic curiosity to see if it was anything that just needed a little tweaking, but at least having this setting noted as a working workaround I think is fine until someone decides they just have to fix it. Again, your efforts are appreciated. :)

**Comment by danilaml** [comment] 2023-07-17 19:09
@klz-fc thanks! Looking at the log, it looks like the issue is not as bad as I feared. It seems that `av_hwframe_transfer_data` doesn't copy metadata props, when transferring the frame from GPU to CPU. The fix for this should be pretty simple.
Could you test that this one works for you (with GPU video decoding, no need to attach the log)?
[yuzu.zip](https://github.com/yuzu-emu/yuzu/files/12073092/yuzu.zip)

**Comment by klz-fc** [comment] 2023-07-17 19:42
This one crashed to teh desktop again, unfortunately.

**Comment by danilaml** [comment] 2023-07-17 20:39
@klz-fc 
According to log
>error: 'scale' filter not present, cannot convert formats.

hm, looks like ffmpeg needs to be updated to include this filter. Don't have a quick way to come up with a test build unfortunately (I can build ffmpeg, but not with nvidia hw decode enabled).

**Comment by danilaml** [comment] 2023-07-17 21:52
@klz-fc Made an ffmpeg build, don't know if nvdec is properly enabled in it (have no hw to test it atm), could you replace the dlls in your yuzu bin folder with these ones and report if it fixes the crash (and attach the log)?
[ffmpeg.zip](https://github.com/yuzu-emu/yuzu/files/12074061/ffmpeg.zip)

**Comment by klz-fc** [comment] 2023-07-17 22:47
Using the original 1495 exe and replacing those files did work and smoothed out the video and plays it back as expected. 

I left the *:Debug setting on for you and it is attached below.
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12074277/yuzu_log.txt.old.txt)

**Closed** 2023-08-29 13:27 UTC
