### ISSUE TITLE
Animal Crossing: New Horizons softlock when redeeming nook miles

### ISSUE THREAD

**Issue by zivshek** [yuzu-emu/yuzu#5006] opened 2020-11-26 04:04 UTC
- yuzu version: 
![Screenshot 2020-11-25 225858](https://user-images.githubusercontent.com/24230685/100306617-d4077300-2f71-11eb-9671-55c0d5eae562.png)
--mainline-0-448
--0b08127
- bug description:
While redeeming the miles, as I scroll down, the item image stopped to update and eventually disappeared. When I tried to leave, I got an empty chatbox and the game was stuck. The issue went away after restarting yuzu. Here are other people getting the same bug: https://www.reddit.com/r/yuzu/comments/i7sl77/animal_crossing_crash_when_redeeming_nook_miles/
- system specs: i7 7700k, GTX 1060, 32GB ram
- unfortunately, I restarted yuzu instead of checking the log file, now it's just an empty file. Can't repro atm.

**Comment by choppymaster** [comment] 2020-11-26 04:16
Again try to redeem nook miles, when it softlock, close yuzu and find log file (don't reopen!) And upload it here.

**Comment by zivshek** [comment] 2020-11-26 04:59
hey I managed to repro it! Here is the log file! 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5600507/yuzu_log.txt)
I haven't fully tested yet, but I think the repro steps are:
1. go to the ATM.
2. select redeem.
3. scroll really fast to the bottom, observe the items' thumbnails and the preview image.

**Comment by choppymaster** [comment] 2020-11-26 07:17
**[  21.841233] HW.GPU <Warning> video_core\shader\shader_ir.cpp:SetInternalFlagsFromInteger:392: Condition codes implementation is incomplete
[  21.842388] Debug <Critical> video_core\shader\decode\arithmetic_integer.cpp:DecodeArithmeticInteger:133: Assertion Failed! Condition codes generation in ISCADD is not implemented
[  21.842393] HW.GPU <Warning> video_core\shader\shader_ir.cpp:SetInternalFlagsFromInteger:392: Condition codes implementation is incomplete
[  21.842399] HW.GPU <Warning> video_core\shader\shader_ir.cpp:SetInternalFlagsFromInteger:392: Condition codes implementation is incomplete
[  21.842574] HW.GPU <Warning> video_core\shader\shader_ir.cpp:SetInternalFlagsFromInteger:392: Condition codes implementation is incomplete**

Implement conditions codes 😌

**Comment by choppymaster** [comment] 2020-11-26 14:06
Ugh ugh hey zivshek, did you redeem the nook miles(it cant be redeemed?)? There is a missing HLE service commmand observed in your log. Maybe that's why the softlock occurs? Opened an issue about that and .....

**Comment by zivshek** [comment] 2020-11-26 15:47
I wasn't able to redeem anything when it happened. If you are sure that's the cause, yeah! What about the function SetInternalFlagsFromInteger, it looks like that function and SetInternalFlagsFromFloat are not implemented, and they've called in many places.

**Comment by Nakotei** [comment] 2020-11-26 16:31
Hi, I'm new here. I have exactly the same issue. I don't have programming knowledge, but I want to fix the game. If you need information about something, tell me.

**Comment by choppymaster** [comment] 2020-11-27 03:34
Zivshek maybe it is caused by the missing HLE service commmand I said because the opened issue by me is closed because my favourite dev says it is a duplicate of this issue.

**Comment by choppymaster** [comment] 2020-11-28 13:45
@zivshek but their is a problem, this issue is a duplicate of issue #4624.

**Comment by Krendeled** [comment] 2020-12-07 13:48
When is this getting fixed? Or any workaround?

**Comment by choppymaster** [comment] 2020-12-07 14:48
Devs don't report when it is going to be fixed. It will be fixed when they implement the services needed for it.

**Comment by benderscruffy** [comment] 2022-09-08 10:08
is this still an issue ??

**Comment by liamwhite** [comment] 2022-09-28 02:33
Comment with a yuzu log if this is still relevant.

**Closed by liamwhite** 2022-09-28 02:33 UTC
