### ISSUE TITLE
The Messenger — Softlocking since canary-2343

### ISSUE THREAD

**Issue by GabeEddyT** [yuzu-emu/yuzu#2566] opened 2019-06-08 07:43 UTC
From canary build [d12e855](https://github.com/yuzu-emu/yuzu-canary/commit/d12e8559866a488d4df81c666e45b23f04c8bb60) on (tested as recently as 2368/[b5679dc](https://github.com/yuzu-emu/yuzu-canary/commit/b5679dc7a2c510a8cb671dcda4754eb967581f8f)), the game will hang on a black screen while music continues to play in the background, similar to #1935. I've tested this on both Ubuntu 19.04 and Windows 10. This issue seemingly occurs at random, but it is easily reproducible around boss fights after 2 or so minutes of play (save file attached for convenience). I wouldn't think the switch to std::chrono in #2545 would cause this, but I don't see any other changes between builds 2342 and 2343.

[gdb.txt](https://github.com/yuzu-emu/yuzu/files/3268258/gdb.txt)
[yuzu_log-after-hang.txt](https://github.com/yuzu-emu/yuzu/files/3268259/yuzu_log-after-hang.txt)
[tower-of-time-boss.zip](https://github.com/yuzu-emu/yuzu/files/3268281/tower-of-time-boss.zip)

**Comment by Hexagon12** [comment] 2019-06-08 07:54
This is happening because #2365 got untagged from Canary releases.

The issue is a duplicate of #1935, even if it's not the same game. Please post your issue there.

**Closed by Hexagon12** 2019-06-08 07:54 UTC

**Comment by Kyareshi** [comment] 2019-06-12 19:41
e
