### ISSUE TITLE
Add detailed cheat settings

### ISSUE THREAD

**Issue by Xatomix** [yuzu-emu/yuzu#13042] opened 2024-02-17 16:09 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add detailed cheat settings

At the moment, you have to add each cheat separately, which is a little inconvenient.

add the ability to add one txt file with cheats and a subsequent selection to activate cheats from this file

Thx!

### Why would this feature be useful?

there will be no need to store a lot of folders for cheats and confusion in them

I have attached an example of a cheat file with many cheats to choose from

[14C878ECCA9D7CB5.txt](https://github.com/yuzu-emu/yuzu/files/14319448/14C878ECCA9D7CB5.txt)

**Comment by FearlessTobi** [comment] 2024-02-18 01:02
Duplicate of https://github.com/yuzu-emu/yuzu/issues/12658.

**Closed by FearlessTobi** 2024-02-18 01:02 UTC
Labels: request
