### ISSUE TITLE
Yuzu crashes when click on Configure

### ISSUE THREAD

**Issue by DasAutoz** [yuzu-emu/yuzu#7169] opened 2021-10-13 09:41 UTC
Reporting a crash on WIn10
Mainline Build - 5019df4ca
Fresh yuzu download access emulation and only configure is available, clicked and program crashed
tried delete all files in %appdata%\yuzu\config,uninstall obs, clean reinstall, Firmware 13.0.0 
3 devices plugged in, keyboard, 1 monitor,2 jack headphones
No other software eg (mangohud, avast, Action recording)

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7336888/yuzu_log.txt.old.txt)

**Comment by slowwdev** [comment] 2021-12-13 15:51
> 

same

**Comment by SLCH** [comment] 2022-02-19 13:44
Can't get in Configure as well
Crashes upon selecting a game in the list too (single left click on game, after 1-2 seconds crash)
It doesn't even log an exception lol (empty log file, doesn't dump buffer?)

Did try removing old config folder
Besides it are running only chrome and a chatting app.
2 monitor setup, tried disconnecting 1.
Using AppImage from latest [yuzu 922](https://github.com/yuzu-emu/yuzu-mainline/releases/tag/mainline-0-922) (which for some reason has title with 636)
First time trying yuzu out.

**Comment by Mewzax** [comment] 2022-02-19 14:00
I fixed my problem. It was caused by Vulkan from ReShade app

**Comment by SLCH** [comment] 2022-02-19 14:07
> I fixed my problem. It was caused by Vulkan from ReShade app

Might as well close the issue :+1:

**Comment by german77** [comment] 2022-03-31 16:06
Gshade, reshade, overwolf, action recording, and outdated streamlabs obs can conflict with yuzu. Uninstalling them should fix yuzu.

**Comment by G-Spawn** [comment] 2022-06-10 03:44
> Gshade, reshade, overwolf, action recording, and outdated streamlabs obs can conflict with yuzu. Uninstalling them should fix yuzu.
Be sure none of these are installed and also try deleting %appdata%\yuzu\config\qt-config.ini then reopening the emulator. If this issue still persists for you then reopen issue.

**Closed by G-Spawn** 2022-06-10 03:44 UTC
