### ISSUE TITLE
Hyrule Warriors: Age of Calamity graphics issues after the first cutscene

### ISSUE THREAD

**Issue by AsrielDewitt** [yuzu-emu/yuzu#10601] opened 2023-06-04 02:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1457

### Description of Issue

![image](https://github.com/yuzu-emu/yuzu/assets/48144566/f8f1a07e-e93a-4615-ad4d-59a385cf329a)
I don't really need to describe it, once the first video cutscene finish playing, there's an in-game cutscene with no audio and after that.... this.

### Expected Behavior

The game just play that in-game cutscene with sound, after that, load into the game.

### Reproduction Steps

Just play the game, Not much recreation needed

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11644647/yuzu_log.txt)

### System Configuration

CPU:Ryzen 5 4600h
GPU/Driver: GTX1650/532.03
RAM:16GB
OS:Windows 11

**Comment by Squall-Leonhart** [comment] 2023-06-04 06:00
Try replacing the copy of avcodec-59.dll with this one, supplied by Liam

https://cdn.discordapp.com/attachments/1107009076707205153/1114790413572776066/avcodec-59.dll

**Comment by AsrielDewitt** [comment] 2023-06-04 06:01
> Try replacing the copy of avcodec-59.dll with this one, supplied by Liam
> 
> https://cdn.discordapp.com/attachments/1107009076707205153/1114790413572776066/avcodec-59.dll

can you give me a proper source for this? I do not trust discord link and random DLL. That just smell potential virus and I'm not willing to risk it

**Comment by Squall-Leonhart** [comment] 2023-06-04 06:09
> can you give me a proper source for this? I do not trust discord link and random DLL. That just smell potential virus and I'm not willing to risk it

https://github.com/yuzu-emu/ext-windows-bin/blob/master/ffmpeg/ffmpeg-5.1.3.7z

**Comment by AsrielDewitt** [comment] 2023-06-04 06:17
> > can you give me a proper source for this? I do not trust discord link and random DLL. That just smell potential virus and I'm not willing to risk it
> 
> https://github.com/yuzu-emu/ext-windows-bin/blob/master/ffmpeg/ffmpeg-5.1.3.7z

![image](https://github.com/yuzu-emu/yuzu/assets/48144566/343d0b85-1ad2-4417-96e0-1234d19831b9)
Done and still the same.

**Comment by Squall-Leonhart** [comment] 2023-06-04 06:23
looking at your settings file though, using the ryujinx folders for your data doesn't work as yuzu doesn't adhere to the official file system structures for save data, though thats a side issue.

Was there a build you remember that this did work?

**Comment by AsrielDewitt** [comment] 2023-06-04 06:26
> looking at your settings file though, using the ryujinx folders for your data doesn't work as yuzu doesn't adhere to the official file system structures for save data, though thats a side issue.
> 
> Was there a build you remember that this did work?

The save file isn't the issue. In fact,I  used to play Mario Oddasy on Ryujinx before going to Yuzu, and that was a long time ago, as my first Switch emulate game. 

As a way to keep my save, I just use Ryujinx folder, but I haven't touch Ryujinx for a long time.

Beside, AOC comes way way after I moved to solely Yuzu

As for the last build I remember working just fine, is 1342. While stuttering and performance used to be an issue back then. It still run a good 30fps here and there.

**Comment by Squall-Leonhart** [comment] 2023-06-04 06:27
Could be a duplicate of #10542 since both issues describe visual glitches and abnormalities.

**Comment by AsrielDewitt** [comment] 2023-06-04 06:29
> Could be the same issue as #10542 since both issues describe visual glitches and abnormalities.

Are you sure? Their bug seems a lot less major than the one I'm having.

**Comment by Squall-Leonhart** [comment] 2023-06-04 06:30
Woops, i meant #10016

**Comment by AsrielDewitt** [comment] 2023-06-04 06:33
Welp, I hope this get fix soon, because this is a major bug

**Closed** 2023-06-08 09:31 UTC
