### ISSUE TITLE
Stopping and restarting emulation causes yuzu to crash

### ISSUE THREAD

**Issue by Eloeri** [yuzu-emu/yuzu#2785] opened 2019-08-09 20:05 UTC
When stopping emulation manually through the tool bar and then restarting emulation/restarting the game causes yuzu to crash.

**Comment by fluffapparition** [comment] 2019-08-10 21:02
Rip

**Comment by FearlessTobi** [comment] 2019-09-08 15:08
Caused by https://github.com/yuzu-emu/yuzu/pull/2364.

**Comment by Morph1984** [comment] 2019-09-11 16:49
Is this really caused by #2364? It was never merged to canary so it was never tested.

**Comment by FearlessTobi** [comment] 2019-09-11 18:36
this has been in Canary for multiple months now

**Comment by FearlessTobi** [comment] 2019-09-21 18:43
Also shows error message: 

`Debug <Critical> core\hle\kernel\scheduler.cpp:SwitchContext:348: Assertion Failed! Thread must be ready to become running.`

**Comment by MysticExile** [comment] 2020-05-04 21:55
This issue appears to have been fixed! If there are any further problems regarding this issue, please feel free to open a new issue.

**Closed by MysticExile** 2020-05-04 21:55 UTC
Labels: regression

**Comment by zyzkevin** [comment] 2020-12-02 17:36
still happening on EA 1180
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5631040/yuzu_log.txt)

**Comment by neonoafs** [comment] 2021-08-18 02:54
Still happening with the latest version 719
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/7004168/yuzu_log.txt)

**Comment by RinMaru** [comment] 2021-08-18 02:59
Still happening in build EA 1995

**Comment by Kane-Kuroneko** [comment] 2023-12-22 00:59
Still exists in Date 2023-12.
