### ISSUE TITLE
Bug Sky-High Sundae Vulkan AMD MK8D

### ISSUE THREAD

**Issue by rgbarros120** [yuzu-emu/yuzu#8808] opened 2022-08-23 20:47 UTC
Some fix forecast for Sky-High Sundae track for Vulkan AMD, so far not fixed. Many games have these graphical bugs, this one is an example of them, due to the lack of RDNA2.

My Specs: Radeon RX 560OC 4GB; RYZEN 5 1600; 16GB DE RAM.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9410530/yuzu_log.txt)
![Sem título](https://user-images.githubusercontent.com/73244003/186262502-6f43914f-9da4-4d6e-a085-0bcfd39ec911.png)

**Comment by G-Spawn** [comment] 2022-08-23 20:52
there was 0 'forecasted' fixes for mk8d graphically, especially on AMD. you'll be waiting a significant amount of time for specific map based issues.

**Comment by rgbarros120** [comment] 2022-08-23 20:57
> there was 0 'forecasted' fixes for mk8d graphically, especially on AMD. you'll be waiting a significant amount of time for specific map based issues.

But after all it will be corrected or not in the future. Because we don't know and with that the bugs are just accumulating.

**Comment by G-Spawn** [comment] 2022-08-23 21:03
Of course they will try to fix it in time. Just 0 ETA. You'll have a much easier time just joining the discord and tracking changes there so you arent turning an issue support request into general inquiry forum.

**Comment by mcastellonc201** [comment] 2022-08-24 14:55
I'm not sure, but for me the texture problem is the decoders from the version 4.3 of ffmpeg, update to version 5.1 (only HEVC decoder), please try it, I just compiled it, I haven't tried it yet.
The version qt.
https://github.com/mcastellonc201/yuzu_cmd-update082022/blob/main/Release.zip

if you want to try other decoders, 
./configure --arch=x86_64 --target-os=mingw64 --enable-shared \
--disable-avdevice \
--disable-avfilter \
--disable-avformat \
--disable-doc \
--disable-everything \
--disable-programs \
--disable-mediafoundation \
--disable-schannel \
--disable-zlib \
--disable-iconv \
--disable-network \
--disable-postproc \
--disable-swresample \
--disable-d3d11va \
--disable-dxva2 \
--enable-decoder=hevc
make -j$(nproc)

for h264, change
--enable-decoder=h264

Good luck.
Regards.

**Comment by FederAndInk** [comment] 2022-09-09 00:47
Same bug on the SteamDeck :/

**Comment by gidoly** [comment] 2022-11-06 01:17
duplicate of #8748

**Closed by gidoly** 2022-11-06 01:17 UTC
Labels: gpu-issue, amd
