### ISSUE TITLE
Fire Emblem Three Houses Crash before battle

### ISSUE THREAD

**Issue by Razucky** [yuzu-emu/yuzu#4460] opened 2020-08-02 17:46 UTC
Game crashes on loading screen on second battle. Tried disabling assembly shaders.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5012537/yuzu_log.txt)

**Comment by NielsGx** [comment] 2020-08-02 18:45
This is for devs, ask for support in the discord server
(No fix available for the random crashes in Yuzu when playing feth)

**Comment by ShyCode-analyst** [comment] 2020-08-02 19:46
many Debug <Critical> error.
You try run without OpenGL ?

**Comment by ShyCode-analyst** [comment] 2020-08-05 04:50
i think it is API error maybe OpenGL. Do you try run with Vunkan ?

**Comment by FearlessTobi** [comment] 2020-08-06 12:34
Probably a duplicate of https://github.com/yuzu-emu/yuzu/issues/4038.
Please add your log as a comment on the original issue.

**Closed by FearlessTobi** 2020-08-06 12:34 UTC
