### ISSUE TITLE
Xenoblade 2 graphic issue [Vulkan]

### ISSUE THREAD

**Issue by rolmerin** [yuzu-emu/yuzu#6867] opened 2021-08-13 05:05 UTC
The grass is broken in Vulkan backend.
![1](https://user-images.githubusercontent.com/88316690/129305958-4381befc-f778-4d0f-962f-cbabd694c0af.jpg)

In Opengl,it rendered correctly.

![4](https://user-images.githubusercontent.com/88316690/129306996-35ebc3ca-a398-4ac1-9f81-cb8e1bb55d99.jpg)

In Vulkan,the screen sometimes becomes too bright,especially going into a dark place.
![2](https://user-images.githubusercontent.com/88316690/129307143-f43f5f4f-6bf2-4af6-893d-86e7f691284a.jpg)

In Opengl,no such problem.
![3](https://user-images.githubusercontent.com/88316690/129307161-c3e35ccc-b36c-4017-8ac9-53118c0c9fa3.jpg)

Spec:
R5 5600X
AMD RX590
Windows 10 21h1

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6980009/yuzu_log.txt)

**Comment by kevin98761234** [comment] 2021-08-13 09:13
On nvidia the grass is fine, but the overbright problem is exactly the same.
![1](https://user-images.githubusercontent.com/88806005/129333796-03bfa675-8564-4ed6-a875-6d576f32e548.png)
It's easier to understand if you go to the Event Theater in the Start menu, set some event to noon on a sunny day, and play it back.
![3](https://user-images.githubusercontent.com/88806005/129333838-5d8e9431-dc32-4bc1-abbe-eff147c6194e.png)
driver version 471.41
Intel(R) Core(TM) i3-8300 CPU @ 3.70GHz
16.0 GB
Windows 10 Home, 64-bit
21H1 19043.1165

**Comment by dmanexe** [comment] 2021-10-17 16:41
Ryzen 3700X
RX570
Windows 10, 64-bit
32GB RAM

same issue

**Comment by dev-whiteflag** [comment] 2021-10-21 03:22
Xenoblade 1 DE, but same grass problem, High GPU Accuracy workaround doesn't work anymore.

Ryzen 5 2600
RX 5500 XT 4GB, Drivers 21.10.2 Vulkan
Windows 11, 64-bit
16GB RAM

**Comment by german77** [comment] 2021-12-07 03:29
Duplicate of #5007

**Closed by german77** 2021-12-07 03:29 UTC
