### ISSUE TITLE
Add game specific options for default docked/handheld mode

### ISSUE THREAD

**Issue by XmemphistoX** [yuzu-emu/yuzu#9754] opened 2023-02-09 20:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What feature are you suggesting?

Add game specific settings for docked/handheld mode.

### Why would this feature be useful?

Games that run better in handheld mode wouldn't need the toggle.

**Comment by G-Spawn** [comment] 2023-02-09 20:49
I'm not sure if they'll consider this since a lot of the time it is just current emulator issues. It could be fixed in the future rendering this kind of feature a little moot.

**Comment by RuinerVoid** [comment] 2023-02-09 23:50
> I'm not sure if they'll consider this since a lot of the time it is just current emulator issues. It could be fixed in the future rendering this kind of feature a little moot.

I think it'd be good, if only to use on the specific games that require Handheld mode if you use Docked as default. It would allow the code to stay 'clean' without having to implement game specific fixes for those titles.

**Closed** 2023-02-10 02:51 UTC
Labels: request

**Comment by gustakasn0v** [comment] 2023-04-25 22:00
@G-Spawn i don't think that's quite what OP meant. As I understand it, the ask is to configure handheld/docked mode (primarily the rendering resolution) on a per-game basis; the reason may be because some games (eg BotW) are too demanding to run on docked mode for some computers

**Comment by G-Spawn** [comment] 2023-04-26 04:53
If you look at what I showed them before I closed the issue it already covers that. You set the custom input profile on a per game basis.

**Comment by gustakasn0v** [comment] 2023-04-26 10:41
@G-Spawn I tried that, but the setting doesn't work on a per-game basis. Here are the troubleshooting steps I tried:

1. Open Yuzu, notice the docked/handheld setting at the bottom left corner of the main UI (in my case it was handheld)
2. Go to Emulation -> Configure, select Controls on the left-hand-side panel
3. Notice the docked/handheld setting at the bottom left corner of the controls config matches the one on the main UI (handheld)
4. If no profile exists (top right), create a new one and save it (let's call it 'handheld'). Make sure to _not_ change the docked/handheld setting
5. Create a new profile called 'docked', change the docked/handheld setting to 'docked', and save it. 
6. Using the dropdown, go back to the 'handheld' profile

Expected behaviour: the docked/handheld profile setting is set to 'handheld'. The global docked/handheld setting at the bottom left corner of the main UI is unchanged

Actual behaviour: the docked/handheld setting is set to 'docked' (the setting from the previous profile carries over to the current profile). If you select the 'docked' profile again, the setting goes back to 'docked', but after exiting the configuration page by pressing 'OK', you'll notice the the docked/handheld setting at the bottom left corner of the main UI has changed to 'docked'

This leads me to think that the profile setting isn't set on a per-profile basis, but instead it changes the global setting. This means you can't have profiles with different docked/handheld settings, which you'll need to make it game-specific

Let me know if the above makes sense, otherwise I can provide a video as well

(I'm running Yuzu v1389 AppImage on a Steam Deck)

**Comment by lolekuk** [comment] 2023-06-30 08:24
I would love that functionality as well,

example, most of the games I have are playing amazingly well in docked mode (1080p) apart from Need For Speed Hot Pursuit.
I can change lots of graphic settings for this game only but I cannot change to play in handheld mode (720p). So I have lots of settings preconfigured for this game only but can't preconfigure handheld/docked mode. Or could it be implemented in 1x 720p or 1x 1080p resolution setting? or possibility to change from hanheld to docked. Thanks.
