### ISSUE TITLE
Star Ocean The Second Story R Close on Marze city yuzu for Android

### ISSUE THREAD

**Issue by hikaruthe1** [yuzu-emu/yuzu#12198] opened 2023-11-27 13:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 141

### Description of Issue

When I arrive in Marze city the emulator closes I'm using version 141 of Yuzu Android I can't continue the game
It just stack in this city
I cannot enter the city to continue the game progress

### Expected Behavior

Game is hang
And return to Yuzu menu when I enter marze city on star ocean the second story r

### Reproduction Steps

Try to enter Marze City to continue the story

### Log File

[ 0.027129] Frontend <Info> main/jni/native.cpp:Java_org_yuzu_yuzu_1emu_NativeLibrary_logDeviceInfo:721: yuzu Version: HEAD-3f34e764c
[ 0.027158] Frontend <Info> main/jni/native.cpp:Java_org_yuzu_yuzu_1emu_NativeLibrary_logDeviceInfo:722: Host OS: Android API level 33
[ 0.027453] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: Device Manufacturer - Xiaomi
[ 0.027480] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: Device Model - 23043RP34G
[ 0.027527] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: SoC Manufacturer - QTI
[ 0.027547] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: SoC Model - SM8250
[ 0.028380] Frontend <Info> main/jni/native_log.cpp:Java_org_yuzu_yuzu_1emu_utils_Log_info:20: Total System Memory - 8.0 GB
[ 0.555720] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3ASO%2FSTAR%20OCEAN%20THE%20SECOND%20STORY%20R%20%5Bforest%20knuckles%20DLC%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[ 0.571864] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3ASO%2FSTAR%20OCEAN%20THE%20SECOND%20STORY%20R%20%5Bsunrise%20ring%20DLC%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[ 0.580077] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3ASO%2FSTAR%20OCEAN%20THE%20SECOND%20STORY%20R%20%5Bpangalactic%20federation%20longsword%20DLC%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[ 0.583556] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3ASO%2FSTAR%20OCEAN%20THE%20SECOND%20STORY%20R%20%5Bprism%20badge%20DLC%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[ 0.592733] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3ASO%2FSTAR%20OCEAN%20THE%20SECOND%20STORY%20R%20%5Bset%20of%20recovery%20items%20DLC%5D%5Bv0%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[ 0.621227] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3ASO%2FStar%20Ocean%20The%20Second%20Story%20R%20%5B010065301A2E0800%5D%5Bv65536%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[ 0.635507] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:451: RomFS: Update (v0.1.0) applied successfully
[ 0.636279] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:451: RomFS: Update (v0.1.0) applied successfully
[ 0.663935] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:451: RomFS: Update (v0.1.0) applied successfully
[ 0.731072] Loader <Warning> core/loader/loader.cpp:GetLoader:259: File primary%3ASO%2FStar%20Ocean%20The%20Second%20Story%20R%20%5B010065301A2E0800%5D%5Bv65536%5D%5BUS%5D.nsp has a different type (unknown) than its extension.
[ 0.748384] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:451: RomFS: Update (v0.1.0) applied successfully
[ 3.345791] Frontend <Info> main/jni/native.cpp:RunEmulation:468: starting
[ 3.345815] Frontend <Info> main/jni/emu_window/emu_window.cpp:EmuWindow_Android:72: initializing
[ 3.345992] Input <Info> input_common/drivers/udp_client.cpp:UDPClient:139: Udp Initialization started
[ 3.346006] Input <Info> input_common/drivers/udp_client.cpp:StartCommunication:331: Starting communication with UDP input server on 127.0.0.1:26760
[ 3.346282] Config <Info> common/settings.cpp:LogSettings:116: yuzu Configuration:
[ 3.346296] Config <Info> common/settings.cpp:operator():109: -- Audio.output_engine: auto
[ 3.346300] Config <Info> common/settings.cpp:operator():109: -- Audio.output_device: auto
[ 3.346301] Config <Info> common/settings.cpp:operator():109: -- Audio.input_device: auto
[ 3.346304] Config <Info> common/settings.cpp:operator():109: -- Audio.volume: 100
[ 3.346306] Config <Info> common/settings.cpp:operator():109: -- Audio.audio_muted: false
[ 3.346307] Config <Info> common/settings.cpp:operator():109: -- Audio.dump_audio_commands: false
[ 3.346309] Config <Info> common/settings.cpp:operator():109: -- Core.use_multi_core: true
[ 3.346313] Config <Info> common/settings.cpp:operator():109: -- Core.memory_layout_mode: Memory_4Gb
[ 3.346314] Config <Info> common/settings.cpp:operator():109: -- Core.use_speed_limit: true
[ 3.346316] Config <Info> common/settings.cpp:operator():109: -- Core.speed_limit: 100
[ 3.346319] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpu_backend: Dynarmic
[ 3.346321] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpu_accuracy: Auto
[ 3.346322] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpu_debug_mode: false
[ 3.346323] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_page_tables: true
[ 3.346324] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_block_linking: true
[ 3.346325] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_return_stack_buffer: true
[ 3.346325] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_fast_dispatcher: true
[ 3.346326] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_context_elimination: true
[ 3.346327] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_const_prop: true
[ 3.346327] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_misc_ir: true
[ 3.346328] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_reduce_misalign_checks: true
[ 3.346350] Config <Info> common/settings.cpp:operator():109: M- Cpu.cpuopt_fastmem: false
[ 3.346351] Config <Info> common/settings.cpp:operator():109: M- Cpu.cpuopt_fastmem_exclusives: false
[ 3.346352] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_recompile_exclusives: true
[ 3.346352] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_ignore_memory_aborts: true
[ 3.346354] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_unsafe_unfuse_fma: true
[ 3.346354] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_unsafe_reduce_fp_error: true
[ 3.346355] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_unsafe_ignore_standard_fpcr: true
[ 3.346356] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_unsafe_inaccurate_nan: true
[ 3.346356] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_unsafe_fastmem_check: true
[ 3.346357] Config <Info> common/settings.cpp:operator():109: -- Cpu.cpuopt_unsafe_ignore_global_monitor: true
[ 3.346359] Config <Info> common/settings.cpp:operator():109: -- Renderer.backend: Vulkan
[ 3.346362] Config <Info> common/settings.cpp:operator():109: -- Renderer.shader_backend: Glsl
[ 3.346363] Config <Info> common/settings.cpp:operator():109: -- Renderer.vulkan_device: 0
[ 3.346364] Config <Info> common/settings.cpp:operator():109: -- Renderer.use_disk_shader_cache: true
[ 3.346364] Config <Info> common/settings.cpp:operator():109: -- Renderer.use_asynchronous_gpu_emulation: true
[ 3.346367] Config <Info> common/settings.cpp:operator():109: -- Renderer.accelerate_astc: Cpu
[ 3.346369] Config <Info> common/settings.cpp:operator():109: M- Renderer.use_vsync: Immediate
[ 3.346371] Config <Info> common/settings.cpp:operator():109: -- Renderer.nvdec_emulation: Gpu
[ 3.346383] Config <Info> common/settings.cpp:operator():109: -- Renderer.fullscreen_mode: Exclusive
[ 3.346385] Config <Info> common/settings.cpp:operator():109: -- Renderer.aspect_ratio: R16_9
[ 3.346387] Config <Info> common/settings.cpp:operator():109: M- Renderer.resolution_setup: Res3_4X
[ 3.346389] Config <Info> common/settings.cpp:operator():109: -- Renderer.scaling_filter: Bilinear
[ 3.346391] Config <Info> common/settings.cpp:operator():109: -- Renderer.anti_aliasing: None
[ 3.346392] Config <Info> common/settings.cpp:operator():109: -- Renderer.fsr_sharpening_slider: 25
[ 3.346394] Config <Info> common/settings.cpp:operator():109: -- Renderer.bg_red: 0
[ 3.346394] Config <Info> common/settings.cpp:operator():109: -- Renderer.bg_green: 0
[ 3.346395] Config <Info> common/settings.cpp:operator():109: -- Renderer.bg_blue: 0
[ 3.346397] Config <Info> common/settings.cpp:operator():109: -- Renderer.gpu_accuracy: Normal
[ 3.346399] Config <Info> common/settings.cpp:operator():109: -- Renderer.max_anisotropy: Default
[ 3.346401] Config <Info> common/settings.cpp:operator():109: -- Renderer.astc_recompression: Uncompressed
[ 3.346402] Config <Info> common/settings.cpp:operator():109: -- Renderer.async_presentation: true
[ 3.346402] Config <Info> common/settings.cpp:operator():109: -- Renderer.force_max_clock: false
[ 3.346403] Config <Info> common/settings.cpp:operator():109: -- Renderer.use_reactive_flushing: false
[ 3.346404] Config <Info> common/settings.cpp:operator():109: -- Renderer.use_asynchronous_shaders: false
[ 3.346404] Config <Info> common/settings.cpp:operator():109: -- Renderer.use_fast_gpu_time: true
[ 3.346405] Config <Info> common/settings.cpp:operator():109: -- Renderer.use_vulkan_driver_pipeline_cache: true
[ 3.346405] Config <Info> common/settings.cpp:operator():109: -- Renderer.enable_compute_pipelines: false
[ 3.346416] Config <Info> common/settings.cpp:operator():109: -- Renderer.use_video_framerate: false
[ 3.346417] Config <Info> common/settings.cpp:operator():109: -- Renderer.barrier_feedback_loops: true
[ 3.346419] Config <Info> common/settings.cpp:operator():109: -- Renderer.debug: false
[ 3.346419] Config <Info> common/settings.cpp:operator():109: -- Renderer.shader_feedback: false
[ 3.346421] Config <Info> common/settings.cpp:operator():109: -- Renderer.nsight_aftermath: false
[ 3.346421] Config <Info> common/settings.cpp:operator():109: -- Renderer.disable_shader_loop_safety_checks: false
[ 3.346422] Config <Info> common/settings.cpp:operator():109: -- Renderer.renderdoc_hotkey: false
[ 3.346429] Config <Info> common/settings.cpp:operator():109: -- Renderer.disable_buffer_reorder: false
[ 3.346432] Config <Info> common/settings.cpp:operator():109: -- System.language_index: EnglishAmerican
[ 3.346434] Config <Info> common/settings.cpp:operator():109: -- System.region_index: Usa
[ 3.346440] Config <Info> common/settings.cpp:operator():109: -- System.time_zone_index: Auto
[ 3.346451] Config <Info> common/settings.cpp:operator():109: -- System.custom_rtc_enabled: false
[ 3.346452] Config <Info> common/settings.cpp:operator():109: -- System.custom_rtc: 0
[ 3.346453] Config <Info> common/settings.cpp:operator():109: -- System.rng_seed_enabled: false
[ 3.346454] Config <Info> common/settings.cpp:operator():109: -- System.rng_seed: 0
[ 3.346455] Config <Info> common/settings.cpp:operator():109: -- System.device_name: yuzu
[ 3.346457] Config <Info> common/settings.cpp:operator():109: -- System.current_user: 0
[ 3.346459] Config <Info> common/settings.cpp:operator():109: M- System.use_docked_mode: Docked
[ 3.346461] Config <Info> common/settings.cpp:operator():109: -- System.sound_index: Stereo
[ 3.346463] Config <Info> common/settings.cpp:operator():109: -- Data Storage.use_virtual_sd: true
[ 3.346463] Config <Info> common/settings.cpp:operator():109: -- Data Storage.gamecard_inserted: false
[ 3.346464] Config <Info> common/settings.cpp:operator():109: -- Data Storage.gamecard_current_game: false
[ 3.346464] Config <Info> common/settings.cpp:operator():109: -- Data Storage.gamecard_path: 
[ 3.346465] Config <Info> common/settings.cpp:operator():109: -- Debugging.use_gdbstub: false
[ 3.346466] Config <Info> common/settings.cpp:operator():109: -- Debugging.gdbstub_port: 6543
[ 3.346467] Config <Info> common/settings.cpp:operator():109: -- Debugging.program_args: 
[ 3.346467] Config <Info> common/settings.cpp:operator():109: -- Debugging.dump_exefs: false
[ 3.346468] Config <Info> common/settings.cpp:operator():109: -- Debugging.dump_nso: false
[ 3.346469] Config <Info> common/settings.cpp:operator():109: -- Debugging.enable_fs_access_log: false
[ 3.346479] Config <Info> common/settings.cpp:operator():109: -- Debugging.reporting_services: false
[ 3.346479] Config <Info> common/settings.cpp:operator():109: -- Debugging.quest_flag: false
[ 3.346480] Config <Info> common/settings.cpp:operator():109: -- Debugging.extended_logging: false
[ 3.346480] Config <Info> common/settings.cpp:operator():109: -- Debugging.use_debug_asserts: false
[ 3.346481] Config <Info> common/settings.cpp:operator():109: -- Debugging.use_auto_stub: false
[ 3.346482] Config <Info> common/settings.cpp:operator():109: -- Debugging.enable_all_controllers: false
[ 3.346482] Config <Info> common/settings.cpp:operator():109: -- Debugging.perform_vulkan_check: true
[ 3.346483] Config <Info> common/settings.cpp:operator():109: -- Debugging.dump_shaders: false
[ 3.346484] Config <Info> common/settings.cpp:operator():109: -- Debugging.dump_macros: false
[ 3.346485] Config <Info> common/settings.cpp:operator():109: -- Debugging.disable_macro_jit: false
[ 3.346485] Config <Info> common/settings.cpp:operator():109: -- Debugging.disable_macro_hle: false
[ 3.346486] Config <Info> common/settings.cpp:operator():109: -- Miscellaneous.log_filter: *:Info
[ 3.346486] Config <Info> common/settings.cpp:operator():109: -- Miscellaneous.use_dev_keys: false
[ 3.346487] Config <Info> common/settings.cpp:operator():109: -- Network.network_interface: 
[ 3.346488] Config <Info> common/settings.cpp:operator():109: -- WebService.enable_telemetry: true
[ 3.346491] Config <Info> common/settings.cpp:operator():109: -- WebService.web_api_url: https://api.yuzu-emu.org
[ 3.346491] Config <Info> common/settings.cpp:operator():109: -- WebService.yuzu_username: 
[ 3.346492] Config <Info> common/settings.cpp:operator():109: -- Controls.enable_raw_input: false
[ 3.346493] Config <Info> common/settings.cpp:operator():109: -- Controls.controller_navigation: true
[ 3.346493] Config <Info> common/settings.cpp:operator():109: -- Controls.enable_joycon_driver: true
[ 3.346494] Config <Info> common/settings.cpp:operator():109: -- Controls.enable_procon_driver: false
[ 3.346495] Config <Info> common/settings.cpp:operator():109: -- Controls.vibration_enabled: true
[ 3.346495] Config <Info> common/settings.cpp:operator():109: -- Controls.enable_accurate_vibrations: false
[ 3.346505] Config <Info> common/settings.cpp:operator():109: -- Controls.motion_enabled: true
[ 3.346506] Config <Info> common/settings.cpp:operator():109: -- Controls.udp_input_servers: 127.0.0.1:26760
[ 3.346507] Config <Info> common/settings.cpp:operator():109: -- Controls.enable_udp_controller: false
[ 3.346508] Config <Info> common/settings.cpp:operator():109: -- Controls.pause_tas_on_load: true
[ 3.346509] Config <Info> common/settings.cpp:operator():109: -- Controls.tas_enable: false
[ 3.346509] Config <Info> common/settings.cpp:operator():109: -- Controls.tas_loop: false
[ 3.346510] Config <Info> common/settings.cpp:operator():109: -- Controls.mouse_panning: false
[ 3.346511] Config <Info> common/settings.cpp:operator():109: -- Controls.mouse_panning_sensitivity: 50
[ 3.346512] Config <Info> common/settings.cpp:operator():109: -- Controls.mouse_enabled: false
[ 3.346513] Config <Info> common/settings.cpp:operator():109: -- Controls.mouse_panning_x_sensitivity: 50
[ 3.346513] Config <Info> common/settings.cpp:operator():109: -- Controls.mouse_panning_y_sensitivity: 50
[ 3.346514] Config <Info> common/settings.cpp:operator():109: -- Controls.mouse_panning_deadzone_counterweight: 20
[ 3.346515] Config <Info> common/settings.cpp:operator():109: -- Controls.mouse_panning_decay_strength: 18
[ 3.346515] Config <Info> common/settings.cpp:operator():109: -- Controls.mouse_panning_min_decay: 6
[ 3.346516] Config <Info> common/settings.cpp:operator():109: -- Controls.emulate_analog_keyboard: false
[ 3.346517] Config <Info> common/settings.cpp:operator():109: -- Controls.keyboard_enabled: false
[ 3.346517] Config <Info> common/settings.cpp:operator():109: -- Controls.debug_pad_enabled: false
[ 3.346518] Config <Info> common/settings.cpp:operator():109: -- Controls.touch_device: min_x:100,min_y:50,max_x:1800,max_y:850
[ 3.346519] Config <Info> common/settings.cpp:operator():109: -- Controls.touch_from_button_map: 0
[ 3.346519] Config <Info> common/settings.cpp:operator():109: -- Controls.enable_ring_controller: true
[ 3.346520] Config <Info> common/settings.cpp:operator():109: -- Controls.enable_ir_sensor: false
[ 3.346521] Config <Info> common/settings.cpp:operator():109: -- Controls.ir_sensor_device: auto
[ 3.346521] Config <Info> common/settings.cpp:operator():109: -- Controls.random_amiibo_id: false
[ 3.346524] Config <Info> common/settings.cpp:operator():113: DataStorage_CacheDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/cache
[ 3.346525] Config <Info> common/settings.cpp:operator():113: DataStorage_ConfigDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/config
[ 3.346526] Config <Info> common/settings.cpp:operator():113: DataStorage_LoadDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/load
[ 3.346527] Config <Info> common/settings.cpp:operator():113: DataStorage_NANDDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/nand
[ 3.346527] Config <Info> common/settings.cpp:operator():113: DataStorage_SDMCDir: /storage/emulated/0/Android/data/org.yuzu.yuzu_emu/files/sdmc
[ 3.346589] Input <Error> ./common/input.h:CreateDevice:510: Unknown engine name: joycon
[ 3.347531] Input <Error> ./common/input.h:CreateDevice:510: Unknown engine name: joycon
[ 3.389542] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:451: RomFS: Update (v0.1.0) applied successfully
[ 3.432503] Loader <Info> core/file_sys/patch_manager.cpp:PatchRomFS:451: RomFS: Update (v0.1.0) applied successfully
[ 3.654850] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:952: Device doesn't support extension VK_EXT_conservative_rasterization
[ 3.654881] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:952: Device doesn't support extension VK_EXT_depth_bias_control
[ 3.654885] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:952: Device doesn't support extension VK_EXT_depth_range_unrestricted
[ 3.654909] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:952: Device doesn't support extension VK_EXT_external_memory_host
[ 3.654911] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:952: Device doesn't support extension VK_NV_geometry_shader_passthrough
[ 3.654912] Render.Vulkan <Info> video_core/vulkan_common/vulkan_device.cpp:GetSuitability:952: Device doesn't support extension VK_NV

### System Configuration

CPU: snapdragon 870
GPU/Driver:turnip
RAM:8GB
OS:ANDROID 13 MIUI 14

**Comment by liamwhite** [comment] 2023-11-27 15:00
duplicate of #12027 (gpu issue)

**Closed by liamwhite** 2023-11-27 15:00 UTC

**Comment by brujo5** [comment] 2023-11-27 16:31
![IMG_20231127_092407_609](https://github.com/yuzu-emu/yuzu/assets/4172898/8a266ece-c2b3-4a58-97a7-406ca3e07cd7)
I have the same processor as him and with more progress in the game and without any crashes.
