### ISSUE TITLE
Fire emblem engage crash during fight with Vulkan

### ISSUE THREAD

**Issue by Elenfire** [yuzu-emu/yuzu#9667] opened 2023-01-24 08:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1316

### Description of Issue

When I use Vulkan api, and I launch Fire Emblem Engage, it’s work perfectly until a dialog box opens during a fight and shows me this error (see "log file" category)

And during a fight without dialog box, I have low fps with freeze. I have test with OpenGL and GLASM, and I am under 30 fps and it’s freeze every second.

### Expected Behavior

No crash

### Reproduction Steps

Launch Frire emblem engage
Wait a fight with dialog box
It’s crash after a few seconds

### Log File

[2835.702590] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:566: 0x0a691c7f8be0551e
[2836.258552] Service <Warning> core\hle\service\sm\sm_controller.cpp:QueryPointerBufferSize:68: (STUBBED) called
[2836.510122] HW.GPU <Warning> video_core/texture_cache/texture_cache.h:RefreshContents:777: MSAA image uploads are not implemented
[2836.510475] HW.GPU <Warning> video_core/texture_cache/texture_cache.h:RefreshContents:777: MSAA image uploads are not implemented
[2836.518013] Render.Vulkan <Critical> video_core\vulkan_common\vulkan_device.cpp:ReportLoss:512: Device loss occurred!

### System Configuration

CPU: Intel i7 12700h
GPU/Driver: Rtx 3060 laptop with Nvidia driver version 30.0.15.1298
RAM: 32 GB
OS: Windows 11

**Comment by liamwhite** [comment] 2023-01-24 11:55
duplicate of #9654

**Closed by liamwhite** 2023-01-24 11:55 UTC

**Comment by Elenfire** [comment] 2023-01-24 12:36
I already saw this issue, but I’ve a different error,
Can you look in more details my log file to compare please :
[2836.510122] HW.GPU video_core/texture_cache/texture_cache.h:RefreshContents:777: MSAA image uploads are not implemented
[2836.510475] HW.GPU video_core/texture_cache/texture_cache.h:RefreshContents:777: MSAA image uploads are not implemented
[2836.518013] Render.Vulkan 

However, the app totally crash when a fight with a dialog box begins, I don’t have a simple freeze ^^
thanks for ur time

**Comment by liamwhite** [comment] 2023-01-24 12:40
I am confirming once again that this is the same issue (Vulkan device loss on Fire Emblem Engage). The way the crash manifests after the device loss is not of any importance.
