### ISSUE TITLE
Just Dance Series Issue

### ISSUE THREAD

**Issue by modoxy** [yuzu-emu/yuzu#9919] opened 2023-03-08 01:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1354

### Description of Issue

When I was using the yuzu emulator and Joycon to play Just Dance, some of the MVs did not play properly

This is more common in the 2018 and 2019 editions

### Expected Behavior

https://user-images.githubusercontent.com/89689473/223592411-d77b626d-8925-4160-a5bb-463d8d76b292.mp4

### Reproduction Steps

This issue can be found when opening some MVs, such as Havana from 2019

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10915325/yuzu_log.txt)

### System Configuration

CPU:i5 10400f
GPU/Driver:rtx 3060
RAM:16gb
OS:windows10 21h2

**Comment by FearlessTobi** [comment] 2023-03-08 01:08
Duplicate of https://github.com/yuzu-emu/yuzu/issues/5283.

**Closed by FearlessTobi** 2023-03-08 01:08 UTC
