### ISSUE TITLE
Yuzu does not launch on lastest Nvidia drivers (Linux/Wayland)

### ISSUE THREAD

**Issue by Dirleye** [yuzu-emu/yuzu#11941] opened 2023-11-01 17:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1607

### Description of Issue

Launching Yuzu under the latest Arch Linux Nvidia drivers (545.29.02) outputs
`error marshalling arguments for get_surface_feedback (signature 4no): null value passed for arg 1`
`Error marshalling request: Invalid argument`
`The Wayland connection experienced a fatal error: Invalid argument`

### Expected Behavior

Yuzu launches in a Wayland session

### Reproduction Steps

Attempt to launch Yuzu under a Linux Wayland session with the latest Nvidia drivers.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13230161/yuzu_log.txt)

### System Configuration

CPU: Ryzen 9 5950x
GPU/Driver: Nvidia Titan Xp/545.29.02
RAM: 32GB DDR4
OS: EndeavourOS Linux

**Comment by willianholtz** [comment] 2023-11-02 03:12
On Arch Linux I don't have any problems with the driver version (535.113.01).
What version do you use?

From what I noticed you use wayland.. And I use Xorg and nvidia's proprietary driver. By Waylando testing here, only with the nvidia-open version can I run games through Yuzu! Maybe because Wayland is not compatible with the proprietary driver. I advise you to test it.

**Comment by leiserfg** [comment] 2023-11-04 13:05
Same issue here.

**Comment by leiserfg** [comment] 2023-11-04 13:35
I used to use yuzu in wayland/hyprland and now I'm getting the same error after moving to sway + nvidia update. I'm not sure what of the two causes the issue (or maybe it's using both).

**Comment by erik-kz** [comment] 2023-11-04 17:37
The Vulkan Wayland window system integration code in the NVIDIA driver was pretty much entirely re-written between 535 and 545, so it's definitely possible something broke. The driver does call get_surface_feedback internally, and argument 1 should be the wl_surface associated with the VkSurfaceKHR. It's strange that it would be NULL...

**Comment by willianholtz** [comment] 2023-11-04 18:14
As I said above, I didn't have a problem with the drive, look at the installed version (using Xorg): 
![Screenshot_20231104_151104](https://github.com/yuzu-emu/yuzu/assets/23488207/07c3763d-a528-4580-87b4-b40443ca931d)

I still think it's a problem with Wayland! Because like I said, for me in Wayland, it doesn't work! But Wayland has not been broken with the Nvidia driver for a few years now!

**Comment by lucasreis1** [comment] 2023-11-04 19:26
Can confirm the issue. Working fine on i3, failing on Hyprland and Plasma-wayland with newest Nvidia drivers.

**Comment by erik-kz** [comment] 2023-11-06 18:48
Yeah, it looks like `wayland_ci.surface` in `Vulkan::CreateSurface` is `nullptr` which is not valid usage as per https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkWaylandSurfaceCreateInfoKHR.html

**Comment by yann-boyer** [comment] 2023-11-07 21:04
I can reproduce the issue with a build of yuzu built by myself, have you any clue on how to fix the issue ? Or maybe we'll have to wait a new driver update ?

**Comment by erik-kz** [comment] 2023-11-07 21:07
It's not a driver bug, it's a bug in yuzu. It should not be passing a NULL wl_surface to vkCreateWaylandSurfaceKHR.

**Comment by yann-boyer** [comment] 2023-11-07 23:51
Ah I see, hope it get fixed in a few days.

**Comment by gdp2000** [comment] 2023-11-08 10:10
Looks like the same issue here on my laptop:

CPU: 12th Gen Intel(R) Core(TM) i7-1270P
GPU: NVIDIA T550 Laptop GPU
Driver: NVIDIA 545.29.02

For me the crash happens directly after launching the yuzu app. In the logs in the initial post it looks to me like a game is launched first. Attache my logs.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13295286/yuzu_log.txt)

**Comment by yann-boyer** [comment] 2023-11-08 10:18
A pull request has been opened if it get merged the issue will be resolved.

**Closed** 2023-11-10 15:38 UTC

**Comment by lucasreis1** [comment] 2023-11-11 00:38
Just want to do a late thanks to @erik-kz, who reproduced the bug and made the job of finding the issue at hand pretty easy. Hopefully it's fixed for everyone.
