### ISSUE TITLE
Age of Calamity Char selection bug

### ISSUE THREAD

**Issue by YuNarukamii** [yuzu-emu/yuzu#5036] opened 2020-11-29 13:21 UTC
When i try to go the char menu it drops to 0 FPS and crashes.
Im using Yuzu EA 1131
My Specs:
Intel I5 5500k Professor
GTX 1050 Ti
16GB Ram

**Comment by G-Spawn** [comment] 2020-11-29 13:23
Please consider this which should have been shown to you when you hit 'create new issue'
- You have read the above.
- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

**Comment by G-Spawn** [comment] 2020-11-29 13:24
Besides that I believe this is known / reported before as the game is unstable for the time being?

**Comment by YuNarukamii** [comment] 2020-11-29 13:28
Yeah But with #4871 you only Need to uncheck Use assambly shaders

**Comment by G-Spawn** [comment] 2020-11-29 13:31
this isn't something you'd receive a 'quick' answer for. Time - patience as the emulator gets further developed to handle oddball games like this. I've yet to see any setup get past this character selection screen smoothly.

**Comment by YuNarukamii** [comment] 2020-11-29 13:32
K

**Comment by choppymaster** [comment] 2020-11-29 13:32
As G spawn said, this is a duplicate of #5001. Also log is needed.

**Comment by YuNarukamii** [comment] 2020-11-29 13:34
Im getting it

**Comment by YuNarukamii** [comment] 2020-11-29 13:37
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5612236/yuzu_log.txt)
here ya go

**Comment by G-Spawn** [comment] 2020-11-29 13:39
Thank you. Hopefully the issue will get sorted out someday as for now there is none that I know of.

**Comment by YuNarukamii** [comment] 2020-11-29 13:40
Debug <Critical> video_core\texture_cache\surface_params.cpp:CreateForTexture:95: Assertion Failed! Unimplemented shadow convert format: 0
thats the last line seems like the texture_cache is broke

**Comment by YuNarukamii** [comment] 2020-11-29 13:41
or something in it

**Comment by YuNarukamii** [comment] 2020-11-29 13:42
im looking in it

**Comment by YuNarukamii** [comment] 2020-11-29 14:11
I can switch chars with ryunjix so my game isnt corruptet

**Comment by YuNarukamii** [comment] 2020-11-29 17:19
that bug is with no reason away lol

**Comment by BSoDGamingYT** [comment] 2020-11-29 19:40
This is a duplicate of issue #4871

**Comment by ReinUsesLisp** [comment] 2020-11-29 19:41
Closing as duplicate.

**Closed by ReinUsesLisp** 2020-11-29 19:41 UTC

**Comment by YuNarukamii** [comment] 2020-11-29 20:17
@BSoDGamingYT it is a duplicate of #5001 stupid
