### ISSUE TITLE
Fire Emblem Warriors crash

### ISSUE THREAD

**Issue by Orcacle** [yuzu-emu/yuzu#7280] opened 2021-11-03 20:55 UTC
yuzu mainline 797 (latest as of making this report) and also yuzu Early Access 2156

The game runs flawlessly until the player starts to kill the surrounding enemies, after which it will either freeze immediately or take up to 5 seconds. Visuals will freeze but the gameplay and audio continues, then shortly after the gameplay stops and audio continues, then shortly after that it all stops and the emulator crashes. In most cases however, the game will continue to run flawlessly if the player does not attack any enemies

Using an i5 8400, ZOTAC GTX 1060 6gb mini, 16gb of DDR4 RAM

Here is a log
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/7470596/yuzu_log.txt.old.txt)

**Comment by lat9nq** [comment] 2021-11-03 21:17
Duplicate of #5972

**Comment by G-Spawn** [comment] 2021-11-03 22:18
> Duplicate of #5972

Closing this in favor of ^. Op approved the close.

**Closed by G-Spawn** 2021-11-03 22:18 UTC
