### ISSUE TITLE
TLoZ: TotK Memory Leak

### ISSUE THREAD

**Issue by EmulationEnjoyer** [yuzu-emu/yuzu#11617] opened 2023-09-27 09:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1569

### Description of Issue

Memory leak in The Legend of Zelda: Tears of the Kingdom. This issue started in either 1568 or 1569 mainline builds, it was not present in the 1567 (the version I was using prior to updating today)

![thicc_memory_usage](https://github.com/yuzu-emu/yuzu/assets/144477224/f3abb406-9c34-4d44-a9d6-715936b05cba)

This might be a general problem with the latest couple builds of Yuzu and not specific to this particular game but this is the one I was playing today

### Expected Behavior

~12GB usage after launching, hovering ~16GB after playing for a while

### Reproduction Steps

N/A

### Log File

[yuzu_1569_log.txt](https://github.com/yuzu-emu/yuzu/files/12735273/yuzu_log.txt)

Note: I am using a title update and a handful of mods, these mods I have used with previous versions of Yuzu without issue (dating back a little over a month). Reverting to 1567 using the same update and mods works as expected with no memory leak

Log of 1567 after reverting and playing for a couple hours: 
[yuzu_1567_log.txt](https://github.com/yuzu-emu/yuzu/files/12736860/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 3600
GPU/Driver: RX 5600XT / 23.5.2
RAM: 32GB 3200 MHz
OS: Windows 10 (22H2)

**Comment by liamwhite** [comment] 2023-09-27 13:22
Are you able to indicate if this is from 1568 or 1569?

**Comment by EmulationEnjoyer** [comment] 2023-09-27 15:06
Played for a little over an hour on 1568 and memory usage hovered ~16GB the entire time (which is fairly typical from what I've observed with this game) - changes in 1569 seem to be the cause. I'll attach the log for 1568 in case you want it for comparison

[yuzu_1568_log.txt](https://github.com/yuzu-emu/yuzu/files/12740183/yuzu_log.txt)

**Comment by liamwhite** [comment] 2023-09-27 15:07
@FernandoS27 QCR regression

**Comment by FernandoS27** [comment] 2023-09-27 16:22
Could you check if this happens in OGL as well?

**Comment by Charliviv97** [comment] 2023-09-27 16:53
I reported this problem 1 month ago on Discord, but the problem only existed on Yuzu EA, and since I didn't have my patreon account linked to Discord they decided to ignore it (politely).

In my case I have 128Gb of ram memory so the emulator allows me to play for 2 hours until for obvious reasons the fps become inconsistent (at this point Yuzu uses 50Gb of ram) so we can assure that it has a limitless black hole.

Note that even if I stop the emulation, Yuzu consumes approximately 10GB of ram in the title selector, perhaps this is related or perhaps it is another bug.

I don't know how the emulator works inside but this error appeared in the EA version as now in the Mainline with the launch of the last part of the Y.F.C project

I hope this serves as a reference for anyone who understands how Yuzu works.

**Comment by FernandoS27** [comment] 2023-09-27 17:16
It would be nice if this is checked in OGL as it will help me narrow down the problem.

**Comment by EmulationEnjoyer** [comment] 2023-09-27 17:24
> Could you check if this happens in OGL as well?

Played for about 30 minutes with OpenGL, usage climbed to ~12GB after the bulk of the shaders built, and it hovered there for 20 minutes or so as I ran around/loaded different areas. The leak doesn't seem to happen with OpenGL enabled


[yuzu_1569_opengl_log.txt](https://github.com/yuzu-emu/yuzu/files/12741498/yuzu_log.txt)

**Comment by Charliviv97** [comment] 2023-09-27 17:35
After enjoying a good slide session (my AMD RX 7900 XT and OpenGL have a bad relationship creating shaders) I agree with @EmulationEnjoyer

Yuzu seems to work correctly under OpenGL, stabilizing once the emulator stops creating shaders.

**Comment by gidoly** [comment] 2023-09-28 00:31
it seems to be amd only issue from what i test played 30 minute but it stays 17gb and drop to 16gb on small areas

**Comment by gidoly** [comment] 2023-09-28 01:06
![Uploading Task
![Taskmgr_HTXPhJDQY2](https://github.com/yuzu-emu/yuzu/assets/66776795/4c450b30-00cf-4b99-acdb-081c387cba03)
mgr_IEx90uT9IX.png…]()

this is after 1 hour

**Comment by FernandoS27** [comment] 2023-09-28 01:24
I wonder if AMD has an issue with recycling query pools. It could need the pool to be killed and recreated.

**Comment by Squall-Leonhart** [comment] 2023-10-01 04:41
This issue is only affecting AMD users that have changed the default configuration (which this game needs btw) of High GPU Accuracy, to Normal.

**Comment by EmulationEnjoyer** [comment] 2023-10-01 07:48
When testing 1569 with GPU accuracy set to high the issue still persists and I assume this issue is still present in all builds after 1569 since I haven't seen any commits in reference to a memory fix. Using normal accuracy in previous builds has had no noticeable effect graphically or otherwise and switching to high accuracy only seems to increase frametiming

I can stand completely still in-game and watch the memory usage consistently climb

![sad_memory](https://github.com/yuzu-emu/yuzu/assets/144477224/eadf6f06-6ea2-4f02-8ddb-e8366a398a42)

[yuzu_1569_vulkan_high_log.txt](https://github.com/yuzu-emu/yuzu/files/12776633/yuzu_log.txt)

Log and screenshot are taken after about an hour of playtime

**Comment by Squall-Leonhart** [comment] 2023-10-01 09:14
Ok, I was told the opposite in this case by someone else (won't throw them under the bus :P)

as they said "there are thousands of query pools leaked per second when using gpu normal on amd" was there a reduction iin the leak rate with high or did it remain the same?

**Comment by Charliviv97** [comment] 2023-10-01 09:31
In my case the rate of increase in RAM usage is the same with the GPU precision set to normal and high.

**Comment by EmulationEnjoyer** [comment] 2023-10-01 09:46
> Ok, I was told the opposite in this case by someone else (won't throw them under the bus :P)
> 
> as they said "there are thousands of query pools leaked per second when using gpu normal on amd" was there a reduction iin the leak rate with high or did it remain the same?
> 
> It's not a "memory leak" in the sense that a memory oriented change will indicate a fix, its an Object leak occuring in the AMD driver using a feature that shouldn't be leaking objects. (Driver bug, exposed by Yuzu code change)

From what I observed, setting to high accuracy actually leaked faster reaching 30GB+ in an hour compared to normal accuracy from my original post where I got to roughly 2 hours before I started noticing something was up and checked the process manager to see the memory usage over 32GB and it hitting the swap file - which is what made me notice the sluggishness initially

What is an "object" in programming terms if not memory? Either way, I won't argue semantics and I'm not here to point fingers because I have no doubt this will be addressed sooner rather than later - the reason I used the term "memory leak" in the title is because I know it's a term no programmer worth their salt is pleased to hear and I'm sure the handful of devs that saw this thread were not impressed

When you say it's a problem with the AMD driver API, this is have absolutely zero doubt it would be a cause. I've had this card for about a year and the card itself is perfectly fine, no issues - but the drivers that AMD releases have been the worst problems I've dealt with on my computer in a long time, which is why in my original post I list I'm using the 23.5.2 driver because it's been the most stable driver for me that they've released in ~5 months. No idea why it is they struggle so much on the software side

**Comment by Squall-Leonhart** [comment] 2023-10-01 10:02
> What is an "object" in programming terms if not memory? Either way, I won't argue semantics and I'm not here to point fingers because I have no doubt this will be addressed sooner rather than later - the reason I used the term "memory leak" in the title is because I know it's a term no programmer worth their salt is pleased to hear and I'm sure the handful of devs that saw this thread were not impressed

I consider them differently because objects have actual volume, they are more a block of data that consume memory rather than the memory itself.

**Comment by EmulationEnjoyer** [comment] 2023-10-01 12:18
After playing for an hour with 1573, memory usage never broke 17GB (memory usage is actually slightly down overall)

1573 resolved the memory leak issue. Much appreciated @FernandoS27 and anyone else that looked into it/did testing

I'll let a maintainer close this in case there's something else to be said but otherwise, tyvm

**Closed** 2023-10-01 16:08 UTC
