### ISSUE TITLE
Unimplemented ioctl

### ISSUE THREAD

**Issue by bukyapavankumar** [yuzu-emu/yuzu#3118] opened 2019-11-15 20:29 UTC
Debug <Critical> core\hle\service\nvdrv\devices\nvhost_gpu.cpp:ioctl:60: Assertion Failed! Unimplemented ioctl

required by pokemon sword and shield 

tested in yuzu 60

**Comment by ReinUsesLisp** [comment] 2019-11-22 05:43
Duplicate of #2643.

**Closed by ReinUsesLisp** 2019-11-22 05:43 UTC
