### ISSUE TITLE
[Bug Report] Yuzu crashing constantly on Pokémon sword

### ISSUE THREAD

**Issue by Erix-glitch** [yuzu-emu/yuzu#6596] opened 2021-07-10 20:03 UTC
Hello, my Pokémon sword is crashing constantly and I am unable to progress, here are my specs:
CPU: Intel core i5-10500H
RAM: 8gb
GPU: Nvidia GeForce GTX 1650 Ti (laptop)

Log: 
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6795873/yuzu_log.txt.old.txt)

My renderer is vulkan

**Comment by G-Spawn** [comment] 2021-07-10 22:26
Consider joining the discord  we'll be able to help more efficiently there if there's anything to be done.

**Comment by Moonlacer** [comment] 2021-07-11 00:10
It's expected for now, wait for further improvements

**Comment by gidoly** [comment] 2022-11-03 08:55
duplicate of sw sh multicore crash issue thread

**Closed by gidoly** 2022-11-03 08:55 UTC
