### ISSUE TITLE
Per-game settings don't use the correct GPU drivers

### ISSUE THREAD

**Issue by iamnotkurtcobain** [yuzu-emu/yuzu#12589] opened 2024-01-06 16:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Current builds

### Description of Issue

If I choose the system (or qualcomm drivers) in a game and then start a game with per-game settings enabled Turnip drivers, the qualcomm drivers are used on this game too even if the settings option shows the Turnip drivers ticked.

### Expected Behavior

It should use the correct drivers.

### Reproduction Steps

Just choose qualcomm drivers on one game and Turnip drivers on another game. Start the qualcomm drivers game and you'll see the other game uses them too even though the settings option says otherwise.

### Log File

No Log needed

### System Configuration

CPU: 8gen2, Odin 2 Pro
GPU/Driver: Adreno 740/System Driver, Turnip R14
RAM: 12GB
OS: Android 13 Stock

**Comment by german77** [comment] 2024-01-06 17:45
duplicate of #12553

**Closed by german77** 2024-01-06 17:45 UTC
