### ISSUE TITLE
[EA 971+] Mario Kart 8 Deluxe - update/version 1.7.1 not recognized anymore [xci file]

### ISSUE THREAD

**Issue by Aris-t2** [yuzu-emu/yuzu#4693] opened 2020-09-21 10:16 UTC
I ran some tests on different EA and mainline builds and came across the mentioned issue.

![970](https://user-images.githubusercontent.com/6013569/93755402-82eea200-fc03-11ea-80ef-7e807ff434a8.JPG)
![971](https://user-images.githubusercontent.com/6013569/93755407-8550fc00-fc03-11ea-8eac-f30789279190.JPG)

- using base game and update combined in a xci file
- the issue does not occur with mainline 384 build
- the issue started to occur in EA 971
- tested a few other games like Mario Tennis Aces, Super Mario Odyssey, Animal Crossing NH, Panzer Dragoon Remake and Mario & Sonic at the Olympic Games Tokyo 2020, which all have updates and base game inside xci files. None of the games suffered from that issue

**Comment by FearlessTobi** [comment] 2020-09-21 21:22
Could this possibly be caused by one of your PRs? @Morph1984

**Comment by v1993** [comment] 2020-09-23 14:17
I can observe possibly related issue on another game of mine that's also packed as base game + update in a single XCI file. In my case, however, update is applied to game and is fully functional, yet Yuzu displays game version as 1.0.0 (not updated). In addition, in "Add-Ons" tab of game-specific config "Update" patch doesn't show its version.

**Comment by slashiee** [comment] 2020-09-23 21:51
To add onto the above: my dumps of Astral Chain and Kirby Star Allies do not show the update version correctly on the UI, but the update is applied.

<img width="468" alt="2020-09-23_14-47-55_yuzu" src="https://user-images.githubusercontent.com/15317421/94073299-1b278b00-fdac-11ea-9fcc-7ad805fc01eb.png">
<img width="1281" alt="2020-09-23_14-48-26_yuzu" src="https://user-images.githubusercontent.com/15317421/94073306-1cf14e80-fdac-11ea-97ec-58d212c302a3.png">
<img width="474" alt="2020-09-23_14-49-16_yuzu" src="https://user-images.githubusercontent.com/15317421/94073329-28447a00-fdac-11ea-85a9-1815dcf231c0.png">
<img width="1281" alt="2020-09-23_14-49-42_yuzu" src="https://user-images.githubusercontent.com/15317421/94073338-2d092e00-fdac-11ea-8eb4-aca5e4f6163a.png">

**Comment by Morph1984** [comment] 2020-09-24 05:27
I've replicated this bug on both SMO and BotW carts with bundled updates, currently working to fix this issue

**Comment by Morph1984** [comment] 2020-09-25 05:23
Should be resolved in EA 992, please test

**Comment by Aris-t2** [comment] 2020-09-25 06:30
Fixed, thanks.

![image](https://user-images.githubusercontent.com/6013569/94234128-5be8e680-ff09-11ea-882c-4db75a82cf40.png)

**Comment by Aris-t2** [comment] 2020-09-26 08:10
Since the initial issue is fixed we can close this now.

**Comment by v1993** [comment] 2020-09-26 08:51
I think it would have been better kept open until merge of #4710. This issue would get automatically closed with helpful note once merge happened.

**Closed** 2020-10-07 05:27 UTC
