### ISSUE TITLE
Luigi's Mansion 3 not rendering well

### ISSUE THREAD

**Issue by FranciscoReMo** [yuzu-emu/yuzu#3071] opened 2019-11-04 06:42 UTC
In the latest build, it's all in black or not rendering well.

Yuzu 36:
![image](https://user-images.githubusercontent.com/43990816/68103004-66efee00-fed5-11e9-8024-5ac05b3b99ea.png)
![image](https://user-images.githubusercontent.com/43990816/68103011-6b1c0b80-fed5-11e9-8714-c4d4027677f3.png)
![image](https://user-images.githubusercontent.com/43990816/68103016-7111ec80-fed5-11e9-9e9e-c89675d6b74c.png)
![image](https://user-images.githubusercontent.com/43990816/68103024-766f3700-fed5-11e9-8367-98b9f47a1b14.png)

Yuzu 42:
![image](https://user-images.githubusercontent.com/43990816/68103061-a28ab800-fed5-11e9-974c-60e421ad6cb4.png)
![Captura](https://user-images.githubusercontent.com/43990816/68103068-aae2f300-fed5-11e9-980f-0577a4e974f6.JPG)
![Captura2](https://user-images.githubusercontent.com/43990816/68103070-ad454d00-fed5-11e9-8e11-215ab30a0ab4.JPG)
![Captura3](https://user-images.githubusercontent.com/43990816/68103074-af0f1080-fed5-11e9-9066-d07ef461d78f.JPG)
![Captura4](https://user-images.githubusercontent.com/43990816/68103077-b0403d80-fed5-11e9-9e16-b235c23b607e.JPG)
![image](https://user-images.githubusercontent.com/43990816/68103082-b46c5b00-fed5-11e9-8ca1-a7943b16a6d3.png)

Log:
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3802839/yuzu_log.txt)

PD: Please add Luigi's Mansion 3 in compatibility.

**Comment by Hexagon12** [comment] 2019-11-04 08:52
Duplicate of #3068

**Closed by Hexagon12** 2019-11-04 08:52 UTC
