### ISSUE TITLE
Headlamp issue in Pikmin 4

### ISSUE THREAD

**Issue by GhostBoy111** [yuzu-emu/yuzu#11125] opened 2023-07-21 09:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3764

### Description of Issue

When entering the first "dark" cave that requires the headlamp to navigate, the headlamp either flickers or doesn't work at all depending on where you're standing in said dungeon.

### Expected Behavior

Headlamp should illuminate a small space around the player character.

### Reproduction Steps

Just enter the cave and it happens every time. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12122149/yuzu_log.txt)

### System Configuration

CPU: i9 10850k
GPU/Driver: Nvidia RTX 3080 Ti, driver version 536.40
RAM: 16.0GB Dual-Channel DDR4 @ 1600MHz (16-18-18-38)
OS: Windows 11

**Comment by tagg7** [comment] 2023-07-21 10:34
Can confirm that I encountered the exact same issue on Vulkan. I had to switch over to Ryujinx to get past that part.

**Comment by filsdugrand** [comment] 2023-07-21 16:05
Yup same problem

**Comment by KataKokinho** [comment] 2023-07-21 20:50
Same problem here. RTX 3060.

**Comment by dcbishop** [comment] 2023-07-23 05:37
Same here. I suspect it's only rendering a single light at a time so any environmental lights around are likely to be blocking it.

Changing the rotation and angle can sometimes cause it to turn on (probably it's becoming the first light).

**Comment by joniale** [comment] 2023-07-23 09:02
I have the same issue with gtx3070, vulkan, high precission.

**Comment by SnekSnak** [comment] 2023-07-23 10:25
Is this the same issue people are having? I was also getting texture flickering on the wood in the tutorial. This is the only issue I seem to have but it makes the game unplayable.

https://github.com/yuzu-emu/yuzu/assets/38109656/76cb395e-357b-4b7d-9f83-be0ddd9132a0

**Comment by Springpaw** [comment] 2023-07-23 12:59
Can confirm same problem here.

**Comment by joniale** [comment] 2023-07-23 15:26
> 

No. In my case you cannot see anything. It is totally dark. Depending on the angle of the camera sometimes the light is activated

**Comment by Conan179** [comment] 2023-07-23 16:01
Is this the same?
https://www.dropbox.com/s/v7nq8k8duspyqcb/Decky-Recorder_2023-07-23_17-56-57.mp4?dl=0
(Steamdeck)

**Comment by joniale** [comment] 2023-07-23 16:15
> Is this the same? https://www.dropbox.com/s/v7nq8k8duspyqcb/Decky-Recorder_2023-07-23_17-56-57.mp4?dl=0 (Steamdeck)

No. For me it is totally dark

**Comment by relu419** [comment] 2023-07-23 18:54
Same problem even with high GPU accuracy.

**Comment by Foxlum** [comment] 2023-07-23 21:02
> Same problem even with high GPU accuracy. Flickering and lighting error.

GPU Extreme doesn't change the situation either, on a RX 6600. There is an issue with the dynamic AO as well which flickers significantly in a similar manner.

**Comment by Conan179** [comment] 2023-07-23 22:18
> > Is this the same? https://www.dropbox.com/s/v7nq8k8duspyqcb/Decky-Recorder_2023-07-23_17-56-57.mp4?dl=0 (Steamdeck)
> 
> No. For me it is totally dark

https://github.com/yuzu-emu/yuzu/assets/1906242/e04c7f47-f4c7-498d-bf44-886cda7b7b41



are you in this cave?

**Comment by Foxlum** [comment] 2023-07-24 04:10
> > > Is this the same? https://www.dropbox.com/s/v7nq8k8duspyqcb/Decky-Recorder_2023-07-23_17-56-57.mp4?dl=0 (Steamdeck)
> > 
> > 
> > No. For me it is totally dark
> 
>  Decky-Recorder_2023-07-24_00-14-52.mp4 
> are you in this cave?

That cave has a lot of lights within it, pretty much is constantly flickering which light it shows, or not at all.

**Comment by Conan179** [comment] 2023-07-24 06:37
joniale writes there
> > Is this the same? https://www.dropbox.com/s/v7nq8k8duspyqcb/Decky-Recorder_2023-07-23_17-56-57.mp4?dl=0 (Steamdeck)
> 
> No. For me it is totally dark
 
he has an additional bug that leaves the picture completely dark so he doesn't see anything. I can't replicate that on my stream deck, only in this one hell where I posted it's pitch black, but that's not a mistake, it's on purpose.

**Comment by Imorales80** [comment] 2023-07-24 13:38
Same here, (rtx3060, i7-12700KF) playing on yuzu 1504 (2023-07-23) and the issue persists, a lot of flickering from the headlamp and headlamp+, equipping and unequipping doesn't seem to affect the issue, light visible from some angles and locations of caves only. There's also the issue of, when playing for long periods of time, performance tanks heavily and video playback such as the title screen and the preview for oatchi's skills, gadgets and such start to flicker, which usually fixes after resetting the emulator.

**Comment by Ariensy** [comment] 2023-07-24 19:02
Can confirm that the bug specifically is a result of the emulator only being able to render one lightsource at a time. Depending on your camera angle and how many objects are placed nearby, mushrooms will randomly render one at a time, and if no glowing mushrooms are in view the headlamp will actualy start glowing.

**Comment by Judosii** [comment] 2023-07-24 23:41
Has anyone found a fix for this then ?

**Comment by Zer0Rem** [comment] 2023-07-25 13:33
Same issue for me

**Comment by Shroopy** [comment] 2023-07-27 19:31
Still an issue

**Comment by cachoubretzel** [comment] 2023-07-28 11:04
i have the same issue

**Comment by gnc431** [comment] 2023-07-29 05:27
same issue here.

**Comment by Evonos** [comment] 2023-07-30 13:43
Exact same issue on the 2nd zone in the cave you need a headlamp for its DARK ( with Headlamps ) rarely lights flicker 1 time on.

6800XT
R7 5700X
Win11
32gb
Yuzu EA 3782

**Comment by no0dlz** [comment] 2023-07-30 19:44
Same bug here in all dark caves.

6700k
3060 12GB
Win 11
16GB RAM
Yuzu EA 3782

**Comment by CVela** [comment] 2023-08-02 22:06
Happens to me as well, unfortunately. Changed graphical settings around but no luck.
RX 7900 XTX
i7-13700K
32GB DDR5
Win 11
Yuzu 1515

**Comment by CJRed1** [comment] 2023-08-05 04:49
Exact same issue here

**Comment by relu419** [comment] 2023-08-18 15:49
Yes. This is a big deal to fix this. I can't play anymore on emulator, since this is an important thing.

**Comment by hunter2k01** [comment] 2023-08-18 21:40
Still an issue for me on 1529

**Comment by SonicTrance** [comment] 2023-08-18 22:39
I wonder if a fix will ever happen.

**Comment by CVela** [comment] 2023-08-18 23:13
> Happens to me as well, unfortunately. Changed graphical settings around but no luck. RX 7900 XTX i7-13700K 32GB DDR5 Win 11 Yuzu 1515

I wanted to add, I think the issue is better when riding Oatchi for some reason. Off of him, it's complete darkness or flickering, but on him the head lamp is more stable.

**Comment by jlarnal** [comment] 2023-08-20 00:14
Yup... Shaders are definitely weird in this game.
For those wondering, this is base camp :
![0100b7c00933a000_2023-08-20_02-11-33-608](https://github.com/yuzu-emu/yuzu/assets/15753255/ea7b150c-97d5-4dc0-b829-02a7c277fbdc)

**Comment by relu419** [comment] 2023-08-20 02:29
> Yup... Shaders are definitely weird in this game. For those wondering, this is base camp after completing the _Engulfed Castle_ cave in the _Serene Shores_ area : ![0100b7c00933a000_2023-08-20_02-11-33-608](https://user-images.githubusercontent.com/15753255/261824895-ea7b150c-97d5-4dc0-b829-02a7c277fbdc.png)

This isn't the problem with the OP problem. Set your GPU accuracy to high and check your shader. I just use Async Shader and NP.

**Comment by jlarnal** [comment] 2023-08-21 11:12
Nope... GPU accuracy was set to Extreme.

**Comment by relu419** [comment] 2023-08-26 16:41
Any workaround for this?

**Comment by SonicTrance** [comment] 2023-08-26 17:22
> Any workaround for this?

I don't think so, at least not yet :(

**Comment by cachoubretzel** [comment] 2023-08-26 21:15
> 

it's weird because it's a major and well known issue with the game but there is no fix yet

**Comment by dasbootbee** [comment] 2023-08-26 22:00
I get the feeling nobody on the dev team cares about Pikmin

**Comment by skylarforce** [comment] 2023-08-27 08:01
Same exact issue for me, praying someone can fix

**Comment by JRGlitches** [comment] 2023-09-06 01:04
Same lamp flickering issue here,
RX 6700XT
Ryzen 5 3600
32 GB of Ram

**Comment by nktails** [comment] 2023-09-07 02:38
Also experiencing this, happens on both my windows machine and my steam deck.

**Comment by RollingStar** [comment] 2023-09-15 02:41
Has anyone tried bisecting with old versions of yuzu?

**Comment by Jaitsu** [comment] 2023-09-16 01:34
Tested this under Vulkan and OpenGL, it's present in both, though in Vulkan it seems to eventually shut off the light entirely while in OGL it just consistently flickers indefinitely. It's not just the headlamp, some other local light sources are affected but not all. It may relate to the intensity of the light, as for example the faint local light of the Beagle's thrusters as it flies into the end of day cutscene seems unaffected.

> Has anyone tried bisecting with old versions of yuzu?

Went back in hundreds as far back as EA 3400, could go further, but it's still present there, albeit the flashing seems to be at a slower, more bearable rate than current versions.

**Comment by relu419** [comment] 2023-09-16 04:34
Well. Let's hope for fix... Someday.

**Comment by IceMaverick** [comment] 2023-09-16 20:19
#11487 is related/duplicate Issue.

**Comment by Jaitsu** [comment] 2023-09-19 04:47
It seems as though light intensities are being applied to the wrong light sources? I've noticed the problem goes away/is much more minimal in underground areas with fewer local light sources, whereas areas with many local lights (such as the blue mushrooms seen in above screenshots) are affected much more strongly.

Turning the camera so the light sources are out of frame and culled reduces the problem, and slowly turning the camera toward light sources seems to add more brightness to the player's headlamp until it overflows and blacks out entirely, then it returns to normal as the light sources are culled out of frame again.

EA 3879. Including a log, and a save file in another cave that's ideal for testing this if you stand in the southeast corner after activating the mushrooms around the level by going near them.

https://github.com/yuzu-emu/yuzu/assets/463807/d8760302-d399-4512-8d4b-3cd854ba2902

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12655956/yuzu_log.txt)
[0100B7C00933A000.zip](https://github.com/yuzu-emu/yuzu/files/12655967/0100B7C00933A000.zip)

**Closed** 2023-09-23 11:00 UTC
