### ISSUE TITLE
Luigi's Mansion 3 Flickering Lights

### ISSUE THREAD

**Issue by AlexFARK** [yuzu-emu/yuzu#9651] opened 2023-01-20 19:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1314

### Description of Issue

I reopened Luigi's Mansion 3 after several months and I'm having big lighting issues: flickering lights and sometimes luigi turns gray under some lights.

https://user-images.githubusercontent.com/106443858/213788458-1e79fb40-6378-4b63-9289-a93fd9a29e7e.mp4

https://user-images.githubusercontent.com/106443858/213788559-ef44f500-f8c4-48c7-9908-cf38baec6dee.mp4

### Expected Behavior

Luigi shouldn't turn gray and the lights shouldn't flicker. I played this game in March 2022 and it didn't have any kind of lighting problem.

### Reproduction Steps

Just open the game
[LM3 Saves.zip](https://github.com/yuzu-emu/yuzu/files/10469507/LM3.Saves.zip)

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/10469643/yuzu_log.txt)

### System Configuration

CPU: Intel Core i3 9100F
GPU/Driver: Nvidia GeForce RTX 3060 Ti / 527.56
RAM: 16GB
OS: Windows 10 21H2

**Comment by AlexFARK** [comment] 2023-01-20 19:40
Oh, I forgot to write that i use:
60Fps Mod; No Lens Flare Mod; Dynamic Resolution Off Mod

And i have ver 1.4.0 of the game

**Comment by Kelebek1** [comment] 2023-01-21 06:31
It's fixed by #9631.

**Comment by AlexFARK** [comment] 2023-01-21 12:13
Oh thanks! But i didn't understand what this is and what should i do with that color thing. Can you help me?

**Comment by solarmystic** [comment] 2023-01-31 16:19
This can be closed now since #9631 has been merged to mainline 1326. No more  flickering confirmed.

**Comment by benderscruffy** [comment] 2023-09-27 12:50
@FearlessTobi 
Can be closed

**Closed** 2023-09-27 21:27 UTC
