### ISSUE TITLE
Weather doesn't reset in yuzu when dates are changed

### ISSUE THREAD

**Issue by zakion1** [yuzu-emu/yuzu#3466] opened 2020-02-26 22:43 UTC
### Weather doesn't resets in yuzu when the dates are changed
![image](https://user-images.githubusercontent.com/61523047/75394173-98257b80-5915-11ea-80ed-fe0766b6bfec.png)
 the weather doesn't change in yuzu as it completely ignoring the pc mentioned time,that means certain pokemon can't be encountered in wild area if the game doesn't resets the weather to change there pokemon area spawn , it all works in regular switch

_Originally posted by @zakion1 in https://github.com/yuzu-emu/yuzu/issues/3320#issuecomment-591679365_

**Comment by DarkLordZach** [comment] 2020-02-26 23:43
This is caused by inaccuracies in yuzu's virtual filesystem. Preliminary internal testing has shown this to be fixed by fixing those problems.

**Comment by swablueme** [comment] 2020-02-27 04:16
> This is caused by inaccuracies in yuzu's virtual filesystem. Preliminary internal testing has shown this to be fixed by fixing those problems.

It works for me though?

**Comment by vishhvak** [comment] 2020-05-27 13:42
What firmware files do I need to make this work? Or is there any other way at this time to get change of weather working?

**Closed** 2021-09-18 21:00 UTC
