### ISSUE TITLE
Mario Oddessy freezes after starting game on Linux Mint 19

### ISSUE THREAD

**Issue by dukenukemx** [yuzu-emu/yuzu#2560] opened 2019-06-07 19:41 UTC
When you start the game and get to the point where you need to look around the game will freeze as well as the entire PC.  The controls also don't seem to remember what I've setup for a gamepad but will remember the keyboard controls.  

System specification:
AMD FX 8350
Linux Mint 19 Cinnamon
RX470, AMD GPU, AMDGPU drivers from Oibaf PPA
yuzu-canary #2355 commit: Head eb6e511

**Comment by Hexagon12** [comment] 2019-06-07 19:45
Duplicate of #2559, closing

**Closed by Hexagon12** 2019-06-07 19:45 UTC
