### ISSUE TITLE
Yuzu crash when launching Tears of the Kingdom

### ISSUE THREAD

**Issue by Duxkle** [yuzu-emu/yuzu#10314] opened 2023-05-15 10:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1434

### Description of Issue

When launching Tears of the Kingdom, it shows the Yuzu loading screen, freezes then CTD.

### Expected Behavior

Game should launch

### Reproduction Steps

I had mods installed, then changed/updated them. Also disabled update 1.1.0. With everything disabled, same result. 

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11476953/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 3400g
GPU/Driver: RTX 2060 12GB
RAM: 16GB 3000mhz
OS: Windows 11

**Comment by Squall-Leonhart** [comment] 2023-05-15 12:01
> GPU/Driver: RTX 2060 12GB

Didn't even know this existed, but be assured this is a duplicate of https://github.com/yuzu-emu/yuzu/issues/10290

**Closed** 2023-05-15 15:01 UTC
