### ISSUE TITLE
Crash on vulcan after vram is full, doing fine on open GL

### ISSUE THREAD

**Issue by MikhailVector** [yuzu-emu/yuzu#11267] opened 2023-08-12 04:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline yuzu 1520 (2023-08-10)

### Description of Issue

Running on rx 580 4 GB on current driver 23.7.2-win10-win11-july25
playing tears of the kingdom
using yuzu 1520 (2023-08-10)

Game Runs fine at 4k with no astc recompression, only getting shorttime slow fps (~25 in basecamp in front of castle hyrule) some times but runs rock-solid otherwise

when changing to vulcan, it crashes after playing like 1 minute after filling up the 4 GB of VRAM
i have to switch to BC1 and use default 1080 / 720 to play without crashes (and even here it crashes after some hours of playing)

Running on rx 580 4 GB on current driver 23.7.2-win10-win11-july25

is this maybe related to https://github.com/yuzu-emu/yuzu/pull/10411 ?

is the only solution for me to play stable using OPEN GL?

thanks for reading!

### Expected Behavior

game might gets slower when VRAM is full but does not crash, as it does on open GL

### Reproduction Steps

set to x2 (1440p / 2160p) resolution and  set ASTC recompression to "uncompressed" and visit a crowded place in game, run around a bit and so stuff and it will crash

### Log File

everything does fine then it just dies

[ 123.635487] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:588: 0xe98987a1fb5697a5
[ 123.638970] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:588: 0xc47fd06915c26eca
[ 123.642557] Render.Vulkan <Info> video_core\renderer_vulkan\vk_pipeline_cache.cpp:CreateGraphicsPipeline:588: 0xde

### System Configuration

CPU: amd ryzen 7 3800x 8 core processor
GPU/Driver: amd rx 580 4 GB / 23.7.2-win10-win11-july25
RAM: 32 + 14 pagefile
OS: win 10 22H2 Build 19045.2251

**Comment by Squall-Leonhart** [comment] 2023-08-13 13:15
This is a duplicate of every other 4GB device OOM crashing in TOTK issue on this issue tracker.

**Closed** 2023-08-13 21:04 UTC
