### ISSUE TITLE
totk crash while entering wind temple

### ISSUE THREAD

**Issue by rookieplayi** [yuzu-emu/yuzu#10505] opened 2023-05-30 13:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

mainline 1452

### Description of Issue

while entering the blizzard entrance to the wind temple  the game always crashes

### Expected Behavior

to make the game doesnt crash

### Reproduction Steps

can you provide me a save to the wind temple to prevent this

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11600529/yuzu_log.txt.old.txt)

### System Configuration

CPU: gen 8 intel i3
GPU/Driver: intel uhd graphics
RAM: 8gb dual channel
OS: windows 11 22h2

**Comment by Squall-Leonhart** [comment] 2023-05-30 20:52
Just completed this temple in a single sitting,

Your hardware is the cause, and its very doubtful that UHD graphics will ever run well without both texture conversion and reducing the internal resolution.

**Comment by FearlessTobi** [comment] 2023-05-31 14:57
I'm closing this as a duplicate of the numerous other totk intel crashes already reported on our tracker.

**Closed by FearlessTobi** 2023-05-31 14:57 UTC
