### ISSUE TITLE
Hogwarts Legacy

### ISSUE THREAD

**Issue by IrsyadLuffy** [yuzu-emu/yuzu#12645] opened 2024-01-11 08:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 189 or any version that start to support UE4

### Description of Issue

https://github.com/yuzu-emu/yuzu/assets/45539585/fcd419f3-bc59-4cae-8802-1d3c1e3b6182

Hogwarts Legacy black texture and bad rendering. Crash on 8GB RAM but playable with major graphic bug on 12GB RAM. Using any turnip driver (mine only support 24 and above) crash on 23.0.0 with partial a7xx and below. 

### Expected Behavior

The game should render correctly. 

### Reproduction Steps

Play the game until you reach Hogwarts and you will see this occured. 

### Log File

No log file generated.

### System Configuration

CPU: Snapdragon 8+ Gen 1
GPU/Driver: Adreno 730
RAM: 12GB
OS: Android 13

**Comment by Squall-Leonhart** [comment] 2024-01-11 10:55
Duplicate of existing issue(s)

This game is not properly rendered on any platform that Yuzu supports.

**Closed** 2024-01-11 13:22 UTC
