### ISSUE TITLE
[Android] Regression performance since commit e968264

### ISSUE THREAD

**Issue by OceanSea1** [yuzu-emu/yuzu#13123] opened 2024-02-23 05:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Build 260, 261, 262 and 264 in this moment.

### Description of Issue

Super Mario Odyssey (and probably other games) regression performance in certain game contexts.

There is a drastic slowdown in the gaming experience with sudden and unnatural drops in fps.

These slowdowns last about 2-3 seconds in the case of chaotic and/or moving scenes with many characters on the screen.

The issue started to appear from commit e968264 - texture cache - build 260 of the Android version. (build 259 is not affected from this problem)

Additionally, the overall device heat seems slightly increased.

### Expected Behavior

Return to the normal operating condition of the emulator and normalization of the heat generation caused by the commit in question.

Thank you.

### Reproduction Steps

The issue occurs occasionally while playing, sometimes it is immediate, other times not, it depends on the type of texture load and therefore on the number of objects on the scene.

However, I attach videos to help you understand the situation better.

(shop purchasing clothing and objects)

### Log File

N/A

### System Configuration

CPU: SnapDragon Gen 3
GPU/Driver: Turnip 24 Revision 17 V2
RAM: 12 GB
OS: Android 14

https://github.com/yuzu-emu/yuzu/assets/160583350/0753e47d-6a6c-4d04-a324-87da6874a4fb

**Comment by liamwhite** [comment] 2024-02-23 05:42
This is almost certainly a duplicate of #13101
Try disabling vibration

**Comment by liamwhite** [comment] 2024-02-23 08:09
Duplicate of #13101

**Closed by liamwhite** 2024-02-23 08:09 UTC
