### ISSUE TITLE
Splatoon 2 Enemy Ink In your own ink issue on vulkan

### ISSUE THREAD

**Issue by Silverdragon122** [yuzu-emu/yuzu#8208] opened 2022-04-14 20:15 UTC
So Ive been having this issue on vulkan in splatoon 2 where in your own ink the game thinks it is enemy ink. I have attached A screenshot of this and Ive seen it happen to other people. It would be great if this would be fixed. It does not seem to happen on Opengl from my testing

![image](https://user-images.githubusercontent.com/101513517/163468416-cbdf4354-67ee-429f-9fa3-da177ae6d9f9.png)

**Comment by Silverdragon122** [comment] 2022-04-14 22:40
https://user-images.githubusercontent.com/101513517/163489214-14ab7aab-477b-4acb-b1fd-524a90244cf4.mp4

This also happens, a different problem but still very weird. (The bad quality is to make it under 10mb, GitHubs max)

**Comment by funtimeandrefoxy** [comment] 2022-04-15 09:01
this bug has been happening for a long time. It manifests itself in different ways depending on the pc (which also has this bug of course) but it always occurs in the same objs. For example I can't climb a wall even though I try friendly paint or I can climb a wall even though there's no paint on it and among other types of this bug. This doesn't only affect the player but the Octos as well, the Salmonoids seem to be unaffected because they probably ignore ink normally (and this is not a bug I think). Due to these bugs there are some stages in Octo Canyon and most stages in Octo Expansion that are impossible to finish. The only way I can complete these levels is either putting the game in OpenGl or adding a mod called "Public Patch" in which I activate "fly mode" and "No Death Zones".

**Comment by PrinceBubloo** [comment] 2022-04-15 17:10
Do upload log pls

**Comment by lat9nq** [comment] 2022-07-09 01:25
Duplicate of #4982

**Closed by lat9nq** 2022-07-09 01:25 UTC
Labels: gpu-issue, vulkan
