### ISSUE TITLE
shader not linked [Error]

### ISSUE THREAD

**Issue by greggameplayer** [yuzu-emu/yuzu#493] opened 2018-05-31 23:31 UTC
## Hardware Specs : 
- Nvidia GeForce GTX 960
- Intel I7-7700K @ 4.5Ghz
- 8 GB Of Ram 3200Mhz
- Windows 10 Pro

## The issue : 
when you launch 1.2.Switch on multi-cores, the game crash with shader not linked.
but on single-core this error doesn't appear.

## List of games with this error : 
- 1.2.Switch
- Arms
- Lego World
- Lego Ninjago the movie videogame
- Super Mario Odyssey

## The last part of the log : 
![Log Image](https://image.noelshack.com/fichiers/2018/22/5/1527809392-capture2.png)

**Comment by Hexagon12** [comment] 2018-06-01 08:26
You can't get to the opening screen, right? What yuzu version are you using?

**Comment by greggameplayer** [comment] 2018-06-01 21:04
yes and I'm currently using HEAD-bdd68fc.

**Comment by Elenedeath** [comment] 2018-06-02 19:47
same for me with a similar configuration
Nvidia GTX 970
Intel I7-6700K
24 go de ram@3000mhz
W10 Pro 64bits

**Comment by greggameplayer** [comment] 2018-06-02 21:51
@Elenedeath canary build and nightly build are the same currently so it's that why The binding of isaac run at the same fps on both builds types.

**Comment by greggameplayer** [comment] 2018-06-03 19:31
this error appear on newer versions too.

**Comment by Elenedeath** [comment] 2018-06-03 19:50
I found why i got the error on all version, it's due to check the "enable multicore" option.
when you uncheck it, the error disappear but i got another error

"[  12.394379] Debug <Critical> video_core/engines/maxwell_3d.cpp:operator():160: Assertion Failed!
Writing the entire query result structure is unimplemented"

**Comment by greggameplayer** [comment] 2018-06-03 19:57
@Elenedeath this error is due to the fact that not all the maxwell 3d engine have been implement

**Comment by Subv** [comment] 2018-06-04 01:29
The 'Shader not linked' error when multicore is enabled is caused by yuzu trying to perform OpenGL state manipulation from a thread that isn't the current OpenGL thread. I don't know if the games are submitting commands from multiple threads or if they're just submitting commands from a single thread that isn't running in the host EmuThread.

**Comment by greggameplayer** [comment] 2018-06-04 01:38
@Subv currently yuzu submitting commands from a single thread or multiple ?

**Comment by Hexagon12** [comment] 2018-07-26 14:06
This issue is fixed now.

Requesting to close.

**Closed** 2018-07-27 05:18 UTC
