### ISSUE TITLE
TotK crashes

### ISSUE THREAD

**Issue by hrkfdn** [yuzu-emu/yuzu#11640] opened 2023-09-30 19:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1572 (Flatpak)

### Description of Issue

After playing TotK for a while yuzu will crash. This was not a problem a few weeks ago, so it seems like a recently introduced regression. Could it be memory exhaustion (`mmap`/`mprotect` fails).

### Expected Behavior

Does not crash.

### Reproduction Steps

Play TotK for a while (~10 minutes), have game crash.

Installed mods: 
![image](https://github.com/yuzu-emu/yuzu/assets/19884/9e337d65-e3c8-435f-927d-c4f64cc30643)

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/12775428/yuzu_log.txt.old.txt)

### System Configuration

CPU: AMD Ryzen 7 5800X3D 
GPU/Driver: AMD Radeon™ RX 6700 XT
RAM: 32 GiB
OS: Linux 6.4.0-0.deb12.2-amd64 on Debian bookworm

**Comment by FernandoS27** [comment] 2023-09-30 20:05
Do you happen to run out of memory?

**Comment by hrkfdn** [comment] 2023-09-30 20:14
There's still plenty left (at least 20 GiB), so I don't think that's it. Only thing I can think of is Flatpak imposing memory limits? But then again I don't understand why it worked fine before the past updates.

**Comment by ArjukKagrim** [comment] 2023-09-30 20:48
For me TotK also crashes since last update. I used yuzu mainline 1567 before and had no problems / could play for hours. Now with 1572 TotK crashed after 40-50 minutes. Seems to have something to do with RAM, I have 32 GB but after said time I run out of memory. When observing memory in task-manager after starting the game it steadily increases till I run out of it and yuzu crashes.

**Comment by Squall-Leonhart** [comment] 2023-10-01 04:32
can you test to see if `sudo sysctl -w vm.max_map_count=262144` helps

**Comment by Squall-Leonhart** [comment] 2023-10-01 04:40
Scratch that, please set the game to High accuracy - the game needs it for some things anyway and its the default for a reason, this would be  duplicate of #11617 which Fernando is already looking into.

**Comment by ArjukKagrim** [comment] 2023-10-01 08:46
In my case, changing the setting to High accuracy does not change the memory issue / crashing behavior.

**Comment by Squall-Leonhart** [comment] 2023-10-01 09:13
I was told that High should be fine, Hrmmmm, but both of you are not seeing a difference. in the leak rate.

**Comment by hrkfdn** [comment] 2023-10-01 09:33
@Squall-Leonhart You mean this?
![Screenshot from 2023-10-01 11-33-07](https://github.com/yuzu-emu/yuzu/assets/19884/1c26074a-287a-4437-8f47-31b537b8a64d)

There's Accurate and Paranoid, which one would be High Accuracy?

**Comment by Squall-Leonhart** [comment] 2023-10-01 09:45
that is the one, but its been confirmed on windows and above by ArjukKagrim that it doesn't help

**Comment by hrkfdn** [comment] 2023-10-01 09:51
Yeah can second that, it still crashes with the same error messages in the log + increasing memory size.

**Comment by Squall-Leonhart** [comment] 2023-10-01 10:13
not sure if the action builds create flatpaks, but a change has been made by Fernando that could do with testing.

**Comment by ArjukKagrim** [comment] 2023-10-01 12:11
The last build 1573 has fixed the issue for me. I did not notice any increase in RAM usage for over 1h.

**Closed** 2023-10-01 16:07 UTC
