### ISSUE TITLE
Poor performance when running under native wayland with desktop display scaling

### ISSUE THREAD

**Issue by vasishath** [yuzu-emu/yuzu#13027] opened 2024-02-16 10:27 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1706

### Description of Issue

When running on wayland under linux with display scaling enabled in KDE/GNOME settings (mine is set to 125%), the performance drops significantly when increasing window size or switching to fullscreen. Performance is fine is scaling is set to 100%. The issue is more pronounced with fractional scaling, as with 200%, the performance impact is far less. Also reproducible on GNOME wayland.
Mangohud shows significantly higher GPU usage with increasing window size.

Issue does not occur when yuzu is used in xwayland mode.

The SDL yuzu-cmd does not have this issue, even when used with `SDL_VIDEODRIVER=wayland`.  I get full performance at all window sizes and full screen.

It seems that yuzu GUI might be drawing at a higher resolution leading to this. Mangohud appearing quite small in size indicates that.

With yuzu GUI:
![yuzu_qt_fullscreen](https://github.com/yuzu-emu/yuzu/assets/6087015/14e83578-f8ba-430a-b2ba-1f2668a6f5e9)

With yuzu-cmd:
![yuzu_sdl_fullscreen](https://github.com/yuzu-emu/yuzu/assets/6087015/db729652-6d25-4e38-87a6-ff13f3620060)

### Expected Behavior

Performance should not be impacted by window size.

### Reproduction Steps

* In KDE/GNOME wayland settings, enable display scaling.
* Start yuzu under native wayland mode.
* Start any game
* Increase window size or switch to fullscreen

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14309701/yuzu_log.txt)

### System Configuration

CPU: Intel Core i5 8250U
GPU/Driver: NVIDIA MX150M
RAM: 16GB
OS: Arch Linux 6.7.3
KDE Plasma 6 RC2

**Comment by german77** [comment] 2024-02-16 11:27
Seems like you maxed out your gpu capabilities. Not really sure why Qt is tasking you gpu so much more.

**Comment by vasishath** [comment] 2024-02-16 12:18
> Seems like you maxed out your gpu capabilities. Not really sure why Qt is tasking you gpu so much more.

I am using 2x resolution in yuzu. But that doesn't change the fact that the bigger window size is asking for more GPU resources. But only on wayland and with desktop scaling.

I will share GPU usage with 1x resolution in yuzu as well

**Comment by vasishath** [comment] 2024-02-16 12:32
> > Seems like you maxed out your gpu capabilities. Not really sure why Qt is tasking you gpu so much more.
> 
> I am using 2x resolution in yuzu. But that doesn't change the fact that the bigger window size is asking for more GPU resources. But only on wayland and with desktop scaling.
> 
> I will share GPU usage with 1x resolution in yuzu as well
> 
> yuzu GUI windowed (1x resolution): ![yuzu_qt_1x](https://private-user-images.githubusercontent.com/6087015/305412550-58b728f3-1a55-4e51-9575-d1559dd90e62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODY2NTAsIm5iZiI6MTcwODA4NjM1MCwicGF0aCI6Ii82MDg3MDE1LzMwNTQxMjU1MC01OGI3MjhmMy0xYTU1LTRlNTEtOTU3NS1kMTU1OWRkOTBlNjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMTIyNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzMzNDViZGQzM2ViYjkyMDFjNjVmMzU4YmU1MjJmYmFmYzNhN2EzZjRlMTM4ODZhMDYzNGJjYzMzMWRlOGFiMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._DkVowwslmZIocSgNayt06PJQtNO3a0M43jbIEXvw58)
> 
> yuzu GUI fullscreen (1x resolution): ![yuzu_qt_1x_fullscreen](https://private-user-images.githubusercontent.com/6087015/305412692-4d79c474-4075-47d3-886e-91572ab060f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODY2NTAsIm5iZiI6MTcwODA4NjM1MCwicGF0aCI6Ii82MDg3MDE1LzMwNTQxMjY5Mi00ZDc5YzQ3NC00MDc1LTQ3ZDMtODg2ZS05MTU3MmFiMDYwZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMTIyNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzY0ZjQyNWNlZmJiNWQ0OGMzNTNhNTMyMDg5MGVhNjdjYmVhZTc5NmE2YWE0NzA2ZmMyNmYzN2UyNjA3YjdhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._uFi-hDnso30c9zYmUCe26RNdWv2aXt9WJJf7j-fgsI)
> 
> yuzu SDL windowed (1x resolution): ![yuzu_sdl_1x](https://private-user-images.githubusercontent.com/6087015/305412823-75223506-f8cc-47a6-b3ad-4d693101ae51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODY2NTAsIm5iZiI6MTcwODA4NjM1MCwicGF0aCI6Ii82MDg3MDE1LzMwNTQxMjgyMy03NTIyMzUwNi1mOGNjLTQ3YTYtYjNhZC00ZDY5MzEwMWFlNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMTIyNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjFiOWMyNzk5ZDYzM2JjN2MzNzYxZTQ1MjhmOWI4NGNlNTVkYjk0OGMxMDc2OGE5ODY1NmU5OTAwZjA5ODJlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hsEc_kLqpwdkjrAOmGsmCUnnJZRlm5Ka6M1DUkk2TlY)
> 
> yuzu SDL fullscreen (1x resolution): ![yuzu_sdl_1x_fullscreen](https://private-user-images.githubusercontent.com/6087015/305412937-8a00315b-3074-49f3-bb4c-cfe0b2f358af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwODY2NTAsIm5iZiI6MTcwODA4NjM1MCwicGF0aCI6Ii82MDg3MDE1LzMwNTQxMjkzNy04YTAwMzE1Yi0zMDc0LTQ5ZjMtYmI0Yy1jZmUwYjJmMzU4YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTZUMTIyNTUwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTNlZTZjNjVkZjlkZTMzNzdkMDcyNTRlOTA2ZjM5YzU5YmJiMDQ5ZWFmZDQ0MjRkNGI3ZDA5NDQyYjgzYTM5ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dhWr27hyUTuMiqsIxmFfTlGiUaQ-h6QdctXIBeD_Jcc)
> 
> notice how the mangohud is quite smaller in QT version, indicating that the surface draw size might be higher.

Yuzu GUI in windowed mode with desktop scaling set to 100%:
![yuzu_qt_windowed_100](https://github.com/yuzu-emu/yuzu/assets/6087015/537ccbcc-ca7c-4b11-a520-fd8a42940b42)

Yuzu GUI in fullscreen with desktop scaling set to 100%:
![yuzu_qt_fullscreen_100](https://github.com/yuzu-emu/yuzu/assets/6087015/3661f634-4d1f-42fc-a6e8-9eab9650621a)

**Comment by liamwhite** [comment] 2024-02-16 14:46
Cannot reproduce issue with gnome 45, rx 6700xt

Using QT_QPA_PLATFORM=wayland,
100%
![Screenshot from 2024-02-16 09-43-11](https://github.com/yuzu-emu/yuzu/assets/9658600/d7e54846-c96f-4ec4-ba53-43b3caf3a533)
125%
![Screenshot from 2024-02-16 09-43-42](https://github.com/yuzu-emu/yuzu/assets/9658600/d2e2e76e-dc80-43ad-8a22-3fe22f72d963)

Enabling fractional scaling tanked the performance of the rest of my desktop though, so I think it just sucks on wayland. And as for installing packages from AUR, there are very good reasons our official releases (which are not published on AUR) don't enable wayland.

**Comment by liamwhite** [comment] 2024-02-16 14:50
Yes, I restarted it between runs.

**Comment by vasishath** [comment] 2024-02-16 14:53
> Yes, I restarted it between runs.

Weird.. maybe your GPU is strong enough to absorb that lol.

Its strange that your whole desktop performance tanked with scaling.

**Comment by vasishath** [comment] 2024-02-16 15:04
> If you want any chance of this being looked at further, get a perf report with symbols. But it's probably some Qt Wayland WSI issue that we have no control over.

I just enabled resolution parameter in mangohud:

at 125%:
![yuzu_qt_resolution_fullscreen_125](https://github.com/yuzu-emu/yuzu/assets/6087015/9e1f83c6-0a18-4fac-915b-6f22e59d74c0)


at 100%:
![yuzu_qt_resolution_fullscreen](https://github.com/yuzu-emu/yuzu/assets/6087015/983e7795-a611-44ae-ae43-2585b9e97aa3)


at 200%:
![yuzu_qt_resolution_fullscreen_200](https://github.com/yuzu-emu/yuzu/assets/6087015/5443961c-d45c-4889-a5fe-f9abe15a6581)


I guess its an issue only with fractional scaling as the resolution at 125% is at 3072x1720 which is bound to tax my GPU.

**Comment by liamwhite** [comment] 2024-02-16 15:07
Closing as wayland WSI issue then - Qt is suggesting a ludicrous resolution to draw at which doesn't match what we request

**Closed by liamwhite** 2024-02-16 15:07 UTC

**Comment by vasishath** [comment] 2024-02-16 15:39
I think since my build was built with QT5, it is still using it's old behaviour for fractional scaling:

(resolution * 2) / scale factor

which makes (1920 * 2)/1.25 = 3072 and (1080 * 2)/1.25 = 1720
at 1.50 it would be 2560x1440 which is inline with my findings.

Will try building with QT6 and see if that changes anything.

**Comment by vasishath** [comment] 2024-02-16 15:56
> I think since my build was built with QT5, it is still using qt's old behaviour for fractional scaling:
> 
> (resolution * 2) / scale factor
> 
> which makes (1920 * 2)/1.25 = 3072 and (1080 * 2)/1.25 = 1720 at 1.50 it would be 2560x1440 which is inline with my findings.
> 
> Will try building with QT6 and see if that changes anything.

Yes.. building yuzu with QT6 fixes this issue.
