### ISSUE TITLE
Yuzu crashing a ton in and out of the game in Super Smash Bros. Ultimate

### ISSUE THREAD

**Issue by sweetenernj** [yuzu-emu/yuzu#5822] opened 2021-01-25 05:32 UTC
This issue has been going on across many Early access and even mainline versions for an extremely long time now and it is beyond annoying. Many people have also been experiencing these issues in regards to random crashing.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5864391/yuzu_log.txt)

**Comment by CrusadingNinja** [comment] 2021-01-25 05:42
This is a known issue and is due to instabilities caused by the latest update 10.1. Reverting to update 9.0.2 improves the stability of the game.

**Comment by fuhuan416** [comment] 2021-01-25 06:05
> This is a known issue and is due to instabilities caused by the latest update 10.1. Reverting to update 9.0.2 improves the stability of the game.

Wow, what's more interesting is how you discovered this solution

**Comment by feudalism1** [comment] 2021-01-25 18:26
it doesnt seem to fix it for me if i revert updates, and going to v1.0 doesnt help either

**Comment by sikuuu** [comment] 2021-01-25 20:16
Try 488, this build worked for me. I have 2 versions of yuzu and only use this for smash

**Comment by Areidz** [comment] 2021-02-09 23:30
For me, the only problem is playing Palutena. Once she's on the stage, after a couple of seconds (less than a minute), the game music keeps playing but the fps drop to 0.

**Comment by Kenshin9977** [comment] 2021-09-21 23:37
I still have this issue and it's becoming a real issue when I'm using [Yuzult](https://github.com/Fcornaire/yuzult-client)

**Comment by FernandoS27** [comment] 2021-09-22 14:59
I'll investigate this later today.

Any tips on reproduction?

**Comment by Kenshin9977** [comment] 2021-09-27 15:37
I'm on the latest mainline version and I'm still having crash issues but only when using Vulkan.
[yuzu_757_coop_vulkan_crash.txt](https://github.com/yuzu-emu/yuzu/files/7237563/yuzu_757_coop_vulkan_crash.txt)

**Comment by G-Spawn** [comment] 2022-06-10 03:49
Stability issues with smash should be fixed on latest mainline versions & early access. If it still happens to you please post updated log file

**Closed by G-Spawn** 2022-06-10 03:49 UTC
