### ISSUE TITLE
Animal Crossing: New Horizons Text not displaying correctly bug

### ISSUE THREAD

**Issue by byt3d3lux3** [yuzu-emu/yuzu#3918] opened 2020-05-11 07:03 UTC
This bug was present using an RX580 and in OpenGL and Vulkan. I heard this this bug also affected some Nvidia users aswell. 
![aaaaaaaaaaaaaa](https://user-images.githubusercontent.com/35120283/81533270-41263300-93a9-11ea-8f40-433bdfdfd5b6.PNG)

**Comment by Joshi234** [comment] 2020-05-11 08:57
@byt3d3lux3 same butt when you scroll down the text appears and in nook shopping, and when you are on a crafting table,(not in the app) there is the same problem

**Comment by Nigh7Stalk3r** [comment] 2020-05-11 11:20
Got the same issue on latest 524 build using OpenGL and Vulkan on an RX 570.

**Comment by capSAR273** [comment] 2020-05-11 12:35
It seems like after you get the Nook Miles+ upgrade, the text is showing in menus now. I'm on AMD and Vulkan.
![image](https://user-images.githubusercontent.com/5252505/81562198-6c396400-9362-11ea-8845-38a331caab94.png)

**Comment by byt3d3lux3** [comment] 2020-05-11 12:45
> It seems like after you get the Nook Miles+ upgrade, the text is showing in menus now. I'm on AMD and Vulkan.
> ![image](https://user-images.githubusercontent.com/5252505/81562198-6c396400-9362-11ea-8845-38a331caab94.png)

That is very interesting, although while using vulkan, doing literally anything crashes like checking mail lol

**Comment by Nigh7Stalk3r** [comment] 2020-05-11 15:04
> It seems like after you get the Nook Miles+ upgrade, the text is showing in menus now. I'm on AMD and Vulkan.
> ![image](https://user-images.githubusercontent.com/5252505/81562198-6c396400-9362-11ea-8845-38a331caab94.png)
It fixed the text on the Nook Miles descriptions for me but thats it, everything else is still missing text.

**Comment by Joshi234** [comment] 2020-05-11 16:09
@capSAR273 same

**Comment by theboy181** [comment] 2020-05-11 20:49
This AMD or Nvidia? Is it driver related when we are talking about Nvidia?

**Comment by leolion0** [comment] 2020-05-11 23:04
I am getting this bug with an Nvidia GTX 770 (and i7-9700k). The bug is present on Vulkan but not OpenGL. Can't comment on Nook Miles+

**Comment by Raquaa** [comment] 2020-05-12 15:38
@capSAR273 I got the Nook Miles+ upgrade already but I still have the text issue. It seems to be less frequent, sure, but it's still there.
I also looked on Reddit & a Yuzu moderator said it's an AMD driver issue, so I updated and got no results. Ryujinx doesn't have the same issue w/ text so I don't think that's it.

**Comment by Joshi234** [comment] 2020-05-13 08:55
In nook miles+ the text of nook miles+ only appears when you scroll down until the normal nook miles get visible

**Comment by Joshi234** [comment] 2020-05-13 08:57
It's not visible at nook shopping,when you buy something with nook miles,the time when not in your own house,when you want to gift something to the museum and some other less obvious things

**Comment by one2gov** [comment] 2020-05-18 05:05
When the text is not visible in some menu it actually appears for a frame when you exit this menu. It feels like it the layer of ui with text has wrong order of rendering.

**Comment by MaksimChan** [comment] 2020-05-24 05:44
same issue with EA535 on  AMD platform

**Comment by howdoinames** [comment] 2020-05-26 14:05
I get the same issue on my build, nookmiles+ renders correctly, but redeeming nookmiles or giving a fossil to blathers there is no text rendered in the menu when using Vulkan but it appears correctly with Open GL. Ive also noticed that the map app on the phone through the vulkan renderer renders incorrectly when using vulkan, and the time and date dont display at all. but again fine on openGL. However OpenGL doesnt deliver the same performance, its much slower when navigating densely weeded areas and the textures will pop away and glitch every now and again, aside from the issues above the vulkan renderer runs this game flawlessly.

My specs are
Ryzen 5 3600k
RTX 2080
16gb RAM 2400
M.2 SSD

**Comment by Joshi234** [comment] 2020-05-27 09:36
@howdoinames they don't care about the issue

**Comment by LolicoreExpress** [comment] 2020-07-03 16:45
Exact same problem as everyone here described.
Happens while using Vulkan or OpenGL, multicore or single core, docked or undocked.

Windows 10 update 2004
Yuzu mainline 301
Ryzen 7 3700X
RX 5700 XT
16gb RAM

**Comment by i32cagoa** [comment] 2020-07-09 02:27
Same here: Rx480 4 GB, i5 9400F, 16 GB RAM Yuzu EA71X

**Comment by DanMossa** [comment] 2020-10-15 01:52
Same here.
Happens in Vulkan and OpenGL

Windows 10 64bit
Yuzu Early Access v1032
Ryzen 5 3600
RX 580 8GB
16gb ram

**Comment by byt3d3lux3** [comment] 2020-10-15 02:19
damn its been sometime since I posted this, guess it isnt fixed yet

**Comment by pixelmune** [comment] 2020-10-16 18:57
Yes, still happening. In my experience, it only happens with AMD cards. Both the igpu on the 3200g, and my gpu rx 470 experience this. I tried a few nvidia cards in openGL, and I didn't run into this.

**Comment by loverthehater** [comment] 2020-11-10 10:15
Still happens with Vulkan for me, build:
GPU: GeForce GTX 1070 w/ Max-Q
CPU: Intel i7-8750H
Memory: 16GB

**Comment by LurkSienn** [comment] 2020-11-13 17:24
Same thing. 
GeForce GTX 1070 
![image](https://user-images.githubusercontent.com/74370896/99101832-5b1a2a00-2607-11eb-9410-69edc879dfe5.png)

**Comment by L0um15** [comment] 2020-11-13 18:39
Same issue here.
Vulkan Yuzu EA 1121

Geforce GTX 1050 2GB
Intel i5 2400
12GB Ram

![obraz](https://user-images.githubusercontent.com/44427021/99108590-dd92f180-25e7-11eb-99f7-903b63e5b10c.png)
![obraz](https://user-images.githubusercontent.com/44427021/99108635-ef749480-25e7-11eb-8647-16ddcc2e56f3.png)

**Comment by DanMossa** [comment] 2020-11-20 01:54
Reading through discord it seems like this would be fixed after the texture cache rewrite

**Comment by zivshek** [comment] 2020-11-26 03:53
I've gotten a similar bug, while redeeming the miles, as I scroll down, the item image stopped to update and eventually disappeared. When I press B to go back and then come back in, I got an empty chat box and the game was stuck. Here are other people getting the same bug: https://www.reddit.com/r/yuzu/comments/i7sl77/animal_crossing_crash_when_redeeming_nook_miles/

**Comment by choppymaster** [comment] 2020-11-26 04:14
Hopefully this will be fixed after the Buffer Cache Rewrite.

**Comment by zivshek** [comment] 2020-12-02 18:08
This only happens to me if I switch to Vulkan. I have an Nvidia card, using Vulkan is more performant, just won't be able to read all the texts, lol

**Comment by Sbrockat** [comment] 2020-12-11 15:23
Same here with Vulkan .

Radeon RX 570
Ryzen 5 3600
16GB Ram

Text is not visible in some menus and baloons. Date and time not visible. 
Finally i'm experencing a lot of causal emulation crashes.

**Comment by gianlucarizzo** [comment] 2020-12-13 18:26
Same here with Vulkan.

Normal text is showing. Clock and balloon text don't.

Radeon RX 580 with latest drivers.

![image](https://user-images.githubusercontent.com/36188953/102020364-1a820d80-3d79-11eb-9eee-099ae10f9a25.png)
![image](https://user-images.githubusercontent.com/36188953/102020372-24a40c00-3d79-11eb-8bd3-daf73f2e032b.png)

**Comment by userofryzen** [comment] 2020-12-26 22:04
+1 here. Vega integrated OpenGL and vulkan. -.-

**Comment by userofryzen** [comment] 2020-12-26 23:31
Early acces fix many things but this, not. So there is no fix yet:(
Switching to ryujinx I think

**Comment by jangofett4** [comment] 2021-01-01 21:50
Same here. OpenGL and Vulkan.
Mainline Build - ae389f668.
Linux 5.10.3, Mesa 20.3.2.
Ryzen 5 3550H and Rx560X, most of the text is missing.

**Comment by goldenx86** [comment] 2021-01-03 00:55
The upcoming Buffer Cache Rewrite will solve this for good.

**Comment by ReinUsesLisp** [comment] 2021-01-03 00:58
This is fixed in WIP changes. Hopefully I can open a pull request with it soon.

**Comment by userofryzen** [comment] 2021-01-03 03:27
> The upcoming Buffer Cache Rewrite will solve this for good.

Nop I have tested it and the version that is upcoming won't resolve this, it's the same

**Comment by goldenx86** [comment] 2021-01-03 03:57
Imagine lying in github.
BCR is not done yet. And yes, it IS solved there.

**Comment by userofryzen** [comment] 2021-01-03 05:04
> Imagine lying in github.
> BCR is not done yet. And yes, it IS solved there.

https://yuzu-emu.org/entry/yuzu-tcr/
Then, this post is a lie If I am understanding well..
It says that the early access version is using it and have it. And the version I have tested is https://aur.archlinux.org/packages/yuzu-early-access/ and at the time of writing before it was updated AFTER the your post above.  So please... Correct that  official post then. Or explain to me.

**Comment by jangofett4** [comment] 2021-01-03 07:10
@goldenx86 pretty sure texture cache rewrite is in right now (since DOF is fixed, no black fog without mods) in d5fe722a30947c5c808717ad8940077e95a3a81c.

**Comment by userofryzen** [comment] 2021-01-03 13:01
> @goldenx86 pretty sure texture cache rewrite is in right now (since DOF is fixed, no black fog without mods) in [d5fe722](https://github.com/yuzu-emu/yuzu/commit/d5fe722a30947c5c808717ad8940077e95a3a81c).

Yes. In the earlier comments, mine is flagged like off topic and I mention that the cache rewrite fix many things included in this game in Linux. But not the missing texts. It's easier to say that someone is living than to ask him ... Awful

**Comment by FearlessTobi** [comment] 2021-01-03 18:22
I'm going to lock the conversation at this point as it has gone pretty offtopic and is not really helpful to diagnosing the bug anymore.
I have confirmed yesterday that this bug is indeed fixed in the upcoming buffer cache rewrite.
This feature isn't available to the public yet, as there is still development going on.
I'd advise you to just be patient a little longer until it is released to the public.

**Comment by ameerj** [comment] 2021-01-17 01:42
fixed by #5741

**Closed** 2021-02-13 06:22 UTC
