### ISSUE TITLE
Master Detective Archives: Rain Code - Persistent Crashes at specific point in chapter 0 

### ISSUE THREAD

**Issue by SRS220** [yuzu-emu/yuzu#10988] opened 2023-07-01 22:30 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 3646

### Description of Issue

During the mystery labyrinth section of chapter zero, the game will always crash upon reading through the dialog that occurs after doing a rebuttal against the enemy for a second time. 

### Expected Behavior

The game should proceed as normal without crashing.

### Reproduction Steps

Play the game up until the first enemy, complete second rebuttal then forward through the following dialogue.
[safe_file.zip](https://github.com/yuzu-emu/yuzu/files/11927328/safe_file.zip)

### Log File

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/11927307/yuzu_log.txt.old.txt)

### System Configuration

**Steam Deck**
CPU: Zen 2 4c/8t, 2.4-3.5GHz
GPU/Driver: 8 RDNA 2 CUs, 1.0-1.6GHz
RAM: 16 GB LPDDR5
OS: steam OS 3.4.6

**Comment by Morph1984** [comment] 2023-07-01 22:39
Duplicate of #10987

**Closed by Morph1984** 2023-07-01 22:39 UTC
