### ISSUE TITLE
pokemon sword lock opening bag key and during fight 

### ISSUE THREAD

**Issue by LimticRage** [yuzu-emu/yuzu#5304] opened 2021-01-07 12:20 UTC
when opening bag an going to the key section the game locks, it locks when just opening the bag during fight

Yuzu 498
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5781526/yuzu_log.txt)

**Comment by FearlessTobi** [comment] 2021-01-08 00:06
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/4227.

**Closed by FearlessTobi** 2021-01-08 00:06 UTC
