### ISSUE TITLE
Systems Without Audio Devices - Games Fail to Launch

### ISSUE THREAD

**Issue by KaiserRoll42069** [yuzu-emu/yuzu#10893] opened 2023-06-23 22:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Mainline 1477, probably others?

### Description of Issue

On systems without an audio device, games will fail to launch - they get stuck on the 'launching' screen.

The log file stops at "Audio.Sink <Critical> audio_core\sink\sdl2_sink.cpp:SDLSinkStream:60: Error opening SDL audio device: WASAPI can't find requested audio endpoint: Element not found."

### Expected Behavior

'Launching' indicator will appear, but it gets stuck and the game will never launch. 

### Reproduction Steps

1. Try to launch any game on a computer without an audio device - this might be replicated by temporarily uninstalling whatever onboard audio one has through device manager.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11853473/yuzu_log.txt)

### System Configuration

CPU: Ryzen 5 1600
GPU/Driver: GTX 1060 6GB
RAM: 16GB DDR4
OS: Windows 11

**Comment by german77** [comment] 2023-06-23 23:00
I managed to get the error but the game booted just fine. It might be specific to botw.

**Comment by KaiserRoll42069** [comment] 2023-06-24 00:13
I also tried it on Mario Kart 8 and got the same thing - will try on other games as well

**Comment by Squall-Leonhart** [comment] 2023-06-24 13:11
duplicate https://github.com/yuzu-emu/yuzu/issues/10712

**Comment by KaiserRoll42069** [comment] 2023-06-24 13:29
The issue manifests differently in different games, apparently
Breath of the Wild: Hangs on Launching screen (seemingly indefinitely)
Mario Kart 8 Deluxe: Hangs on Launching screen (seemingly indefinitely)
Luigi's Mansion 3: Works up until title screen, then crashes at some point later.
Animal Crossing New Horizons: Hangs a little on Launching screen, then game loads but crashes.

By looking at the log files, it seems crashes happens whenever the audio system is initialized, reinitialized, or switched, which makes sense.

**Comment by FearlessTobi** [comment] 2023-06-25 18:05
Closing as duplicate of https://github.com/yuzu-emu/yuzu/issues/10712.

**Closed by FearlessTobi** 2023-06-25 18:05 UTC
