### ISSUE TITLE
Save corruption issue - SD Gundam G Generation Genesis - KOR/ENG version

### ISSUE THREAD

**Issue by SeibaEX** [yuzu-emu/yuzu#6233] opened 2021-04-23 16:56 UTC
Yuzu version: 595

Issue: Yuzu is able to save the system data correctly for this game, but when I actually try to make an actual save file, the game hangs on the warning not to turn off the Switch. Closing Yuzu results in a corrupted savefile. I cannot create a savefile for this game. A log has been attached. Both OpenGL and Vulcan have been used to confirm this.

**Comment by german77** [comment] 2021-04-23 17:01
Post a log after the crash. Hopefully the error was logged before crashing

**Comment by SeibaEX** [comment] 2021-04-23 17:50
Funny, I thought I attached it.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6367198/yuzu_log.txt)

**Comment by german77** [comment] 2021-04-23 18:39
SD card folder is invalid pleas use a valid folder location like `C:\Users\user\AppData\Roaming/yuzu/sdmc/`

**Comment by SeibaEX** [comment] 2021-04-23 20:44
SD card folder changed to folder specified, same error. I erased the save files and started over again to create a full log.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6367983/yuzu_log.txt)

**Comment by FluxCapacit0r** [comment] 2021-04-27 20:50
I am also having this exact same issue.

Yuzu version 600
The game runs fine otherwise but hangs at the saving screen.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6387577/yuzu_log.txt)

**Comment by fuhuan416** [comment] 2021-05-01 06:26
Same issue here.

**Comment by whitewolf-lab** [comment] 2021-05-08 09:58
Did not fix the issue with the Kernal Rework #6266 yet. Here is a log from EA 1665 version. Can anyone clarify is it correct? 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6445646/yuzu_log.txt)

**Comment by whitewolf-lab** [comment] 2021-05-09 03:54
Here is another log from EA 1666 build, noticed an additional error line 
Kernel <Error> core\hle\kernel\svc.cpp:MapSharedMemory:1197: Failed with result: 56321

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6446906/yuzu_log.txt)

**Comment by FluxCapacit0r** [comment] 2021-05-10 06:29
611 still presenting me with the same issue.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6449939/yuzu_log.txt)

**Comment by lampuiho** [comment] 2021-05-21 00:04
> Yuzu version: 595
> 
> Closing Yuzu results in a corrupted savefile.

The save file is fine but the thumbnail is not. (info.dat)
I doubt that it crashes when making the header. I suspect that it is more likely caused by buffer access. I do not exactly know though so don't quote me on that.

this log comes from multiple runs. Always crash with the same stack with various versions of Yuzu.

[yuzu_crash_log.txt](https://github.com/yuzu-emu/yuzu/files/6519244/yuzu_crash_log.txt)

**Comment by delta7890** [comment] 2021-06-21 20:55
Same issue here.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/6687476/yuzu_log.txt)

**Comment by tapperp** [comment] 2021-12-15 11:40
This issue still persists, using yuzu 848. Same hang when trying to save, resulting in a "corrupted" save file in-game. FWIW the save functionality does work correctly in ryujinx.

I previously  [reported here](https://github.com/yuzu-emu/yuzu/issues/7456) before realizing this thread was already made.

**Comment by tapperp** [comment] 2022-03-02 21:36
This issue appears to be fixed now! It may have been fixed earlier but I only just tried it today using the most recent builds as of March 2 2022. Try it out everyone.

I was able to successfully save my game and keep playing, and was able to successfully load that save on a subsequent run.

**Comment by delta7890** [comment] 2022-03-02 22:48
> This issue appears to be fixed now! It may have been fixed earlier but I only just tried it today using the most recent builds as of March 2 2022. Try it out everyone.
> 
> I was able to successfully save my game and keep playing, and was able to successfully load that save on a subsequent run.

Can confirm.  Saving and loading are working just fine now!

**Comment by G-Spawn** [comment] 2022-06-17 05:44
@SeibaEX  Please try on latest yuzu versions. If it still happens to you feel free to reopen issue.

**Closed by G-Spawn** 2022-06-17 05:44 UTC
Labels: hle-issue
