### ISSUE TITLE
CTR crashing after some races

### ISSUE THREAD

**Issue by Myers78** [yuzu-emu/yuzu#4935] opened 2020-11-18 00:27 UTC
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5556963/yuzu_log.txt)

It's as the title says. The game breaks after some races, and some stages are more prone to break than others... I have asked some people if they were getting this error, but just some of them did get it... I'm using the latest Yuzu's builds, latest gpu drivers and pagefile is set to 20gb. 

System: r3 2200g; gtx 1660 6gb; 16gb ram; Windows 10 20H2

I'll post the part where I get the error down below, but I also attached the full log up there.

```
[2426.772663] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:613: Signalling debugger, PANIC! info1=0x0000000000000000, info2=0x0000000000000000
[2426.772684] Debug.Emulated <Critical> core\hle\kernel\svc.cpp:Break:665: Emulated program broke execution! reason=0x0000000000000000, info1=0x0000000000000000, info2=0x0000000000000000
[2426.772686] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:266: Backtrace, sp=000000000000000A, pc=000000000E152998
[2426.772689] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:268: Module Name         Address             Original Address    Offset              Symbol
[2426.772690] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:269: 
[2427.034973] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100333180    000000000E0FC180    0000000000333180    nnosBreak
[2427.034982] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100519C0C    000000000E2E2C0C    0000000000519C0C    __nnmusl_osBreak
[2427.034984] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071004CBD80    000000000E294D80    00000000004CBD80    abort
[2427.034986] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071004C81DC    000000000E2911DC    00000000004C81DC    
[2427.034988] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071004C7BE8    000000000E290BE8    00000000004C7BE8    __cxa_pure_virtual
[2427.034991] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100254334    000000000E01D334    0000000000254334    _ZN2nn3hid13VibrationNode16SyncSampleNumberEv
[2427.034993] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071002543D0    000000000E01D3D0    00000000002543D0    _ZN2nn3hid13VibrationNode6UpdateEv
[2427.034997] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                0000007100376B30    000000000837AB30    0000000000376B30    _ZN7Display24igNxVibrationClipUpdater23vibrationThreadFunctionEPv
[2427.034998] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: main                0000007101778D9C    000000000977CD9C    0000000001778D9C    _ZN4Core18igNxThreadFunctionEPv
[2427.035000] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000071003344B4    000000000E0FD4B4    00000000003344B4    
[2427.035002] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 0000007100338980    000000000E101980    0000000000338980    
[2427.035003] Core.ARM <Error> core\arm\arm_interface.cpp:LogBacktrace:274: sdk                 00000070F2236FFC    FFFFFFFFFFFFFFFC    FFFFFFFFF2236FFC    

```

**Comment by FearlessTobi** [comment] 2020-11-26 22:59
Duplicate of https://github.com/yuzu-emu/yuzu/issues/4644.

**Closed by FearlessTobi** 2020-11-26 22:59 UTC

**Comment by Myers78** [comment] 2020-11-26 23:25
But there's no fix for this issue?
