### ISSUE TITLE
SMO runs at 1FPS on windows but fine on Linux

### ISSUE THREAD

**Issue by lolxnn** [yuzu-emu/yuzu#2061] opened 2019-01-27 11:43 UTC
Super mario odyssey runs vary badly on windows:
-1 FPS
-Can't see text
-Audio glitches
But it runs quite smoothly on linux.
PC SPECS:
-CPU: Intel i5-6500
-GPU: AMD RX480
-RAM: 8GB
-OS: Windows 10, Arch
LOG:
https://gist.github.com/lolxnn/40389402810d4b50458d568e964fc33b

**Comment by Hexagon12** [comment] 2019-01-27 11:49
Duplicate of #1324.

**Closed by Hexagon12** 2019-01-27 11:49 UTC
