### ISSUE TITLE
[Windows7 64bit]Collar X Malice black screen with sound playing.

### ISSUE THREAD

**Issue by darkkidxin** [yuzu-emu/yuzu#3810] opened 2020-04-28 06:03 UTC
Yuzu Mainline 240
GeForce GTX 960
Seems the situation only happened when playing movies/videos.
[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/4543626/yuzu_log.zip)

**Comment by Hexagon12** [comment] 2020-04-28 06:33
Duplicate of #2643

**Closed by Hexagon12** 2020-04-28 06:33 UTC
