### ISSUE TITLE
Graphics regression in Super Smash Bros. Ultimate in latest EA 1370 and Mainline 516

### ISSUE THREAD

**Issue by sweetenernj** [yuzu-emu/yuzu#5817] opened 2021-01-24 22:11 UTC
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5863318/yuzu_log.txt)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5863319/yuzu_log.txt)

So I noticed in the latest early access 1370 and mainline 516 that there is a graphics downgrade in Super Smash Bros Ultimate. Both Palutena and Ness' hitboxes and animations getting screwed. More characters like Lucas and such are probably affected too. Providing before (EA1344) and after (Mainline516+EA1370) 
![3e33](https://user-images.githubusercontent.com/76490222/105645034-27f5e180-5e67-11eb-835e-296238a1a5d8.png)
![unknown](https://user-images.githubusercontent.com/76490222/105645035-2a583b80-5e67-11eb-9447-f7e83434c8bc.png)
![asd](https://user-images.githubusercontent.com/76490222/105645038-2cba9580-5e67-11eb-8a53-c4e10a60dc64.png)
![ddddd](https://user-images.githubusercontent.com/76490222/105645039-2d532c00-5e67-11eb-9b06-0d26badc34f6.png)

**Comment by lat9nq** [comment] 2021-01-25 00:18
I was able to reproduce it here. This is a graphical issue caused by #4713, thus a regression since Mainline 515. Gameplay is not affected. To my eyes, a notable difference is Palutena's side special attack and her victory pose.

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/5863504/yuzu_log.txt)

**Comment by ReinUsesLisp** [comment] 2021-01-27 05:30
Fixed by the linked PR.

**Closed by ReinUsesLisp** 2021-01-27 05:30 UTC
