### ISSUE TITLE
Super Mario Odyssey random crashes related to audio 

### ISSUE THREAD

**Issue by bergauznoam** [yuzu-emu/yuzu#10382] opened 2023-05-19 10:52 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

1438

### Description of Issue

It happens kind of randomly. I just got into the Wooded Kingdom and the game crashed after 20 minutes while collecting coins. 

### Expected Behavior

Game works as expected.

### Reproduction Steps

Like I said, it is random and excuse me for not providing any reproducible steps, but it always happens around the 10-20 minutes of playtime. It didn't happen when I played the previous worlds.

### Log File
Two crash occasions, both related to the same bug -
Log file 1: https://pastebin.com/j3J4jXeb
Log file 2: https://pastebin.com/a58Zt60d

> [ 592.703498] Service.Audio <Error> audio_core/renderer/voice/voice_context.cpp:GetInfo:48: Invalid voice info index 0070

### System Configuration

OS: Fedora release 37 (Thirty Seven)
KERNEL: 6.2.12-200.fc37.x86_64
CPU: AMD Ryzen 9 3900X 12-Core
GPU: AMD Radeon RX 5700 XT (navi10, LLVM 15.0.7, DRM 3.49, 6.2.12-200.fc37.x86_64)
GPU DRIVER: 4.6 Mesa 23.0.2
RAM: 32 GB

Additional info: Using Xbox One Wired Controller

**Comment by Squall-Leonhart** [comment] 2023-05-20 22:28
That isn't a critical error and likely has nothing to do with the crash, rather it could be another crash involving video memory exhaustion.

**Comment by AccidentalCalzone** [comment] 2023-05-21 11:19
I suspect I'm experiencing the same issue. Crashes occur seemingly at random with every other crash being immediately preceded by an "Invalid voice info index" error; the remaining crashes have no indication of an error in the log whatsoever. When ran through a terminal, however, the error printed is `/usr/include/c++/13.1.1/span:282: constexpr std::span<_Type, _Extent>::element_type& std::span<_Type, _Extent>::operator[](size_type) const [with _Type = AudioCore::AudioRenderer::VoiceInfo; long unsigned int _Extent = 18446744073709551615; reference = AudioCore::AudioRenderer::VoiceInfo&; size_type = long unsigned int]: Assertion '__idx < size()' failed.`

As OP stated, the occurrence seems completely random; however, the frequency of the crashes has definitely increased since reaching Wooded Kingdom (10-20 minutes of playtime seems about right). I've monitored VRAM usage multiple times and it never seems to exceed 3 GiB (usually hovering at around 2.5 GiB).

Full log attached
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11524394/yuzu_log.txt)

**Comment by DeviousDream** [comment] 2023-05-23 17:33
> That isn't a critical error and likely has nothing to do with the crash, rather it could be another crash involving video memory exhaustion.

bruh, this happens on TotK and literally every single time I get this specific crash, there's a wall of:

> [10499.224498] Service.Audio <Error> audio_core\renderer\voice\voice_context.cpp:GetInfo:48: Invalid voice info index 03F0

 It's the only common point between those crash instances. this error also NEVER appears in my logs unless this CTD happens.
Everything was going just fine resources-wise.
 
 
 Here's the log just in case: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11546893/yuzu_log.txt)

**Comment by Kelebek1** [comment] 2023-06-08 20:45
> I suspect I'm experiencing the same issue. Crashes occur seemingly at random with every other crash being immediately preceded by an "Invalid voice info index" error; the remaining crashes have no indication of an error in the log whatsoever. When ran through a terminal, however, the error printed is `/usr/include/c++/13.1.1/span:282: constexpr std::span<_Type, _Extent>::element_type& std::span<_Type, _Extent>::operator[](size_type) const [with _Type = AudioCore::AudioRenderer::VoiceInfo; long unsigned int _Extent = 18446744073709551615; reference = AudioCore::AudioRenderer::VoiceInfo&; size_type = long unsigned int]: Assertion '__idx < size()' failed.`
> 
> As OP stated, the occurrence seems completely random; however, the frequency of the crashes has definitely increased since reaching Wooded Kingdom (10-20 minutes of playtime seems about right). I've monitored VRAM usage multiple times and it never seems to exceed 3 GiB (usually hovering at around 2.5 GiB).
> 
> Full log attached [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11524394/yuzu_log.txt)

Can you get a full stack for this error so I can see where it's coming from?

**Comment by FinishedFragment** [comment] 2023-06-15 14:28
I have a full trace for you! This has rarely happened to me on Breath of the Wild and I finally caught one in gdb. #9335 and #10673 may or may not be the same issue. In either case, these random freezes are super annoying.

[yuzu-gdb.txt](https://github.com/yuzu-emu/yuzu/files/11758859/yuzu-gdb.txt)

**Comment by emememu** [comment] 2023-07-31 04:36
I'm experiencing this crash in ToTK on Linux (Flatpak). Here's the relevant syslog output:

    Jul 29 22:11:52 hostname plasmashell[24385]: /usr/include/c++/12.2.0/span:278: constexpr std::span<_Type, _Extent>::element_type& std::span<_Type, _Extent>::operator[](size_type) const [with _Type = AudioCore::AudioRenderer::VoiceInfo; long unsigned int _Extent = 18446744073709551615; reference = AudioCore::AudioRenderer::VoiceInfo&; size_type = long unsigned int]: Assertion '__idx < size()' failed.
    Jul 29 22:11:52 hostname plasmashell[24374]: /app/bin/yuzu-launcher: line 25:    13 Aborted                 (core dumped) prlimit --nofile=8192 yuzu "$@"

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12211438/yuzu_log.txt)

Linux, Flatpak, PipeWire, 32 GB RAM, AMD Ryzen 9 7950X3D, Radeon RX 480 4GB.

> That isn't a critical error and likely has nothing to do with the crash

I think you're mistaken, because:

- That assertion failure is exactly correlated with the crashes that I've investigated so far, and with those reported by the others who have commented here.
- I have never known a C++ assertion failure not to result in a crash. That's what [assert](https://en.cppreference.com/w/cpp/error/assert) is supposed to do, after all.
- We can see in the backtrace provided by @FinishedFragment  that the process did indeed end with a SIGABRT, as one would expect from a failed assertion.

The crashes are mostly random in my experience, but they seem to happen slightly more often in fights and storms, when the sound of a thunderclap or explosion is supposed to play.

**Comment by emememu** [comment] 2023-07-31 04:46
Yuzu 1509 is the most recent version I've tested, but the crashes are not new to this version. Yuzu has crashed nearly every time since I first tried it a month or two ago.

**Comment by Squall-Leonhart** [comment] 2023-07-31 05:04
The sound event logged is not the cause of the crash, its a symptom of it, the cause is that OOM has been reached due to fragmentation induced memory exhaustion,

**Comment by emememu** [comment] 2023-07-31 05:59
> the cause is that OOM has been reached due to fragmentation induced memory exhaustion,

Can you please explain why you believe that?

All the information I've seen suggests otherwise, but if there's something I'm overlooking, I would be happy to be made aware of it.

**Comment by Squall-Leonhart** [comment] 2023-07-31 07:32
> All the information I've seen suggests otherwise, but if there's something I'm overlooking, I would be happy to be made aware of it.

Because I can simulate the behaviour reliably on low memory systems, and its a _size related assertion._

**Comment by emememu** [comment] 2023-07-31 07:44
I see. Your opinion is based on circumstantial evidence.

Size-related assertions have many causes, most of which are not OOM conditions. And this is happening on systems with a lot of memory.

I don't want to argue with you, though. I'll just hope the developers get a chance to take a closer look soon.

**Comment by emememu** [comment] 2023-07-31 07:45
Maybe related:

#9287

llvm/llvm-project#45224

**Comment by liamwhite** [comment] 2023-08-31 02:38
Fixed by #11408

**Closed by liamwhite** 2023-08-31 02:38 UTC
