### ISSUE TITLE
Any news about the Ring Fit Adventure？

### ISSUE THREAD

**Issue by knaxLFea** [yuzu-emu/yuzu#8004] opened 2022-03-12 02:10 UTC

**Comment by german77** [comment] 2022-03-12 02:21
A custom driver is being worked on to connect a real ringcon to yuzu. As for the PR it needs someone to review it before it can be merged.

**Comment by pktiuk** [comment] 2022-03-12 13:44
Issue to be closed.  
Duplicate of https://github.com/yuzu-emu/yuzu/issues/7535#issuecomment-1053676683

**Closed** 2022-03-12 15:16 UTC
