### ISSUE TITLE
a crash when try to configure yuzu with linux mint

### ISSUE THREAD

**Issue by skarmiglione** [yuzu-emu/yuzu#3399] opened 2020-02-11 12:54 UTC
Version: yuzu-linux-20200210-02339c2de
I just execute it and work until i want to start the configure option, then i have this crash

./yuzu
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: custom style sheet is disabled
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
malloc(): memory corruption
Aborted (core dumped)
   

when i use DRI_PRIME=1  it crash too when i try the configure option in the menu too

DRI_PRIME=1 ./yuzu
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
qt5ct: custom style sheet is disabled
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
QPixmap::scaled: Pixmap is a null pixmap
Segmentation fault (core dumped)

My hardware bring by neofetch:
neofetch 
MMMMMMMMMMMMMMMMMMMMMMMMMmds+.      
MMm----::-://////////////oymNMd+`     ------------- 
MMd      /++                -sNMd:                                  OS: Linux Mint 19.3 Tricia x86_64 
MMNso/`  dMM    `.::-. .-::.` .hMN:                            Host: X555QG 1.0 
ddddMMh  dMM   :hNMNMNhNMNMNh: `NMm      Kernel: 5.5.0-2.1-liquorix-amd64 
    NMm  dMM  .NMN/-+MMM+-/NMN` dMM            Uptime: 1 day, 23 hours, 43 mins 
    NMm  dMM  -MMm  `MMM   dMM. dMM             Packages: 4191 
    NMm  dMM  -MMm  `MMM   dMM. dMM              Shell: bash 4.4.20 
    NMm  dMM  .mmd  `mmm   yMM. dMM                Resolution: 1366x768, 1280x1024 
    NMm  dMM`  ..`   ...   ydm. dMM   WM: i3 
    hMM- +MMd/-------...-:sdds  dMM   Theme:                
    -NMm- :hNMNNNmdddddddddy/`  dMM   Icons:      Faba [GTK2/3] 
     -dMNs-``-::::-------.``    dMM   Terminal:  xfce4-terminal 
      `/dMNmy+/:-------------:/yMMM   Terminal Font: Carlito Bold 9 
         ./ydNMMMMMMMMMMMMMMMMMMMMM   CPU: AMD A12-9720P RADEON R7 4C+8G 
                                                                                             (4) @ 2.700GHz 
            .MMMMMMMMMMMMMMMMMMM      GPU: AMD Radeon R5/R6/R7 Graphics 
                                                                            GPU: AMD Radeon HD 8670A/8670M/8690M 
                                                                             Memory: 9231MiB / 10992MiB 

                                                              

- You have provided the version (commit hash) of yuzu you are using.
- You have provided sufficient detail for the issue to be reproduced.
- You have provided system specs (if relevant).
- Please also provide:
  - For any issues, a log file
  - For crashes, a backtrace.
  - For graphical issues, comparison screenshots with real hardware.
  - For emulation inaccuracies, a test-case (if able).

-->

**Comment by Yvar192** [comment] 2020-02-11 13:03
duplicate of https://github.com/yuzu-emu/yuzu/issues/2957

btw i love that neofetch formatting

**Comment by Hexagon12** [comment] 2020-02-11 13:03
Duplicate of #2957

**Closed by Hexagon12** 2020-02-11 13:03 UTC
