### ISSUE TITLE
Yuzu failing to load games when in steam big picture mode / remote play

### ISSUE THREAD

**Issue by lief480** [yuzu-emu/yuzu#6166] opened 2021-04-08 02:46 UTC
Yuzu commit Hash: 636-4903-ge106f8897
RTX 2070, i9-9900k
Geforce Driver 465.89 (Latest)

If running Steam big picture mode, I get errors stating that the graphics core could not be loaded (Using Vulkan)

I have to close steam big picture mode, then restart yuzu to be able to start games. 

This worked before I updated my Nvidia drivers to the latest version.

[  41.896189] Render.Vulkan <Error> video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:121: Vulkan initialization failed with error: VK_ERROR_OUT_OF_DEVICE_MEMORY
[  41.897776] HW.GPU <Error> video_core\video_core.cpp:CreateGPU:50: Failed to initialize GPU: Vulkan initialization error VK_ERROR_OUT_OF_DEVICE_MEMORY
[  41.899312] Core <Critical> core\core.cpp:Load:229: Failed to initialize system (Error 5)!

**Comment by swilkens** [comment] 2021-04-14 11:50
I can confirm this.

Yuzu release: 590 (HEAD-mainline-636-5043-g66a4fc088)

GTX 1060 with Geforce Driver 465.89

Vulkan works fine when loading outside of steam's big picture mode, but fails with the attached error when starting a Vulkan session from steam big picture mode.

OpenGL is not affected.

[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/6310587/yuzu_log.txt.old.txt)

**Comment by swilkens** [comment] 2021-04-21 14:06
To clarify, it's fine if you start the emulator from Desktop mode - it's only big picture mode that causes this.

**Comment by MastaG** [comment] 2021-04-21 20:10
Same here.
I've already tried to disable Steams shader  caching and the Steam overlay but that didn't fix it.
When launching Yuzu through Steam's big picture mode only OpenGL seems to work for now.

**Comment by jollybully** [comment] 2021-05-13 11:49
Same here - GTX 1660 Super / 466.27

**Comment by jollybully** [comment] 2021-05-13 12:31
> I'm having the same issue but _only_ when launching Yuzu from Steam BPM via Moonlight and/or Steam Link
> 
> GTX 1660 Super / 466.27
> 
> [ 0.832789] Render.Vulkan video_core\renderer_vulkan\renderer_vulkan.cpp:RendererVulkan:121: Vulkan initialization failed with error: VK_ERROR_OUT_OF_DEVICE_MEMORY
> [ 0.834722] HW.GPU video_core\video_core.cpp:CreateGPU:50: Failed to initialize GPU: Vulkan initialization error VK_ERROR_OUT_OF_DEVICE_MEMORY
> [ 0.836586] Core core\core.cpp:Load:230: Failed to initialize system (Error 5)!

This was resolved by installing the latest Beta Vulkan Drivers from Nvidia

**Comment by v1993** [comment] 2021-06-14 19:53
Since this is reported to be fixed on latest nvidia drivers, can we close this now?

**Comment by hbprotoss** [comment] 2021-07-13 02:44
> Since this is reported to be fixed on latest nvidia drivers, can we close this now?

still has problem with 471.11

**Comment by Gyurn-hash** [comment] 2022-06-07 02:34
Work around is to have steam match the resolution of the client device when streaming.  

Go into settings on steam, remote play, advanced host settings, and check "change desktop resolution to match streaming client".

Tested on my phone, I'm sure it would work for other devices too.

**Comment by G-Spawn** [comment] 2022-06-17 05:37
@lief480  Please confirm if this still happens to you on newer yuzu versions.

**Comment by Gyurn-hash** [comment] 2022-06-17 17:49
Problem no longer persists for me, Vulkan now working with Big Picture Mode in steam without the need for a work around.

**Comment by G-Spawn** [comment] 2022-06-17 17:51
Thank you for confirming

**Closed by G-Spawn** 2022-06-17 17:51 UTC
