### ISSUE TITLE
Missing libzlib.dll (mingw Windows)

### ISSUE THREAD

**Issue by ampnjdevs** [yuzu-emu/yuzu#2544] opened 2019-06-04 18:23 UTC
The Windows mingw canary releases 2330-2333 immediately crash due to missing file libzlib.dll. This file is not included in any of the release archives. Commits 17decdc, a0950a5, 35aabb7, f68fa3b are currently affected.

**Comment by ampnjdevs** [comment] 2019-06-06 00:26
Canary 2351 (or potentially earlier) fixes this issue, closing

**Comment by ampnjdevs** [comment] 2019-06-13 17:45
Issue has reappeared in Canary 2376-2380

**Comment by DarkLordZach** [comment] 2019-06-25 21:07
This is from PR #2539, which hasn't been merged yet. I'd say to report it on the PR, but it was already reported there. It will be fixed before BCAT is put back onto canary.

**Comment by Irastris** [comment] 2019-10-05 03:49
Issue has appeared yet again from Canary 2695-2705 and potentially beyond.

**Comment by Irastris** [comment] 2019-10-05 23:53
Continued presence in Canary 2708.

Workaround is to make a copy of `zlib1.dll` and rename it to `libzlib.dll`. I have not monitored any regressions in doing this so far.

**Comment by goedzo** [comment] 2019-10-12 11:46
I can confirm that renaming zlib1.dll to libzlib.dll is indeed a valid workaround for the canary build of yuzu-windows-mingw-20191011-9d29c1b in which this issue still occurs.

**Comment by jbeich** [comment] 2019-10-16 03:06
Can you check if #2947 fixes this?

**Comment by goedzo** [comment] 2019-10-16 09:46
Sorry but i cannot since i only download the nightly canary build for testing. I don't build any code at all.

**Comment by lat9nq** [comment] 2021-01-07 19:46
Appears to have been fixed with either yuzu-emu/build-environments#8 or #3735. Besides MinGW builds no longer being released, it seems that `zlib1.dll` is being packaged with MinGW PR verification builds now.

**Closed** 2021-01-07 23:39 UTC
Labels: build-system-issue
