### ISSUE TITLE
Fire Emblem: Three Houses glitching out 

### ISSUE THREAD

**Issue by icelandiiic** [yuzu-emu/yuzu#3075] opened 2019-11-05 16:33 UTC
Hello, I use a Geforce RTX 2060 6GB and an i5-8300H. I downloaded Yuzu on my laptop and I kinda knew something was up seeing other people post videos of a perfectly playable version of Fire Emblem Three Houses. 
After trying a few builds of Yuzu I decided to ask on discord. I was given a developer version of a driver supporting Vulkan 1.1 that I could try using to fix my problem but that sadly didn't work either and the problem stayed the same. 
So, I would like to know if this bug related to rtx cards would be fixed in the near future or if there's some other way to go about this.
![unknown](https://user-images.githubusercontent.com/57408749/68226313-2639c700-fff2-11e9-8877-0e47b25343cf.png)

**Comment by Hexagon12** [comment] 2019-11-05 16:37
Duplicate of #2967 

It's a RTX exclusive issue.

**Closed by Hexagon12** 2019-11-05 16:37 UTC
