### ISSUE TITLE
Zelda Skyward Sword visual issues on cutscenes [Vulkan] 

### ISSUE THREAD

**Issue by iWeaker4you** [yuzu-emu/yuzu#6666] opened 2021-07-17 15:05 UTC
It has rendering problems in the cutscenes, as well as a few minor glitch graphics problems in the gameplay, but they are minor, compared to this which is quite noticeable.

PC rig:
Debian 11
NVIDIA GTX 1060 6gb
Driver 470.42.01
Vulkan Instance Version: 1.2.162
Vulkan Driver: 1.2.175
![Captura de pantalla de 2021-07-17 08-01-52](https://user-images.githubusercontent.com/49424816/126041112-90527536-3518-4bcc-882a-852a276bf571.png)

**Comment by v1993** [comment] 2021-07-18 11:45
Can you check if this still happens with #6585? There's a decent chance this is already fixed there.

**Comment by iWeaker4you** [comment] 2021-07-26 20:21
Still happens..

**Comment by german77** [comment] 2021-12-07 03:10
Duplicate of #7133

**Closed by german77** 2021-12-07 03:10 UTC
