### ISSUE TITLE
Super Mario Odyssey doesnt boot with update 1.3.0

### ISSUE THREAD

**Issue by EliasM108** [yuzu-emu/yuzu#3083] opened 2019-11-08 11:55 UTC
Log File:
[yuzu_log_withBxcat.txt](https://github.com/yuzu-emu/yuzu/files/3824440/yuzu_log_withBxcat.txt)

Tried with and without boxcat but the result is the same

**Comment by Hexagon12** [comment] 2019-11-08 12:34
Duplicate of #2715

**Closed by Hexagon12** 2019-11-08 12:34 UTC
