### ISSUE TITLE
[Android] Game closes after a few seconds of black screen when using Turnip

### ISSUE THREAD

**Issue by laplaces-entropy** [yuzu-emu/yuzu#11620] opened 2023-09-27 19:11 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

android-82 and 83 so far

### Description of Issue

Yuzu closes the game after a few seconds of black screen when using Turnip drivers, with default or other Qualcomm drivers it works (ignoring graphics problems).
Before android-82 it worked without problems.
Since no one has reported the same issue (at least I didn't find a similar report) I assume it may be an Adreno 725 (Snapdragon 7+ Gen 2) or device (Poco F5) specific bug

### Expected Behavior

Starts after a few seconds

### Reproduction Steps

1. Install android-82 or 83
2. Complete the setup
3. Install Turnip driver
4. Start any game

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/12742429/yuzu_log.txt)

### System Configuration

CPU: Snapdragon 7+ Gen 2
GPU/Driver: Adreno 725 / Turnip ([7xx Support R5](https://github.com/K11MCH1/AdrenoToolsDrivers/releases/tag/A7xx_R5))
RAM: 12 GB
OS: Android 13 / MIUI 14

**Comment by EDDIPOWER** [comment] 2023-10-13 05:21
I have the error, it persists even in version 99

System Configuration
CPU: Snapdragon 888+
GPU/Driver: Adreno 660
RAM: 8GB
OS: android 12

**Comment by djdp77** [comment] 2023-10-22 10:36
I also have a Poco F5 and do not have this issue. To me however, the latest Qualcomm drivers work better than Turnip R5 in general. I have more crashes and visual bugs with Turnip, but think it's something Mesa has to sort out, not Yuzu

**Comment by laplaces-entropy** [comment] 2023-10-23 18:50
> I also have a Poco F5 and do not have this issue. To me however, the latest Qualcomm drivers work better than Turnip R5 in general. I have more crashes and visual bugs with Turnip, but think it's something Mesa has to sort out, not Yuzu

@djdp77 could you tell me what version are using? I tested "current" (android-110), have the same issue.

About the turnip and adreno drivers bugs, that is strange, in my experience Turnip works a lot better in almost any case

**Comment by djdp77** [comment] 2023-10-23 19:01
@laplaces-entropy I'm using the Yuzu Playstore and Turnip_7xx_R5 (R6 and R7 do not work on a725 but think that's on Mesa)

For example on Hollow Knight I get the same performance with any driver, but Turnip shows visual artifacts on some effects

**Comment by EDDIPOWER** [comment] 2023-10-23 19:36
Hi
The problem persists for me too.
Since version 82, the turnip drivers generate a crash when running a game.

It works perfectly with qualcomm drivers but I want to use turnip they have better performance and fewer bugs

**Comment by djdp77** [comment] 2023-10-24 15:27
Re-tested this with the latest Yuzu version and also get this error. Most games crash when using Turnip on a Poco F5. It does not happen with the Playstore version

**Comment by Starling0808** [comment] 2023-10-26 19:06
I have exactly same problem, before ver. 82 it worked perfectly, after that I can only the Qualcomm driver. 

I have a Galaxy S22+ with the Qualcomm 8 Gen 1 Adreno 730 and Android 13 with OneUI 5.1.


Currently I have yuzu ver. 113 with the Turnip driver R8. I also use the Turnip R8 in Yuzu v17 paid version and it works perfectly.

Also, for me no Skyline version is working, any configuration, any version and any driver, none of them work. I debloated my system and Uninstalled a lot of things, I thought it was for that I but I see that I am not the only one.

**Comment by djdp77** [comment] 2023-10-26 21:25
Yup, still happens with android-113, not on all games but most: [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13183047/yuzu_log.txt)

**Comment by EDDIPOWER** [comment] 2023-10-26 23:56
I decided to update a non-stock rom for that reason.

I loved my stock system but it was the only way to get juzu to not close games with turnip controllers.

System Configuration
CPU: Snapdragon 888+
GPU/Driver: Adreno 660
RAM: 8GB
OS: android 13 ( custom rom )

**Comment by Starling0808** [comment] 2023-10-27 01:02
Did it work? Is it not closing anymore?

**Comment by Starling0808** [comment] 2023-10-29 03:33
Ver. 116 still not working.

**Comment by EDDIPOWER** [comment] 2023-10-29 04:51
Maybe I don't explain myself

Change my stock system (presents the juzu error with turnip when opening games)

Now I have a custom rom (the tunrip drivers work with juzu, the games don't close)

but it was not my desire to update to a custom rom. (it was the solution I could give myself)

System Configuration
CPU: Snapdragon 888+
GPU/Driver: Adreno 660 (juzu 116/ Turnip Driver v23.3.0 - Revision 8)
RAM: 8GB
OS: android 13 ( custom rom )

**Comment by laplaces-entropy** [comment] 2023-10-29 05:30
So in summary we can assume the following:

- It is not the fault of the Turnip driver itself
- It seems to be neither SOC specific bug unlike what I initially thought nor Adreno architecture (because @EDDIPOWER has an 888+).
- Maybe it's partly the fault of the customization layer (because according to @EDDIPOWER switching to a custom rom fixed the problem).
- Apparently some games work, so maybe it's a specific instruction that not all games use that is causing the bug.

As a speculation, I would think that maybe the problem is originating from #11225, since it seems to be the only major change between version # 81 and # 82.

**Comment by djdp77** [comment] 2023-10-29 09:02
@FernandoS27 could you take a quick look at this? Think you drove the major push behind Y.F.C.

My comment above has a log with "Graphics debugging" enabled but tldr most games result in "device loss occurred" since android-82. Unclear to me if this affects only some or all a7xx qualcomm gpus

**Comment by djdp77** [comment] 2023-10-29 20:49
Another log (with Graphics debugging on): [yuzu_log (1).txt](https://github.com/yuzu-emu/yuzu/files/13199203/yuzu_log.1.txt)

**Comment by djdp77** [comment] 2023-10-29 20:51
Used Turnip_R8 which I confirmed is working in Dolphin emulator (though requires "Store XFB Copies to Texture Only" Hack to be Off to render with no artifacts)

**Comment by Starling0808** [comment] 2023-10-30 03:41
I am very happy to announce that the Turnip driver R9 came and it is working properly in Yuzu 116, yuzu 117 should be out already so I am going to check that version now but 116 is working!

**Comment by djdp77** [comment] 2023-10-30 08:43
For me it does not work still, sd7gen2 user here

**Comment by Starling0808** [comment] 2023-10-30 15:41
Shit. For some reason it was working in yuzu 116, today I deleted yuzu 116 and tried 117 but it did not work... I went back to 116 but it is not working again... I have tried everything to get to work but nothing. Shit next time I will just stay using whatever is working 🤦‍♂️🤦‍♂️🤦‍♂️

**Comment by EDDIPOWER** [comment] 2023-10-31 03:48
I'm sorry I can't contribute anything more to help you.

I resorted to changing the system as you already know, right now I'm on Yuzu 118 and it works fine, and any version from 82 onwards I'm sure. (previously I couldn't use any version with the turnip drivers, error when opening games)

I left a video on YouTube, I just opened a channel to upload games running: https://youtu.be/o_XcPGj7W08

**Comment by Starling0808** [comment] 2023-10-31 04:07
Well as I will upgrade to Android 14 with OneUI 6 to check if it helps. Thanks man I will suscribe to your channel.

**Comment by EDDIPOWER** [comment] 2023-10-31 05:23
> Well as I will upgrade to Android 14 with OneUI 6 to check if it helps. Thanks man I will suscribe to your channel.


good luck friend, may your problem be resolved

you are the first subscriber hehehe

**Comment by djdp77** [comment] 2023-11-10 09:53
@laplaces-entropy @Starling0808 This is fixed, it was a small problem with Turnip

I made a build with the latest Mesa with the fix here: https://github.com/djdp77/freedreno_turnip-CI/releases

**Comment by EDDIPOWER** [comment] 2023-11-10 13:51
Hi
I returned my stock rom and was surprised that Yuzu now works without problems with the turnip drivers. (games do not crash when opened)

**Comment by Starling0808** [comment] 2023-11-10 17:15
Thanks 🥳🥳🥳🥳🥳🥳

**Comment by laplaces-entropy** [comment] 2023-12-22 00:50
forgot to close, sorry

**Closed** 2023-12-22 00:50 UTC
Labels: android
