### ISSUE TITLE
Its not possible to load games from Windows / Samba network share

### ISSUE THREAD

**Issue by ruthan** [yuzu-emu/yuzu#2913] opened 2019-09-27 20:18 UTC
Hello,
its good for sharing games dumps for multiple computers on 1 pleas and its could be also safer, because target disk could be crypted on lots of Nases when is turn off. 

  Its working with most of other emulators, but with last version of Yuzu, when i try to load game from share, i dont have game icon.. and when i run game from list it crashed, same game copied to local drive is working fine.

**Comment by FearlessTobi** [comment] 2019-09-27 20:20
Duplicate of https://github.com/yuzu-emu/yuzu/issues/2805.

**Closed by FearlessTobi** 2019-09-27 20:20 UTC
