### ISSUE TITLE
The Legend of Zelda Link's Awakening

### ISSUE THREAD

**Issue by lgczszs** [yuzu-emu/yuzu#3150] opened 2019-11-22 08:11 UTC
I got stuck after killing the boss.
ubuntu 18.04.3 r5 3600 ,16gb, rx580.
![a](https://user-images.githubusercontent.com/23278901/69407760-4979ab80-0d40-11ea-9c21-cc54ac61a371.png)

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3878501/yuzu_log.txt)

**Comment by FearlessTobi** [comment] 2019-11-22 08:14
Duplicate of https://github.com/yuzu-emu/yuzu/issues/3056.

**Closed by FearlessTobi** 2019-11-22 08:14 UTC
