### ISSUE TITLE
Ultra Street Fighter 2: Menu navigation speed issue (core timing?)

### ISSUE THREAD

**Issue by legend800** [yuzu-emu/yuzu#2102] opened 2019-02-10 18:11 UTC
When navigating the all the game's menus, the selection cursor moves ~5 spots instead of 1 (mentioned it's probably a core timing problem). You have to go up and down repeatedly until you randomly land on where you're trying to go. 

Same with dpad and analog stick. No setting seems to impact this at all. 

Config:
Windows 10 64-bit
GeForce GTX 1080
i7-6700k @ 4GHZ
16GB RAM

**Comment by Hexagon12** [comment] 2019-02-10 18:25
Duplicate of #1821, please report the issue there.

**Closed by Hexagon12** 2019-02-10 18:25 UTC
