### ISSUE TITLE
Hyrule Warriors: Age of Calamity Crashes

### ISSUE THREAD

**Issue by scorp2290** [yuzu-emu/yuzu#5296] opened 2021-01-05 17:40 UTC
There are a couple of crashes I've experienced so far in Hyrule Warriors: Age of Calamity. 1 being near the start of the game when fighting the first moblin; the crash seems to only occur if the player is near the moblin when it plays a specific animation after batting enemies near aside, it does not always happen and I have not been able to reliably reproduce; appears to be fairly random. 

The second crash occurs while the player is controlling Impa. Attempting to apply a seal to an enemy or using one of the strong attacks results in a crash. The attached log (with extended logging enabled) was from playing Impa and performing a strong attack during a weak attack combo.

This has been tested on EA 1287, 1288, and the latest 1289 (HEAD-86bd73cd5) in docked and undocked mode, with 'Accurate' and 'Unsafe' (all options checked) CPU. Also tried with and without asynchronous shader building (Use assembly shaders is disabled); all play attempts resulted in a crash at the above mentioned Impa scenario. I am unable to provide a save file as the game does not appear to save prior to this point, but I am willing to help with any further testing. 

Specs:
CPU: Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
RAM: 16GB DDR4 @ 1600MHz
GPU: NVIDIA GeForce GTX 1060 6GB

[yuzu_log.zip](https://github.com/yuzu-emu/yuzu/files/5771615/yuzu_log.zip)

**Comment by FearlessTobi** [comment] 2021-01-08 00:02
Thanks for your detailed report! I think it is a duplicate of https://github.com/yuzu-emu/yuzu/issues/4871 and therefore I'll close this issue.
It would be great if you could repost your write-up and information over there.

**Closed by FearlessTobi** 2021-01-08 00:02 UTC
