### ISSUE TITLE
Crash when Network Interface is not set

### ISSUE THREAD

**Issue by liberodark** [yuzu-emu/yuzu#9026] opened 2022-10-06 22:40 UTC
Hi,

I think Yuzu is impacted when network interface is not set.
I hope log can help you for find idea.

Best Regards 

```
[ 576.397131] Network <Error> core/internal_network/network_interface.cpp:GetSelectedNetworkInterface:202: Couldn't find selected interface "None"
[ 576.397138] Service.LDN <Error> core/hle/service/ldn/ldn.cpp:InitializeImpl:524: No network interface is set
[ 576.397139] Service.LDN <Error> core/hle/service/ldn/ldn.cpp:Initialize2:514: Network isn't initialized, rc=11979
```

Crash with EA 2989 (On Steam Deck in Offline)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9709672/yuzu_log.txt)

Crash with EA 3000 (On Steam Deck)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9729057/yuzu_log.txt)

**Comment by german77** [comment] 2022-10-06 22:46
duplicate of #9002

**Closed by german77** 2022-10-06 22:46 UTC
