### ISSUE TITLE
totk consume all my ram and crash my pc

### ISSUE THREAD

**Issue by frajusu** [yuzu-emu/yuzu#10351] opened 2023-05-16 23:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

3593 EA i tried with a lot of versions all the same problem

### Description of Issue

the game consume almost all my ram and in some places the rams go up and consume all my ram crashing my pc

### Expected Behavior

play without crash

### Reproduction Steps

play the game and go to the dephs or some cities

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/11492716/yuzu_log.txt)

### System Configuration

CPU: xeon e5 2689
GPU/Driver: rx 550 - 23.4.3
RAM: 16 gb 1600mhz
OS: windows 10

**Comment by frajusu** [comment] 2023-05-17 00:00
api: vulkan

**Comment by Squall-Leonhart** [comment] 2023-05-17 06:10
This is a duplicate of an existing issue that has many replies to it already, i just can't remember which # it is, Liam mentioned encountering the same out of system memory event in it.

**Closed** 2023-05-17 14:41 UTC
