### ISSUE TITLE
TOTK Black background when pressing L button

### ISSUE THREAD

**Issue by Chocobobobo** [yuzu-emu/yuzu#10612] opened 2023-06-04 17:10 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1458

### Description of Issue

When you press the L button to get the ability wheel, everything is black.

### Expected Behavior

You should see the current game background

### Reproduction Steps

Press the L button in game and watch.

### Log File

Nothing to log, just a visual bug.

### System Configuration

CPU: 13600K
GPU/Driver: 3080 Latest NVIDIA driver
RAM: 64GB
OS: WIn10
![RealSwitch](https://github.com/yuzu-emu/yuzu/assets/23947970/c0856f8d-a89c-481e-9be0-3129217dd238)
![EA3636Blackscreen](https://github.com/yuzu-emu/yuzu/assets/23947970/f89c63b1-72c5-4976-ac1d-8d05aadee484)

**Comment by BSoDGamingYT** [comment] 2023-06-04 17:18
Your issue is caused by using FPS mods. Closing this as its not a legitimate issue

**Closed by BSoDGamingYT** 2023-06-04 17:18 UTC

**Comment by BSoDGamingYT** [comment] 2023-06-04 17:24
FWIW, there is a workaround mod for this issue. If you want more info on it and its usage...it would be best to join the projects discord server and ask about it in its game-mods channel
