### ISSUE TITLE
Splatoon 3 | "A communication error has occurred" when starting a match in The Shoal |

### ISSUE THREAD

**Issue by ManiaSonicRUS** [yuzu-emu/yuzu#12705] opened 2024-01-18 15:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Early Access 4069

### Description of Issue

It's possible to create a lobby in The Shoal, select maps, settings, but "A communication error has occurred." happens when trying to start a match.

### Expected Behavior

Like the previous issues I posted, I expect the network features to work just like the Splatoon 2 ones do.

### Reproduction Steps

Just create a lobby in The Shoal and try to start the match. Might require two or three attempts, as sometimes it shows the 2318-0006 error when you're trying to create a lobby.

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/13978561/yuzu_log.txt)

### System Configuration

Vulkan
CPU: i5-12400F
GPU/Driver: GTX 1650 SUPER
RAM: 2x16GB DDR4 3200
OS: Windows 11

**Comment by ManiaSonicRUS** [comment] 2024-01-18 15:32
![VMv0lerfFVc](https://github.com/yuzu-emu/yuzu/assets/77688386/ca9830db-f3ba-4fc4-bf40-b169cd19f628)

**Comment by FearlessTobi** [comment] 2024-01-21 17:57
Duplicate of https://github.com/yuzu-emu/yuzu/issues/11141.

**Closed by FearlessTobi** 2024-01-21 17:57 UTC
