### ISSUE TITLE
TOTK black lines bug on 7000 series amd graphics cards

### ISSUE THREAD

**Issue by Yuzuman45** [yuzu-emu/yuzu#10343] opened 2023-05-16 17:09 UTC

**Comment by Moonlacer** [comment] 2023-05-16 17:16
Duplicate of #10228

**Closed** 2023-05-16 17:29 UTC

**Comment by KeennyyW** [comment] 2023-05-22 19:03
will we get any updates in this thread?

**Comment by OscarDeOssian** [comment] 2023-05-25 13:24
Hi! as the original thread is locked , I just wanted to say that someone finded kind of a fix by mixing two resolution mods that supposedly couldn't work together but for this that makes a HUGE improvement , tested it myself, I have a 7900 XT , in my case I only made it work on docked mode, on handheld it just went to a black screen after launching the game.

But it makes a huge improvement 

here's the original post:

https://www.reddit.com/r/yuzu/comments/13kawba/comment/jlhts3v/?utm_source=share&utm_medium=web2x&context=3

Hope it helps anyone else that has the issue or to find a way to fixing it in a propper manner

**Comment by Araraura** [comment] 2023-05-27 08:07
> Hi! as the original thread is locked , I just wanted to say that someone finded kind of a fix by mixing two resolution mods that supposedly couldn't work together but for this that makes a HUGE improvement , tested it myself, I have a 7900 XT , in my case I only made it work on docked mode, on handheld it just went to a black screen after launching the game.
> 
> But it makes a huge improvement
> 
> here's the original post:
> 
> https://www.reddit.com/r/yuzu/comments/13kawba/comment/jlhts3v/?utm_source=share&utm_medium=web2x&context=3
> 
> Hope it helps anyone else that has the issue or to find a way to fixing it in a propper manner

Doesn't seem to be working with the 1080p AO fix https://www.reddit.com/user/ChucksFeedAndSeed/comments/13svbg2/yuzu_totk_fixed1080pao_build_ea_3617/

**Comment by ianscorpio** [comment] 2023-06-02 12:23
Any updates on this amd series 7000 gpu situation?

Running on:
-RX 7900 XT driver version 23.5.2 (23/05/2023)
-Yuzu EA 3629
-TOTK 1.1.2

The issue still persists, haven't found any mod that could fix it.
![0100f2c0115b6000_2023-06-02_14-23-23-364](https://github.com/yuzu-emu/yuzu/assets/19175469/41728937-483a-462e-a9d5-58b667c82f84)

**Comment by ianscorpio** [comment] 2023-06-03 14:44
The exact same issue happens with botw in cemu, only it can be fixed by enabling the option "accurate barriers" from the debug menu:
![botw3](https://github.com/yuzu-emu/yuzu/assets/19175469/1bf7649e-7424-43f9-965f-cf614a0fed1b)
Without accurate barriers:
![botw](https://github.com/yuzu-emu/yuzu/assets/19175469/0db6a4b7-5529-475c-bcac-3211297c4c4c)
With accurate barriers:
![botw2](https://github.com/yuzu-emu/yuzu/assets/19175469/0bcfb8f3-46fe-4f1e-9393-e7ed3fb459d6)
Not sure if there's any similar workaround for yuzu, would love to hear about that.
