### ISSUE TITLE
Korean fonts are displayed as ???

### ISSUE THREAD

**Issue by psw14kr** [yuzu-emu/yuzu#3138] opened 2019-11-18 03:31 UTC
In the latest version of Yuzu, only Korean font ?? is displayed.
In the version of yuzu, which came out about a month ago, the Korean font was displayed normally using the shared_font file.

yuzu 62 version
![yuzu 62 폰트](https://user-images.githubusercontent.com/35949882/69022816-def30380-09ff-11ea-9346-66ec98292478.png)

yuzu 11 version
![yuzu 11 폰트](https://user-images.githubusercontent.com/35949882/69022826-e4e8e480-09ff-11ea-9d19-59a418d85ad9.png)

**Comment by lgjx123** [comment] 2019-11-19 02:28
@psw14kr yes, and Chinese has same problem. [#3101](https://github.com/yuzu-emu/yuzu/issues/3101)

**Comment by FearlessTobi** [comment] 2019-11-19 16:31
I'm gonna merge this with https://github.com/yuzu-emu/yuzu/issues/3101.

( Duplicate of https://github.com/yuzu-emu/yuzu/issues/3101 ).

**Closed by FearlessTobi** 2019-11-19 16:31 UTC
