### ISSUE TITLE
Missing HLE service unimplemented function 'GetCurrentIpAddress': port='IGeneralService'

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [yuzu-emu/yuzu#2875] opened 2019-09-19 05:59 UTC
## needed by Grid Auto sports

[log.zip](https://github.com/yuzu-emu/yuzu/files/3629640/log.zip)

**Comment by ReaperOfSouls1909** [comment] 2019-09-19 06:07
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3629660/yuzu_log.txt)
just incase the log above is not the right one

**Comment by Hexagon12** [comment] 2019-09-19 06:44
Duplicate of #2630

**Closed by Hexagon12** 2019-09-19 06:44 UTC
