### ISSUE TITLE
ARMS with Update 5.40 not working

### ISSUE THREAD

**Issue by FranciscoReMo** [yuzu-emu/yuzu#2862] opened 2019-09-15 14:37 UTC
All the tests, I run game and then close yuzu and then generate new log for test.
ARMS version 1.0.0 run good.
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3613852/yuzu_log.txt)
![ARMS](https://user-images.githubusercontent.com/43990816/64923042-68a30c80-d7d6-11e9-9ffd-1de2c9175dc4.JPG)

ARMS version 5.4.0 with shadercache.
[yuzu_log [With Update].txt](https://github.com/yuzu-emu/yuzu/files/3613855/yuzu_log.With.Update.txt)
![ARMS Update 5 4 0](https://user-images.githubusercontent.com/43990816/64923070-b0299880-d7d6-11e9-9856-2879d8a1254b.JPG)

ARMS version 5.4.0 no shader cache.
[yuzu_log [With Update, No ShaderCache].txt](https://github.com/yuzu-emu/yuzu/files/3613856/yuzu_log.With.Update.No.ShaderCache.txt)
![imagen](https://user-images.githubusercontent.com/43990816/64923100-f252da00-d7d6-11e9-807e-6b4f674c9258.png)

**Comment by FearlessTobi** [comment] 2019-09-15 14:38
Needs `IsStandardNetworkSystemClockAccuracySufficient`

**Comment by Hexagon12** [comment] 2019-09-15 14:40
Duplicate of #2569

**Closed by Hexagon12** 2019-09-15 14:40 UTC
