### ISSUE TITLE
Animal Crossing: New Horizons stuck

### ISSUE THREAD

**Issue by geGao123** [yuzu-emu/yuzu#3910] opened 2020-05-10 09:34 UTC
I got stuck when K.K. Slider concert.
Yuzu EA 522.
windos 10, 16GB, gtx1070.
![image](https://user-images.githubusercontent.com/6398228/81495496-31441b80-92e3-11ea-93d8-864e52377c45.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/4605423/yuzu_log.txt)

**Comment by spycris** [comment] 2020-05-10 23:27
How did you get it to work? I have prod.keys and title.keys in appdata/roaming/yuzu/keys and I have xci and nsp in folder, and when I select it, the game doesnt appear.

**Comment by geGao123** [comment] 2020-05-11 03:08
[01006F8002326000.zip](https://github.com/yuzu-emu/yuzu/files/4607370/01006F8002326000.zip)
try this save data.
![image](https://user-images.githubusercontent.com/6398228/81520766-c5f85900-9377-11ea-9d4f-5881615f29ae.png)

**Comment by geGao123** [comment] 2020-05-12 03:49
> 您是如何工作的？我在appdata / roaming / yuzu / keys中有prod.keys和title.keys，并且在文件夹中有xci和nsp，并且当我选择它时，游戏不会出​​现。

https://yuzu-emu.org/game/animal-crossing-new-horizons/
follow the document

**Comment by Vero44** [comment] 2020-05-16 18:13
I've been stuck here for a while now too ;-;

**Comment by SullySaysNo** [comment] 2020-05-20 19:48
Transfer your YUZU animal crossing save to Ryujinx, complete the concert on there and then transfer the save back to YUZU. Done.

**Comment by AaryanTalks273** [comment] 2020-05-22 13:44
> Transfer your YUZU animal crossing save to Ryujinx, complete the concert on there and then transfer the save back to YUZU. Done.

Ryujinx keeps starting a new game instead of using my save. Anything I can do to fix this?

**Comment by SullySaysNo** [comment] 2020-05-24 13:18
Make sure that you have the same update and DLC's installed on Ryujinx

**Comment by DamianPereira** [comment] 2020-10-12 07:06
Isn't this a duplicate of https://github.com/yuzu-emu/yuzu/issues/4071, which is fixed?

**Comment by FearlessTobi** [comment] 2020-10-12 19:27
I think you're are right. If not, please inform me and I'll reopen this.

**Closed by FearlessTobi** 2020-10-12 19:27 UTC
