### ISSUE TITLE
Unimplement ioctl on Link's Awakening

### ISSUE THREAD

**Issue by Gpinchon** [yuzu-emu/yuzu#3000] opened 2019-10-19 11:27 UTC
When attempting to launch Link's Awakening from the NAND, it exits at a UNIMPLEMENTED_MSG("Unimplemented ioctl") 
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/3746600/yuzu_log.txt)

<meta name="titleids"  content="01006BB00C6F0000">

**Comment by MysticExile** [comment] 2019-10-19 11:49
Looking at your log, it seems that you're running an unknown yuzu version. Please test once more with the latest mainline build which can be download [here](https://yuzu-emu.org/downloads/)

**Comment by Gpinchon** [comment] 2019-10-19 13:46
I compiled Yuzu myself, so it's the current head of the master branch, commit 8d009a7aae129ce7bc9b33e047f5344ebdc3ab92

**Comment by Hexagon12** [comment] 2019-10-19 15:54
That's normal for the mainline build. It's playing a cutscene, but video decoding isn't implemented. Just wait through it or get a save file and skip it.

**Comment by FernandoS27** [comment] 2019-10-19 20:16
> I compiled Yuzu myself, so the issue is on the current head of the master branch, commit [8d009a7](https://github.com/yuzu-emu/yuzu/commit/8d009a7aae129ce7bc9b33e047f5344ebdc3ab92)
> The latest mainline build results with a black screen and audio playing

you need to ignore asserts. Add this PR over: https://github.com/yuzu-emu/yuzu/pull/1340

have in mind that grapjoc fixes for yuzu aren't merged into master yet.

**Comment by ReinUsesLisp** [comment] 2019-11-22 05:42
Duplicate of #2643.

**Closed by ReinUsesLisp** 2019-11-22 05:42 UTC
