### ISSUE TITLE
Bug Vulkan AMD - Pokemon Sword e Shield

### ISSUE THREAD

**Issue by rgbarros120** [yuzu-emu/yuzu#8576] opened 2022-07-13 16:09 UTC
In the game pokemon sword and shield, in the field where it catches the initial pokemons, it is disappearing and flashing all the time, this bug has been occurring since the hades project was implemented and until today it has not been fixed, remembering that this bug is only occurring on Vulkan from AMD.

My specs: Radeon RX 560 OC 4GB; Ryzen 5 1600; 16GB de RAM
Driver: 22.6.1

![178156191-9f15319e-4a7d-4b18-a2b8-831d02229cd8](https://user-images.githubusercontent.com/73244003/178780593-f9912cd0-f0b2-4e25-870b-4d5211c57f4f.png)
[yuzu_log.txt.old.txt](https://github.com/yuzu-emu/yuzu/files/9104050/yuzu_log.txt.old.txt)

**Comment by G-Spawn** [comment] 2022-07-13 16:11
Please try to provide a better log when you can. It didn't generate anything worthwhile.

**Comment by G-Spawn** [comment] 2022-07-13 16:12
Also we don't support unofficial installers for early access. Please only use the official installer https://yuzu-emu.org/downloads/

**Comment by rgbarros120** [comment] 2022-07-13 16:35
> > Also we don't support unofficial installers for early access. Please only use the official installer https://yuzu-emu.org/downloads/
> 
> This bug is occurring in both yuzu builds, both mainline and EA since when the hades project was implemented and until today none of the developers fixed this bug.

**Comment by G-Spawn** [comment] 2022-07-13 16:47
Indeed. But you actually getting a log that represents the issue properly can also help more.

**Comment by G-Spawn** [comment] 2022-07-13 16:48
if you don't want to oblige no worries. These types of issues will take a fair bit of time to solve anyways.

**Comment by rgbarros120** [comment] 2022-07-13 16:50
> if you don't want to oblige no worries. These types of issues will take a fair bit of time to solve anyways.

I am sending you the photo of the blue field bug and the emulator log file for verification.

![Sem título](https://user-images.githubusercontent.com/73244003/178788126-2c5b5206-a228-4919-ad63-e2f858407076.png)
[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9104341/yuzu_log.txt)

**Comment by rgbarros120** [comment] 2022-07-13 16:55
> > if you don't want to oblige no worries. These types of issues will take a fair bit of time to solve anyways.
> 
> I am sending you the photo of the blue field bug and the emulator log file for verification.
> 
> ![Sem título](https://user-images.githubusercontent.com/73244003/178788126-2c5b5206-a228-4919-ad63-e2f858407076.png) [yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/9104341/yuzu_log.txt)
> 
> I put the photo of the current mainline build with the log

It's right now. Sorry if I was a little rude.

**Comment by pacoa-kdbg** [comment] 2022-07-13 17:14
@rgbarros120 can you try without any additional mods ?

**Comment by pacoa-kdbg** [comment] 2022-07-13 17:17
> @rgbarros120 can you try without any additional mods ?

nvm I am able to reproduce the issue

**Comment by rgbarros120** [comment] 2022-07-13 18:46
> 

Even with the mods disabled the bug still persists, it's the emulator problem. Before the hades project was implemented in the emulator there was no such bug. The bug started when this project was implemented and all this time passed and until today it has not been resolved by the development team.

**Comment by Moonlacer** [comment] 2022-07-13 21:27
> > 
> 
> Even with the mods disabled the bug still persists, it's the emulator problem. Before the hades project was implemented in the emulator there was no such bug. The bug started when this project was implemented and all this time passed and until today it has not been resolved by the development team.
> 
> I think it's not that difficult to solve this bug.

Bugs can be incredibly complicated to solve, or the root could be as simple as changing one line of text, but it will be fixed in time

**Comment by rgbarros120** [comment] 2022-07-13 21:46
> > > 
> > 
> > 
> > Even with the mods disabled the bug still persists, it's the emulator problem. Before the hades project was implemented in the emulator there was no such bug. The bug started when this project was implemented and all this time passed and until today it has not been resolved by the development team.
> > I think it's not that difficult to solve this bug.
> 
> Bugs can be incredibly complicated to solve, or the root could be as simple as changing one line of text, but it will be fixed in time

Well they could put a mod to solve this bug.

**Comment by lKobi** [comment] 2022-07-15 06:42
I though the team was aware of this bug, that texture has been bugged ever since Pokémon Sword/Shield runs on Yuzu, is not limited to that area either, also happens in Piers Gym and maybe some other areas I can't remember.

> > > > 
> > > 
> > > 
> > > Even with the mods disabled the bug still persists, it's the emulator problem. Before the hades project was implemented in the emulator there was no such bug. The bug started when this project was implemented and all this time passed and until today it has not been resolved by the development team.
> > > I think it's not that difficult to solve this bug.
> > 
> > 
> > Bugs can be incredibly complicated to solve, or the root could be as simple as changing one line of text, but it will be fixed in time
> 
> Well they could put a mod to solve this bug.

Don't be ridiculous, we need emulator fix.

**Comment by chichibooxd** [comment] 2022-07-20 15:01
> > > > 
> > > 
> > > 
> > > Even with the mods disabled the bug still persists, it's the emulator problem. Before the hades project was implemented in the emulator there was no such bug. The bug started when this project was implemented and all this time passed and until today it has not been resolved by the development team.
> > > I think it's not that difficult to solve this bug.
> > 
> > 
> > Bugs can be incredibly complicated to solve, or the root could be as simple as changing one line of text, but it will be fixed in time
> 
> Well they could put a mod to solve this bug.

I just wanted to inform the devs that this issue affected me but I'm pissed at how this guy thinks debugging is easy and using mods to fix game issues instead of fixing the underlying issue. Not everything is simple, there's a reason most emulators avoid game specific hacks. It's because it's inherently just putting band aid over a snake bite. Stop whining and cooperate so they can find the underlying issue and fix that bug.

Btw, I'm using Ryzen 3 - 3250U and 8GB of ram. Runs fine but the bug is kinda annoying.

**Comment by G-Spawn** [comment] 2022-07-21 12:05
Your understanding - patience regarding this type of issue is appreciated. It will def be something they try to fix in emu someday not something requiring hack or mod. They are still fixing some regressions after some of the major rewrites - projects (TCR - BCR - Hades ). 🙏  Pardon the inconvenience.

**Comment by z0z0z** [comment] 2022-11-07 05:58
This is also present on Linux with a 5500XT and mesa-git.

**Comment by Immersion95** [comment] 2023-09-01 08:02
It is now solved on latest EA + Windows 11 + AMD :) (Mario Tennis too)

**Comment by Immersion95** [comment] 2023-09-01 14:09
> > It is now solved on latest EA + Windows 11 + AMD :) (Mario Tennis too)
> 
> No offense but this was solved months ago...

Are you sure ? I think this https://github.com/yuzu-emu/yuzu/pull/11402 solved it and it was done 5 days ago

**Comment by Immersion95** [comment] 2023-09-01 14:27
> > > > It is now solved on latest EA + Windows 11 + AMD :) (Mario Tennis too)
> > > 
> > > 
> > > No offense but this was solved months ago...
> > 
> > 
> > Are you sure ? I think this #11402 solved it and it was done 5 days ago
> > Nontheless it's a great news
> 
> That commit is entirely unrelated, and the fix for this issue was covered by developers months ago, as already stated.

Just tested now for the sake of it. It is happening with EA 3840 and is first solved in EA 3841. It was thus solved for me 5 days ago.

**Closed** 2023-09-02 20:59 UTC
