### ISSUE TITLE
Compability issues with Intel Xeon CPUO E3-1231 v3

### ISSUE THREAD

**Issue by Salberolav** [yuzu-emu/yuzu#12812] opened 2024-01-27 00:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Affected Build(s)

Yuzu 1694

### Description of Issue

No dumped game is able to be played in Vulcan. OpenGL works but performance isnt acceptable(very laggy). No matter how i dump a game from my switch once i try to start it in vulcan it crashes after loading the shaders or it and if i try to verify the integrity it always results in a "File contens may be corrupted" promt. vkdiag doenst report anything problematic and the yuzu community in discord forwarded me to the github since they cant help if its cpu related.

### Expected Behavior

game is played(and doesnt crush) on vulcan after shaders load

### Reproduction Steps

in description ^

### Log File

[yuzu_log.txt](https://github.com/yuzu-emu/yuzu/files/14070387/yuzu_log.txt)

### System Configuration

CPU:ntel Xeon CPUO E3-1231 v3 3.40GHz
GPU/Driver:GTX 970 4GB
RAM:16 GB of normal DDR4 RAM
OS:Windows 10 updated (25.01.2024)

**Comment by FearlessTobi** [comment] 2024-01-27 08:06
Bad performance is to be expected with your system configuration.
Also, how did you dump your game? The rom being corrupted has nothing to do with your CPU.

**Comment by Salberolav** [comment] 2024-01-27 12:50
I used the guide on the yuzu quickstart page and successfully merged my game dumps with nxDumpFuse.exe. 
Every time i try to verify these dumps in yuzu i get the may be corrupted promt even tho i send these same dumps to a friend of mine who has yuzu and they were fine on his system! 

So i'm pretty sure the fault doesnt lie in me wrongly dumping them but something in my system or yuzu. 
I know my system configs arent the best but they are well above minimum but being forced to play in OpenGL(which had worse performance on my previous system before it broke) instead of vulkan adds to the performance issues.

**Comment by Squall-Leonhart** [comment] 2024-01-29 01:48
nothing going on in yuzu that can be attributed to Haswell-E that wouldn't be seen on Ivy E as well.

> Bad performance is to be expected with your system configuration.

The cpu can handle most games full speed no problems, the GPU is the problem.

Duplicate of https://github.com/yuzu-emu/yuzu/issues/9146

**Closed** 2024-01-29 10:09 UTC
